### ISSUE TITLE
Frame rate correction

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#10]
In 6502.ts, timing is adjusted via cycles / second. In stella, timing is based on frames / second and needs correction for games with unorthodox frame timings.

**Comment by sa666666** [comment]
Note that this also affects sound playback in some ROMs, so any sound issues reported should be mentioned here until this functionality is restored.

**Comment by thrust26** [comment]
I suppose this report is related:
http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-2#entry3651960

**Comment by DirtyHairy** [comment]
Indeed it is.

**Comment by sa666666** [comment]
There is a partial fix for this in https://github.com/DirtyHairy/stella/commit/e618a6c72c7ca9abd4e34cb3a38c6e485430e87b.  However, there is another issue that related to how unusually large scanline counts are handled, described in https://github.com/DirtyHairy/stella/issues/37.  So I'll leave this bug open for now.

**Comment by sa666666** [comment]
Issue https://github.com/stella-emu/stella/issues/37 is now implemented, so closing this.
