### ISSUE TITLE
Bottom line constantly flickering in Demon Attack

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#100]
This is described in more detail at http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-6#entry3710779.

I'm not sure what the problem is, but in worked in pre4 and Stella 4.7.3, so it's definitely a regression in pre5.

**Comment by DirtyHairy** [comment]
This is caused by a less-than-clever bug in code that I introduced to clear the first view pixels of the first scanline if frame start is autodetected and VBLANK is turned off somewhere in the middle of a scanline. Fixed in c7da6c5.
