### ISSUE TITLE
stella_6.7.1_amd64.deb not install in Ubuntu 20.04

### ISSUE THREAD

**Issue by Augusto7743** [stella-emu/stella#1010]
Thanks for reading my topic.

Not is possible install new version 6.7.1 in Lubuntu 20.04.6.
Requirement is libc6 2.34.
Ubuntu 20.04.6 libc6 version is 2.31.
libc6 2.34 not is available for Ubuntu 20.04.6 in Ubuntu servers.

**Comment by sa666666** [comment]
As of Ubuntu 24.04 (due this April), we'll probably only support Ubuntu 22.04 and above.  I used to have a contributor that did builds for older systems; I will contact them to see if they're still willing to do this.

**Comment by Augusto7743** [comment]
Thanks for your reply.
Please my friend ... my topic not was demanding to create an build fo Ubuntu 20.04.
That message was only to report not work in Ubuntu 20.04.
However if you wish contact contributors to create builds for 20.04 not problem can help users using old distro.

**Comment by sa666666** [comment]
Future releases will require a minimum of Ubuntu 22.04, since the codebase has moved to C++20, and we need to use more recent compilers.  So closing this one.

**Comment by Augusto7743** [comment]
In https://stella-emu.github.io/downloads.html download infomation continue pointing wrong to 20.04. Need update information to 22.04.
