### ISSUE TITLE
Elevator Agent NTSC and Stella core Retroarch

### ISSUE THREAD

**Issue by Anths2016** [stella-emu/stella#1014]
Hello! I try the game with the Retroarch core, and the character does not move. How come?
https://champ.games/downloads

**Comment by thrust26** [comment]
Most likely the detected controller is wrong.

**Comment by thrust26** [comment]
@Anths2016 Does the problem still exist? Have you tried contacting the RetroArch people?

I tested the demo in Stella 7.0 and 6.7.1, it work in both.
