### ISSUE TITLE
Paddles no longer listed in device types like they were in older versions

### ISSUE THREAD

**Issue by ZombieNoSleep** [stella-emu/stella#1026]
There used to be a paddle device type in Retro Arch Stella core, but it appears to be no longer listed, using latest version.  Can someone please advise on that? Stella stand-alone has the options and works fine on there.

**Comment by ZombieNoSleep** [comment]
I asked over there and they sent me here "It is up to the core, so no point posting this here.", so you guys refer me over there and they refer me here lol.  The thing is it used to have paddles listed but they are not in current version, wondering why they were removed it worked fine then
![nopaddles](https://github.com/stella-emu/stella/assets/162681799/a9006132-3590-4fa7-8a36-17df1bca0713)

**Comment by thrust26** [comment]
We did not change anything here, so I have no idea how to help you. Also, we do not have the resources to support Retro Arch problems. Sorry.
