### ISSUE TITLE
32-bit version executable on distribution in detected as malware

### ISSUE THREAD

**Issue by walterg74** [stella-emu/stella#1029]
As per title, the 32-bit version executable, standalone or in the complete package is detected as malware:

https://www.virustotal.com/gui/file/28487026aacd87fb2ea5f1825202b7f21136fe9c08059b4922e6b51df3a1670c/detection/f-28487026aacd87fb2ea5f1825202b7f21136fe9c08059b4922e6b51df3a1670c-1705649565

**Comment by thrust26** [comment]
See #1008

**Comment by walterg74** [comment]
Thanks. So it's duplicita but original was closed without really having taken any action..? Why wasn't it submitted for correction to VT if really a false positive..?

**Comment by thrust26** [comment]
> Why wasn't it submitted for correction to VT if really a false positive..?

Virustotal is only an aggregator. We would have to contact each company which had a false positive by ourselves. I assume you understand that this is not feasible for a hobby project.

**Comment by walterg74** [comment]
Agreed "sort of". 

Same thing hapened to the sheepshaver (mac emulator) guys. Just submitted to a couple was enough, cascade effect I guess. 

https://www.emaculation.com/forum/viewtopic.php?p=78362#p78362

Was also "concerned" cause I read on the other it would be pulled but still there. 

Anyway, fine for me, I just deleted the 32-bit version on my system since I don't use it anyway. 
  
Thanks.
