### ISSUE TITLE
Libretro build failures

### ISSUE THREAD

**Issue by LibretroAdmin** [stella-emu/stella#1032]
Hi there,

in the past few days some commits have been pushed which now cause build failures for the various platforms that libretro targets.

Here is a log -
https://git.libretro.com/libretro/stella/-/pipelines/270622

**Comment by thrust26** [comment]
@sa666666 Looks like your commits are causing problems here.

**Comment by sa666666** [comment]
Going forward, Stella requires g++-11 and C++20 support.

The current issue is that `numbers` doesn't seem to be supported by the compiler you're using.  I could back out that change, but then there's no guarantee that we won't use another C++20 feature that's not supported by your compiler environment.

**Comment by sa666666** [comment]
Since all these build issues are `<numbers>` related, I attempt to fix this in 49166ca9949708c3bddaed5cc549194c4bfcfae5.  But going forward, I can't promise that further C++20 usage won't break something else.

Please respond whether or not this fixes the build issues.

**Comment by LibretroAdmin** [comment]
Here are the current build failures -
https://git.libretro.com/libretro/stella/-/pipelines/270849

**Comment by sa666666** [comment]
These new errors are from further C++20 feature usage; ones which I can't work around.  Are you sure you're enabling the C++20 compiler support here?

**Comment by LibretroAdmin** [comment]
I think you added those C++20 compilation flags yourself to the Makefile here - 

https://github.com/stella-emu/stella/blob/master/src/os/libretro/Makefile#L49

As well as Android.mk. 

Anyway, knowing what I've experienced with C++ toolchains in the past, most likely this issue can be solved by including a header for whatever STD class it is complaining about in the file. C++ toolchain headers usually are not consistent with one another and on various platforms you tend to need to include one or more header files to get it to compile across all platforms. At least that has been the experience with C++11 and C++17 toolchains across the board.

**Comment by sa666666** [comment]
True, I added the `-std=c++20` to the Makefile.  But I have no way of testing that.  And I don't see it reflected in the build logs.

Also, the errors we're getting now are not the result of missing headers.  They're specific features of C++20 keywords that just aren't being recognized.

**Comment by sa666666** [comment]
Some more info.  The builds which succeed have `-std=c++20`, while the ones that fail have `-std=c++2a`.  Furthermore, if I force C++17 on my local Linux system, it gives very similar errors to the ones reported here.

So for whatever reason, it seems that C++20 support isn't being used.

**Comment by LibretroAdmin** [comment]
C++20 wasn't supported on Android NDK until last year -
https://github.com/android/ndk/releases/tag/r26

So to get it to compile on Android will require a toolchain upgrade on our server. Which is also a portability issue since these newer NDKs cut off support for older OS versions we still care about. So it will take up more server space and we already run out of disk space. Anyway, none of that is your problem and I respect that.

I guess this leaves the Apple side. warmenhoven is taking a look there what can be done there.

**Comment by warmenhoven** [comment]
The `c++2a` standard was based off of a draft of c++20 before it contained `stringstream::view`, among others. It contains a good deal of what is in c++20 but not everything.

For the libretro buildbot we use Xcode 12.2 because it supports back to iOS 9; it supports c++2a. While we could consider updating Xcode, the first version of Xcode that supports `c++20` as a std is Xcode 14.0, which drops support for iOS versions before 11. So in order to continue maintaining support for Stella on iOS9, it would need to use only the parts of c++20 that were in the c++2a implementation.

**Comment by LibretroAdmin** [comment]
We can move it to our M1 buildbot which would kill off iOS 9 backwards compatibility but it is what it is.

We'll likely create a snapshotted version of the last Stella version that still compiled there and just add a year to it, like stella2014. That way there will be stella2014, stella2023 and stella-current (upstream).

**Comment by sa666666** [comment]
Yeah, Stella 7.0 is going to be somewhat a 'breaking' release.  We're discontinuing 32-bit support, moving to C++20, etc.  It makes sense to do this at a major version number, and 7.0 will be it.

I guess this issue can be closed, and I leave it to you guys to change your build environment as you like.

**Comment by LibretroAdmin** [comment]
https://github.com/stella-emu/stella/commit/9f13401d0d18a15d6d14a05f0e0b3cb7faa56ebf#diff-0661725ce9e39127f4794096376761731f72e1917d580ae38cf279be47a80454R63

It is defaulting to C++2a right now for Linux in the libretro Makefile based on compiler version (some heuristic that you added I believe, see linkn above) and the Linux build doesn't compile either. So C++2a might not have enough functionality for whatever you're attempting here now.

https://git.libretro.com/libretro/stella/-/jobs/5199709

**Comment by LibretroAdmin** [comment]
While we can make a new Docker that has a newer GCC version, honestly this is bad because it will cripple backwards compatibility. The reason we choose a certain baseline compiler and toolchain for the Linux builds is so that all cores can be guaranteed to work cross-distro. If we have to bump up the compiler toolchain then we lose all that backwards compatibility and it would almost necessitate a new Linux build as well.

**Comment by sa666666** [comment]
Going to close this one now.  There's nothing we can do on our end, since we're moving to requiring more recent compilers.
