### ISSUE TITLE
version 'tag' always visible

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#1035]
I have a locally built stella 7.0_pre
When i run it via double-click of a binary, the stella version tag remains onscreen without disappearing.

<img width="204" alt="Screenshot 2024-06-21 at 9 37 34 PM" src="https://github.com/stella-emu/stella/assets/16424075/7c6af00f-683b-4530-9d17-32a29ad2910e">

If I go to debugger and back, the tag is no longer there.

I believe there should be a short timeout on the tag display. Is "always on" intentional, or a bug?

**Comment by thrust26** [comment]
MacOS I suppose?

**Comment by andrew-davie** [comment]
> MacOS I suppose?
> 
> Does not happen with Windows.
> 
> @sa666666 @DirtyHairy Can you reproduce the problem?

MacOS Sonoma 14.5

**Comment by sa666666** [comment]
I'm not back in my office until Tuesday, which is where my Mac is.  So I can't get to it until then.

**Comment by thrust26** [comment]
@sa666666 Did you test this?

**Comment by sa666666** [comment]
Sorry, I forgot.  Will test tomorrow when back in my office.

**Comment by sa666666** [comment]
I cannot reproduce this with a build of Stella from Xcode.  Building Stella the 'UNIX' way is not fully supported or tested, so it's likely you will run into these little gotcha's if you do so.  Did you build Stella this way?

**Comment by thrust26** [comment]
No reply, closed.
