### ISSUE TITLE
Constant background hum in Vong demos

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#104]
Reported here: http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-7#entry3715819

Confirmed that it 's only happening in Windows, not Linux or OSX.

[vong.zip](https://github.com/stella-emu/stella/files/836942/vong.zip)

**Comment by sa666666** [comment]
I'm going to leave this until we get to the new sound core, since I think it might be related, and I don't want to waste any more time fixing code that will be disappearing soon.

**Comment by DirtyHairy** [comment]
This noise is most likely a resampling artifact: AUDC = 4, AUDF = 0 generates a square wave that changes polarity with every audio tick (twice each scanline), which makes it a ~16kHz square wave. I guess what happens exactly depends on the frequency of the OS audio stack and on the quality of the resampling that happens. On my Mac, I get no hum, but I can hear a high-pitched screetch if I turn the volume up. I stumbled over this while implementing PCM support in 6502.ts: I am doing rather crude resampling there, and the result is audible and annoying noise.

**Comment by sa666666** [comment]
Fixed with the latest sound core.
