### ISSUE TITLE
Crash bug on startup when buttonless controller connected

### ISSUE THREAD

**Issue by JDavidRawle** [stella-emu/stella#1043]
My computer has flight controllers connected including rudder pedals which act as a buttonless joystick.
There is a crash bug from an unchecked array access at
https://github.com/stella-emu/stella/blob/master/src/common/PJoystickHandler.cxx#L948

I fixed it changing the line to this:

  const int button = stick < static_cast< int >(j->buttonLast.size())  ? j->buttonLast[stick] : -1;

but I don't know the code enough to know the potential effects of choosing -1 as a default value. It did stop the crash and allow the UI to function.

**Comment by thrust26** [comment]
@sa666666 Do you happen to have a buttonless joystick for testing?

**Comment by sa666666** [comment]
No, I don't.  Actually, I didn't even know such a joystick existed (hence the reason for the bug).  I think setting to -1 is the right thing to do in this case.

**Comment by thrust26** [comment]
Yes, JOY_CTRL_NONE (-1) should be used here. But I wonder why `buttonLast` is an array at all.
