### ISSUE TITLE
Stella 7.0 does not start

### ISSUE THREAD

**Issue by github-fanuser** [stella-emu/stella#1046]
I downloaded Stella 7.0b (Windows,zip). When I click on stella.exe, nothing happens.

**Comment by thrust26** [comment]
@github-fanuser Can you start Stella.exe from the command line? Is there some kind of error reported then?

**Comment by github-fanuser** [comment]
for clarification; when I click on stella.exe, i get the blue spinning circle for a few seconds, then nothing. No error message. Nothing pops up. I also tried starting from command prompt.

**Comment by thrust26** [comment]
And did you install the Visual C++ files?

**Comment by github-fanuser** [comment]
Thank you! Installing Visual C++ fixed the problem. You might consider adding an error message and a link to download. Is there a way to choose where the c:\users\appdata\roaming\stella folder is located? I prefer to have it in the same folder as the program.

**Comment by thrust26** [comment]
RTFM! 😏 

Look for "-basedir" commandline argument.

**Comment by sa666666** [comment]
If you want it in the exe directory, "-baseinappdir" is more appropriate.

**Comment by thrust26** [comment]
@github-fanuser Can we close this one?

**Comment by GoodWall533** [comment]
Please excuse my ignorance but how exactly would one go in using that command to make portable mode? I'm not well versed with these.

**Comment by sa666666** [comment]
Right-click on Stella icon and add that text to the commandline option somewhere in the dialog.  Sorry I can't help more right now; I'm not in front of my Windows machine.

**Comment by thrust26** [comment]
@GoodWall533 @sa666666 

Can we close this one?
