### ISSUE TITLE
Add cut/copy/paste of text in various GUI elements

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#105]
There is already partial (undocumented) support for this in EditTextWidget.  In particular, pressing Ctrl-x,c,v does Cut/Copy/Paste of the current text to an internal buffer, that can then be placed in another EditTextWidget.  This needs to be generalized, to allow copying to/from the operating system (ie, outside of the app), between different types of widgets, and also to allow selecting of text (with keyboard and mouse).

**Comment by sa666666** [comment]
Pushing this to post-5.0 release, so we can get the 5.0 release done soon.

**Comment by thrust26** [comment]
I just had a first look into the code. It seems that we may have to change some hotkeys first. E.g. switching a tab is currently done with SHIFT + LEFT/RIGHT, which is usually used for marking text (at least in Windows). 

In Windows the standard is CTRL + TAB for forward and CTRL + SHIFT + TAB for backward. So like normal tabs through files, but with CTRL key added. How do Linux and OSX do this?

**Comment by juanitogan** [comment]
Can we at least have system paste working and worry about text selection later?  Use case: keeping a scratch pad of commands elsewhere (like my source file) for pasting into the CLI.

**Comment by thrust26** [comment]
> Can we at least have system paste working and worry about text selection later? Use case: keeping a scratch pad of commands elsewhere (like my source file) for pasting into the CLI.

Done with my last commit. It will become part of the next release (6.4).

**Comment by thrust26** [comment]
@sa666666 I wonder how to implement a blinking cursor (caret). Cut currently there is no functionality to update a widget regularly. Instead a widget informs the dialog that it has become dirty (on init and by user interaction) and `Dialog::render()` only checks if a dialog has become dirty. 

IMO it should be vice versa. The dialog checks each of its widget and asks if the widget has become dirty (`isDirty()`) and redraws only the widgets which are dirty. Then the `EditableWidget` could implement a cursor timer in there.

Thoughts?

**Comment by sa666666** [comment]
What you say makes sense, but I'm always weary of touching the UI code, particularly the event-handling part of it.

Also, something else to take into account is that I've exerted quite some effort to only draw the UI when absolutely necessary, otherwise CPU usage rises.  So we'd want to keep that functionality.

Finally, note that under the current renderers, a redraw of _any_ part of the UI redraws the whole thing.  So when you say "redraws only the widgets which are dirty", what will happen is the whole dialog is redrawn.  This is because for OpenGL and Direct3D, it's easier (and often faster) to update the entire texture than just a small part of it.  So keep in mind that for the debugger at least, a blinking cursor will mean an update of the entire window every second or so (depending on the frequency you want for blinking).

**Comment by sa666666** [comment]
Also, we don't _need_ a blinking cursor.  Many UI's have a UI and text selection but without a blinking cursor.

**Comment by sa666666** [comment]
Any console; konsole in Linux, Terminal in macOS, maybe even a DOS box in Windows.  A blinking cursor is configurable.  Another option is to have the cursor be a different colour than the text (that's how Stella does it).

**Comment by thrust26** [comment]
> What you say makes sense, but I'm always weary of touching the UI code, particularly the event-handling part of it.

Me too.

> Also, something else to take into account is that I've exerted quite some effort to only draw the UI when absolutely necessary, otherwise CPU usage rises. So we'd want to keep that functionality.

Yes, that's what I wanted to make sure too.

> Finally, note that under the current renderers, a redraw of any part of the UI redraws the whole thing. So when you say "redraws only the widgets which are dirty", what will happen is the whole dialog is redrawn. This is because for OpenGL and Direct3D, it's easier (and often faster) to update the entire texture than just a small part of it. So keep in mind that for the debugger at least, a blinking cursor will mean an update of the entire window every second or so (depending on the frequency you want for blinking).

Hm, now it is getting complicated. 

I noticed that currently e.g. the whole debugger window is redrawn even when I am just e.g. focus a different element. With my approach only the widgets which are affected by the focus effect are redrawn. Since we are drawing into a single surface, wouldn't the renderers still update the whole surface? So that we save drawing time and everything else stays the same, no?

**Comment by thrust26** [comment]
> Any console; konsole in Linux, Terminal in macOS, maybe even a DOS box in Windows.  A blinking cursor is configurable.  

Configurable yes, but AFAIK there is always the option for a blinking cursor. And it seems to be the default configuration.

> Another option is to have the cursor be a different colour than the text (that's how Stella does it).

But that's IMO much less obvious. And probably the reason why blinking cursors are the default.

**Comment by sa666666** [comment]
> I noticed that currently e.g. the whole debugger window is redrawn even when I am just e.g. focus a different element. With my approach only the widgets which are affected by the focus effect are redrawn. Since we are drawing into a single surface, wouldn't the renderers still update the whole surface? So that we save drawing time and everything else stays the same, no?

Yes, that's what I was referring to above.  _Any_ change to the dialog results in the entire surface being redrawn.  And if you have a cursor flashing several times per second, that becomes a full redraw several times per second.  Maybe it doesn't matter in the end; I just wanted you to be aware of how the current rendering works.

Honestly, I think it's an awful lot of work to reorganize the UI code _just_ to get a blinking cursor.  If there are other reasons for it, then I suppose we could look into it.  But just for a blinking cursor?  I don't know about that.

There are other options for cursors.  There can be a 'block' which inverts the text as it moves over it.
<img width="245" alt="Screen Shot 2020-11-03 at 10 34 45 AM" src="https://user-images.githubusercontent.com/16061066/97994773-3c729280-1dc0-11eb-9d66-2214beeca6bc.png">
<img width="206" alt="Screen Shot 2020-11-03 at 10 34 55 AM" src="https://user-images.githubusercontent.com/16061066/97994784-40061980-1dc0-11eb-8697-e9008caa5dfb.png">
While this would be more work to do, it's still probably easier than enabling blinking in the UI.

**Comment by sa666666** [comment]
Also, I think we're conflating two different things here.  Whether a cursor blinks (or not), or even how it looks, is separate from being able to select a block of text.

**Comment by thrust26** [comment]
Yes and no. I found it hard to select a block without a blinking cursor. Maybe just because I am used to it.

Anyway, I fully understand why you wouldn't want to touch the UI code just for a cursor. And as of now I cannot come up with a reasonable idea where we would need UI animation in Stella.

But maybe I will come back to this and experiment a bit. I don't like how the current widgets are interacting in Stella. It seems inefficient and strange.  E.g. the tabs seem like integrated as an afterthought.

**Comment by thrust26** [comment]
> There are other options for cursors. There can be a 'block' which inverts the text as it moves over it.
> <img alt="Screen Shot 2020-11-03 at 10 34 45 AM" width="245" src="https://user-images.githubusercontent.com/16061066/97994773-3c729280-1dc0-11eb-9d66-2214beeca6bc.png">
> <img alt="Screen Shot 2020-11-03 at 10 34 55 AM" width="206" src="https://user-images.githubusercontent.com/16061066/97994784-40061980-1dc0-11eb-8697-e9008caa5dfb.png">
> While this would be more work to do, it's still probably easier than enabling blinking in the UI.

Good alternatives. Thanks!

**Comment by sa666666** [comment]
It's no surprise that some things seem like an afterthought; they were/are.  TBH (and I know I've said this before), a lot of the things we want to do/are doing in the UI are outside the original design.  If you had seen how this code originally worked, you'd be really surprised by what we managed to achieve, considering its design constraints.

Regarding the example above, that's from the console I'm using.  I use a console of some sort about 4-5 hours a day, so I'm more used to that approach than a blinking cursor.  In fact, I specifically turn off anything blinking in the UI's I use 😃

**Comment by thrust26** [comment]
> If you had seen how this code originally worked, you'd be really surprised by what we managed to achieve, considering its design constraints.

Never doubted that. But there is no ceiling which stops the code from improving even more.

**Comment by sa666666** [comment]
Sure, I just mean that the more features we attempt to add, the more invasive the required changes will become.  We're getting to the point where all the 'low hanging fruit' have been picked, and further work requires structural reworking.

And that's not to say the original code was bad in any way; we're just adding things it was never designed to do.

**Comment by juanitogan** [comment]
I don't know if another opinion matters here but I'll add mine for what it's worth.  Personally, I don't care if the cursor flashes or not.  Sure, a flashing cursor is typical (and hails from when flash used to be a property of terminal color and, thus, was handled by hardware), and typical is always nice, but I wouldn't worry about it if it's a hurdle.

Regardless, here are some relevant points I've observed about flashing cursors.  The flash tempo is commonly once a second and, thus, two redraws a second.  Ideally (in modern times), they only flash when idle.  Cursors (text carets in particular) disappear or freeze when the editor widget does not have focus.  Note that this is widget focus and not app focus.  Thus, even in a text editor, the caret can disappear when in the menus or elsewhere in the app.  Thus, in the Stella debugger prompt, ideally, caret flashing would be a minor performance hit (twice a second) only when the prompt widget has the focus.  Unless, of course, you also want the carets in all the other text boxes to flash as well (which, by the way, are indeed a different color from the text -- they are red)... but still only twice a second when if focus.

**Comment by sa666666** [comment]
Yep, I don't think twice a second is going to be a major issue performance-wise.  Much more difficult will be to rearrange the event loop/design so that the UI can do animations.  Maybe we can do it with some sort of timer in the the active widget only, so when it's activated it fires a redraw every second; once for cursor on and once for off.  And when deactivated, the timer stops.

**Comment by thrust26** [comment]
We already have some kind of timer. The UI is checked for redraws every 1/60 second. And if we allow the individual widgets to report their redraw requests, we can implement a cursor flash quite easily. And then we can still decide if we want to redraw the whole UI or only the reporting widget(s).

**Comment by thrust26** [comment]
@sa666666 In my last commit I have some TODOs in `EditableWidget` regarding some keys (CTRL+K,U,W). As of now I cannot replicate the correct behavior here when some text is already selected, because I have no UI which supports these keys and text selection.

Can you help here? Or link me to an UI I can use for testing?

How about the mouse? Should we support the functionality here too? Or is that overkill?

BTW: `PromptWidget` is not enhanced yet.

**Comment by sa666666** [comment]
Don't know if I responded elsewhere to this, but yes, we would eventually want mouse selection and a popup menu for cut/copy/paste as well.  You just _know_ that if we offer keyboard shortcuts to do it, then someone will request the mouse too :smiley:   So we should leave the issue open for that.

The `PromptWidget` not being done (yet) is already another issue, so we needn't worry about that one here.  So once mouse support is added to `EditableWidget`, we can close this one.

**Comment by thrust26** [comment]
Shouldn't be too complicated. :smile:

**Comment by thrust26** [comment]
Added mouse support with c0814818. Should we close this one now?

**Comment by sa666666** [comment]
Before I even read the message that you say it will be easy, I see another that it's already done :smile: As I've said before, I don't know where you get the extra energy, but I wish I could somehow borrow some of it.

We are done with this one, so I will close.
