### ISSUE TITLE
Add support to paths with Unicode characters

### ISSUE THREAD

**Issue by GeometryEmperor** [stella-emu/stella#1054]
I tried to open one of my roms from a specific path, that had Greek characters. On the UI, the name of the path would appear invisible and when I would load the rom, it would immediately crash. I then tried to move the rom to a different file, one where the path does not have Greek letters, and this time it would open like normal.

That made me realize that it is simply Greek letters (or Unicode characters in general) that cause this. I hope this is in the works for fixing in the near future.

**Comment by thrust26** [comment]
See #1051
