### ISSUE TITLE
Add keyboard/joystick mappings per virtual controller

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#106]
Currently, if one assigns joy0 button1 to, say, the left joystick fire button, then it cannot be assigned to anything else.  But if you were running a keypad game, for example, then we'd like to possibly assign the same button to the virtual keypad, but not erase the assignment to the joystick (on the assumption that you can't have both plugged in at the same time anyway).

Put another way, the mapping is currently one-to-one, and we need it to be one-to-many (one 'joy0 button1' press can generate multiple different actions, and the virtual controller currently in use will pick whichever one is appropriate).

This is needed in particular for those using Stelladaptor-II devices which modify the hardware to add extra buttons not originally present, and would like to map those buttons in Stella.

**Comment by sa666666** [comment]
Pushing this to post-5.0 release, so we can get the 5.0 release done soon.

**Comment by thrust26** [comment]
Not sure if I get you here. I have my fire button assigned to Left Ctrl and Space.

**Comment by sa666666** [comment]
What you have is many-to-one in terms of actions to events.  That is, many different inputs (Left Ctrl, Space, etc) can be mapped to one event (Left Joy Fire).

There are cases where we also need one-to-many (ie, button 0 on some device means different things to different virtual controllers, depending on what's 'plugged in'.  This is mostly for 2600-daptor devices.  In particular, if you assign button 0 to the virtual 'Left Joy Fire', it should also be assignable to other virtual 'Left' controllers, on the assumption that you can never have a Left Joystick and a Left Paddle (for example) plugged in at the same time.

Again, this was an issue for Stelladaptor/2600-daptor.  I forget the details right now, but there was an issue that needed to be resolved.

**Comment by thrust26** [comment]
@sa666666 This is redundant to #307, right?

**Comment by sa666666** [comment]
Yes, this can be closed now.
