### ISSUE TITLE
TV jitter

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#11]

**Comment by sa666666** [comment]
When we get to this, the following ROM will be useful in comparing output to the old core:
[jitter.zip](https://github.com/stella-emu/stella/files/720770/jitter.zip)

Use cursor keys to adjust scanlines, and press space to use the selected count.  The effects in pre4 are already quite close to the old core, but still incomplete since the 'tv.jitter' and 'tv.jitter_recovery' options aren't being used.

**Comment by sa666666** [comment]
Refer to this [thread](http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-6#entry3704333) on AtariAge for more information.

**Comment by DirtyHairy** [comment]
I have started to look into this and am confused be the behavior of the implementation in the old core. What I *do* understand is that, if frame length changes, a CRT requires some time to lock onto the new sync timings, causing the screen to "roll into place".

However, I would have assumed that, if frame lenght increases, the next frame will start too early and thus appear shifted towards the bottom and then roll into place. However, what I observe in Darrell's example is precisely the opposite behavior. In addition, things get even more funky above 169 lines or 89 lines (again in jitter.bin). Bevore I invest more time in understanding this: is the old implementation just an effective implementation that rolls in a superficially convincing way, or is there more to it?

I can't test atm (away from home) and don't have a CRT at any rate, so I am asking instead from testing :smirk:

**Comment by SpiceWare** [comment]
bingo - _"just an effective implementation that rolls in a superficially convincing way"_

I did it after encountering one too many [posts like this](http://atariage.com/forums/topic/240879-game-test-on-harmony-cart/) where the programmer had no way to test on real hardware and was surprised when others encountered jitter.  I just made it so the problem would be readily apparent.

My last [three blog entries about Stella](http://atariage.com/forums/blog/blog-148/cat-176-stella) are on the jitter implementation.

**Comment by SpiceWare** [comment]
Also note that what happens at the extremes totally depends upon the TV/monitor. Some end up showing 2, or even 3, stable images.  See [reply #76 & 77](http://atariage.com/forums/topic/183085-bus-stuffing-like-the-graduate/?p=3608133)

**Comment by DirtyHairy** [comment]
:smile: That's about what I expected. In this case, I'll aim for the same effect, without attempting an exact recreation .

**Comment by DirtyHairy** [comment]
This commit reimplements jitter. The new implementation works differently, but the effects look similar :smirk:.
