### ISSUE TITLE
Inconsistent trackball controller naming

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#111]
In the command line two trackballs are named differently than in the game properties list (Trakball vs CX-22 Trakball; AtariMouse vs CX-80 Mouse).

I would opt for the command line names.

**Comment by sa666666** [comment]
Where/how do you see the commandline names?

**Comment by thrust26** [comment]
In the documentation. And the values listed there are working correctly.

**Comment by sa666666** [comment]
OK, I only see one instance of this: Trakball is called "CX22 Trakball" in the UI.  I don't see any reference to CX80 anywhere.  In fact, a grep of the entire codebase only shows this once, as a comment in the code (which I will also fix).

**Comment by thrust26** [comment]
Yup, sorry. The CX22 was the initial (and only) difference. I must have accidentally looked at 4.7.3 for CX80.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/7a0f322224fa11803b1b7d24c2079d6e74f33aba.
