### ISSUE TITLE
stella-4.7.3-gcc7.patch

### ISSUE THREAD

**Issue by sergiomb2** [stella-emu/stella#116]

**Comment by sergiomb2** [comment]
[stella-4.7.3-gcc7.patch.txt](https://github.com/stella-emu/stella/files/925361/stella-4.7.3-gcc7.patch.txt)

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/fb6e573263b7fb80a12d0eb74d22e13899f745ee.
