### ISSUE TITLE
Checking hosttype doesn't detect aarch64 arch ? 

### ISSUE THREAD

**Issue by sergiomb2** [stella-emu/stella#117]
Checking hosttype... 
WARNING: could not establish system type, assuming unix like 

yes is Linux Fedora on aarch64,  please take a look here: 
http://koji.rpmfusion.org/kojifiles/work/tasks/3931/103931/build.log
http://koji.rpmfusion.org/koji/taskinfo?taskID=103931

Best regards

**Comment by sa666666** [comment]
I've updated the config files to the latest version here: https://github.com/stella-emu/stella/commit/1dd8c04f6813779e509fa7427b06bbc47d408329.  In one case, the version being used was 12 years old!  Please test and report back, since I don't have access to aarch64 hardware to test myself.

**Comment by sergiomb2** [comment]
Hi, it passed aarch64 but now it fails on ppc64le [1]  do you want try to fix it or should I exclude ppc64 archs ? 
Thanks in advance.
[1]
http://koji.rpmfusion.org/koji/taskinfo?taskID=105016
http://koji.rpmfusion.org/kojifiles/work/tasks/5016/105016/build.log

**Comment by sa666666** [comment]
Well, since I'm using the very latest config.guess and config.sub from FSF, I don't know how to fix any further issues.  That tangle of bash scripting is beyond me, so I guess for now you can just exclude ppc64 archs.  But there really should be a fix for this in some other package; this issue must have come up before.

**Comment by sergiomb2** [comment]
fail on ppc64le is in compiling : 

```
g++ -MMD -MF "src/unix/.deps/OSystemUNIX.d" -MQ "src/unix/OSystemUNIX.o" -MP -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mcpu=power8 -mtune=power8   -Wall -Wextra -Wno-unused-parameter -Wno-ignored-qualifiers -Wno-multichar -Wunused -fno-rtti -Woverloaded-virtual -Wnon-virtual-dtor -std=c++11 -fomit-frame-pointer -D_GLIBCXX_USE_CXX11_ABI=1 -DUNIX -DBSPF_UNIX -DHAVE_GETTIMEOFDAY -DWINDOWED_SUPPORT -DSOUND_SUPPORT -DDEBUGGER_SUPPORT -DJOYSTICK_SUPPORT -DCHEATCODE_SUPPORT -DTHUMB_SUPPORT  -Isrc/emucore -Isrc/common -Isrc/common/tv_filters -Isrc/gui -I/usr/include/SDL2 -D_REENTRANT -Isrc/unix -Isrc/debugger -Isrc/debugger/gui -Isrc/yacc -Isrc/cheat -c src/unix/OSystemUNIX.cxx -o src/unix/OSystemUNIX.o
In file included from src/emucore/EventHandler.hxx:30:0,
                 from src/emucore/FrameBuffer.hxx:33,
                 from src/emucore/OSystem.hxx:40,
                 from src/unix/OSystemUNIX.hxx:23,
                 from src/unix/OSystemUNIX.cxx:20:
src/emucore/Event.hxx: In member function 'void Event::clear()':
src/emucore/Event.hxx:112:25: error: cannot convert 'bool' to '__vector(4) __bool int' in assignment
         myKeyTable[i] = false;
```

**Comment by sa666666** [comment]
I'll look into this and get back to you.

**Comment by sa666666** [comment]
This seems to be a bug in either SDL2 or gcc, depending on who you speak to.  Workaround is to undefine 'bool' after including SDL headers, which is what commit https://github.com/stella-emu/stella/commit/38deb5b1cfdce8b86a49c71cd7ce34a8fafd3884 does.  Please test to see if it fixes the issue.

**Comment by sergiomb2** [comment]
Applying commit to stable stella-4.7.3 finish with [1] , so I going optout by exclude ppc64 for now , unfortunately I can't spend much time with stella

Thanks for your time 

[1] 
```
In file included from src/emucore/Event.hxx:24:0,
                 from src/emucore/EventHandler.hxx:30,
                 from src/emucore/FrameBuffer.hxx:33,
                 from src/emucore/OSystem.hxx:40,
                 from src/unix/OSystemUNIX.hxx:23,
                 from src/unix/OSystemUNIX.cxx:20:
src/common/StellaKeys.hxx:23:23: fatal error: SDL_lib.hxx: No such file or directory
 #include "SDL_lib.hxx"
                       ^
compilation terminated.
Makefile:155: recipe for target 'src/unix/OSystemUNIX.o' failed

```

**Comment by sa666666** [comment]
I understand you don't have a lot of time to work on this, but this error above was because the patch included a new file, not just modifications to existing files.  I'd really like to get this fixed.  Is it possible for me to get access to your build servers so I can test it myself?  Even if we don't get it in 4.7.3, I'd still like to have it fixed for the 5.0 release.

**Comment by sergiomb2** [comment]
yes , in last resource you may become packager maintainer [1] , but I think you can send scratch build to koji ... let me know if you want become a packager maintainer ? 

[1] https://rpmfusion.org/Contributors

**Comment by sa666666** [comment]
I don't think I would have time to become the maintainer, as I already have to maintain the codebase across 3 platforms (Linux, OSX, Windows).  And I use DEB-based distros, so don't really know a lot about RPM stuff.  But if I could get access to do scratch builds, it would allow me to fix compile issues before release (not relevant for 4.7.3, but definitely for 5.0).

**Comment by sergiomb2** [comment]
After thinking and if the request is update to 5.0 I don't have problem to do that in devel branches , is for that they exist , just need know what tag or commit I should use , for that the better and we (RPMFusion) like have the request documented, for that please fill one very short bug report in https://bugzilla.rpmfusion.org/enter_bug.cgi?component=stella&product=Fedora&version=f27%2Frawhide ,please write the version do you think is the best to update the package .

**Comment by sergiomb2** [comment]
what a coincidence ! I'm going try build 5.0.0-pre7 sa666666 tagged this 4 minutes ago on RPMFusion

**Comment by sergiomb2** [comment]
Failed to build on  arch ppc64le [1]

[1] http://koji.rpmfusion.org/koji/taskinfo?taskID=110529 and 
http://koji.rpmfusion.org/kojifiles/work/tasks/532/110532/build.log

**Comment by sa666666** [comment]
Try the following patch from https://github.com/stella-emu/stella/commit/684c227381fe0d9cece3bfeed0f37eebab05404c.  This seems to be related to the last fix for bool, but I should have went further and undef'ed all items.  Also added original bug report against Wesnoth for this to SDL_lib.hxx, so we have a reference to it.

**Comment by sergiomb2** [comment]
Fixed now ! built successfully on a bunch of arches 
http://koji.rpmfusion.org/koji/buildinfo?buildID=3899

Cheers.
