### ISSUE TITLE
Stella won't automatically open certain rom images on Mac when opened via Finder.

### ISSUE THREAD

**Issue by wizard1969** [stella-emu/stella#118]
Having a little trouble with my assembled code on the mac (Mac OS X 10.11.6)
 
If I download a binary rom file and double click it from finder, the bin extension is associated with Stella.app and Stella starts up with that particular binary file, exactly as you would expect it to do.
 
If I assemble something (with DASM) and double click on the binary , Stella opens, but it does not run the rom file and is at the rom select screen with the default rom directory, as if I started it with no arguments.  
 
I have downloaded many example programs from Atariage.com etc., ones that include the source and a binary. The binary runs as soon as I double click it, but when I assemble the same code the resulting binary does not automatically run when double clicked.

**Comment by sa666666** [comment]
Confirmed.  I will look into this when I get a chance.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/9dce4c9db1d1061542038ee1993b87ade9ab4c6d.
