### ISSUE TITLE
State save and restore

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#12]

**Comment by sa666666** [comment]
This is completed for several TIA classes, but cannot be fully completed until all TIA classes are finalized.

**Comment by sa666666** [comment]
Mostly done in https://github.com/stella-emu/stella/commit/fd4122e017562407df64400af8a4334949b95aa9.  Still have to fix TIA display, and figure out how to serialize a vector.

**Comment by sa666666** [comment]
Loading/saving TIA display in debugger now works, which fixes rewind as well.  Done in https://github.com/stella-emu/stella/commit/73beb8cb40194f203aa5a9936f0e0022275d26fe.

**Comment by sa666666** [comment]
Final fix is in https://github.com/stella-emu/stella/commit/94cd456076743a316a152dc1ff110bd741e0093d.
