### ISSUE TITLE
Potential bug in DPC+ music code

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#121]
I have started taking a closer look at DPC+ with the goal of implementing it in 6502.ts. Reading through CartDPCPlus.cxx, it seems to me that there is a bug in updateMusicModeDataFetchers: I think that the block

```
  for(int x = 0; x <= 2; ++x)
  {
    myMusicCounters[x] += myMusicFrequencies[x];
  }
```
really should read
```
  for(int x = 0; x <= 2; ++x)
  {
    myMusicCounters[x] += myMusicFrequencies[x] * wholeClocks;
  }
```
as this basically calculates the time index for sampling the waveforms.

I have done a quick check of the DPC+ demo from [here](http://atariage.com/forums/topic/163495-harmony-dpc-programming/page-1) and Stella indeed sounds seriously out of tune. The change above pretty much fixes this (as far as my ears are concerned) :guitar:

@sa666666 , @SpiceWare , what do you think? For reference, I created a new build of the DPC+
 demo using the latest DPC+ driver I could find as the old one would not run on my harmony cart:
 [dpcp_demo.zip](https://github.com/stella-emu/stella/files/956512/dpcp_demo.zip)

**Comment by sa666666** [comment]
It's entirely possible that this is a bug.  I didn't write that code, and don't really know how it works, but with the fix you provided, the sound is much better.  This also affects the CTY, BUS and CDF schemes, since the code is copied there verbatim.  For BUS at least, adding this fix makes @SpiceWare music demo sound much better.

**Comment by SpiceWare** [comment]
Awesome!  I notice a minor difference in Stay Frosty 2, and that definitely fixed the audio problem with the BUS and CDF music demos.  I'll go ahead and commit the change.

If I remember correctly, batari (Fred Quimby) wrote that part of the driver as I didn't comprehend how he'd implemented the audio in the DPC+ Harmony/Melody driver.

**Comment by sa666666** [comment]
I can fix it if you like, since I already have it ready to be committed.

**Comment by DirtyHairy** [comment]
Great! As you both have the commit ready, I'll refrain from offering to do the change, too :smiling_imp: 

BTW, out of curiosity: is the ARM source for the various harmony drivers available somewhere?

**Comment by sa666666** [comment]
Fix is in https://github.com/stella-emu/stella/commit/742eb36654192bc6482b8ba2b19cf959c0481fb5 for DPC+, BUS, CDF, and https://github.com/stella-emu/stella/commit/3e1b03bed5244a521390dbd4794404fa807d56a2 for CTY.

**Comment by SpiceWare** [comment]
The drivers haven't been released for reasons I'm not sure I can go into in a public area.  I'll send you a PM via AtariAge.

**Comment by sa666666** [comment]
Since this is fixed, I'll go ahead and close this.  Also, nice catch @DirtyHairy.  This is the real benefit of having a new set of eyes looking at old code.
