### ISSUE TITLE
bankswitch hotspots in debugger wrong

### ISSUE THREAD

**Issue by SpiceWare** [stella-emu/stella#123]
While working on the CDF debugger screen, I notice the hotspots are not shown correctly.  This appears throughout the debugger such as for F8:
<img width="648" alt="screen shot 2017-04-25 at 7 54 03 pm" src="https://cloud.githubusercontent.com/assets/26531922/25413599/360be8ea-29f1-11e7-8dc1-26f5a8ab8406.png">

FF8 is in the middle of the 4K cartridge address space, while the actual hotspot is at the end, so it should be displayed as 1FF8 or FFF8.  FFxx makes more sense to me as that's next to the [65xx's vector table](https://en.wikipedia.org/wiki/Interrupts_in_65xx_processors), though 1Fxx is probably easier to parse.

**Comment by thrust26** [comment]
100% correct would be e.g $mff9 (where m = 2n+1, n=0..7), but I have no idea for a short annotation. 

I can live with anything odd (1, 3,... f) instead of m.

**Comment by sa666666** [comment]
I think it was kind of assumed that the user knows this, but I suppose we can change them all to start with 'F'.  This is purely cosmetic, so it's easy to change (it won't affect the logic in any way).  But I will have to finish the TIA tab stuff before I get to this.

**Comment by SpiceWare** [comment]
Woke up and realized I had braino when I typed that last night.  FF8's in the middle of the 6507's 8K address space, not within the cartridge space.  

Programmers who've been working on the 2600 for a while are probably OK with it; but we do see a constant stream of new programmers, whom I could see getting confused by it.

I suspect this was carried over from Kevin's bankswitch list, an [earlier version](http://www.classic-games.com/atari2600/bankswitch.html)(1996) shows this:
```
(blank) No bankswitching.
  F6    FF6/FF7/FF8/FF9 bankswitching
  F8    FF8/FF9 bankswitching
  FA    FF8/FF9/FFA bankswitching (aka CBS' RAM Plus)
...
```
While a [later version](http://www.qotile.net/minidig/docs/sizes.txt)(1997) shows this:
```
  |     - (nothing);  Not bankswitched (2K and 4K only)                   |
  |  F8 - 'Standard' 8K; uses 1FF8 and 1FF9                               |
  |  F6 - 'Standard' 16K; uses 1FF6 to 1FF9                               |
```

Using FF8 would be fine if the hotspots were only *within* the cartridge's 4K addressing space, but it can be outside such as with FE which uses 01FE and 01FF.

Anyway I don't  consider this a high priority, just wondered how we should address it (leading with '1' or 'F') so I could update BUS and CDF while I'm working on their debug widgets.

**Comment by thrust26** [comment]
We could use the addresses which are used (last) in the ROM. Though that would be quite a lot of overkill for such a minor problem.

**Comment by sa666666** [comment]
I'd say just use 'F'.  But if you're absolutely set on '1', I won't argue.  I just need to know which, to be consistent with the rest of the schemes.

**Comment by SpiceWare** [comment]
'F' it is :)

**Comment by ale-79** [comment]
I think there's no reason to indicate different addresses for the 2 banks as the 3 upper bits are irrelevant, and a game can use any of the mirrors for any bank.
If you use 'F' for the hotspots, you should use the same for the address map of each bank. So for F8, it should be

Bank 0 @ $F000 - $FFFF (hotspot = $FFF8)
Bank 1 @ $F000 - $FFFF (hotspot = $FFF9)

**Comment by sa666666** [comment]
In at least a few schemes, those different ranges are actually auto-detected.  That is, they're determined from the disassembly of the ROM, so bank 0 actually **is** in Dxxx, and bank 1 in Fxxx.  Now, whether or not we want to expose that info is another question.

**Comment by thrust26** [comment]
Yup, and I have adapted my code accordingly. For easier debugging, I use different origins for each bank.

**Comment by ale-79** [comment]
Ah, ok. I thought it was a fixed text.
If it's autodetected from the code, it's good to have that info exposed.

**Comment by sa666666** [comment]
It is fixed in some cases.  Perhaps in the cases where it's autodetected, a (*) or something could be placed there, indicating as such.

**Comment by SpiceWare** [comment]
In F8 that's done with this bit of code:
```
  // Eventually, we should query this from the debugger/disassembler
  for(uInt32 i = 0, offset = 0xFFC, spot = 0xFF8; i < 2; ++i, offset += 0x1000)
  {
    uInt16 start = (cart.myImage[offset+1] << 8) | cart.myImage[offset];
    start -= start % 0x1000;
    info << "Bank " << i << " @ $" << Common::Base::HEX4 << start << " - "
         << "$" << (start + 0xFFF) << " (hotspot = $" << (spot+i) << ")\n";
  }
```

That won't work for BUS, CDF, or DPC+ as only the last bank is required to have 6507 code.  For the games I've written so far the other banks only contain ARM assembly and data, though Draconian's most likely going to need 2 banks of 6507 code due to all the reposition kernels.

I've never tried different address ranges ORGs myself as I'd put common subroutines like PosObject in the same location of each bank, and received *Label mismatch errors* when I tried to do so.  However, I do see how it could be a benefit so suspect I should hardcode the text in those formats to use $1000-$1FFF, ... $D000-$DFFF, $F000-$FFFF for the banks.

**Comment by sa666666** [comment]
It's done differently for different schemes.  The straightforward ones (like F8) just look at the reset vector, some use disassembly info, and many don't do anything at all.  This is an area that I never did get back to, so it's inconsistent among different schemes.  The reason I stopped is that other, more important things came up, and also it wasn't always possible to determine it (at least not without a more complete disassembly for multi-bank ROMs, which is something else I'd like to revisit at some point).

**Comment by sa666666** [comment]
These are all now changed in https://github.com/stella-emu/stella/commit/1eca60dac5171d79ed132c837ba7a560dfc0e8d5, as well as removing colons (I was in the same class, so it was easier to do both at once).  It was a good idea to do this, since for some of schemes I had to look back at the documentation to see if they needed an 'F' pre-pended or not (some didn't).

BTW, as for removing colons, should it be done for the general UI too, or just the debugger stuff?

**Comment by thrust26** [comment]
I would prefer it for the whole UI, it looks nice and clean. 

But since it requires a lot of rework (e.g. adjusting the gaps) I will leave that up to you.

**Comment by sa666666** [comment]
This is now done in https://github.com/stella-emu/stella/commit/50cef5767019ba31c241e8f0e0b3706feade4d76.   Barring any other dialogs that pop up, I think it's completed for the entire UI.  Unfortunately, it means all the screenshots for the manual have to be updated :cry:

**Comment by thrust26** [comment]
Before you start doing so, can you post some screenshots for review? In pre7, a few colons were removed without adjusting the gaps between label and field. This should be fixed. E.g.
![label](https://cloud.githubusercontent.com/assets/24360774/25778831/f94b1d78-3309-11e7-8046-3d099a099635.png)

**Comment by sa666666** [comment]
I've changed so much that it's easier to simply do another pre-release and have you look at each dialog yourself.  I will wait another few days for this, since @SpiceWare will be sending updated CDF code soon.

**Comment by SpiceWare** [comment]
Actually BUS code :)

I was planning to check it in this morning, but woke up to find cd-w had posted a number of new CDF drivers that I needed to test as the fix for 7800 support broke other things.  

About to head out for lunch, will wrap up my review and check in BUS (and a few minor changes to CDF) afterwards.  I'll also take a quick look at the Label/Dec/Bin that Thomas posted as I'd removed the colons from there when I was updating the CDF debugging Widget.

**Comment by sa666666** [comment]
I already fixed the Label/Dec/Bin stuff, so you can just concentrate on the new bankswitching code.

**Comment by thrust26** [comment]
The cartridge tab is half done already. The description part is fine, the bank selection part still has colons.

**Comment by sa666666** [comment]
My commits over the past day or so have removed colons from the entire UI.  You're not seeing that yet since I did it after pre7 release.  Once @SpiceWare uploads his bankswitch changes (not for looks, but for logic changes), I'll do another pre-release.
