### ISSUE TITLE
(Symbol) File names used in debugger?

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#136]
When debugging a know game, Stella is looking for .lst and .sym files which have the same name as the Stella database. I am not sure what this is useful for, but it is a bit annoying when disassembling old games. Then all the files generated usually have a different, generic name (e.g. Pitfall.bin, .lst, .sym). Now Stella doesn't use the ROM file name here, but the internal name (e.g. "Pitfall (1982) (Activision)") when looking for the .lst and .sym, which then fails of course. 

A workaround is to change one byte, so that Stella doesn't recognize the ROM. But IMO it would be better if Stella uses the ROM file name here.

Or do I miss something?

**Comment by sa666666** [comment]
So you mean to always use the ROM filename and never the built-in name?  This is easy enough to fix; I just want to make sure that it doesn't break anything else.

**Comment by thrust26** [comment]
Yes, that would help.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/a7b3ee4448238e6f7d53733e3dc1345208acffcc.
