### ISSUE TITLE
Investigate possible backwards compatibility for old DPC+ revisions

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#139]
See [this](http://atariage.com/forums/topic/265938-dpc-playfield-bug-with-stella-4x/) thread on AA. Basically, the question is whether it is worthwhile to support some of the older revisions of the DPC+ driver.

The example that triggered this question is Epic Adventure: this worked fine in Stella 3.x (and is released on AA), but fails on Stella 4.x (jittering playfield) due to @SpiceWare's changes that match DPC+ to recent revisions of the driver. The question is what other revisions of the driver there are, what was changed and whether they were widespread enough to warrent emulation. I think the minimal criterion should be the existence of ROMs released to the AA store or BBasic revisions that used the driver and that worked on real hardware at some point.

Options for emulation would be a non-persistent option via command line and / or cartridge DB and autodetection by checksumming the ARM driver (provided that the number of different driver revisions that circulated makes this manageable).

**Comment by sa666666** [comment]
DPC+ ROMs from an older version of the scheme:

[arm_demo.zip](https://github.com/stella-emu/stella/files/1030506/arm_demo.zip)
Takes quite some time to start up, but eventually immediately enters the debugger with message "instructions > 500000".  Basically it traps on this condition.

[arm_music_demo.zip](https://github.com/stella-emu/stella/files/1030507/arm_music_demo.zip)
Crashes Stella almost immediately.

**Comment by sa666666** [comment]
I'm unable to find a version of Stella where the first demo works.  I've worked back to 3.9.3 so far, without success.  I will continue to search back further still, but note that the further back we go, the more things have changed.

The music demo works from 3.9.3 to 4.7.1, and breaks in 4.7.2.  This is where the Thumbulator ARM emulation code was updated, so I'm hesitant to change anything there (the new code probably fixes a bug in the original ARM assembly that the old ROM was written to use).  Maybe we could at least fix it so Stella doesn't crash, but outputs an error or something.

Also, the ARM code in each ROM doesn't match (now makes sense, since I can't get Stella to work with the first ROM at all).

**Comment by SpiceWare** [comment]
I'm not surprised the early DPC+ ARM examples aren't supported by Stella as it didn't support ARM when those were written.  I'm pretty sure ARM support was in flux at the time, though don't recall specifics of what was changing.  I consider those early ARM demos the same as the WIP demos for BUS and CDF, so I don't see the need to make them work in Stella.

Lack of ARM support made early development of Stay Frosty 2 quite challenging at times.  I often resorted to taking videos of the game, then analyzing them frame-by-frame to figure out problems. You can see that in [Part 11](http://atariage.com/forums/blog/148/entry-11697-the-story-of-stay-frosty-2-part-11/) (extra lines on left/right edge of screen)
![extra lines on left/right edge of screen](http://www.atariage.com/forums/uploads//monthly_01_2015/blogentry-3056-0-14484800-1422722970.jpg)
and [Part 13](http://atariage.com/forums/blog/148/entry-11776-the-story-of-stay-frosty-2-part-13/)(invisible text causing screen roll)
![invisible text causing screen roll](http://www.atariage.com/forums/uploads//monthly_02_2015/blogentry-3056-0-12512500-1424639510.jpg)
of [The Story of Stay Frosty 2](http://atariage.com/forums/blog/blog-148/cat-201-stay-frosty-2).

**Comment by DirtyHairy** [comment]
OK, I have conducted a few experiments, and the results leave slightly confused :confused: I have written a small script to checksum the driver of the DPC+ ROMs that I have lying on my disk (without any claim to completeness):

```
13f6faa1a7542bb70c7b6745c6ae952b - : ./DPC+ ARM Music Demo.bin
17884ec14f9b1d06fe8d617a1fbdcf47 - : ./SFW.bin
17884ec14f9b1d06fe8d617a1fbdcf47 - : ./Space_Cactus_Canyon_Beta_3.bin
17884ec14f9b1d06fe8d617a1fbdcf47 - : ./Space_Cactus_Canyon_beta_2_2.bin
17884ec14f9b1d06fe8d617a1fbdcf47 - : ./epicadv1.bin
56c4ff5eb9bc39d221caa22d200b394c - : ./DPC+ ARM Demo.bin
56c4ff5eb9bc39d221caa22d200b394c - : ./DPC+ demo.bin
5f80b5a5adbe483addc3f6e6f1b472f8 - : ./SF2_20131217_RC8_NTSC.bin
5f80b5a5adbe483addc3f6e6f1b472f8 - : ./collect2.bin
5f80b5a5adbe483addc3f6e6f1b472f8 - : ./dpc+timer.bin
5f80b5a5adbe483addc3f6e6f1b472f8 - : ./dpcp_demo.bin
8dd73b44fd11c488326ce507cbeb19d1 - : ./EMRII22.bin
8dd73b44fd11c488326ce507cbeb19d1 - : ./EMRII29demo.bin
8dd73b44fd11c488326ce507cbeb19d1 - : ./epicadv22.bin
8dd73b44fd11c488326ce507cbeb19d1 - : ./epicadv28.bin
b328dbdf787400c0f0e2b88b425872a5 - : ./scramble_20160106.bin
b328dbdf787400c0f0e2b88b425872a5 - : ./scrolldemo_20150210.bin
b328dbdf787400c0f0e2b88b425872a5 - : ./space_rocks.bin
b328dbdf787400c0f0e2b88b425872a5 - : ./spacerocks20121129_NTSC.bin
```
There are some more, but those are all driver revisions I can identify without digging the forums. Of those, I think `13f6` and `56c4` are ancient and can be ignored.

I then proceeded to strip the driver from `epicadv28` (the latest version of Epic Adventure that I could find) and replaced it with version `b328`, `5f80` and `1788`. Of these, only the most recent one (`5f80`) runs on my Harmony (PAL50, eeloader 1.04e, hbios 1.05). Surprisinglingly, I get **no  playfield jitter** (as opposed to Stella and 6502.ts).

It seems that the current version of the DPC+ driver handles the lowest part of the fractional fetchers differently from the current Stella DPC+ code. @SpiceWare , do you remember what prompted you to make this change in the first place?

For reference, the script I use is 
```
#!/bin/sh

echo `head -c 3072 "$@" | md5sum` : "$1"
```

**Comment by SpiceWare** [comment]
This [topic](http://atariage.com/forums/topic/240879-game-test-on-harmony-cart) is what lead me to add jitter support for variable scanline counts and make the change to DPC+'s fractional fetchers.  Based on [RevEng's reply](http://atariage.com/forums/topic/240879-game-test-on-harmony-cart/?p=3287943) the DPC+ jitter issue is known in the bB community.  I've not done much with bB, so don't know which version of the DPC+ driver they've been using.

There's also a[ patch](http://atariage.com/forums/topic/220696-new-harmony-product-harmony-encore/?p=3107739) that some people have done to fix a [compatibility issue](http://atariage.com/forums/topic/220696-new-harmony-product-harmony-encore/?p=3107645) with the [Harmony Encore](http://harmony.atariage.com/Site/Order_Encore.html) (the version of Harmony that supports games as large as 512K). That'll lead to different checksums even though everything else in the DPC+ driver is the same.  

> To fix any errant DPC+ games, use a hex editor to change the bytes at offset 0x200 from 00 A0 85 to 01 A0 C5. Then they will load on Encore (or any other Harmony version) with no problem.

**Comment by DirtyHairy** [comment]
Interesting. I have applied Batari's change and it indeed fixes `b328` and `1788` :smirk: And, guess what: they jitter. The same fix also lets me run the original build `8dd7`, which doesn't jitter. As a sidenote: the change generates new checksums that are not shared with any other game I have downloaded, so I guess no one circulated any fixed versions.

So, it seems that we have no jittering for ancient versions of the driver, jittering for old ones, and no jittering for the latest version :smile: I'll bring this up at the harmony forum later when I find time and see if I can take a look at the driver source.

**Comment by SpiceWare** [comment]
ran across [this](http://atariage.com/forums/topic/163834-harmony-dpc-arm-programming/?p=2274138) post from 2011 from batari about those old DPC+ demos that don't work anymore:

> Yes, these older demos will not work. At least two reasons for its failure is that these older demos have ARM code for the setup, and the entry points are different. If you rebuild them with the latest custom.S and lds files, they should work.

**Comment by sa666666** [comment]
This was the rabbit hole I spoke of :smiling_imp:

**Comment by DirtyHairy** [comment]
> This was the rabbit hole I spoke of :smiling_imp:

Indeed, but I don't think we have to enter it :stuck_out_tongue: I don't see any compelling reasons to support these old demos --- they're just demos, and they can't be run from hardware anymore, either.

As I said, I am more interested in changes that broke actual, released homebrew that still runs on hardware. Of that type, the BB playfield jitter issue is the only one I could identify so far. Actually, my tests suggest that the latest published DPC+ driver differs from Stellas behavior yet again :smirk: What I want to do now as soon as I find time is to take a look at the disassembly of the various driver revisions and compare the handling of fractional fetchers. If the current driver indeed differs from Stella, I would suggest to match Stella to the current driver, but I'd like to look at the actual driver code before going any further along this road.

**Comment by iesposta** [comment]
I couldn't get an answer from Fred on what was the newest driver when the Harmony Encore first came out, and some DPC+ binaries worked and some didn't. 
He sent me code that seems to always work, however I had to hack 2 instances where DPC was changed to CPC. 
It is just text, but Stella was looking for DPC to set its bank switching, and it failed with "CPC". 

Then he took the hard way IMHO of having the firmware fix all .bins so any version used would work, but I have seen that solution fail and crash the Encore and even corrupt it to where it needs a firmware re-flash to work again. Plus firmware 1.6 was never coded for PAL users. 

For batari Basic he really should have taken this new code I got working, RevEng's bB fixes and additions, given it all his blessing, collected all the latest scattered kernels, Titlescreen kernel, parts and pieces to have a single bB 2.0 download to make setting up a coding development for 2600 games easier. (Or delegate someone to collect everything for him.) And then update his bB website. 
All set up, bB lets basic programmers create binaries from the 1.0 kernel, the other kernel variations and trade offs, the multi-sprite kernel, to the DPC+ kernel. 

Assembly programmers can also use bB as a tool. Code up a complex logic and math routine using basic, and once that's compiled you can read the .lst .sym and .asm output to see what it compiled to get the 6507 to do said routine. And optimize that, or include it directly in their assembly game project.

**Comment by thrust26** [comment]
> Plus firmware 1.6 was never coded for PAL users.

I suppose could fix that by patching the files, because I released an unofficial version 1.7, which allows navigating the menu with a joystick in the right port.

**Comment by SpiceWare** [comment]
CDP+ is a typo, it was supposed to be something else, such as DPC@ or DPCA, and the wrong byte got changed.  It's is a variation on DPC+ where one of the waveform buffers was changed from 32 bytes to 2048 bytes so it could be used for digital sample playback.  More info in this [Harmony Cart Development topic](http://atariage.com/forums/topic/181683-dpc-enhancement)

It was used in [Frantic](http://atariage.com/forums/blog/blog-148/cat-59-frantic) builds during part of 2011.  I ended up [removing the digital samples](http://atariage.com/forums/blog/148/entry-8600-bye-bye-digital-audio/) when we finally figured out the solution to the [bug with the ARM](http://atariage.com/forums/topic/186560-frantic-2600/page-5#entry2362805) that would cause code executing in flash memory to crash under unspecified conditions.  The fix was to partially disable cache, which caused a big enough performance hit that I longer had time for preparing the sample (it had to be copied into a 2K RAM buffer, which is why BUS and CDF can now play packed samples from ROM)

**Comment by sa666666** [comment]
Epic Adventure is now working, and will be in 6.1.  Do we have any other ROMs that we care about, or can we just assume the rest are demos that no longer matter?  Would like to get this closed otherwise.

**Comment by SpiceWare** [comment]
I'm only aware of Epic Adventure.  I'd close it.

**Comment by DirtyHairy** [comment]
I agree; let's close it. If other affected revisions of the driver show up (or if I get to looking at the disassembly of the various different versions as I intented), we can always add their checksum.
