### ISSUE TITLE
Sample playback update for BUS & CDF

### ISSUE THREAD

**Issue by SpiceWare** [stella-emu/stella#140]
The original sample playback would only work for samples stored in ROM.  This update allows a sample to be played back from RAM.  

The changes are in the peek() functions of CartBUS.cxx and CartCDF.cxx

[Archive.zip](https://github.com/stella-emu/stella/files/1034329/Archive.zip)

Discovered this bug while implementing Draconian's 2-channel sound effect support, which is complicated by having to co-exist with Digital Samples.  Samples are played by doing a 
```
LDA #<AMPLITUDE
STA AUDV0
``` 
on every scanline, so for a sound effect to work on channel 0 I create a 1 byte sample of VOL * 0x11 for the current sound effect.   The 0x11 is because the upper or lower nybble may be used due to the "unpack the sample" logic.

**Comment by sa666666** [comment]
Committed in https://github.com/stella-emu/stella/commit/e419bbbcabd181dd59a242ade0f390d836b272bb.
