### ISSUE TITLE
Random startup bank

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#141]
I am not sure, if this was requested before. Anyway:

Currently Stella seems to start always at bank 0. AFAIK, on real hardware the start bank is random. So this bank should be randomized. Maybe with an option like randomizing the CPU at startup.

**Comment by sa666666** [comment]
Is this true for all schemes?  I guess the option can be added, and just not used for schemes that are hardcoded to work in a specific bank??

**Comment by thrust26** [comment]
For the standard Atari schemes this is true, for the others I am not sure. 

If the add that as an option (off by default), we can test the other schemes.

**Comment by DirtyHairy** [comment]
Actually, I am pretty sure that I have encountered historic schemes and ROMs that crash in certain startup configurations; I just don't remember any examples from the top of my head. I'd advise **very** carefuly testing if we are to implement this, some ROMs **will** break.

**Comment by thrust26** [comment]
Quite some ROMs break with randomizing unused TIA pins, so as long as this is just an option, I cannot see a problem here. And it will help to avoid errors during development,.

**Comment by DirtyHairy** [comment]
Hm, I don't quite agree about the definition of errors here --- if a historic bankswitch scheme actually started up in a specific configuration, it is absolutely correct for homebrew to assume the same thing from an emulator. Randomizing undefined TIA reads is slightly different to me, as this is actually really software relying on a undefined hardware state that (afaik) is known to break on real hardware, too :smirk:

Nevertheless, this is propably splitting hairs, I see no harm with an option here, either. However, I would consider overlaying a warning on the screen if this options is enabled, in order to avoid yet another reason for bogus bug reports. Now that I think about it, that would make sense for "drive unused...", too :smiley:

**Comment by DirtyHairy** [comment]
Addentum: I just did some experimenting and I could not come up with a working example of a historic game depending on a specific initial bank. So, maybe, it may be just my memory playing tricks on me :smirk:

**Comment by sa666666** [comment]
Have a look at the c'tors in the various Cart classes.  There are a few cases where the start bank needs to be a certain value, and others where 0 was just chosen.  If we add the option (and have if default to off), then I guess it could be used in the case where 0 was chosen.

**Comment by DirtyHairy** [comment]
I have been looking at the 6502.ts code with the same reasoning :smiley: There, I have a peculiar selection for F8 (bank 1), and there is special handling in Stella as well for this one --- it even contains special cases for particular ROM checksums.

Tigervision is another thing that comes to my mind. I have found one resource (http://problemkaputt.de/2k6specs.htm) that mentions a particular initial state that is enforced by real hardware. I'll try to reproduce this later when I find time.

**Comment by sa666666** [comment]
That's the nocash emulator page.  You're right that the document contains quite a few errors, but some parts of it that we need may be valid.  After all, even a stopped clock is right twice a day :smiling_imp:

**Comment by sa666666** [comment]
Have we decided whether we want this?  It is easy enough to add.  It is also easy to only enable it for certain bankswitch schemes (since we need to modify every class that will use anyway).

**Comment by DirtyHairy** [comment]
I see no harm in adding the option. However, I'd suggest to hold this off until 5.0 is released :smirk:

**Comment by thrust26** [comment]
Implemented in a14fa6a for DPC, F0, F4, F4SC, F6, F6SC, F8, F8SC, FA, FA2 and UA.

EF and EFSC might work too, but does even a ROM exist which uses them?

Any others I am missing?

**Comment by thrust26** [comment]
@DirtyHairy 
> Tigervision is another thing that comes to my mind. I have found one resource (http://problemkaputt.de/2k6specs.htm) that mentions a particular initial state that is enforced by real hardware. I'll try to reproduce this later when I find time. However, these docs do contain other flaws, so it is entirely possible that this is a fluke.

I checked all Tigervision 8K ROMs. The all take care for random startup banks, except for one version of Polaris (md5: 203049f4d8290bb4521cc4402415e737). This version requires 3 as startup bank or the RAM initialized with 0. The latter is the reason why it currently works with a fixed startup bank of 0.

Since this is the only exception, there are two possibilities:
1. the startup bank can be random, the Polaris version is buggy
2. that version of Polaris came late and meanwhile the developers had learned that 3F always starts at bank 3.

I am pretty sure it is 1.

**Comment by DirtyHairy** [comment]
@thrust26 I just checked this version of Polaris. Even starting from bank 3, I get varying glitches that depend on initial RAM state (garbled logo, submarine on main screen moves backwards, frame start jump, garbage sprites etc.). I think your theory of a bad dump may be correct.

**Comment by thrust26** [comment]
The ROM works with startup bank 0 and RAM initialized to 0. But that's just plain luck.

**Comment by thrust26** [comment]
All original types are covered. Except for FE which requires starting in bank 0 due to Decathlon (no startup vector in bank 1).

**Comment by andrew-davie** [comment]
Bear with me while I fix up that exemplar... doh

**Comment by andrew-davie** [comment]
Here are the exemplars.  Both will run on Stella.
"hardwired" will fail if the startup bank is non-zero.
the other will work regardless of startup bank
May be useful for future testing, I hope!

**Comment by thrust26** [comment]
It depends on the cart's hardware if the startup bank is random or not. That's why some ROMs only work with bank 0. Stella starts with bank 0 if no startup bank is defined in the code. Or a different bank which can be defined in Stella's ROM properties. 

If you want random banks, enable that in developer options.
