### ISSUE TITLE
Add ability to override per-ROM phosphor effect and blend level

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#144]
The current default blend level is 30, but I foresee a need to be able to change that dynamically, without having to release a new version of Stella, and without having to modify every single ROM that uses phosphor mode.  So I propose a video setting where we can override both enablement and blend level globally, with the option to revert to per-ROM settings too.

**Comment by sa666666** [comment]
For now, only the global default blend level is implemented.  We can revisit global enablement in a future release if it is desired.

**Comment by ale-79** [comment]
> We can revisit global enablement in a future release if it is desired.

I vote for adding that in future releases. I'd like a way to enable the new phosphor mode for all roms (together with the blargg effects, it looks truer to a real CRT, so I see no reason to disable it) .

**Comment by sa666666** [comment]
I decided to go ahead and implement global enablement of phosphor mode in https://github.com/stella-emu/stella/commit/bd759b68cb14cef23ea0db894cba57c7509e4714.

**Comment by thrust26** [comment]
Something doesn't work well here. 

If -ppblend is set to e.g. 50 and I then use "Stella.exe -ppblend 30" and open a ROM which doesn't use phosphor, a blend of 30 is displayed in Game Properties/Display. So it seems a new default is set. However, if I then exit and start Stella again without parameter, the same ROM displays 50 again.

**Comment by sa666666** [comment]
It is somewhat confusing.  Being able to edit something in 2 places is always confusing.  Plus, it was added late in the development cycle, so it didn't get a lot of testing.
