### ISSUE TITLE
Screen 'jumps' when starting a ROM

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#149]
@DirtyHairy, this is more directed to you, since you're more familiar with the relevant code.  And I think this was mentioned before, but I forget where, so I'm starting another issue.

Sometimes when starting up a ROM, the picture jumps into place.  I assume this is the ystart autodetection happening.  It's fairly obvious in River Raid, but also in quite a few other ROMs (sometimes you have to restart the ROM a few times to see it).  Now this isn't a major issue, and probably not worth holding up the 5.0 release for, but it would be nice if this could be fixed.  It didn't happen in Stella 4.x (since we didn't have ystart autodetection), so it could be seen as a regression.

**Comment by DirtyHairy** [comment]
Unfortunately, I think that there is no easy fix for this. Depending on how the first few frames look like, the autodetection algorithm may take a few frame to lock onto the signal. In this time, the image will exhibit the observed "jump". What might work is supressing the first few frames of display until the algorithm has stabilized. I'll give this a shot later this week.

**Comment by DirtyHairy** [comment]
bdded5e6 implements this by enforcing at least 10 stable frames (frames where the detected ystart has not changed) before rendering starts. If 20 frames have passed, rendering starts anyway.

My testcase is Demon Attack (I can't see the effect on River Raid), and with these settings, the jump is gone for me, at the price of a small delay before rendering starts (the first few frames are gobbled). Interestingly, I was seeing occasional jumps even if I fixed ystart, so I guess that, at least for Demon Attack, the timing of the first rendered frame might really depend on the initial state.
