### ISSUE TITLE
Small scanline jumps and the 'TV jitter/roll effect'

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#150]
Something new that I noticed after jitter effect has been re-implemented; some ROMs now have inconsistent scanline counts each frame, and with jitter enabled the entire image is unstable.  Yahtzee is the most obvious example.  It has scanline count of 257/259 alternating, and when jitter is turned on the dice are unstable.  Now this could be related to #149, or could just be how the jitter effect works.  I believe in the old implementation, we skipped scanline differences of 2 or less, so only 3 or more activated the jittering.

I just noticed that this is also present in 'Tapper' ROM, where the counts are 261/262.

EDIT: I should add that I feel that skipping the case of 2 or less scanlines is 'hacky', and somehow feels wrong.  It will fix the ROMs in question, but I'd really like to have a better understanding of why those ROMs aren't unstable on a real console.

**Comment by thrust26** [comment]
For me Yahtzee jumps in both versions (less in 4.7 and more in 5.0), but not on my TV. Debugging shows that the dices always start in scanline 39. So the is only a difference in overscan between frames, which seems to be ignored by my TV.

BTW: The ROM also has a problem with VBLANK, which is not enabled every other frame.

**Comment by sa666666** [comment]
If the die should always start in scanline 39, then the issue is really in #149 (or related), and once fixed there, the jitter/roll effect shouldn't detect any difference.

**Comment by thrust26** [comment]
Scan line differences above the display kernel are always noticeable, while **small** differences below are absorbed by CRTs.

**Comment by thrust26** [comment]
BTW: Yahtzee shows in color on my PAL **Crt**, both screens, title (246 scan lines) and in game (257/259). 

Hmm...

**Comment by DirtyHairy** [comment]
Both Yahtzee and Tapper actually *do* produce an unstable signal. For Yahtzee, turning on logging output in FrameManager gives

```
vsync 0 -> 1: state 0 @ 15
state change 0 -> 1 @ 15
vsync 1 -> 0: state 1 @ 3
state change 1 -> 2 @ 3
frame complete @ 0 (257 total)
state change 2 -> 3 @ 27
state change 3 -> 0 @ 212
vsync 0 -> 1: state 0 @ 17
state change 0 -> 1 @ 17
vsync 1 -> 0: state 1 @ 3
state change 1 -> 2 @ 3
frame complete @ 0 (259 total)
state change 2 -> 3 @ 27
state change 3 -> 0 @ 212
```
This demonstrates that the game alternates between 15 and 17 lines overscan. As Thomas said, this propably lies in the tolerance region of real CRTs, but in Stella, it triggers Jitter emulation. I don't see any alternative other than the hack you suggested: ignore small frame height changes. As real CRTs behave the same way, I think this is fine. I guess I can do this the next few days if we agree :smirk:

**Comment by thrust26** [comment]
If possible (do you have CRTs to test?), we should test Yahtzee on a few other CRTs. Also I could provide a simple test program, which lets us test the tolerances of those CRTs.

Same for the PAL color loss issue. But IMO that has time for a later release.

**Comment by thrust26** [comment]
I have created a small test program. It alternatively displays one frame with 262 (right difficulty = B) or 312 (right difficulty = A) scan lines and the other frame with a changed number of scan lines. The delta can be controlled with joystick up and down. 

On the screen, below the current delta value, there is a colored rectangle, which (for PAL) allows checking for color loss.

[TestJitter.zip](https://github.com/stella-emu/stella/files/1070834/TestJitter.zip)

The results for my 15"PAL Sony Trinitron:
- In NTSC mode, it looses sync at delta = -19 (= 243 scan lines) and (probably) switches between PAL and NTSC at +26 (288). In between the picture is completely stable, no jitter at all.
- In PAL mode, it starts switching between PAL and NTSC at -25 (287) and stays stable up to the maximum of 49 (361).
- The color behaves interestingly: With odd delta values (no matter how large or small), the top lines (~20%) of the green rectangle flicker in an orange color. Below there is another area (~15%) where it flickers between orange and green. The remaining area is plain green, same as with even deltas.

So for my CRT and this test case, the jitter tolerance is pretty large. And emulating colors loss seems pretty complicated.

**Comment by DirtyHairy** [comment]
Unfortunately, I don't own a CRT, so I am pretty much useless when it comes to testing here :smirk: I plan on getting one when we move into our house next year, but if I cram one in our flat my wife may be throwing me out :smile:

Your results are interesting. Did you also tried Darrell's jitter test on the Sony (I think it is attached in #11)? I have a suspicion that the CRT may behave differently depending on whether the scanline mismatch in in vsync or in overscan.

**Comment by thrust26** [comment]
I just tested Darrell's jitter program with values around 128:
- between 126 and 130 the picture is perfectly stable
- at 125 there is a noticeable (~40 scan lines) roll up and then down again 
- the smaller the values, the bigger the roll up gets 
- at 131 there is a minimal (5-10 scan lines) roll down and then up again 
- the larger the values, the bigger the roll down gets 
- the recovery time is always very fast, maybe 5-10 frames
- sometimes (1 out of ~5) no roll happens (not sure if this info is useful)
- no noticeable difference between PAL and NTSC

The code does about the same as my test. But here the changes are permanently, where in my test, the change only happens every other frame. 

Conclusion (for my CRT):
- **permanent** changes of +/-2 scan lines cause no roll at all*, above the roll starts and gets stronger with the changes
- **temporary** changes cause no roll at all

*else some imperfectly programmed old games (e.g. Congo Bongo or Gas Hog) would roll permanently

I am quite sure it makes no difference to jitter where the scanline mismatch happens. The CRT doesn't know that.

**Comment by ale-79** [comment]
I tried the  "TestJitter" rom on my 28" sony and I get the same results as Thomas.
Regarding "Tapper", it displays interlaced on my TV ([http://atariage.com/forums/topic/260024-tapper-cart-vertical-hold-issue/#entry3652188](http://atariage.com/forums/topic/260024-tapper-cart-vertical-hold-issue/#entry3652188)), and with the wrong colors in the top part of the screen (I have to find an older TV from the '80s. Probably there would be color loss there, while wrong colors in the top area of the screen is how more recent TVs behave with odd number of scanlines).

**Comment by DirtyHairy** [comment]
To me these result suggest improving the jitter simulation by ignoring scanline changes that don't persist over several changes or are small. I think we have to do this before releasing 5.0 as the current implementation breaks any ROM that is flawed this way.

**Comment by DirtyHairy** [comment]
I've limited jitter to frame differences of tree or more scanlines in 628133d2. As for the temporal component: @thrust26 , @ale-79 , do you have a feeling of how many frames it takes fir jitter to start (just a rough estimate, I don't think it is worthwhile to try and be overly precise here)?

**Comment by thrust26** [comment]
More than one. Else, no clue, sorry.

**Comment by DirtyHairy** [comment]
:smile: OK, if Alex doesn't have a better estimate I'll make it three. Have a nice vacation!

**Comment by thrust26** [comment]
That should work, I doubt this will break any existing original games or any well programmed homebrew.

**Comment by ale-79** [comment]
> OK, if Alex doesn't have a better estimate I'll make it three. 

I haven't, and I can't think an easy way to measure it. 
If it doesn't break original games, it's fine.

@thrust26 
Have a good time on your vacation!

**Comment by DirtyHairy** [comment]
I think breaking anything is virtually impossible, unless there is some twisted piece of code that actually *relies* on jittering.

**Comment by DirtyHairy** [comment]
4515e79b changes jitter to take effect only if the "stable frame height" has changed. "stable frame height" in this context means the last time frame height was constant for three or more consecutive frames.
