### ISSUE TITLE
Expand the launcher's search box capabilities.

### ISSUE THREAD

**Issue by Keatah** [stella-emu/stella#154]
Expand the launcher's search box capabilities so that it can look inside sub-folders.

Is there a way to use the search box to search through all folders and sub-folders in a "master directory"? If not, perhaps prepending or appending the search term with a unique string could trigger the function. Something like from the old modem days, +++ or ~^~. When the search routine sees that it it would look in all sub-folders. To make it polished, the string could be user-definable too.

Perhaps a simple check-box next to the search box could be used to determine if searches look in all folders or just the current folder.

Additionally more support for regular expressions would be nice.

**Comment by Keatah** [comment]
Adding these here from the Stella test thread on AA.

I have a couple of more feature suggestions:

1- In the Game List, being able to move to directories using Shift + (letter). For example, I keep my ROMs sorted by manufacturer, so being able to type Shift + P to jump to Parker Bros.

2- And consequently the search box should recognize a folder's brackets [Atari].

3- Being able to save a game screenshot from the debugger with F12.

**Comment by sa666666** [comment]
Point 1 and 2 is #160.
Point 3 is issue #161.

**Comment by thrust26** [comment]
Wildcard support has been added with 94fae3de.

**Comment by sa666666** [comment]
@thrust26, I think we are done with this one?

**Comment by thrust26** [comment]
I have improved the code a bit. I will commit and close.

**Comment by thrust26** [comment]
Subdirectory search implemented with 9a68e484
