### ISSUE TITLE
Debugger documentation error for trap ranges

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#156]
For setting a range of traps the documentation says:
> trapread - Trap read access to address(es) xx [to yy]

So I typed "trap CXP0M **to** CXPPMM" and this doesn't work, instead "trap CXP0M CXPPMM" does work. IMO the "to" is wrong or at least irritating in the doc.

**Comment by sa666666** [comment]
Neither the actual documentation text or snapshots have been updated yet.  This is a known issue.

**Comment by thrust26** [comment]
Oh, has the syntax been changed here?

**Comment by sa666666** [comment]
Yes, in #99.

**Comment by thrust26** [comment]
Ah, missed that detail. Thanks!

**Comment by sa666666** [comment]
Well, technically it is still a bug, so the issue could have been left open.  Or closed I guess, it doesn't really matter; I need to get to it soon anyway.

**Comment by thrust26** [comment]
Whatever you prefer. :)

**Comment by sa666666** [comment]
I'm reopening this, since I will forget to fix it otherwise.
