### ISSUE TITLE
listtraps too verbose

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#157]
Due to all possible mirrors being listed too, listtraps became not very useful anymore. 

I suggest to list only the original labels/addresses and state "+ mirrors" (like when setting a new trap). 

And for those who need to know more details, maybe a new prompt command (or extra parameter for listtraps) to list all mirrors for a certain address or address range.

**Comment by thrust26** [comment]
For me it shows ... + mirrors. What exactly did you test?

**Comment by ale-79** [comment]
Try setting more traps (see attached screenshot)
![senzanome](https://user-images.githubusercontent.com/24704739/29251765-64549790-805b-11e7-91df-2eab24b26eeb.png)

**Comment by thrust26** [comment]
Confirmed.

**Comment by sa666666** [comment]
Let's make sure the discussion happens in the other item (#190).  Technically, this one here is already fixed (output is no longer verbose).
