### ISSUE TITLE
High CPU usage in Rom Selector screen.

### ISSUE THREAD

**Issue by Keatah** [stella-emu/stella#159]

**Comment by Keatah** [comment]
This may or may not be similar to the high-usage in the Debugger screen. But on an energy efficient Atom or Celeron 1.4Ghz machine I can see 50% CPU in both the Debugger and ROM Selector screens. And on a truly legacy machine, it pegs at 100% and everything slows down. But yet the actual emulation for playing games is fine and uses less CPU power.

3.9.3 doesn't have this problem - it idles in the ROM Selector screen at just a couple 2 or 3 percent at most. This seemed to have changed to high power consumption when Direct3D, OpenGLES, and OpenGLES2 were added as new/additional renderer options. Whichever version that was I don't recall offhand.

It doesn't really matter what option is selected though. Personally I think the problem lies with the graphic libraries being used.

**Comment by sa666666** [comment]
Same issue as #158, so all communication will happen there.
