### ISSUE TITLE
Feature Request - front end navigation

### ISSUE THREAD

**Issue by NathanStrum** [stella-emu/stella#160]
It would be great to be able to select directories in the front end list by using Shift + typing the first letter(s) of a directory's name. Example: Shift+ T, E would select Telesys. Or Shift+ T, I would select Tigervision.

**Comment by thrust26** [comment]
@NathanStrum Did you know that you can search with e.g. 'space', '[', 't', 'e' ... here?
@sa666666 Is there a reason for the space in front of the directories? Without it, the current directory search would become a bit easier.
