### ISSUE TITLE
Open documentation tasks

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#164]
This ticket is a tracker for open documentation tasks.

* ~~Changed behavior of phosphor effect, cf. #75~~
* ~~Changes to trackball controller naming, cf. #111~~
* ~~Debug color changes (those again :smirk:), cf. #114 , #162~~
* ~~Changed debugger traps, cf.  #156~~ 
* ~~Debugger command line changes, #99~~
* ~~Document delay queue widget, cf. #15~~
* ~~Document shadow register display handling in debugger, cf. #15~~
* ~~Document frame autodetection (many different tickets)~~

**Comment by DirtyHairy** [comment]
I've put my name behind the items that I think would be best documented by me. I suggest that we modify the ticket description to keept it up to date and ~~strike through~~ those items that have been adressed.

**Comment by sa666666** [comment]
Trakball updates in https://github.com/stella-emu/stella/commit/e1bc5c92e470b97662f1802a34e3ac9281b86d5c.

**Comment by sa666666** [comment]
Debugger traps fixed in https://github.com/stella-emu/stella/commit/f177aed814dd75d0a40515b9840d584714f54a6c.

**Comment by sa666666** [comment]
Further debugger documentation updates, and updated all debugger screenshots (new functionality, removed colons, etc).

@DirtyHairy and @thrust26, there is a FIXME in debugger.html where a better description of the new TIA functionality should go.  This is probably where the #15 items above should be described.

**Comment by DirtyHairy** [comment]
Thanks! I was going to write some documentation yesterday evening, but real life got the better of me --- I'll do it in the next few days :smirk:

**Comment by DirtyHairy** [comment]
@sa666666 Do you have any preferences where documentation related the frame autodetect should go?

**Comment by sa666666** [comment]
No, and I'm not sure what to really say about it either.  I guess once we decide what to say, then it will become obvious what section it goes under.

**Comment by DirtyHairy** [comment]
Good question :smile: I wondered about the same thing, and I think we should 1. mention that it exists and 2. how to configure it.

**Comment by thrust26** [comment]
I am on a cycling tour for the next 2 weeks, only afterwards I could document phosphor.

**Comment by DirtyHairy** [comment]
> I am on a cycling tour for the next 2 weeks, only afterwards I could document phosphor.

Happy cycling :bike:

**Comment by sa666666** [comment]
TBH, there's not really much to document about the phosphor stuff.  Mostly the new UI that I am creating for it, and how the default value can be changed but per-ROM can still be used, etc.  But beyond that, what do we really say?  It's there, it quite accurately emulates blending of frames on a real TV, and here a few sliders to adjust it :smile: 

Also, good luck on the cycling and the rest of your vacation.  Don't worry about documenting this; I'll get to it, since I plan to have the new release done before 2 weeks time.

**Comment by DirtyHairy** [comment]
aa5be284 adds a short note on setting ystart to zero for autodetect. @sa666666 , ping me if you'd like to see this somewhere else.

**Comment by sa666666** [comment]
I've decided to do the release on Sunday, July 16 (a week from today).  All is left is adding a UI to set the debug colours, and documentation updates.

If anyone has anything else that needs to be done, please contact me this week.  It's time to get this done and out there ...

**Comment by sa666666** [comment]
@DirtyHairy, could you also think of some things to add about the TIA to the Change.txt file?  Right now it's quite sparse, but the new TIA is the major feature of the new release, so the changelog should reflect that.

**Comment by DirtyHairy** [comment]
Will do. However, I am travelling the 'till thursday, so it may take some time until I get to it, but uit'll be definitely done before sunday :smirk:

**Comment by sa666666** [comment]
Added phosphor and debug colors information in https://github.com/stella-emu/stella/commit/d74bbba4f97e246d845b02d6d93f1ec21c3edfcc.  I'll leave this open until @DirtyHairy completes what he mentioned above, but otherwise I think we're mostly done.

**Comment by DirtyHairy** [comment]
Will do today, didn't find time before 😉

**Comment by DirtyHairy** [comment]
I've added what I could scrape from my brain in 30f1e268. Closing...

**Comment by sa666666** [comment]
I think that's it.  I'm about to do up the webpages and builds now, and release it tomorrow morning.  Thanks everyone for the work on this, and hopefully this will be the best release ever :smile:

**Comment by DirtyHairy** [comment]
Thanks for all the work you are putting into Stella 😊

**Comment by sa666666** [comment]
Release is now done, and mentioned at http://atariage.com/forums/topic/267810-stella-50-released.  There will also be a link on the main AtariAge frontpage soon.

**Comment by thrust26** [comment]
Can we add some additional information to the phosphor mode? I would like to describe that the optimal blend rate will differ between the monitors used. For slow LCDs a lower blend rate should be used than for fast LCDs. And due to the way a LCD works, the phosphor mode can never be 100% like on a real CRT.

Probably that would best fit to -tv.phosblend.

**Comment by sa666666** [comment]
Go ahead and add the text :smile:   You can set up git access, download, and then do a pull request.  Or just write up what you want, and I'll include it.  The reason I ask that you do it is that you wrote the code, so you can explain best what it is you want to say.

**Comment by thrust26** [comment]
Will do.

BTW: -ppblend <number> | Set "Display.PPBlend" property, used for phosphor effect (0-100). Default is 77.

Isn't the default 50?

**Comment by thrust26** [comment]
Here is my text (please add at the end of existing -ppblend description):
_Higher blend values will intensify the phosphor effect. Depending on your display and personal preferences, the optimal default for you may vary. Slow LCDs (especially for office use) may only need a low blend of around 30, while fast switching gamer LCDs may need about 70 to look similar to a CRT._

**Comment by sa666666** [comment]
Yes, that's a typo.  But technically it isn't 50 per-se; it's whatever -tv.phosblend is set to.  So that setting changes the default for the other one.  A bit confusing, I know.

To be clear, the default for -ppblend is technically 0, which means to use whatever is defined by -tv.phosblend.  This confusion results from the fact that there is now a global setting, as well as a per-ROM setting.

**Comment by thrust26** [comment]
But for the user it is 50, because that's the GUI value displayed, even if phosphor is disabled and has never been set differently.

**Comment by sa666666** [comment]
I will add the text in a moment.  However, just wanted to mention that tv.phosphor, tv.phosblend, and ppblend are all mentioned in the manual.  For the former two, they are also mentioned next to a screenshot of their corresponding UI items.

**Comment by thrust26** [comment]
My bad. For whatever reason I had looked into the documentation of pre9.

**Comment by sa666666** [comment]
This is now fixed in https://github.com/stella-emu/stella/commit/11ee61e3512de2b1f78ccc1601f011ec1cc1724b.  If this is the only issue, you can go ahead and close this again.
