### ISSUE TITLE
Breaking on late WSYNCs

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#169]
I am not sure if this is already possible.

Being able to set a Break when a WSYNC is started at cycle 74 or 75 would be helpful for kernel optimization and debugging.

**Comment by sa666666** [comment]
Stop adding new requests :imp: 

Seriously though, this one would probably be best served by creating a special '_wsync' pseudo-op in the  debugger.

**Comment by thrust26** [comment]
Good idea.

No new ideas. (until maybe I travel back by train in two weeks. ;)

**Comment by thrust26** [comment]
Added new pseudo-op `_scycles` (cycles into current scanline, just for convenience because `_scycles*3==_cclocks`)

This can be handled with trapif (e.g. _trapif_ _\_scycles>#74_ _WSYNC_)
