### ISSUE TITLE
Autocomplete in debugger

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#170]
I am pretty bad a typing without errors, so autocomplete for debugger commands and labels would be cool. 😄 Also filtering previous commands when starting to type.

Similar to Windows command line.

**Comment by sa666666** [comment]
The first one (autocomplete) is mostly present.  In fact I just fixed a bug less than a week ago where one had to use uppercase only for TIA registers; now you can autocomplete on upper or lowercase (or a mixture).

The second one (search through history) would be very nice.  I find myself wanting that quite a bit at times.

**Comment by thrust26** [comment]
Redundant to #240
