### ISSUE TITLE
Enhanced label display (was: Mouse over labels in memory windows)

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#171]
When hovering over e.g. the ZP or cartridge RAM, it would be helpful if the label name would be displayed. If no label for this address is defined then display the previous label (e.g. "gfxPtr+1").

**Comment by sa666666** [comment]
This one might be stretching the limits of the UI code in Stella.  Remember that the code came from ScummVM, and was meant for use as a simple UI only; adding temporary mouseovers, popups, etc may prove difficult.

**Comment by thrust26** [comment]
If the UI code doesn't allow this easily, close this issue. It's not THAT important.

**Comment by thrust26** [comment]
Would it be possible to enhance the label display in general? 

If e.g. $80 is defined as "pointer" and $81 is undefined, then the label would display "pointer+1" for $81 (instead of ram_81). So that whenever an address is undefined the previously defined address is used and the offset is displayed. 

This would not only help for the RAM display but also make the disassembly much more readable.

**Comment by thrust26** [comment]
This should be configurable, because it only makes sense for own code, where all labels are defined. For foreign ROMs, where almost no labels are known, this would be confusing.

**Comment by thrust26** [comment]
This is now done with the tool tips.
