### ISSUE TITLE
Inconsistent behaviour when reading from write-only TIA registers

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#173]
This is from http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-15#entry3803462.  Basically, the ROM shows pink invaders in Stella 5.0, and white in Stella 4.0 (and all other emulators).  I think I fixed this in Stella 4.x, but it may be a regression in the current core.

In the current code:
>// If pins are undriven, we start with the last databus value
>// Otherwise, there is some randomness injected into the mix
>// In either case, we start out with D7 and D6 disabled (the only
>// valid bits in a TIA read), and selectively enable them
>uInt8 lastDataBusValue =
    !myTIAPinsDriven ? mySystem->getDataBusState() : mySystem->getDataBusState(0xFF);
> ...
>return (result & 0xC0) | (lastDataBusValue & 0x3F);

Note that this seems to sometimes enable the upper 2 bits.

From Stella 4.x: 
>// If pins are undriven, we start with the last databus value
>// Otherwise, there is some randomness injected into the mix
>// In either case, we start out with D7 and D6 disabled (the only
>// valid bits in a TIA read), and selectively enable them
>uInt8 value = 0x3F & (!myTIAPinsDriven ? mySystem->getDataBusState() :
>                        mySystem->getDataBusState(0xFF));
>  ...
>// This shouldn't happen, but if it does, we essentially just
>// return the last databus value with bits D6 and D7 zeroed out
>return value;

So it seems that in Stella 4.x, bits D7 and D6 are always 0.  And in Stella 5.0, they can sometimes be 1.  Tests on real hardware seem to confirm that Stella 4.x is correct here.

**Comment by sa666666** [comment]
OK, now I'm completely lost.  After looking at the Stella Programmers Guide, I see that D7 and D6 are the only valid bits used for a TIA peek.  So now I don't know what the code in Stella 4.x is doing at all :confused:  @DirtyHairy, can you offer any suggestions??

**Comment by sa666666** [comment]
The major difference I see is that in the new code, the default case assigns the last databus value to 'result', while the code in Stella 4.x doesn't do anything in the default case.  Sure enough, if I set result to 0 in the default case, it matches Stella 4.x behaviour.  The question is whether this is correct or not.  I think it is, since the last databus state shouldn't affect bits that can be set by collisions, only the bits that are floating.

**Comment by DirtyHairy** [comment]
If I remember the code correctly, my reasoning was that, if the read doesn't match a valid registers, all bits are undriven. However, I really don't know for sure what real hardware is doing - this depends on the details of the TIA schematics. A test ROM might clarify the issue but, until then, if Stella 4 matches hardware, I suggest we stick with it 😉 I am currently abroad, so it'll take some time until I can look at this more closely.

**Comment by sa666666** [comment]
My assumption is that the applicable bits are zeroed, and only the unused bits are undriven.  In fact, this difference in assumptions is exactly the difference in behaviour we're seeing.  For now, I'm going to revert the functionality to Stella 4.x, since it matches real hardware and all the other emulators.  Maybe we can re-visit this after 5.0, and analyze in more detail.

**Comment by DirtyHairy** [comment]
If Stella 4 matches hardware, then I guess you are correct: D7 and D6 are always driven and are low if no valid read drives then high.
