### ISSUE TITLE
Check Blargg presets

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#179]
Where do the values for the predefined TV Effect parameters come from? They seem to match these (  [https://emulation.miraheze.org/wiki/File:NTSC_settings.png](url)) divided by 2, but not exactly. 

- For Composite the resolution is 57 vs 50 
- S-Video is most different: Sharpness 50 vs 60, Resolution 72 vs 60
- RGB is 100% identical

I wonder why there are differences.

**Comment by sa666666** [comment]
The link above doesn't work.

The actual definitions are at the bottom of https://github.com/stella-emu/stella/blob/master/src/common/tv_filters/AtariNTSC.cxx.  The definition for "struct Setup" is near the top of https://github.com/stella-emu/stella/blob/master/src/common/tv_filters/AtariNTSC.hxx.

**Comment by thrust26** [comment]
Try this one: https://emulation.miraheze.org/wiki/File:NTSC_settings.png

**Comment by sa666666** [comment]
Assuming I haven't made a mistake in coding, I guess it depends on who we consider the authoritative opinion on these settings; Blargg or the link you mentioned.  Code-wise, it's easy enough to change; I just need justification for which one to pick.

**Comment by thrust26** [comment]
I checked the settings for SNES and SMS too (search for e.g. _snes_ntsc.c_ and _.h_). Here are the values:

Stella (sharpness, resolution):
- Composite: 50, **57**
- S-Video: **50**, **72**
- RGB: 60, 85

NES & SNES:
- Composite: 50, 50 
- S-Video: 60, 60
- RGB: 60, 85

SMS:
- Composite: 50, 63 
- S-Video: 50, 63
- RGB: 60, 85

All other parameters are completely identical. So only exactly the values in question differ between SMS and (S)NES. 

Now the only question left is, who defined those values and especially those for Stella? @sa666666 Were the same values in the original source code you got? And who provided that?

**Comment by snes2600** [comment]
blargg atari_ntsc filters have a somewhat complicated history.

> 1) early version for Atari 800
http://svn.akop.org/psp/tags/atari800/2.1.0.1/atari_ntsc.c
http://svn.akop.org/psp/tags/atari800/2.1.0.1/atari_ntsc.h

> 2) 2006 update for Kat 5200
https://kat5200.jillybunch.com/downloads/kat5200-0.8.1.tar.gz
```
0.0, 0.0, 0.0, 0.0, 0.0, ||  0.0, 0.0, || 0.0, 0.00,        0.0,  0.0, 1.0, 0.0
0.0, 0.0, 0.0, 0.0, 0.2, || -1.0, 0.0, || 0.0, 0.20,       -1.0,  0.0, 1.0, 0.0
0.0, 0.0, 0.0, 0.0, 0.2, || -1.0, 0.0, || 0.0, 0.70,       -1.0, -1.0, 1.0, 0.0
 a    b    c    d    e        f    g       h    i      j     k     l    m    n
```
which is where those picture #s come from.

> 3) 2007 update for Atari 800 with heavy modifications
https://github.com/atari800/atari800/archive/ATARI800_2_2_0-RC2.zip

> 4) Fancy 2009 version for Stella
https://github.com/stella-emu/stella/archive/release-3.7.zip
```
0.0, 0.0, 0.0, 0.0, 0.0, ||            || 0.0, 0.15,  0.0,  0.0,  0.0
0.0, 0.0, 0.0, 0.0, 0.0, ||            || 0.0, 0.45, -1.0, -1.0,  0.0
0.0, 0.0, 0.0, 0.0, 0.2, ||            || 0.0, 0.70, -1.0, -1.0, -1.0
 a    b    c    d    e        f    g       h    i      j     k     l    m    n
```

```
http://slack.net/~ant/libs/ntsc.html
a = hue
b = saturation
c = contrast
d = brightness
e = sharpness

f = burst_phase
g = hue_warping  (** Removed hue_warping for now, due to its obscurity **  0.2.2)

h = gamma
i = resolution
j = artifacts
k = fringing
l = bleed

m = merge_fields
n = decoder_matrix
```

Important to know is the 2009 Stella contributor:
> Ian Bogost and the Georgia Tech Atari Team
https://stella-emu.github.io/credits.html

My first impression is that Stella blargg atari_ntsc is the untouched, real code. I've never seen any NTSC library dated past 2006-2007 before. And being the GIT reputation, less likely to mod it without directly notating changes.

But could be worth following up with them.

```
 sms_ntsc_setup_t const sms_ntsc_monochrome  = { 0,-1, 0, 0,.2, 0, .20,-.2,-.2,-1, 0, 0 };
 sms_ntsc_setup_t const sms_ntsc_composite   = { 0, 0, 0, 0, 0, 0, .25,  0,  0, 0, 0, 0 };
 sms_ntsc_setup_t const sms_ntsc_svideo      = { 0, 0, 0, 0, 0, 0, .25, -1, -1, 0, 0, 0 };
 sms_ntsc_setup_t const sms_ntsc_rgb         = { 0, 0, 0, 0,.2, 0, .70, -1, -1,-1, 0, 0 };

  md_ntsc_setup_t const md_ntsc_monochrome   = { 0,-1, 0, 0,.2, 0, .00,-.2,-.2,-1, 0, 0 };
  md_ntsc_setup_t const md_ntsc_composite    = { 0, 0, 0, 0, 0, 0, .00,  0,  0, 0, 0, 0 };
  md_ntsc_setup_t const md_ntsc_svideo       = { 0, 0, 0, 0, 0, 0, .20, -1, -1, 0, 0, 0 };
  md_ntsc_setup_t const md_ntsc_rgb          = { 0, 0, 0, 0,.2, 0, .70, -1, -1,-1, 0, 0 };

 nes_ntsc_setup_t const nes_ntsc_monochrome  = { 0,-1, 0, 0,.2, 0, .20,-.2,-.2,-1, 1, 0, 0, 0, 0 };
 nes_ntsc_setup_t const nes_ntsc_composite   = { 0, 0, 0, 0, 0, 0, .00,  0,  0, 0, 1, 0, 0, 0, 0 };
 nes_ntsc_setup_t const nes_ntsc_svideo      = { 0, 0, 0, 0,.2, 0, .20, -1, -1, 0, 1, 0, 0, 0, 0 };
 nes_ntsc_setup_t const nes_ntsc_rgb         = { 0, 0, 0, 0,.2, 0, .70, -1, -1,-1, 1, 0, 0, 0, 0 };

snes_ntsc_setup_t const snes_ntsc_monochrome = { 0,-1, 0, 0,.2, 0, .20,-.2,-.2,-1, 1, 0, 0 };
snes_ntsc_setup_t const snes_ntsc_composite  = { 0, 0, 0, 0, 0, 0, .00,  0,  0, 0, 1, 0, 0 };
snes_ntsc_setup_t const snes_ntsc_svideo     = { 0, 0, 0, 0,.2, 0, .20, -1, -1, 0, 1, 0, 0 };
snes_ntsc_setup_t const snes_ntsc_rgb        = { 0, 0, 0, 0,.2, 0, .70, -1, -1,-1, 1, 0, 0 };
```

Sharpness change is believable.

Resolution seems realistic enough for Blargg tweaking. Maybe he did choose 0.45 to try and simulate any fringing or ringing, or based on TV comparison?

**Comment by snes2600** [comment]
Somone tried emailing @gblargg (gblargg@gm***.com). But no response for awhile.
http://forums.nesdev.com/viewtopic.php?f=23&t=19176
http://blargg.8bitalley.com/libs/ntsc.html
http://www.slack.net/~ant/libs/ntsc.html

I guess the world may never know.

**Comment by thrust26** [comment]
Let's close this now, because we obviously cannot find out.
