### ISSUE TITLE
Feature Request: Portable Mode

### ISSUE THREAD

**Issue by scottluker** [stella-emu/stella#183]
Making it so all Stella's config files are in the applications root directory at launch, rather than having to manually change it every time the folder either changes location or drive.

**Comment by scottluker** [comment]
Ok so I found the documentation for the config file being in the base directory and I can use a powershell script to change the paths manually before loading.

**Comment by sa666666** [comment]
Yes, that option exists, but it's not ideal.  I'll leave this issue open for now, since we may come up with a better approach.  Probably something like modifying the path in the icon itself would be easier??

**Comment by scottluker** [comment]
A command line option would be good as on windows you can create a shortcut that uses that option every time you open it making it more convenient. Plus then when used with frontends you can launch it using that command line option as well.

**Comment by sa666666** [comment]
This will be implemented when https://github.com/stella-emu/stella/issues/352 is complete.  So I'm closing this now, since the required functionality will be in Stella 6.1.
