### ISSUE TITLE
preliminary disassembly saving functionality for multi-bank rom 

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#184]
I think that even if currently Stella cannot create a disassembly that is direclty compilable for bankswitched games, maybe it could allow to save separate disassemblies for each bank (adding a _BANK# suffix to each filename).
Even if they can't be compiled as-is and require furher editing and merging to to make a working disassembly, they would still be useful IMHO. 
You could have some message printed in the debugger prompt to make users aware of the issue and even add a disclaimer, and maybe also the bankswicth description, as comment in each generated disassembly file.

**Comment by thrust26** [comment]
Good idea!

**Comment by sa666666** [comment]
This is something that I've wanted to work on for quite some time.  In fact, when I first got involved with Stella many years ago, my main interest was in getting a debugger and disassembler integrated and working.  But something else always comes along, and here I am, almost 17 years later. :smile:

**Comment by thrust26** [comment]
Implemented with d639cdb. You have to take care of the banks saved manually.
