### ISSUE TITLE
Diagnostic Test Cartridge 2.0 - Stella debugger freeze 

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#188]
[http://atariage.com/forums/topic/267810-stella-50-released/page-4#entry3826496](http://atariage.com/forums/topic/267810-stella-50-released/page-4#entry3826496)

This rom causes stella to freeze most of the times if started with the "-debug" option.
Also happens if switching to the debugger after the rom is loaded, altough less frequently.

[DOM2_0.zip](https://github.com/stella-emu/stella/files/1220465/DOM2_0.zip)

**Comment by thrust26** [comment]
For me it always freezes in both ways of entering the debugger. Same with 4.7.2

**Comment by sa666666** [comment]
Yes, the freezing is the same in both.  Currently investigating this, as it's more serious than issue #189.

**Comment by ale-79** [comment]
Confirmed. I initially got the impression that it was happening more often with "-debug", but after more tests, it seems to be the same.

This is what happens for me:

1) Once every 10 or 15 attempts, I can enter the debugger.

2) When in there, it usually hangs if I step throught the code when I reach frame 19.

3) On some occasions, I can get past that and, if so, everything seems to work fine: I can switch to emulation and back to the debugger without issues.
If I reset the rom (with CTRL-R) in emulation or with the "reset" command in the debugger prompt, I'm back to 2)

**Comment by thrust26** [comment]
I had the debugger crashing in the past sometimes during debugging too. Didn't find a real pattern, but it seemed related to illegal opcodes being hit due to bankswitching failing.

**Comment by sa666666** [comment]
The debugger (or app) should _never_ crash.  Now the ROM it is running may 'crash' and result in the emulator doing nothing useful, but the emulation itself should never lock up.

**Comment by thrust26** [comment]
Agreed.

EDIT: Changing just one byte (e.g. $fc00) in the unused data fixes the problem. Then the result is 3 (ROM) because of the changed ROM checksum. Also the ROM cannot be identified by Stella anymore, so maybe it's just a Stella database problem?

**Comment by sa666666** [comment]
How did you determine it was DiStella (I'd also assumed it was, but haven't yet tested it)?  And do you know exactly where it's locking up?

**Comment by thrust26** [comment]
I breaked (can you say that?) execution and looked at the call stack. Then I set a break at line 111 in `Distella::Distella(): disasm(myPC, 1);`
The while loop seems to run endless,  myPCEnd = $f03f. This is the code there:
```
LF03C
    .byte $00,$00,$01,$03,$07,$0F,$1F,$3F,$7F,$FF
LF046
    ldy    #$04
```
