### ISSUE TITLE
listtraps only showing the first trap

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#190]
maybe caused by the fix in  #157, now listtraps only displays the first trap (the one with lower address)

**Comment by sa666666** [comment]
Confirmed. Also placing image here from the other thread.
![29251765-64549790-805b-11e7-91df-2eab24b26eeb](https://user-images.githubusercontent.com/16061066/29252313-19cbbdaa-803f-11e7-92a4-2d8da356c98a.png)

**Comment by thrust26** [comment]
Maybe you can fix that before 5.0.2 release?

**Comment by sa666666** [comment]
That was the plan.  I won't be doing the release until Friday or Saturday anyway, so maybe we can squeeze in a few more fixes too.

**Comment by thrust26** [comment]
Looking at the labels, there are only very few bugs left.

**Comment by sa666666** [comment]
But maybe some of the enhancements.  If I can get these &&$#^^ing exams done.
