### ISSUE TITLE
Diag 2.0 fails with Error 6

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#191]
Related to #189 
This is indicating an error with the joystick ports.

Here is the code failing:
```
LF583
    .byte $FA,$F5,$FA,$F5,$AF,$5F,$AF,$5F
LF58B
    lda     #$00        ; 2
    sta     SWCHA       ; 4
    ldy     #$80        ; 2
    ldx     #$07        ; 2
    tya                 ; 2
LF595
    sta     SWACNT      ; 4   A = $80
    lda     LF583,x     ; 4   X == 7 -> A == $5f
    cmp     SWCHA       ; 4   SWCHA returns $7f here
    bne     .error      ; 2
```
More errors:
- SWACNT = $40, SWCHA = $bf, expected $af 
- SWACNT = $20, SWCHA = $df, expected $5f 
- SWACNT = $10, SWCHA = $ef, expected $af 

Pretty odd.

**Comment by sa666666** [comment]
I'm confused.  Didn't we just determine that error 6 is what we should be getting??

**Comment by thrust26** [comment]
No, 6 was the error we got with the old Stella, which was wrong here too. 

To be 100% precise we should get 9 (assuming the test ROM is correct).

**Comment by sa666666** [comment]
So should I not have made the change I just committed?  IOW, is it better to be wrong at 8 or wrong at 6?? :imp:

**Comment by ale-79** [comment]
6 is what I get on real hardware too. I think that you're supposed to use test plugs in the joystick ports in order to pass the test (9).

**Comment by thrust26** [comment]
That makes sense. The commit is fine.

**Comment by ale-79** [comment]
I actually built the test plugs for the diagnostic cart 2.6, but they seem to make no difference in real hardware. Maybe 2.0 uses different plugs, or I made some mistake (I will check them). If you look at the schematic, there are jumpers between some of the pins, which would explain why the rom is expecting different values when reading back SWCHA after setting some of the pins low
![post-6315-1172617052](https://user-images.githubusercontent.com/24704739/29251859-703c235a-805d-11e7-8269-483d6f9f702c.gif)

**Comment by thrust26** [comment]
Ok, so failing at 6 is OK. I removed the check and then it fails with 7 (paddles).

**Comment by sa666666** [comment]
It would be nice to get the plugs working correctly, and determine for sure how this is supposed to be emulated.

**Comment by thrust26** [comment]
If we manage to pass 6+7 we are done. This is the final screen.

![diag_2 0](https://user-images.githubusercontent.com/24360774/29251995-ac8338d8-805f-11e7-8d0e-8276b8d64b30.png)

**Comment by ale-79** [comment]
By looking at the code, the Diag 2.0 definetely uses different test plugs than the 2.6 version. This is what the schematics should look like. 
![testplug_20](https://user-images.githubusercontent.com/24704739/29253892-df7df11e-8088-11e7-986e-bb9e6bd77f8e.jpg)


I see if I can verify this on real hardware in the next days.

**Comment by ale-79** [comment]
It works!
I set up the test plugs on a breadboard following the schematic above, tested on real hardware (PAL 6-switch console) and got the screen with the Atari logo.

As for the resistors connected to the paddle lines (pins 5 and 9), I tried a few different values from what I had on hands: 

```
jumper (0 ohm)	ok
10 		ok
330 		ok
4k7 		ok
10k		ok
43k		ok
100k		ko (error 7)
```

So if it gets implemented I suggest just choose a value in the known working range and mentioning that the exact value is unknown at the moment.
(BTW, the code waits about 128 scanlines between setting SWCHA and reading the paddle lines)

The plugs also work if the diode is replaced by a jumper.

**Comment by thrust26** [comment]
Thanks for the test. 👍 

@sa666666 Should we really implement the test plugs as new controller types? Else we can close this issue.

**Comment by sa666666** [comment]
No, I don't need we need to emulate the actual plugs; what would be the use case for it??  I just wanted to confirm that emulation is working correctly.  I will go ahead and close this now.

**Comment by ale-79** [comment]
Agreed. 
Moreover, you should implement 2 different testplugs, one for each version of the diagnostic cart, and there's at least another (yet undumped) version out there which might need a third one...
The fact that they're documented somewhere is enough IMHO.

**Comment by thrust26** [comment]
And then there is that Golf Diagnostic  cart...
[Golf Diagnostic (1983) (Video Soft, Jerry Lawson, Dan McElroy) (Prototype) ~.zip](https://github.com/stella-emu/stella/files/1222903/Golf.Diagnostic.1983.Video.Soft.Jerry.Lawson.Dan.McElroy.Prototype.zip)
