### ISSUE TITLE
Flashback Paddles with Retronic Adapter on Stella

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#192]
Referenced in http://atariage.com/forums/topic/266361-help-flashback-paddles-with-retronic-adapter-on-stella.  Basically, there are two issues:
- Stella doesn't see joysticks with only 1 axis (very likely an SDL issue, which I have to follow up with them)
- When using 2 axes, paddle movement isn't working very well

Circus Atari and Kaboom! are affected.

**Comment by thrust26** [comment]
Dead zones at **both** ends don't look like they are a Stella problem.

**Comment by sa666666** [comment]
I haven't looked into it yet, so I can't really say.  But if that's the issue, it could still indicate a need to be able to define the allowable range for a controller.

**Comment by sa666666** [comment]
There has not been any followup on this from the original reporter.  So I'm going to go ahead and close it.
