### ISSUE TITLE
Debugger crash/stall

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#194]
It is possible to crash or stall the debugger. 

Example: 
- start Millipede, select 2K bankswitching type and reload, then enter debugger and try to forward one scanline. The debugger will freeze. It seems to be stuck in `TIA& TIA::updateScanlineByStep()`

**Comment by sa666666** [comment]
@thrust26, can you test the latest code from https://github.com/stella-emu/stella/commit/c1f7c5c90baa24c8b2df28850ab81028244c6fe1?  Basically, I check that M6502::execute() succeeds, else drop out of the loop.

Note that in your Millipede example, the PC doesn't move when stepping.  But it's not an app lockup; the CPU emulation has essentially crashed in such a case, and the PC no longer moves.  But Stella itself is still functional, you can still exit the debugger, etc.

**Comment by thrust26** [comment]
What difference should the fix make?

Also, I will try to find examples which really crash the debugger. 😃

**Comment by thrust26** [comment]
The new code also fixes a real crash in the old version: 

- start Fatal Run
- enter debugger
- switch bank to 5
- forward multiple lines (keep CTRL+L pressed) until the debugger crashes

Very good!
