### ISSUE TITLE
Blargg display cut of

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#195]
While TV effects are enabled, the picture looks shifted right by 1.5 pixel and the rightmost pixel looks cut of too. So the rightmost two or three pixels are missing. This is most notable in games like Combat, which draw a thin frame around the screen. 

1. The shift by two pixel is because Blargg computes the new pixels from left too right. If you look closely, only the very first column is all black, the 2nd column contains some barely visible blurring.
2. The missing rightmost pixel is because BLACK is used here, instead of the rightmost pixel of the input.

2 is probably done to blur the last pixel column too (you can see that if you zoom in), but at the cost of missing pixel. The fix is easy:
```
    // finish final pixels
    ATARI_NTSC_COLOR_IN(0, line_in[0]);
    ATARI_NTSC_RGB_OUT_8888(0, line_out[0]);
    ATARI_NTSC_RGB_OUT_8888(1, line_out[1]);
    ATARI_NTSC_RGB_OUT_8888(2, line_out[2]);
    ATARI_NTSC_RGB_OUT_8888(3, line_out[3]);

    ATARI_NTSC_COLOR_IN(1, line_in[1]);
    ...
```
This makes the the right gap disappear and IMO looks better. Here are before/after screenshots (TV mode = Composite).
![combat 1977 atari _org](https://user-images.githubusercontent.com/24360774/29313113-7bad5b08-81b8-11e7-9e81-e4f574d6b130.png)
![combat 1977 atari _fixed_right](https://user-images.githubusercontent.com/24360774/29313117-7dd7bf72-81b8-11e7-90d2-70e15f0749fe.png)

Regarding 1, we could move the whole buffer by 1 or 2 pixel to the left.
`memcpy(rgb_out, static_cast<uInt32*>(rgb_out) + 1, out_pitch);`

The result looks like this:
![combat 1977 atari _moved1](https://user-images.githubusercontent.com/24360774/29313252-4fe639bc-81b9-11e7-95f4-926981922576.png)
Now the right playfield columns looks as wide as the left one.

But to really overcome the problem, we would have to extend the display screen by 3 (?) pixel. Then no pixel would be cut off at the left and right and they would still blur nicely with TV effects.

Is that feasible?

**Comment by thrust26** [comment]
Here are the same screenshots with a test program, which makes the problem more obvious.
![blarggtest_org](https://user-images.githubusercontent.com/24360774/29314527-a2f2b860-81be-11e7-975b-c9e66ef44318.png)
![blarggtest_fixedright](https://user-images.githubusercontent.com/24360774/29314532-a50c4a26-81be-11e7-8e52-c140a59c908a.png)
![blarggtest_moved1](https://user-images.githubusercontent.com/24360774/29314534-a79eb4fe-81be-11e7-8ffd-acd970da7b09.png)
Note that even the last screenshot is missing half a pixel on the right.

**Comment by sa666666** [comment]
Adding 3 pixels to the width is probably not very easy.  The code is set up to be 7/2 of the input width, and also I believe to be divisible by 8.  Changing that assumption might mean changing how it generates its kernel, and that's really something I don't want to get into.

Also, the blank on the left is sometimes used for 'colour bleed'.  This is most noticeable in Pitfall 2 (or I suppose any Activision ROM), where the rainbow between the sky and the treetops juts out when using 'Bad Adjust' mode.  So we can't just remove the blank area entirely.

We may just be coming up on limitations of the Blargg filter ...

**Comment by sa666666** [comment]
Also, aren't the extreme edges of the display not visible on a real TV anyway?  Maybe the filters are doing that, and assuming you wouldn't see it anyway.

**Comment by thrust26** [comment]
I don't think we cannot fix this. AFAIK Blargg only expect an even number. So if the input from Stella contains two extra blank columns (black from the TIA palette) then Blargg should be able to handle this. We only would have to adapt the phosphor code.

Thanks for pointing out Pitfall II, I will try adjust the test program accordingly. 

On a TV you have a large black area all around the 2600 display. So all edges are fully visible.

**Comment by sa666666** [comment]
I suppose you could modify the Blargg buffer to be 560 + 2 pixels wide, instead of modifying the actual TIA framebuffer to be 160 + 2 pixels wide.  The former can be done just inside the Blargg code (where I would rather it would happen), while the latter breaks assumptions in other parts of the code (160 for width is hardcoded).

**Comment by thrust26** [comment]
Here is the updated test program now with a rainbow output. 
[Uploading BlarggTest2.zip…]()
And the first two results using _Bad Adjust_ mode (the third one makes no sense anymore, since moving left is not an option as Stephen pointed out above).
![blarggtest2_org](https://user-images.githubusercontent.com/24360774/29315722-f5ca72fc-81c4-11e7-9433-9ba8a9b27245.png)
![blarggtest2_fixed_right](https://user-images.githubusercontent.com/24360774/29315725-f7a28146-81c4-11e7-9caa-1c4327fbc060.png)

**Comment by thrust26** [comment]
> I suppose you could modify the Blargg buffer to be 560 + 2 pixels wide

Good idea. I will look into this now.

> (160 for width is hardcoded).

Yes, lots of "magic numbers" in the code. That's IMO another TODO. 😉

**Comment by sa666666** [comment]
Well technically, the 160 is stored in an enumerated item, not hardcoded into the app.  But I think that this is actually a valid 'magic number'.  The TIA framebuffer _is_ 160 pixels wide, and will never be anything else.

Now there may be other times that magic numbers are used, and if so I try to find and convert them to enumerations, etc.  But the TIA one is justified, IMO.

**Comment by sa666666** [comment]
Your ZIP attachment didn't actually attach to the message.

**Comment by thrust26** [comment]
Fixed

**Comment by sa666666** [comment]
The first place you should start for changing the Blargg width is AtariNTSC::inWidth() and in particular AtariNTSC::outWidth().  The latter in particular needs to be changed so that the internal framebuffer is created at the right size.  These changes will also involve having to change the phosphor rendering loop, since the scanline stride will be different too.

**Comment by thrust26** [comment]
Yes, that's exactly were I started. I wonder if outWidth = 567 may become a problem?

**Comment by sa666666** [comment]
I thought you said the #'s needed to be even?  In any event, maybe just make it 568 (then it's even, and still a multiple of 8).

**Comment by thrust26** [comment]
Only the input width. And only for the current code. But I will go to 162 nevertheless, to get every minimal blur.

**Comment by sa666666** [comment]
OK, it's up to you.  As long as you keep any changes restricted (as much as possible) to the Blargg class(es).

**Comment by thrust26** [comment]
Works. Here are the fixed files. Looks good, doesn't it?
[tv_filters.zip](https://github.com/stella-emu/stella/files/1225157/tv_filters.zip)

![blarggtest_fixed](https://user-images.githubusercontent.com/24360774/29318234-7e0508d0-81cf-11e7-8740-c3e54e6f502d.png)

**Comment by sa666666** [comment]
Looks good to me.  I'll integrate this soon, when I get some extra time.  For now, perhaps you can test in a few other ROMs to make sure it works everywhere (although I can't see how it would break anything).

**Comment by thrust26** [comment]
The final scaling might be a little problem. The output window in Stella has a constant with. But the Blargg display is slightly wider now. There blargged output is horizontally squeezed a little and the pixel don't match 1:1. 

But the scaling works well and doesn't look bad.

**Comment by thrust26** [comment]
I didn't find any problems during my tests.

**Comment by sa666666** [comment]
Just wondering why the blank on the right is now wider than on the left?  Maybe decrease it by a pixel or two?  Also not sure why you jumped from 560 to 567.  What is the significance of the 7 here??

**Comment by thrust26** [comment]
Look closely at the screenshots. On the right edge you can see minor blur even in the very last column. That minor blur is cut off at the beginning of a line, due to the way Blargg is calculating. Where the vertical lines are most to the left, look **closely** at the left side and compare the left most pattern with the same at the right side. It should be the same but it isn't. That's due to Blargg, not my code.

567 because every 2 original pixel are converted into 7 new pixel. And I added 2 pixel to gain space for the rightmost blur. 

I think I could remove two or three of very right columns if you really want that. They contain only minimal greenish blur.

**Comment by thrust26** [comment]
Here is a version with 565 pixels. Now it looks symmetrical at the borders.
[tv_filters.zip](https://github.com/stella-emu/stella/files/1226194/tv_filters.zip)

**Comment by sa666666** [comment]
Yes, this looks good.  I will commit in a moment.

**Comment by thrust26** [comment]
Not committed yet, or did I miss it?

**Comment by ale-79** [comment]
Isn't this one?
 6f60437a9ceef9fade40977c1d1a5bbbf78b8476

**Comment by thrust26** [comment]
Yup, so I just missed it.
