### ISSUE TITLE
Phosphor effect toggle (ALT-P) inconsistent

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#196]
Very, VERY minor glitch:

If you have phosphor effect always enabled in video settings, and you run a game which does not have it set in its game properties, the first time  you use the ALT+P key combo, the effect stays enabled (as confirmed by the on-screen message), as if Stella didn't recognize that it was already on. After that, the toggle command works as expected.

**Comment by sa666666** [comment]
There is a related issue when dynamically changing phosphor level; I will take care of both issues here.
