### ISSUE TITLE
Benchmarking support

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#197]
Provide the means to run Stella without frame limiting and report the maximum FPS thus achieved

* Render every 1000th or so frame in order to continue providing visual clues on (de)activated options while avoiding slowdowns due to OS calls
* Deactivate audio
* Dump FPS to Stdout
* Expose benchmark mode via CLI.

**Comment by thrust26** [comment]
Why should we even display any frames? Just for determining where we are?

**Comment by DirtyHairy** [comment]
I initially was in the "no display at all" boat, but I think that having at least some visual feedback shouldn't impair the benchmark and will give more confidence in the benchmark (you see what is happening and can play with toggling different settings in real time).

**Comment by thrust26** [comment]
I would like to control that via an option. 

Also it would be cool if we could run a number of ROMs (each for n frames). Then we could create a nice benchmark suite.

**Comment by DirtyHairy** [comment]
Actually, I think the "run multiple ROMs" part would be better moved to external scripting.

**Comment by thrust26** [comment]
No problem, if you write the script and accumulate the results. :wink:

**Comment by DirtyHairy** [comment]
Well, feel free to do it in C++ :stuck_out_tongue:

**Comment by thrust26** [comment]
Basic benchmark when frame rate is not set to 'Auto' implemented with b111a8c

**Comment by sa666666** [comment]
With the new profiling support, can this one now be closed?

**Comment by DirtyHairy** [comment]
👍
