### ISSUE TITLE
Pipline-style parallelization of video processing (Blargg, phosphor)

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#198]
Modify the main loop and run emulation and video processing on separate threads. The loop should look like this:

1. Process events
2. Run emulation and generate new frame
3. Wait for previous frame to finish processing (if threading is enabled)
4. Start processing new frame on video processing thread
5. Blit previous frame to screen (if threading is enabled) / wait and blit processed frame to screen (if threading is disabled)
6. Sleep / busy wait as necessary to control FPS
7. Go back to 1

The loop is designed to draw from the main thread; google suggests that there may be issues if OS calls are made from secondary threads. This will introduce a deterministic delay of one frame if pipelining is enabled. An option should be provided the enable / disable threading.

**Comment by thrust26** [comment]
3. waits for the video processing thread, right? (`join()`)

Also, if possible 5. + 6. should be swapped to reduce lag.

**Comment by DirtyHairy** [comment]
Yep, exactly. The same happens in step 5 if pipelining is disabled (I changed my wording, as it is still threading) :smirk: As we also discussed, we could also for a completely unthreaded approach in that case --- I'd defer this descision until we have actual code and do whatever is easier then.

**Comment by sa666666** [comment]
@DirtyHairy, isn't this somewhat (mostly?) done now?   And if so, we can close this one??

**Comment by DirtyHairy** [comment]
@sa666666 Nope, not really. What I was aiming at is moving Blargg and Phosphor to one or multiple separate threads, so that they can run while the main thread is still blocking in SDL. However, this is a duplicate of #410 , so we can definitely close this one 😛
