### ISSUE TITLE
AtariVox SpeakJet support (without hardware)

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#207]
This has been unsuccessfully attempted in the past. Maybe eventually someone will try again.

**Comment by sa666666** [comment]
I assume you mean 'sound only'?  Since the Savekey part is already emulated??

**Comment by thrust26** [comment]
Yup

**Comment by sa666666** [comment]
Some preliminary info at http://atariage.com/forums/topic/88811-emulating-the-atarivox.  I also have a Windows binary to generate phonemes (it may be the same app that Batari mentions in the above thread).

**Comment by sa666666** [comment]
Closing this due to the Speakjet hardware creators not wishing to have the hardware details in the public.
