### ISSUE TITLE
HMCLR not reflected in debugger

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#211]
It seems like HMCLR doesn't update the display in the debugger.

**Comment by sa666666** [comment]
Test case/ROM and a description of how I can duplicate this, please.

**Comment by thrust26** [comment]
Any ROM, e.g. Combat and _trap HMCLR_. You will see that the HM values are not 0.

**Comment by sa666666** [comment]
I assume it's only a debugger display issue, since otherwise the ROM would be completely broken??

**Comment by sa666666** [comment]
Hmh, looks like an issue in the TIA shadow registers; they don't seem to be updated.

**Comment by thrust26** [comment]
Yup, display only.

**Comment by sa666666** [comment]
I saw, I just wanted to confirm for sure before I went down the wrong path.
