### ISSUE TITLE
CTRL-G ("grab mouse") not working when emulating digital devices

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#214]
[http://atariage.com/forums/topic/269337-colony-7-2600-in-stella-with-trackball/#entry3835390](http://atariage.com/forums/topic/269337-colony-7-2600-in-stella-with-trackball/#entry3835390)

Like the title says, CTRL-G doesn't have effect when you're emulating a digital controller. (e.g. try playing the original Missile Command using a PC mouse)

EDIT:
The command line option "-grabmouse" doesn't work either

**Comment by thrust26** [comment]
This is related to the fix in #72

**Comment by ale-79** [comment]
Probably the option should work depending on what the user set for "Use mouse as a controller" in the "Devices & Ports" tab (Always/Analog devices/Never).
![senzanome](https://user-images.githubusercontent.com/24704739/29748588-d1c9ec80-8b19-11e7-9fef-35fd6ef84d8c.png)

**Comment by thrust26** [comment]
Yup, the result of that evaluation should decide if the mouse is grabbed or not.
