### ISSUE TITLE
Remove 32-bit counters; move to 64-bit everywhere

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#218]
There's at least one place that uses a 32-bit counter (system cycles) that needs to be reset each frame to prevent overflow.  The complicates the code slightly, as we need to make sure that the reset is propagated throughout all classes that need it.  It would be much easier to simply use a 64-bit counter, and never have to worry about overflow (basically, overflow wouldn't happen for ~487 millenia :smile:)

There are probably other areas that would benefit from 64-bit types too; more research is required.

**Comment by thrust26** [comment]
Which counters do you have in mind?

**Comment by sa666666** [comment]
The primary one is System::myCycles.  We currently need to call System::resetCycles() after each frame, and propagate that change to other parts of the system (call systemCyclesReset() on each device).  It would be easier if this whole idea just disappeared, and used uInt64 directly.

@DirtyHairy may have some other counters wrt the TIA code.

**Comment by sa666666** [comment]
I know this is a priority 3 issue, but I felt the urge to fix it, and went with it :smiling_imp:   Implemented the conversion of System::myCycles to 64-bit in https://github.com/stella-emu/stella/commit/ebb8725126601530e0cf8707e5edba8ef238ad52.

I'll leave this issue open for now, since you guys may find other cases of where going to 64-bit is beneficial.  If you can't think of any, we can close it.

**Comment by thrust26** [comment]
This must have **really** bugged you. :)

**Comment by sa666666** [comment]
Well, I have a lot of really annoying things going on at work ATM, and believe it or not, refactoring and fixing niggling issues actually reduces my stress levels.  Yes, I am weird, and yes, I've been told that before :smiley:  Besides, through judicious use of 'ack-grep', it only took about 90 minutes to fix it all.

**Comment by thrust26** [comment]
I can understand that very well. 

**Too** well actually.

**Comment by thrust26** [comment]
Now that we don't reset the cycle counter, maybe we should make it available in the debugger.

**Comment by sa666666** [comment]
I'm about to make the frame cycle counter and debugger pseudo-op (in fact, there's already a FIXME for it in line 102 of Debugger.cxx):
```
//FIXME  { "_fcycles", "Number of cycles since frame started" }
```
Is this what you mean, or is there some other counter functionality that should be in the debugger?

**Comment by thrust26** [comment]
For long running tasks (longer than one frame) it might be helpful in debugging and e.g. optimizing.

**Comment by sa666666** [comment]
OK, I can easily add it as a pseudo-op named '_cycles'.  What you do with it is up to you (as with all things in the debugger).

**Comment by sa666666** [comment]
The '_fcycles' pseudo-op is implemented in https://github.com/stella-emu/stella/commit/b6907d0d8a14aa21ab93af7b3b14764cc1a949d9.  Adding support for raw cycles is problematic, since the pseudo-op infrastructure is set up to return int, and cycles is now a uInt64.  So I need to think a little about how to fix this.

**Comment by thrust26** [comment]
**You** wanted to go 64-bit. 😛

**Comment by sa666666** [comment]
True, but it's easy enough to fix; just return an Int64 everywhere instead :smile:

**Comment by sa666666** [comment]
I'm going to put the '_cycles' part on hold for now, since the code is currently set up in many places to receive integer data only in the debugger.  Actually, all the debugger really needs is 16-bit, but since we also use negative values, it's bumped to 32-bit signed int instead.  Going to 64-bit in this cases gains absolutely nothing.

What would have been '_cycles' in the old code is now available as '_fcycles'.  I don't think we need '_cycles' at all, actually, and adding code to do it would greatly complicate other things.

Can you suggest the use case for _cycles?  Perhaps I can add other pseudo-registers that more properly fill those needs, without needing to use _cycles directly.

Note that there's no rush on responding; this is the part that falls under 'more research', and it is priority 3 after all.

**Comment by thrust26** [comment]
I posted one use above. Also IMO it would simplify breakpoints at certain times over multiple frames as you wouldn't have to calculate with frames and (potentially varying) fcycles. 

How about _cyclesLo and _cyclesHi? That would be still better than nothing.

**Comment by DirtyHairy** [comment]
Yikes, that went fast :) Referring to your comment above, @sa666666 : there aren't any counters in the TIA that I can think of that are candidates for refactoring --- everything is periodic.

**Comment by sa666666** [comment]
Doing _cyclesLo and _cyclesHi should be easy enough.

**Comment by sa666666** [comment]
Now that the above commands have been added, this issue can be closed.
