### ISSUE TITLE
Improve Distella output

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#221]
This is a request for improving the output format of Distella.

- The formatting of the file created is quite odd, e.g. the code in indented by 7, then follow three chars for the mnemonics and 4 spaces before the parameter. So that's 14. I suggest 4 spaces before the mnemonics and 5 after mnemonics, so that's 4. 
- There are superfluous colons after each label.  I did use them myself before, until I realized that they make no sense.
- There should be a blank line after each JMP, to visualize the control flow break (like RTS does).
- The cycle counters should be improved too. After a conditional branch, the count should be 2/3. Also branches which cross a page should either have a * added or the cycle count corrected. The ';' should be start at column 41 (instead of 33) do have more space for longer label names.
- the start (and maybe break) vectors should use the labels for the addresses, not just the values.
- personally I prefer lowercase for the mnemonics, but that's only my personal taste.
- ...

**Comment by sa666666** [comment]
Not you again, with a bunch of new suggestions :imp: 

Seriously though, at first glance I don't think most of these are terribly difficult.  I may have some questions about at least one of them.  But not right now; I **really** have to finish the debugger rewind stuff.

**Comment by thrust26** [comment]
Just making sure that you never feel obsolete. :wink:

**Comment by thrust26** [comment]
And if you don't mind, I can take over this one.

**Comment by sa666666** [comment]
No problem, except for maybe the sizing of the columns.  For that one we should collaborate, since it isn't just in DiStella.cxx, but also in the UI code (which you probably want to avoid).

**Comment by thrust26** [comment]
I just noticed that. The cycles are displayed broken. Where do you read them for the debugger window?

**Comment by thrust26** [comment]
Figured it. Here is a list of more TODOs for DiStella:

1. Better cycle count (in progress already)
2. Identify and output start and break vectors correctly
3. Add code from break vector (if used) to disassembled addresses
4. Identify ZP addresses accessed (like '(D)' for ROM addresses)
5. Fix data incorrectly identified as CODE (*)
6. Fix code not identfied
7. ...

**Comment by ale-79** [comment]
I really like the changes.

Maybe you could add a symbol after cycle counts of indexed and branch instructions that take an additional cycle when crossing a page, in addition to the "!" indicating that the additional cycle is _actually_ taken in the specific case. 
While this information isn't of much use in the debugger, it could be useful in case of saved disassemblies when someone is hacking games and moving code around.

example (from "Combat"):

```
LF2CC
    lda     (ram_BB),y              ;5'        
    sta     ram_BD,x                ;4        
    bcc     LF2D4                   ;2/3'      
    dey                             ;2        
    dey                             ;2   =  15
LF2D4
    iny                             ;2        
    dex                             ;2        
    dex                             ;2        
    bpl     LF2CC                   ;2/3'      
    rts                             ;6   =  14
    
LF2DA
    lda     ram_8A                  ;3        
    sec                             ;2        
    sbc     #$02                    ;2        
    bcc     LF30C                   ;2/3!     
    sta     ram_8A                  ;3         *
    cmp     #$02                    ;2         *
    bcc     LF30B                   ;2/3!      *
    and     #$01                    ;2         *


```

**Comment by thrust26** [comment]
The cycles are currently all coming from static analysis of the code. But I have some plans for improving runtime analysis. Then I will have a look at it.

**Comment by sa666666** [comment]
I also propose to change the output to match the Combat example from @ale-79 above.  In particular, labels should be on their own lines, and the beginning of code lines brought back to column 6 or so.  I will probably look into this one myself, since it's not strictly DiStella related, but a change in RomListWidget.

**Comment by thrust26** [comment]
For the files created, we already have this format.

**Comment by thrust26** [comment]
Wrong button :smile:

**Comment by sa666666** [comment]
Yes, but I mean to change the output in the disassembly window to match it.  It would eliminate the huge spacing in front of the opcodes (which is there currently to accommodate long label names).

**Comment by thrust26** [comment]
I know. And actually I like the current compact view. You can see more code this way.

I know we have problems with very long label names, so I wonder if we could display them completely on demand only.

**Comment by thrust26** [comment]
Combined static and runtime code analysis is working now. For more runtime cycle improvement, please open new issues.
