### ISSUE TITLE
Ball moving odd in RAM-Pong (Paddles)

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#223]
@DirtyHairy The game is not working with Stella 5.x. When the ball is missed, it often comes back bouncing completely erratically (NTSC and PAL-60, but not PAL-50). I never saw this happening on real hardware of with Stella 4.x

[RAM-Pong (v1.0).zip](https://github.com/stella-emu/stella/files/1308547/RAM-Pong.v1.0.zip)

**Comment by DirtyHairy** [comment]
To me, it looks like it is detecting a spurious collision above the paddle, and the logic that tries to account for edge collisions assigns an absurd vertical speed. Does this make sense? Funnily, this only happens on the PAL-60 and NTSC versions. Hmmm....

**Comment by DirtyHairy** [comment]
Some logging confirms my theory regarding the spurious collision.

**Comment by DirtyHairy** [comment]
Got it! It seems that collisions are not detected during vblank, and the schematics confirm this (each signal goes into an AND gate together with ~vblank). Fixed in 8485b082.
