### ISSUE TITLE
Add echo to debugger prompt

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#224]
It would be useful to be able to output an expression result at the debugger prompt. 

E.g. `echo _fcycles` or `echo a==x`

**Comment by thrust26** [comment]
Implemented with 43e9693

**Comment by sa666666** [comment]
There is already a similar command 'print' that could have been adapted to do the same thing.  I have no issue with leaving them both there, since 'print' is more general purpose and outputs results in all 3 bases, whereas 'echo' seems to use only the current base.
