### ISSUE TITLE
Swapped ports displayed incorrectly in debugger

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#232]
Swapped ports are not correctly represented in the debugger.

Example:
- P0 Controller = Joystick; P1 Controller = Paddles; swapped ports enabled

This is displayed in the debugger I/O tab as:
- Right (Paddles) | Left (Joystick)

But what is really meant is:
- Left (Paddles) | Right (Joystick) (when referring to the ports)
or
- P1 (Paddles) | P0 (Joystick) | (when we are referring to the players)

IMO referring to the ports makes more sense in the debugger.

**Comment by thrust26** [comment]
This is related to #234.

**Comment by thrust26** [comment]
Fixed with cd18905

**Comment by ale-79** [comment]
> IMO referring to the ports makes more sense in the debugger.

I agree and I think that it would make more sense in the "controller" tab too.

The current "P0/P1 Controller" label is confusing in case of paddles (where two players use the same port, and there can be more than 2 players) or for AtariVox, Savekey and other devices connected to the ports that are not "controllers" in the true sense and therefore are not associated to players.
I'd replace that with "left port" and "right port" (maybe the tab could also be renamed "Ports").

The "swap ports" and "swap paddles" checkboxes already provide information about the order used to map the emulated controllers to the players (and thus to the real controllers used in Stella)
![controller](https://user-images.githubusercontent.com/24704739/31141451-bfade332-a877-11e7-8e93-d34bf3bfb63a.png)
