### ISSUE TITLE
Dialogs less tall when launcher height very small

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#236]
Some option dialogs are slightly shrunken when opened from within the launcher, while the launcher height is < ~500. It looks like the launcher height is somehow limiting the dialog height (too much).

This already happened in 4.7.2 but due to the new options/redesign it becomes obvious now. 

Examples (emulator at 2x, launcher with height = 480):
1. from the emulator at 2x:
![image](https://user-images.githubusercontent.com/24360774/31171517-44dba21e-a900-11e7-94ef-7904971f433e.png)
![image](https://user-images.githubusercontent.com/24360774/31171476-1e53c266-a900-11e7-9561-7a8a4672764f.png)

![image](https://user-images.githubusercontent.com/24360774/31171526-4d8bf7ce-a900-11e7-8eab-0090284a9b36.png)
![image](https://user-images.githubusercontent.com/24360774/31171488-296fae44-a900-11e7-90df-6959dc602575.png)

**Comment by thrust26** [comment]
Found the problems.

There are two sets of dialogs, one for the launcher and one for emulation. Both a created with different maximal sizes. Either launcher size * 0.8 or current frame buffer size. I cannot see any advantage of the different sizes, because we have no dialogs which can resize dynamically. And the chance of error is increased. 

I think I will fix this by setting both set to the same maximum sizes (e.g. 640x480 * 0.9).

@sa666666 What do you think?

**Comment by sa666666** [comment]
I will fix this.  And there are reasons why I had differing sizes, so that will have to stay for now.

**Comment by thrust26** [comment]
Reverted the "fix".
