### ISSUE TITLE
Stella crashes with breakpoints in .script file

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#239]
As soon as the .script/.stella file provided for a ROM contains a _break_, Stella gets stuck in the debugger (DiStella) and finally crashes.

Happened in 4.7.2 too.

**Comment by sa666666** [comment]
Goes to show how much this part of the codebase has been tested (ie, not at all).  I will look into it.

**Comment by sa666666** [comment]
Just tried it with a simple break and River Raid, and unable to duplicate.  Please forward exact use case that causes this.

**Comment by thrust26** [comment]
Sorry, thought I had added it already.
[Three.s.zip](https://github.com/stella-emu/stella/files/1369685/Three.s.zip)

**Comment by thrust26** [comment]
> Goes to show how much this part of the codebase has been tested (ie, not at all). I will look into it.

Since it doesn't happen all the time, I wouldn't be that pessimistic.

**Comment by sa666666** [comment]
Well, seeing how Windows users couldn't even save a script file, I'm pretty sure the loading part of the equation hasn't been well tested ...

**Comment by thrust26** [comment]
Windows users are maybe a bit special. At least **I** am very lazy (and bad) with typing commands. :wink:

Linux users are probably more used to command lines.

**Comment by thrust26** [comment]
I suppose this is the critical code in DebuggerParser::run():
~~~
if(commands[i].refreshRequired)
        debugger.myBaseDialog->loadConfig();
~~~
This causes an endless recursion.

**Comment by thrust26** [comment]
The bug was there since 7f75957 which was committed 07.09.2010. So I guess the script functionality is not used by anyone.

Maybe we should point it out in the documentation?

**Comment by thrust26** [comment]
BTW: loadconfig was for ROMs with ORG = $f000 (= probably most of them) broken too.
