### ISSUE TITLE
Possible missile width issue with late writes to NUSIZ

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#24]
Eshu has a testcase on [AtariAge](http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/?p=3646091) which exhibits a discrepancy between old and new core connected to a late write to NUSIZ.

This should be clarified on real hardware and, if applicable, fixed.

**Comment by thrust26** [comment]
Can't test on real hardware :(

**Comment by DirtyHairy** [comment]
Still waiting for my Harmony Encore :package:  (and for time to AV mod my 2600)

**Comment by DirtyHairy** [comment]
I could run the ROM provided by eshu after adding two bytes of padding to the end. This is how it looks like on our LCD (I haven't yet finished my composite mod, so the poor quality is due to HF modulation).

![img_20170102_145222](https://cloud.githubusercontent.com/assets/2444224/21590814/2409bca8-d0ff-11e6-9395-a8721a1eba84.jpg)
![img_20170102_145147](https://cloud.githubusercontent.com/assets/2444224/21590815/240b38a8-d0ff-11e6-9250-cc1bf6b1de37.jpg)

For reference, this are two screenshots in PAL mode with the old and with the new core. Now core:
![long005_padded_1](https://cloud.githubusercontent.com/assets/2444224/21590881/a23be29a-d0ff-11e6-89ed-c6f71e0f8d3c.png)
Old core:
![long005_padded_2](https://cloud.githubusercontent.com/assets/2444224/21590882/a242a36e-d0ff-11e6-979b-9724fa02159a.png)

I think this resolves the issue: the new core is displaying correctly. Note that there appear to be additional dark pixels at the right edge of several objects, but I think this are artifacts due to HF (de)modulation and color bleeding. I will recheck once I have my composite mod complete.

**Comment by thrust26** [comment]
Can you post the ROM?

**Comment by DirtyHairy** [comment]
Sure. 
[long005_padded.zip](https://github.com/stella-emu/stella/files/680940/long005_padded.zip)

**Comment by thrust26** [comment]
Oh, just zeroes. :)

**Comment by thrust26** [comment]
How did you use that with your Encore? I tried using the Harmony Programming Tool, but EFSC* is not supported.

**Comment by DirtyHairy** [comment]
I had to flash to the latest NTSC firmware. After that, autodetection worked for me with the padded ROM.

**Comment by thrust26** [comment]
I have a Melody like version (no SD Slot), so I have to repy on the Programming Tool.

**Comment by DirtyHairy** [comment]
Ah, I see. Sorry, I have no idea how to get this to work there 🤔
