### ISSUE TITLE
feature-request: "steppointif" command in debugger

### ISSUE THREAD

**Issue by SvOlli** [stella-emu/stella#247]
The new "trapif" command in the debugger is wonderful. But most times it triggers, when the problem happens, and going one step back is too much most of the times (thanks for not dropping the step-back-list anymore when leaving the debugger).

So how about if there is a command that would just add a saved state to the step-back-list. A rather generic approach: something like this could do a steppoint for every frame, and one could then replay the situation that led to the problem rather easily:
`steppointif { (_scan == 0) && (_scycles < 5) }`

**Comment by thrust26** [comment]
Implemented with 01d3a29
