### ISSUE TITLE
HMOVE emulation error in Doctor demo

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#250]
The 'doctor' demo seems to have an incorrectly positioned P0, which may be due to setting "HMP0 too early after HMCLR".  The ROM in question is [3lb_doctor_emu.zip](https://github.com/stella-emu/stella/files/1459279/3lb_doctor_emu.zip), but the error occurs with the rotating cube in bank 1, which is here: [3lb_doctor_emu.001.zip](https://github.com/stella-emu/stella/files/1459285/3lb_doctor_emu.001.zip).

A snapshot from debug mode clearly shows that P0 should be positioned more to the right, to smooth out the side of the cube:
![3lb_doctor_emu](https://user-images.githubusercontent.com/16061066/32631073-a205413a-c579-11e7-8f32-12c01facb64f.png)

**Comment by DirtyHairy** [comment]
Mmmhh  is this really a bug? The cube display wrong on real hardware, too :smirk:

**Comment by sa666666** [comment]
Yes, @thrust26 noticed this as well.  And I can confirm after checking on real hardware that this is the correct behaviour.  I will check real hardware before opening issues in the future.
