### ISSUE TITLE
Support FA2 saving data onto cart

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#252]
Support games like Star Castle Arcade which allow saving e.g. high scores directly onto the cart.

**Comment by sa666666** [comment]
Just got an email on this.  Don't we already do this in ```CartridgeFA2::ramReadWrite()``` and/or ```CartridgeFA2::flash(uInt8 operation)```?

**Comment by thrust26** [comment]
You are right. I missed or forgot that.

**Comment by thrust26** [comment]
BTW: I didn't find that in the documents. Might be worth mentioning.
