### ISSUE TITLE
Ski Hunt sounds not correct compared to 5.0.2

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#254]
Starting up Ski Hunt now results in weird sounds, that are different each time the game is reset.  This makes me think that something is being initialized incorrectly (or not at all).  We've made many changes over the past few weeks, so this one may take some time to track down.

**Comment by thrust26** [comment]
I don't think there is a bug. This happens when you enable "Drive unused TIA pins..."

**Comment by DirtyHairy** [comment]
What do you think about adding a persistent "watermark" overlay to the image if "drive TIA pins..." is enabled?

**Comment by thrust26** [comment]
There are more options which may break some ROMs (e.g. randomize memory or startup bank).

I am currently moving all those options into developer setting. Maybe we should indicate those being enabled?

**Comment by sa666666** [comment]
Then I guess there is some issue with how those options are being set.  When the ROM is launched in 5.0.2, it sounds fine.  But the same ROM launched in the latest git code doesn't sound fine.  And this is without me changing any settings.

So if the bug isn't in the ROM, it's in the processing of the settings.  Launching a ROM in 2 versions of Stella, without manually changing any settings, should lead to the same behaviour.

**Comment by thrust26** [comment]
Yes, that might be the case. I have fixed some code in between, but not committed yet (waiting for your OK).

**Comment by sa666666** [comment]
OK, go ahead with your commits.  I probably won't be doing any more header rework until Monday, when I get access to a fast computer again.  Just remember to pull/remerge before you commit (or stash, etc, whatever method you use).

**Comment by thrust26** [comment]
Commited, please check.

**Comment by sa666666** [comment]
Seems to be working now.  But I wonder what is the point of having two versions of certain settings?

**Comment by thrust26** [comment]
As a developer or tested, you always want to have to most available checks for coding errors. But besides that, you also use Stella for simply playing games. 

The two different settings makes switching easier.

**Comment by sa666666** [comment]
I agree in theory, but I wonder about setting things in different places/ways.  I don't mind having two different places for _changing_ settings, but I think there should only be _one_ setting to check.  Your renaming is fine; I don't mean that you should revert that or anything.  But IMO if you have a setting called ```dev.colorloss```, we should get rid of ```colorloss```.  You can still set it in two places, but there should never be a case where one is on and another is off; that would be ambiguous.

**Comment by sa666666** [comment]
Or more to the point.  Rearranging the UI to keep related things in one place is good.  Having multiple setting strings for the _same_ setting is confusing.

**Comment by sa666666** [comment]
Finally, we should move this to Gitter ...
