### ISSUE TITLE
Support correct file sized ROMs for E7 bankswitching

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#255]
While all dumps for M-Network's E7 bankswitching are 16K, this is only because they were dumped that way to make it easier for emulators.

The correct sizes are:
- Bump 'n Jump: 8K
- Burgertime: 12K
- Masters of the Universe - The Power of He-Man: 16K

**Comment by sa666666** [comment]
Seems easy enough; we just need to check for E7 in each of those file sizes.  The main issue is making sure that the checks don't give false positives.  I have a tool written to do that, but again it's in Linux, and won't be available until I get my system up and running again.

**Comment by thrust26** [comment]
see #260
