### ISSUE TITLE
Doc updates for 5.1

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#258]
Let's start a list of updates to Stella, what has to be updated and [who] volunteers for what.
(~~strike though~~ what is done)

**Emulator/Launcher**
- ~~Video Settings Dialog (color loss, debug colors and jitter removed)~~ [Thomas]
- ~~UI Settings (Debugger tab removed)~~ [Thomas]
- ~~Input Settings/Device & Ports (refactoring, SaveKey erase)~~ [Thomas]
- ~~Game Properties refactoring~~ [Thomas]
- ~~Developer Settings dialog (moved and new options)~~[Thomas]
- ~~various screenshot updates (from above and due to ellipsis)~~ [Thomas]
- ~~frame rewind/unwind/continuous rewind~~ [Thomas] 
- ~~basic 7800 support~~  [Thomas]
- ~~different colors lums for PF debug colors~~ [Thomas]
- ...?

**Debugger**
- ~~trapif~~ [Thomas]
- ~~savestateif~~ [Thomas]
- ~~breakif toggles (also for TIA display breakpoint)~~ [Thomas]
- ~~'save...' commands changes (paths!), 'exec' too~~
- ~~new controller widgets (SaveKey...)~~ [Thomas]
- ~~fcycles, _scycles, _cyclesLo, _cyclesHi~~ [Thomas]
- ~~enhanced commands (dump, print, rewind...)~~ [Thomas]
- ~~prompt enhancements~~ [Thomas]
- ~~Options... button~~ [Thomas]
- ~~new stuff from uhrm~~ [Thomas]
- ...?

**Bugfixes and Improvements** (e.g. for Changelog) 
- ~~TIA fixes (collisions disabled during VBlank, autostart, HMOVE...)~~ [Christian]
- ~~swapped ports fixes in System Logs and controller widgets~~ [Thomas]
- ~~snapshot 1x fix (corrupted)~~ [Stephen]
- ~~snapshot fix (double blending)~~ [Stephen]
- ~~power-on options fixes~~ [Stephen]
- ~~Genesis controller reload fix~~ [???]
- ~~displayed x-positions fixed~~ [Christian]
- ~~HMCLR display fix~~ [Stephen]
- ~~7 digit cheat codes are now accepted~~ [Thomas]
- ~~FE banking updates~~ [Stephen]
- ~~save commands working now~~ [Stephen]
- ~~Distella updates~~ [Thomas]
- ~~SaveKey tracking and erase~~ [Thomas]
- ~~Trackball widgets~~ [Thomas]
- ...?

**Comment by sa666666** [comment]
Oh, my.  I just marked my last paper for the semester last night, and will be able to get back to Stella now.  But I see you've been very busy, and it's probably going to take a day or two just to absorb all the new changes, test in other environments, etc.  And of course we still need to finish the rewind stuff (but it's very close, I think).

**Comment by thrust26** [comment]
I have structured the debugger documentation and aligned it a bit to the emulator doc. I have added a contents chapter at the beginning, some internal links and extra information.

**Comment by thrust26** [comment]
@sa666666 @DirtyHairy Almost everything is done, I will leave the rest to you guys.

**Comment by ale-79** [comment]
regarding the improved "dump" command, there's no mention in the docs about what the "dump to file" flags mean (1: memory; 2: CPU state; 4: INPUT registers).

**Comment by sa666666** [comment]
Since all items are documented, I will close this now.
