### ISSUE TITLE
Please add Chinese support

### ISSUE THREAD

**Issue by qingan1996** [stella-emu/stella#262]
Please add Chinese support！
I want to localize him in China, but I can't show Chinese after compiling.

**Comment by thrust26** [comment]
It maybe feasible, but the framework is definitely not prepared for it. And since I assume that no one of the core team knows Chinese, we would need a lot of support from outside here. So if you are really interested, you should find a developer who can help us here.

**Comment by DirtyHairy** [comment]
Apart from layout issues, this would require full unicode support in the UI code. This is a major change, and chances are this won't be happening unless someone provides a PR. Sorry.
