### ISSUE TITLE
Continuous video scaling 

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#263]
Currently Stella supports three fixed zoom factors. It would be cool to make that scaling continuous.  Maybe even scale by changing the window size.

@sa666666 At least the width is already modified by NTSC/PAL aspect ratio, so if there is no limitation for height, I cannot see any major problem here. Do you?

Additional request: Display the resulting size in the Video Dialog too.

**Comment by sa666666** [comment]
Now that most backends are basically using hardware accelerated scaling, the scaling no longer _has_ to be integer based.  This is a holdover from when Stella had mostly a software-only renderer, and doing non-integer scaling was very hard (to code, and to make it look 'right').

Also, it doesn't support only _three_ fixed factors; it auto-calculates them based on the desktop size.  So on my 1080p monitor here, it supports 2x-5x.  On my 2560x1440 monitor at work, it goes to 6x.  And on my 4K monitor (if I ever get the (*#%*#ing computer working again), it probably goes to 8x or more.

I suggest when we get to this (_after_ 5.1) that there be sliders for width and height, and also a set of buttons to 'lock' to integer scaling if desired.  Note also that when fullscreen stretch is in effect, it is already using non-integer scaling.  So the restriction is really only for windowed modes.

**Comment by sa666666** [comment]
It's easy enough to change the window size by 'dragging' from the corner; I've just turned off that ability in SDL when the window is created.

But all of this is only possible in emulation mode (ie, when the TIA output is being shown).  In pure UI mode (ROM launcher, debugger, etc), it can't be done, since the UI code is set up to be created with an initial size/layout, and not changed afterwards (aka, not dynamic).  That's why there's a UI element for changing launcher and debugger window size, fonts, etc.  It has to be done __before__ the window is created.

**Comment by thrust26** [comment]
Emulation mode is perfectly sufficient. Something nice for 5.1.1.

I didn't know that zoom is determined by monitor size. (BTW: I doesn't consider aspect, so I can make it a bit larger than full monitor width).

**Comment by sa666666** [comment]
See ```FrameBuffer::maxWindowSizeForScreen```, which is the method that determines max zoom level.  And you're right that it doesn't consider aspect ratio correction.

**Comment by sa666666** [comment]
Leaving this until after 6.0, as it needs more discussion.

**Comment by thrust26** [comment]
@sa666666 What discussion is missing?

**Comment by sa666666** [comment]
Now that we have steps in 1/4 increments, perhaps this is enough, and we can close this one.  @thrust26, what do you think?

**Comment by thrust26** [comment]
Originally I had thought this would be an intermediate step. But I think you are right, this is sufficient.
