### ISSUE TITLE
_scan not reliable

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#268]
Try `breakif (_scan%#10)==0`. This should break every 10th scanline. But it sometimes skips. E.g. Space Invaders only breaks at 0, 10, 50, 70..230, 260. 

I think this might be related to INTIM loops.

Maybe other _pseudo registers are affected too. I have to test this.

**Comment by DirtyHairy** [comment]
This is a design error in the way the debugger interacts with the emulation :) At the beginning of each instruction, the break conditions are evaluated and checked. However, the TIA (and RIOT) state is only advanced on register access. If no register access happens for multiple lines, the TIA will skip through all of them without the conditions being evaluated, and the debugger will speed past the breakpoint.

The only solution that I see is forwarding the TIA and RIOT states after each instruction if any break conditions are set, at the expense of a slight slowdown. @thrust26 , @sa666666 , what do you think?

**Comment by thrust26** [comment]
Since the slowdown only happens when someone is debugging, I definitely say "yes" to your solution.

All commands which can use conditions (and access TIA pseudo registers) should be considered (breakif, trap(R/W)if, savestateif, stepwhile...)

**Comment by DirtyHairy** [comment]
Yes, basically any pseudo register that exposes TIA or RIOT state is affected.

**Comment by thrust26** [comment]
I can only think only of triggering (break, trap, save...) commands using conditions (which may refer to those registers) which are affected. Correct? So your solution would be sufficient?

**Comment by DirtyHairy** [comment]
Exactly. The issue is relevant only when the debugger is running side-by-side with the emulation.

**Comment by DirtyHairy** [comment]
e5d7c234 should make the necessary changes. @thrust26 , can you check whether you can still reproduce the problem? If not, go ahead and close the ticket :smirk:

**Comment by thrust26** [comment]
That seems to fix **this** issue. 

If you now could also fix #266 I am happy. For now... :smile:
