### ISSUE TITLE
Changed registers and RAM not highlighted in debugger

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#269]
I just compiled an up to date build (got carried away with other things in the past weeks and I need to catch up with all the improvements and changes...), and I noticed that modified registers and RAM locations aren't highlighted anymore with the red background.

**Comment by thrust26** [comment]
Typical example of fixing one bug and creating another. Please check again.

During testing I found another (old) bug: see #270

**Comment by ale-79** [comment]
Everything seems to work fine now, also with rewind. 👍
