### ISSUE TITLE
Query SDL renderers

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#273]
SDL supports functions to retrieve the available drivers (SDL_GetNumRenderDrivers, SDL_GetRenderDriverInfo). Stella should make use of them instead of hard coding the names.

**Comment by thrust26** [comment]
@sa666666 @DirtyHairy Committed (disabled) with 0385dd4

Works well for Windows (I get all but OpenGLES), please test for other OS.

Note: planned for **after** 5.1

**Comment by sa666666** [comment]
I went ahead and committed this, since it's relatively straightforward.
