### ISSUE TITLE
Feature request: move scanline count/ bankswitching info outside the TIA image

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#277]
Is it possible to show the scanline count/bankswitch type info on its own status line, instead of overlaying it on the TIA image? 
![tiainfo](https://user-images.githubusercontent.com/24704739/34905504-3c694718-f85a-11e7-94fe-4ffbebcf6c70.png)

That will require enlarging the window or rescaling the TIA output in fullscreen mode when you toggle it on with ALT-L, but it wouldn't cover part of the image anymore (especially when using low zoom settings).
![tia_info2](https://user-images.githubusercontent.com/24704739/34905506-47f09758-f85a-11e7-8019-d42f6c56034b.png)

Moreover, I think it could be useful to show if "developer settings" are on, and to have the status line  always displayed in that case, to reduce the chances of false bug reports.
![tia_info_dev](https://user-images.githubusercontent.com/24704739/34905508-4b8262de-f85a-11e7-93c8-2485a7f46498.png)

**Comment by thrust26** [comment]
Good ideas. How about making the overlay transparent or semi-transparent?

**Comment by ale-79** [comment]
> How about making the overlay transparent or semi-transparent instead?

Yes, that would work too.

> Regarding the Developer Settings: This won't help if people change the Player Settings. We would have to be more detailed here.

You're right, but I think that just indicating if the developer settings are on will suffice in most cases, relying (or hoping) on the fact that a user playing with the settings know what he's doing.
Going into more detail might be overkill, and it would be hard to come up with something that's compact enough and still easy to understand.

My main issue is that I always forgot what mode I'm in and I have to check in the menu... :smile:

What about putting "developer settings" in the window title? There would be no indication in fullscreen, but I guess window mode is more commonly used during development, anyway.

**Comment by thrust26** [comment]
How about this?
![infostats](https://user-images.githubusercontent.com/24360774/34944144-befd21b8-f9fe-11e7-8655-f842bab69e45.png)

**Comment by ale-79** [comment]
Looks good! 👍

**Comment by thrust26** [comment]
Implemented with b22c292
