### ISSUE TITLE
Fix odd string shortcutting

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#278]
When a string becomes too long to display, Stella automatically creates a shortcut using an ellipsis. Unlike any other application I know, the string is cut in the middle and not at the end. This should be fixed.

**Comment by g012** [comment]
Can we have the full name when hovered by the mouse ?

**Comment by thrust26** [comment]
I doubt that. The framework is not prepared for that at all.

Where would you need it most?

**Comment by g012** [comment]
In the label names, intertwined with asm code, the display space is really short. I had to shorten them a few times to know where I am.

**Comment by thrust26** [comment]
Wait for the next release, we have optimized the layout quite a bit.

**Comment by thrust26** [comment]
fixed with 43be89f
