### ISSUE TITLE
Inverted color in snapshots on Raspberry Pi

### ISSUE THREAD

**Issue by mediamoshpit** [stella-emu/stella#280]
Snapshots produced by Stella seem to be inverted on the Raspbian. It's probably more accurate to say that they are wildly incorrect, as black appears to be a constant no matter what.

**Comment by mediamoshpit** [comment]
Sure. [Here's a link](https://postimg.org/gallery/320y887ak/) to a gallery of four images. They were all snapped in game play.

**Comment by sa666666** [comment]
Looks like R and B swapped.  I once saw something like this when working on the software renderer.  Maybe the endian-ness is different for the Pi, and we haven't tested for it (since most current systems are little-endian).

**Comment by sa666666** [comment]
Also, I really need to get a Pi to see these things for myself, and perhaps do some testing before releases.

**Comment by DirtyHairy** [comment]
@mediamoshpit, is this a standard Pi? I have access to some of those and could give it a shot when I find time.

**Comment by mediamoshpit** [comment]
I'm using a Raspberry Model 3B, but I believe it affects all models.

**Comment by thrust26** [comment]
@mediamoshpit You images are gone. Can you post them here?

**Comment by sa666666** [comment]
I'm going to close this one, since we haven't gotten any feedback, and the images are missing.
