### ISSUE TITLE
ESC key should work everywhere

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#282]
Currently there is a mix of keys which exits a dialog or mode. Sometimes ESC works and sometimes not. 
Here is how it currently looks like:
- ~~Emulator mode: entered from launcher (ENTER or mouse) or command line, exited with ESC~~
- ~~Options Dialog: entered with TAB, exited with ESC; TAB does not work~~
- ~~Options Subdialogs: entered with ENTER or mouse, exited with ESC~~
- ~~Command Menu: entered and exited with '\\', ESC does not work~~
- Debugger: entered and exited with '`', ESC does not work
- ~~Pause mode: entered and exited with PAUSE key, ESC does not work~~
- ~~Time Machine: entered and exited with 'T', ESC does not work~~

We should make this consistent. ESC and the key for entering a dialog or mode should always exit it. 
Note: Since TAB is used for navigation, it cannot be used for exiting Options Dialog.

**Comment by sa666666** [comment]
I will look into the debugger one.  But do we really want to exit the debugger with ESC?

**Comment by thrust26** [comment]
Sure why not?

BTW: With your new code, I know how to do it.

**Comment by thrust26** [comment]
Debugger works since 7d9b738 too

**Comment by sa666666** [comment]
The problem is that now ESC exits from the debugger *and* the ROM.  ESC is registered on a key press, while the backtick is registered on a key release.  I don't recall the reason for this, but it was for a reason.  So unless we can get ESC to work exactly like backtick when exiting the debugger, we cannot use ESC for this purpose.

**Comment by thrust26** [comment]
I reverted that fix.

Now this happens: 
- If you press and keep pressed ESC in the debugger, eventually the keyboard repeats (controlled by the OS delay setting) and not only exits the debugger, but also the emulator. 
- If you do the same within any dialog, this does not happen. Only the dialog is closed. 

So somewhere the existing code is able to prevent keyboard repeats. But this does not work inside the Debugger. We have to find out why.

**Comment by thrust26** [comment]
It finally works in debugger, but now there is #516.
