### ISSUE TITLE
Debugger exited while within subdialogs

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#283]
If you press '`' inside the debugger, while a dialog (e.g. Options or Search/Compare dialog) is open, this exits the debugger. This shouldn't happen.

It seems that the EventHandler doesn't handle those cases.

@sa666666: I can fix this key (with a hack), but not the ESC (see #282) key. If I press ESC while being in a dialog, the EventHandler first closes the dialog and then repeats processing the ESC key and closes the debugger. 
It seems that the EventHandler needs some rework here.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/d7bcde29dc2087be1a55540cacd475ed0e953ff2.
