### ISSUE TITLE
Some debugger enhancement requests

### ISSUE THREAD

**Issue by juanitogan** [stella-emu/stella#287]
Wow!  I haven't powered up Stella in over 15 years.  The debugger is outstanding!  Very impressive work on the UI as well.  Anyhow, some debugger feature requests, if I may:

- Please add signed decimal to the RIOT RAM display for those of us week on our binary and hex.  Perhaps a +/-Dec or ±Dec or sDec label.  A Hex field could be handy as well for when the grid loses focus.  If a selection indicator (such as colored or heavy border) can be added to the grid cell, it would eliminate the need for a separate hex field.
- Related to above, consider persisting the last selected RAM location between breakpoint runs so that a value is easier to follow between breakpoints.
- Please consider adding three or so more pixels to the height of the PS flags to indicate state by highlight rather than (or in addition to) case.  Attach thin boxes above the current field boxes that use color to indicate state.  Thus, change hiliting can happen as it does now, in addition to state coloring.  An alternative might be to label the boxes like the PF boxes are, but instead put ones and zeroes in the boxes instead of color (due to change hiliting overriding the option to colorize the box).

Thanks again for this tool.

**Comment by thrust26** [comment]
- The first point is already covered. Below the RIOT RAM area, the currently selected value is displayed in all formats.
- The 2nd point is a good idea.
- If I get you right, the difference is not obvious enough for you, right. We could use bold for uppercase here, but I think that interferes with the font settings.

**Comment by juanitogan** [comment]
To clarify the first point, the Dec value is displayed but not the _signed_ decimal value, which is sometimes useful to interpret separately.

**Comment by thrust26** [comment]
OK, got you.

**Comment by juanitogan** [comment]
Just a mockup showing a possible thin solution to my third point from above:

![image](https://user-images.githubusercontent.com/2923222/89851598-171c1280-db4a-11ea-8cb6-544e67b37f0a.png)

**Comment by thrust26** [comment]
- Hex field added, signed values can be created using the 'Neg' button.
- Focus done
- The current display for PS will stay as is.

**Comment by thrust26** [comment]
With d3125f23 we have added tooltips which (also) display signed values for many debugger widgets.
