### ISSUE TITLE
Better use of game specific property files

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#288]
Currently Stella can only **create** game specific property (.pro) files and they have to be manually integrated into Stella.pro.

This could be improved:
1. let Stella search for those files and use them automatically 
2. offer a hotkey to load the matching property file manually

**Comment by thrust26** [comment]
Implemented with 2a3bb43

But IMO it now makes the code overly complex.

**Comment by sa666666** [comment]
Since we've removed the ability to create game-specific property files, this issue is no longer relevant.
