### ISSUE TITLE
Timeline calculation error

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#295]
This is a very odd bug and here is how to reproduce:
- disable the TM and start a ROM
- switch do debugger
- do a few steps
- leave debugger
- open TM dialog a few seconds later 
- rewind by one state (display: "- x seconds", note that end time is 00:00.00)
- unwind that one state (display: "+ x cycles")

Obviously that doesn't fit.

Also it seems like the first rewind doesn't rewind at all and that the last two states are the same.

**Comment by sa666666** [comment]
I have a good idea what is causing this; will look into it soon.

**Comment by thrust26** [comment]
Its complicate, because when TM is disabled, the current state is intentionally not saved when opening the dialog. The first rewind then does two steps in one, it rewinds to the last step but one. So when there are e.g. 10 save states, the current state would be an 11th one. But this one is not saved and then the first rewind goes to the 9th save state and unwind goes back to 10th.

IMO, what should happen is a rewind to the last (10th) state in this case. Probably an extra check should do the job.
