### ISSUE TITLE
Snapshots with phosphor in 1x mode not showing phosphor effect

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#296]
This was reported by PM from AtariAge.  I've confirmed that phosphor and TV effects on full-size snapshots are working, and TV effects work on 1x snapshots.  But not phosphor on 1x.  I remember we talked about something relating to this, but can't remember the details.

**Comment by thrust26** [comment]
See #222

**Comment by sa666666** [comment]
Right, that was what I was referring to.  But now we are back to the original question; if 1x mode disables everything (or is supposed to), why do we allow it to show TV effects?  And if we allow TV effects, why not phosphor?  I understand why the code does what it does; I guess I question the design decision (even if I'm the one that made it :smile: )

I think 1x mode should either disable everything (and give raw TIA output) or not.  Completely.  Having it disable one aspect of output (phosphor) but not another (TV effects) is IMO contradictory, and not immediately apparent to the end-user why it's happening.

Perhaps 1x mode should be a developer setting, and have the default be for the snapshot to include exactly what they see onscreen (aka, non-1x mode).

**Comment by sa666666** [comment]
Also, while 'ss1x' option defaults to off, users may be using an old settings file and have mistakenly turned it on.  If we change this to a developer setting, the option name will change, and the problem takes care of itself.

**Comment by thrust26** [comment]
I vaguely remember some discussion, but I have to look it up.

**Comment by thrust26** [comment]
I just checked the current build, for me 1x snapshots definitely show phosphor and TV effects. 

![asteroids 1981 atari _0036e762](https://user-images.githubusercontent.com/24360774/36112233-4106f6a8-1029-11e8-948d-2be3b946f12b.png)

How did you test?

**Comment by sa666666** [comment]
Phosphor mode and Blargg (TV) effects are saved to the snapshot, but not scanlines.  Not surprising, really, since the scanline drawing happens later in the pipeline.

Not really sure how to address this.  Possibilities include:
- document it as such (it's not a bug, it's a feature!)
- rework taking snapshots in 1x mode to just take them at the current zoom level and downscale them
- remove 1x snapshots option entirely
- fix it all so that 1x snapshots are feature-equivalent to larger ones

Which approach we take will obviously depend on the work involved ...

**Comment by thrust26** [comment]
Scanlines make no sense for 1x resolution, because no scanlines are duplicated. So they would be completely artificial. Therefore I opt for option 1.

BTW: The current scanline approach might not work for intermediate zoom levels (e.g. 2.5x).

**Comment by sa666666** [comment]
OK, option 1 it is.

As for the scanlines and non-integer scaling, we will have to test it out.  But it should be relatively easy to adjust the scanline texture to take the actual height into account, and have it look reasonable.

**Comment by thrust26** [comment]
I leave that up to you. Alternatively we could switch to Blargg here too.
