### ISSUE TITLE
POV Hat UI Control Issue

### ISSUE THREAD

**Issue by Pr3ttyF1y** [stella-emu/stella#300]
Using a Sony DualShock3 controller via the MotionInJoy controller driver, any use of the POV hat (i.e., the d-pad on the DualShock3) in the UI causes the hat input to be repeated indefinitely unless interupted by another hat input or leaving the UI. This is what the UI input configuration shows as far as how the hat is detected/setup by default:

J0/H0/up
J0/H0/down
J0/H0/left
J0/H0/right

This repeating input does not affect emulation and use of the left joystick in the UI menu works fine. It is only the hat which causes the problem, so if you tap up on the d-pad, the UI responds as if you are continually holding up on the d-pad. Then if you press down, the UI will respond as if you are continually holding down on the d-pad.

Again, this issue does not affect the a2600 emulation nor have I had this issue in any other emulator/game/control panel config/etc.

**Comment by sa666666** [comment]
I think I have found the issue here, after running Stella through Coverity.  I will update again when I can reproduce the bug.
