### ISSUE TITLE
Exit popup

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#302]
It quite frequently happens that I am exiting the emulator using ESC accidentally. So there should be a (maybe configurable) message pop, where the user confirms that he really wants to exit.

**Comment by sa666666** [comment]
But you're the one that wanted Escape to exit from everything :smiling_imp: 

In any event, it shouldn't be too hard to add such a thing.

**Comment by thrust26** [comment]
Yes, I still stick to my intentions. :smile:

**Comment by thrust26** [comment]
Done with 5f28428
