### ISSUE TITLE
Default PAL palette is off

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#303]
The current default Stella PAL palette doesn't really match what I see on my hardware (composite modded Darth Vader, Sony Trinitron CRT). So I created my own PAL palette file.
[Stella272a.zip](https://github.com/stella-emu/stella/files/1865212/Stella272a.zip)

Here are two screenshots from my color test program:
Stella palette:
![colortest pal50](https://user-images.githubusercontent.com/24360774/38160295-a6dca6d8-34bb-11e8-8b74-91b3a352d66d.png)

Own palette (see Stella doc how to use it):
![colortest pal50 _1](https://user-images.githubusercontent.com/24360774/38160299-a8f0d84a-34bb-11e8-986e-826a3f0618e5.png)

Most obvious is the higher contrast of my own palette. The brightness of the grays is significantly lower here. And some of my colors are more reddish.

The test program I developed has two modes, which can be switched with the fire button and the Color/BW switch. The first mode is shown above. The second mode shows only one color with its luminosities. In both modes you can select color with up and down, and luminosity with left and right.
[ColorTest (PAL50).zip](https://github.com/stella-emu/stella/files/1865208/ColorTest.PAL50.zip)

I don't know how representative my hardware is, therefore I need **HELP** from other people with a PAL hardware setup. Please add your findings (text, screenshots, palette files... whatever)  here, so that we can create a better default PAL palette for Stella.

**Comment by sa666666** [comment]
@thrust26, you recently updated the PAL palette, so can this be closed now?

**Comment by thrust26** [comment]
Yes.
