### ISSUE TITLE
Libretro port

### ISSUE THREAD

**Issue by orbea** [stella-emu/stella#305]
Hi,

I was wondering if the libretro port of stella could be upstreamed? I'm not sure how much work this would entail or how much progress has been made on this in the past, but it would be good to merge both code bases so everyone who wants to use stella can benefit from general fixes. This would also make it a lot better for package maintainers and would hopefully result in more people submitting pull requests  and issue reports in one place.

Please see the libretro repo for more info.
https://github.com/libretro/stella-libretro

Thanks!

**Comment by iesposta** [comment]
Updated Stella in libretro is now very desirable. 
Two main reasons are: 
1) The current lr-Stella is using 3.9.3. 
2) RetroArch / libretro has the feature of eliminating lag with a simple wizard that ends up skipping ahead. 
Seeing it demonstrated with edited fix; press a button - watch screen character react late, to: Press a button — on-screen instant action. 

Feel free to cross-post this for a Stella enhancement also: 
The operation of regular Stella with frame lag adjustment .

**Comment by sa666666** [comment]
Closing this one, since it now seems to be progressing in https://github.com/stella-emu/stella/issues/377.

**Comment by orbea** [comment]
Thanks for pointing out the new issue, I missed it until now! :)
