### ISSUE TITLE
Improve controller mapping

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#307]
The controller mapping needs improvement. 

TODOs:
- core changes (...)
- UI changes (Game Info, Event Mapping)
- better paddle axis inverting in UI (and code)
- add Trackball mapping
- update documentation

**Comment by thrust26** [comment]
@sa666666 Now that we have reworked the keyboard mapping, couldn't this issue profit from the results?

**Comment by sa666666** [comment]
Yes, this was a necessary first step.  Now we can think about how to solve this one.  In particular, how to have the same action map to two different events at the same time.  We can discuss this further on gitter.

**Comment by thrust26** [comment]
I suppose this can be closed now, no?

**Comment by sa666666** [comment]
I suppose we should leave it open until after testing/feedback from beta 3 (whenever that may be).

**Comment by thrust26** [comment]
I would rather create individual issues for that. That's easier to track.

**Comment by sa666666** [comment]
OK, then I guess we can close it.
