### ISSUE TITLE
deb package build: remove usage of own png code

### ISSUE THREAD

**Issue by SvOlli** [stella-emu/stella#308]
The usage of the own png code is only required up to building Ubuntu 14.04.

Debian 8 and 9, as well as Ubuntu 16.04 and the upcoming 18.04 build fine using the libpng provided by the system.

On the other hand, using the supplied png code breaks on rather exotic systems like ARM64 on any distro. So placing the "--force-builtin-libpng" argument for configure with a build dependency to "libpng-dev" should be a "more modern" option.

Patch containing suggested changes:
[stella-deb.diff.txt](https://github.com/stella-emu/stella/files/1922842/stella-deb.diff.txt)

**Comment by sa666666** [comment]
Implemented in https://github.com/stella-emu/stella/commit/1bb3790e12746f89bb09b730bbf0f9973ec75fa0.
