### ISSUE TITLE
Build binary without UI.

### ISSUE THREAD

**Issue by monirz** [stella-emu/stella#309]
How can I build a binary (not Debian binary or something like that), so it can be called  just as an emulator without the UI? I mean something like this: ./stella <rom name> ?

**Comment by sa666666** [comment]
First of all, the following is for Linux only; I will address Windows and OSX afterwards.

- You can disable the debugger and its associated UI with an option to 'configure' in Linux.
- You can set the commandline option 'UI Settings -> Launcher -> Exit to Launcher' to 'If in use', and then when exiting a ROM, it will completely exit the app (ie, it will not show the UI).

With the last option in particular enabled, you can launch with './stella ROM_NAME' and it will go directly into the game, and when exiting it will go back to the console (no ROM launcher shown).

Launching the app with './stella' will currently always start in UI mode.  What else should it do?  So just don't launch it that way, and you never see the UI.

As for the UI within the app, don't press 'Tab', and then it won't be shown.  Of course in that case you won't be able to change any options within the app, but then you _are_ disabling the UI, so you get what you asked for.

For Windows and OSX, you'd need to modify the build scripts to have the binary built without debugger support.  This has never been requested, so it is not a priority.

Really, in almost all cases you can 'not see' the UI by just not pressing a key that shows it (ie, don't press '~' for the debugger, 'Tab' for the options menu, etc).  Having the UI code still be in the app is irrelevant at that point.

But I guess the real question I should ask is: why do you want to even do this?  What is the use case for it??

**Comment by monirz** [comment]
The first option: you mean should I disable it in the config file like this _build_debugger=no?
Second option: Are you referring to GUI, I need it in the build/compile time so I just can execute the binary with another language 
Yes, I'm on Linux. What I want is run/execute it from another language.

**Comment by sa666666** [comment]
The debugger can be disabled completely by not including it in the app at all (incidentally, this will also make emulation slightly faster).  This needs to be done by the 'configure' script.  Run './configure --help' for more information; the applicable option is '--disable-debugger'.

As for wanting to run from another language; sorry, I need more explanation on that, as I have no idea what you mean.

**Comment by smga3000** [comment]
Thanks sa666666, we're just building a little front end in golang for multiple emulators to be hosted and launch roms, so we don't want to display any UI's from the emulators. Full credit of course will be there, it's just an experiment at the moment. thanks again.

**Comment by monirz** [comment]
Aha :| , but ./stella <rom-name> just starts the game interface. I think that's what we want here, what we need is just don't want to call the rom separately from GUI.

**Comment by monirz** [comment]
@DirtyHairy So, there's no way for it to disable the GUI in compile time?

**Comment by smga3000** [comment]
By disable, you mean to leave the code out to make a tighter binary?

**Comment by monirz** [comment]
Yes, right because we don't need the GUI, so it would better to leave it off.

**Comment by sa666666** [comment]
There are really only 3 cases where the UI appears:
- the debugger (which can be completely removed from the app, by not compiling it).
- the ROM launcher (which can be avoided by always starting the app with a ROM, and with the `exitlauncher 0` commandline option, it will not exit into it either).
- the in-game UI, used for settings.

Only the last one is really an issue, and if you disallow the user to press 'Tab', then it will never appear anyway.

Actually making the app be compile-able without any UI at all is not something that has ever been requested, and TBH I'm not sure how much memory it would really save anyway.  If you on a RAM-constrained system, I can suggest much better ways of saving RAM (in particular, not compiling in the ROM properties database, which will save over 550KB alone).  But really, the entire app only uses about 32-45 MB of RAM anyway, so I'm thinking not much can be gained in this area.

**Comment by monirz** [comment]
OK got it, thanks @sa666666

**Comment by sa666666** [comment]
I will leave this open for now, as it might be something we pursue in the future.  But it will have a low priority.

**Comment by sa666666** [comment]
I think we can close this one.  Currently SDL, PNG, ZLIB, cheats, debugger, joystick and sound can be compiled out of the app.  The UI code doesn't actually take up much space, and if you don't press a key to activate it, it's as if it's not there at all.

And we can run on the Retron77, which is a very constrained system.  And there is now a libretro port that doesn't make use of the UI at all either, but still compiles it in.  If it works in those cases with the built-in UI, I think we can basically ignore any (small) amount of extra space it takes.

**Comment by sa666666** [comment]
In the end, I implemented this anyway, for the libretro port.  I still believe it won't make much difference, but it ended up being only a few hours work, and it eliminates compiling ~47,000 lines of code.
