### ISSUE TITLE
YStart display property ignored

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#31]
Probably a missing feature: The values in YStart have no effect (e.g. see Jammed).

Also, unrelated to the new core: Changing the Height property seems not to work anymore. E.g. see Acid Drop, the height is displayed is displayed as 210 (the same value for all games I checked) but the game displays ~260 lines.  Changing the value doesn't change the display.

[Jammed (2001) (XYPE) (NTSC).zip](https://github.com/DirtyHairy/stella/files/643702/Jammed.2001.XYPE.NTSC.zip)

**Comment by sa666666** [comment]
Yes, I haven't gotten to these yet.

**Comment by DirtyHairy** [comment]
I have reimplemented ystart in 452f083 . In the old core, there was always a fixed ystart with the default being 34. The new default is 0 which translates to "autodetect" . In 7b733d6 , I have made a small step towards weeding out ystart from the props where it isn't required. From what I have seen, I think that autodetect will cover almost all cases where ystart was adjusted manually (though the autodetected value will usually differ from the manual value by a few scanlines).

I think that we actually should make the effort and remove it for all cartridges that run fine without it. @sa666666 , @thrust26 : what do you think?

**Comment by sa666666** [comment]
I will go through the ROMs and remove it as necessary.

**Comment by thrust26** [comment]
Autodetection may need a little rework:
http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-4#entry3676348

The top white line is missing.

**Comment by sa666666** [comment]
I adjusted a few ROMs manually to deal with such issues; I figured that it wasn't a problem with the ystart detection, just how the ROM worked.  If this is fixed in code, I can go back and re-adjust those ROMs (perhaps eliminating the ystart property from them entirely).

**Comment by thrust26** [comment]
I checked, Time Pilot has **no** YStart property. But it has a quite large bottom black area. That makes me think that automatic centering isn't working correctly here.

**Comment by sa666666** [comment]
Yes, most ROMs no longer have any YStart property (default of 0).  What I meant is that in a few other ROMs, I manually changed it from 0 to something else to detect the missing top line or 2.  If this is an error in coding, I will go back and re-adjust them accordingly.

Also, there is no automatic centering happening, nor was there in the old core.  The only time centering ever happened in the old core was when the window was smaller than the size of the TIA image, in which case the image was vertically centered with top and bottom cut off.  This was mainly for 'small' systems (cellphones, hand-held gaming machines that had low resolution), and was never an issue on a desktop system.  In any event, even this code was removed some commits back, since it interfered with automatic ystart calculation.

**Comment by DirtyHairy** [comment]
I'll check this out once I get the other issues fixed. It is totally possible that there is a +-1 error lurking around somewhere in the algorithm that gobbles the first line.

**Comment by thrust26** [comment]
Ok, but then I don't understand why Time Pilot doesn't work correctly. VBLANK is disabled at the beginning of scanline 35, which is where the missing white line is drawn too. There seems to be a one line delay in the code.

**Comment by sa666666** [comment]
Come to think of it, for a number of ROMs I manually adjusted, only 1 or 2 extra lines were needed.  Perhaps we should just add 2 to anything that is calculated by ystart autodetection :wink:

**Comment by DirtyHairy** [comment]
Actually, thinking of it, I see what is happening: after vblank is turned off, state is switched *on beginning of the next line* --- that's where the one line is coming from. I guess that this can be fixed cleanly. If not, then adding 1 or 2 would be a pragmatic solution :smirk:

**Comment by thrust26** [comment]
In 5.0 the same YStart value starts the display one line later than in the old core. That's one line to too late now.

**Comment by sa666666** [comment]
Can we get this one fixed soon?  Because there are quite a few ROMs that won't need specific ROM properties if the display starts one line later.

**Comment by DirtyHairy** [comment]
Fixed in 8f93704 . Rendering is now started in the very same line in which vblank is turned off, and the one line offset w.r.t. Stella 4 when setting ystart explicitly is gone.
