### ISSUE TITLE
Savekey autodetection not working in 5.1.1

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#312]
Report is from AtariAge (http://atariage.com/forums/topic/275179-stella-51-released/page-3#entry4030763), as follows:

> I just installed 5.1.1 for Windows 10 and I'm having an issue with Savekey, but only for my games (Scramble, Super Cobra and Mappy). No matter what I do I can't get Stella to detect that I have a Savekey configured in the right port.
>
> I have changed the Controllers for the Right port to be Savekey and restarted the ROM using Ctrl-R, but my games do not detect a Savekey. I've also tried via the command line with -rc savekey but still no luck.
>
>I tried with 4.7.3 and all 3 of my games can find the Savekey with that version (as it does on real hardware). What's strange is that I tried Juno First on 5.1.1 and it *does* find the Savekey properly. I'm not sure if it's something in my code, but like I said it does work on real hardware and I had no issues prior to 5.1.1, so I'm not sure if it's Stella or something else.
>
>I have uninstalled and re-installed Stella, deleted the entire AppData\Stella directory and re-installed, even installed the 32-bit version but no difference. Is there something in the registry that I may need to clean out?
>
>Any one else experiencing the same issue? I've attached the final ROMs for Scramble & Super Cobra Arcade if anyone has a minute to try it in Stella 5.1.1 on Windows with Savekey enbaled; you should see "SAVEKEY FOUND" on start up with the Atari Age splash screen. Remember, you can enable Savekey by going to Options|Controllers and setting the Right controller to Savekey (or Atarivox) and then reloading the ROM using Ctrl-R.

[scobra_final.zip](https://github.com/stella-emu/stella/files/2019857/scobra_final.zip)

I'm about to test in each version of Stella from the last 4.x release to determine when the problem started.

**Comment by sa666666** [comment]
Symptom found, but still researching the cause.

If the `savekey_eeprom.dat` file already exists, then Super Cobra detects it correctly.  However, if it doesn't already exist, while it _will_ be created, the app doesn't seem to register that fact.

In Stella 5.0.2, if the file doesn't exist, it will be created, _and_ the app knows about this (so the ROM will work).  Furthermore, running Stella 5.1.1 afterwards will work fine.

So it seems something changed from 5.0.2 to 5.1 wrt creating the `savekey_eeprom.dat` file.  The 5.1 changelog also notes that Savekey changes were made, so I guess an unintentional bug crept in.

**Comment by sa666666** [comment]
I think I've found the issue, but I have to recheck other Savekey ROMs to make sure nothing is broken.  If this is the issue, I will do a 5.1.2 release.

**Comment by sa666666** [comment]
Problem was actually that `MT24LC256::systemReset` changed behaviour from 5.0.2.  I await feedback from the original bug reporter that this indeed fixes the issue.

**Comment by thrust26** [comment]
Funny reason.

**Comment by sa666666** [comment]
Confirmed that commit in https://github.com/stella-emu/stella/commit/626182ddecb91cefaf9f9298072b92cf69a945f1 fixes this issue, so I will close it now.
