### ISSUE TITLE
Use canonical list for SaveKey/AtariVox allocations in EEPROM file

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#313]
This was suggested by johnnywc of AtariAge.  Currently the Avox/SaveKey code keeps track of accesses to the EEPROM file, and afterwards knows which section of the file the specific ROM 'owns'.  Note that these locations are also maintained by Al of AtariAge, and given out as ROMs are finalized.

The suggestion is to somehow make use of this maintained info in Stella, perhaps by adding it to the ROM properties database or something, so we know for sure which area is allowed to be accessed.

There is also a 'scratch area' at $3000 used for ROM testing.  Perhaps we can also add a button (or something) to edit/reset this area too.

**Comment by thrust26** [comment]
Hm... I am not sure about the benefit of such a list.

I would rather implement a developer option which shows a warning when an access outside a  user defined area happens.

**Comment by sa666666** [comment]
Is this relevant any longer.  @thrust26, you've already added a message when EEPROM access occurs, so is there anything else here that needs to be done?  If not, you can go ahead and close it.

**Comment by thrust26** [comment]
IMO we can close it.
