### ISSUE TITLE
Stella crashes via commandline with SaveKey enabled

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#314]
The message surface is still NULL. Probably happens due to auto detect loop.

I wonder if there are other bugs hiding.

**Comment by sa666666** [comment]
I would suggest an extra method that both tests 'uimessages' is enabled *and* checks if the buffer is non-null; perhaps something like `canShowMessages()` or something.

Of course we still need to add calls to it to the codebase, but that should be easy enough to do; just look for calls to `getBool("uimessages")` and replace as appropriate.

**Comment by thrust26** [comment]
So should I fix the fix again?

**Comment by sa666666** [comment]
I was simply addressing your comment _"I wonder if there are other bugs hiding"_.  My suggestion would take care of all such potential bugs, because we'd basically be tying 'checking whether we _should_ print a message' with 'checking whether the surface is valid' into the same logical block.

**Comment by thrust26** [comment]
Hm... isn't that what the code is currently doing anyway? Why an extra method for checking?

**Comment by sa666666** [comment]
I interpreted your comment _"I wonder if there are other bugs hiding"_ to mean that there may be **other** cases of checking for messages being enabled, but forgetting to check that the surface is valid.  IOW, while you fixed it in this case, you were wondering if _other_ places may have the same bug.

My suggestion to add a method to check both at the same time would take care of this type of issue for good, now and in the future.  And really, when you think about it, checking the boolean is no longer sufficient.  That check, and the check for a valid surface, logically belong (a) together and (b) abstracted away into a separate function.

**Comment by sa666666** [comment]
To be clear, I am thinking of other places this may happen in the _current_ code, and its re-occurrence in _future_ code.

**Comment by sa666666** [comment]
Arrgh, never mind!!!  I see that your change IS in the method that shows messages.

Context is important, and I failed to see where your change was added.  I was just looking at the code you fixed, and not WHERE you fixed it.  :zzz:
