### ISSUE TITLE
Short VSYNC should cause jitter

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#316]
Certain game jitter on real hardware when VSYNC is not created correctly. 

When the signal is enabled for at least 3 full scanlines, the picture is stable. Anything shorter may cause a jittering picture. I am not sure if that comes from the too short signal or the varying length of the signal.

**Comment by thrust26** [comment]
The attached ROMs shows jitter on real hardware in the map select screen for **some** maps (constant e.g. 4th and last one, intermediate in last but 2 and last but 4).
[ut2600_20180603_BETA4.zip](https://github.com/stella-emu/stella/files/2071177/ut2600_20180603_BETA4.zip)

**Comment by thrust26** [comment]
I think we should emulate jitter in both cases:
- VSYNC is hit at varying cycles
- VSYNC is enabled less than 3 full scanlines (maybe with a little tolerance)

**Comment by sa666666** [comment]
If possible, I'd like to get this one fixed for 6.3.  There have been quite a few reports of ROMs working perfectly in Stella and rolling on real console, and I suspect this is the cause.

**Comment by sa666666** [comment]
If possible, I'd like to get this one working for 6.4; too late for 6.3 now.

**Comment by sa666666** [comment]
@DirtyHairy and @thrust26, did we get anywhere on this one?

**Comment by thrust26** [comment]
I haven't looked into this. I suppose @DirtyHairy had to provide support here.

**Comment by thrust26** [comment]
I think there are several things here which could be improved. 
- We already have jitter implemented based on varying scanlines. But the trigger is using fixed parameters (see `JitterEmulation::Metrics`). It might be better to parameterize this (needs research), since not all TV are the same.
- For VSYNC we probably need parameters too, e.g. a varying start (or length) of the VSYNC signal can cause jitter, and a too short VSYNC too. This is also different per TV.

Probably we should combine all parameters into one jitter sensitivity setting.
