### ISSUE TITLE
Genesis controller issue

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#317]
The test roms in [this thread](https://atariage.com/forums/topic/279570-auto-detecting-controller-at-startup/) on AA behave differently than real hardware.
The genesis pad should be detected as paddle but it isn't in Stella because only the paddle line on pin 9 (INPT1/INPT3 depending on the port) is pulled high, while on real hardware both paddle lines (pins 5 and 9) are.

**Comment by thrust26** [comment]
How should the test program behave correctly?
[PaddleTest.zip](https://github.com/stella-emu/stella/files/2095229/PaddleTest.zip)

**Comment by ale-79** [comment]
The bar corresponding to a port (left/right) where a genesis pad is plugged in should be red

**Comment by thrust26** [comment]
So pin should be always pulled high, right? Is it reset with VBLANK too?

Is there some e.g. button connected to pin 9? If not, why is the controller doing that?

**Comment by ale-79** [comment]
There's no button connected to that pin, as, on a Genesis/Mega Drive console, that's the power (+5V) pin. 
https://gamesx.com/wiki/doku.php?id=controls:megadrive_genesis_controller_3

**Comment by thrust26** [comment]
Hm, ...can this be used to auto detect a Genesis?

**Comment by thrust26** [comment]
I just committed a fix, which works for the test program. 

Do you know anything I can use as regression test?

**Comment by sa666666** [comment]
Hmm, if there's no connection, wouldn't that imply max resistance (ie, an open circuit)??

**Comment by thrust26** [comment]
Well, the test program only works with minimum resistance.

**Comment by ale-79** [comment]
The pin is connected to pin 16 of the multiplexer IC inside the controller and to the resitor array. It's not completely clear to me why the controller still works on the 2600 even if power is applied to the wrong pin. I guess pin 1 of the 74157 IC (which is connected to pin 7 of the controller port, which in turn is power on the Atari) has an internal pullup resistor which allows the controller to be powered from that. I don't think the pad can be distinguished from a set of paddles by an autodetection routine just by testing the paddle lines.

**Comment by ale-79** [comment]
> Do you know anything I can use as regression test? 

I tried Scramble and Stay Frosty 2 (see issue #206): both show no regression and correctly detect the genesis pad. Also the "Testcart" now correctly shows both paddle lines with minimum resistance (as on real hardware).

**Comment by thrust26** [comment]
Thanks for testing.

**Comment by sa666666** [comment]
@ale-79, can you point me to the specific Scamble and Stay Frosty 2 ROMs you used for testing?  I want to have them locally to test this functionality in the future, in case something breaks again :smiling_imp:

**Comment by ale-79** [comment]
The roms I used are from my local romset. I'm not sure they're the latest versions:
[roms.zip](https://github.com/stella-emu/stella/files/2095547/roms.zip)
