### ISSUE TITLE
Add an alternative '10-ft UI' ROM launcher interface

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#323]
This was first brought up in http://atariage.com/forums/topic/266544-retron-77/page-77#entry4071022.  Although it is wrt the Retron77, this is a feature that many people using the PC version of Stella might be interested in too.

The basics of such a UI are very easy to do; all the infrastructure is there in Stella (loading and displaying PNG images, file and directory navigation, etc).

**Comment by thrust26** [comment]
Wouldn't a (much) larger font solve the problem?

**Comment by sa666666** [comment]
Still wouldn't solve the problem of the UI essentially still being text-based.  And the buttons being there essentially implying to use a keyboard and mouse.

What the new UI would look like is still up for debate.  But I guess the main difference is one is a keyboard/mouse (aka, WIMP) interface, and the other will be more graphical (skins, etc) and icons only (think Windows Metro or Apple iOS).

**Comment by thrust26** [comment]
IMO a joystick controlled UI has to be much closer to a keyboard controlled UI than a touch controlled UI.

**Comment by sa666666** [comment]
Well, yes, behind the scenes the code will mostly be the same, and could be controlled from either a joystick or a keyboard.  What I want to remove is the requirement of a mouse (but I suppose it could still work with one).  And having buttons, scrollbars, etc.

Basically make it look very similar to the R77 UI, but have all the features of Stella file/directory handling behind the scenes.  And be skin-able; this is very important to many people.

**Comment by thrust26** [comment]
Agreed, the 4 launcher buttons make not much sense in such an UI. Also searching for files by name without a keyboard is pretty tedious and useless.

And instead of scrolling you will have paging.

**Comment by sa666666** [comment]
Yes, it's all relatively easy to do.  Removing stuff is of course very easy.  And what you call 'paging' is simply scrolling (so use the current) a page at a time :)  It's mostly a re-arrangement of the current UI elements, and changing what's drawn in the background (solid colours vs. PNG).  Nothing insurmountable.  Of course even if I get to this, it will only be for Stella 5; I'm not backporting anything else to Stella 3.

Logging off for evening ...

**Comment by thrust26** [comment]
I wonder what the icons should display, as generic icons make little sense and are just a waste of space.

- ROM size
- Controller type
- Company logo
- screenshot thumbnail, maybe even animated

We could make this configurable by the user. And also if the want large icons or small ones. In the end it might look like that Windows Explorer which I am never using. :smile:

**Comment by thrust26** [comment]
Instead of icons, we could also display the (scaled) images from the ROM Info viewer.

**Comment by sa666666** [comment]
I think everything we need is in the current version of Stella: large fonts, resizeable snapshot area, text that 'flows' on linebreaks, etc.  So I consider this done.
