### ISSUE TITLE
First start 'Browse' button not working

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#324]
When you start Stella's launcher the first time, a popup with two options ('Default' and 'Browse') appears. The latter should open a file dialog but it only closes the popup. And the next time you start the launcher, the popup appears again.

Actually it seems as if both buttons are reversed.

**Comment by sa666666** [comment]
Well, the implication is that the user should then select the browse button immediately afterwards, but I guess it doesn't hurt to force it right away.

And now that I think about it, 'Default' doesn't really mean anything anyway???

**Comment by thrust26** [comment]
Which browse button? 

Default makes sense as an alternative to browse if the latter would really cause a browse dialog to open.

**Comment by ale-79** [comment]
The current behaviour seems correct to me:
if you click "DEFAULT" a dialog is opened to choose the default rom directory, while if you click "BROWSE" the popup is closed and you just browse the filesystem from the launcher (it starts in my $HOME directory if I delete/rename the "stellarc" file).

In 5.1.3 and older versions those buttons were labeled "OK" and "CANCEL", so it was clear that clicking "CANCEL" would have just closed the popup.
![senzanome](https://user-images.githubusercontent.com/24704739/42738084-4131ef3e-887e-11e8-9376-c3322565c5dc.png)

**Comment by sa666666** [comment]
I haven't looked at the startup dialog in a long time, so I may be mis-remembering the details.  I will have to actually look at it again before I can add any more comments.

**Comment by thrust26** [comment]
Maybe i was just confused. How can I enable the dialog again?

**Comment by ale-79** [comment]
Rename/delete/move the "stellarc" file.

**Comment by sa666666** [comment]
It's only enabled (ie, pops up at starup) when 'romdir' argument is empty (aka, no starting point known).  This of course happens when you delete the stella config file, but you could also do it manually.

**Comment by thrust26** [comment]
Hm... I think the old names where actually less confusing. And replacing _OK_ with _Select_ seems to be the best solution right now.

BTW: I have used Stella for months on the computer, but never the launcher. So the message should be adapted to launcher usage not Stella in general.

**Comment by ale-79** [comment]
> BTW: I have used Stella for months on the computer, but never the launcher. So the message should be adapted to launcher usage not Stella in general.

You could just remove the first sentence and start from "Before you can start a game..." since the popup shows up because no default rom dir has been set and that doesn't automatically means that's the first time you're running Stella (or the launcher).

**Comment by thrust26** [comment]
I suppose that's a the best idea.

@sa666666  What do you think?

**Comment by sa666666** [comment]
I have no real preference either way.  Whatever happens, when 'romdir' is empty, it will keep asking for it until it is set to something.  So my idea is this:

- Whichever option it selected, it eventually leads to romdir being set.
- One option selects the current dir and sets romdir to it.
- The other option shows a browser dialog, and sets romdir to whatever _it_ selects.
- The actual choice of text for the buttons is up to you, so long as it properly enumerates these choices.

**Comment by thrust26** [comment]
Agreed on all points, except for the 2nd. IMO _romdir_ should be set when a game is started. That way the user can navigate to his ROMs and start playing. 

And _romdir_ could become something like _lastdir_. So the emulator remembers the last directory used for playing.

Thoughts?

**Comment by sa666666** [comment]
I suppose it could be done that way.  So if the user just selects ROM right away, then they also are implicitly setting romdir.  Otherwise a browser pops up, and through this the _explicitly_ select romdir.  Either way, it is selected, which TBH is my only requirement.

I don't have a problem with romdir being set when it is empty, but I don't know if I'd want to change it _every_ time after the program exits.  Or more to the point, while it's fine to remember the last rom, I don't  know if I want to remember the last dir all the time (it's nice to go back to the 'root/base' dir on each start.

Maybe for now we don't worry about that part, and only set romdir when it's empty (in the fashion you explain above).  Anything further than that, we can document it here for inclusion _after_ 5.2/6.0.

**Comment by thrust26** [comment]
Ok, let's skip _lastdir_ for now.

But if we do it like I suggested above, we don't need that dialog (and the browse dialog) at all. If _romdir_ is empty, the user simply navigates to his ROMs and starts playing. 

Or is there some functionality we would loose?

**Comment by sa666666** [comment]
Hmm, I see what you mean now.  This browser functionality was added at the request of Brad many years ago.  But thinking back, I think that the original launcher window _wasn't_ browse-able, so we had to offer the option of browsing to that initial directory.  Now that the ROM launcher is browse-able itself, I see what you mean in not needed the dialog at all.

I am almost always in agreement for removing code, so maybe we go that route and remove that functionality entirely.  The first ROM that is selected will implicitly set romdir.  Thereafter, it will not be set.  Whether we want to have a lastdir (or not) is something that can wait until after the next release.

**Comment by thrust26** [comment]
Great. Do you want to change that yourself?

**Comment by sa666666** [comment]
Yes, I can get to it.  Maybe not before the first beta, but it will be done before the final release.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/5bc8d2d1b094faa782186b285a03c227a9233be9.
