### ISSUE TITLE
Improve linux symlink support in launcher

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#325]
I think I once mentioned this on the AA forums and browsing the filesystem using the launcher yesterday while testing the initial popup dialog remembered me about it.

I use symbolic links a lot to organize my files and this causes a few (minor) issues while browsing through them in Stella:

**1.**  The name of the destination file/dir is displayed instead of the link name. This can be consfusing and also cause several files/dir with the same name to appear in the launcher browser (See this picture as an example: the two links "_emu_e_prog_" and "_immagini_" point to two separate directories both named "_atari_", so I get two "_atari_" entries in the browser and it's impossible to know which is which)

**2.**  The path (displayed on the bottom of the laucher) is always the absolute one and doesn't consider links. (in the example it's "_\~/docs/informatica-elettronica/retrocomputer-consolle/atari_" even if I actually went there using the symlink "_\~/docs/atari_"). If you browse through links, the launcher doesn't remember the path you followed and selecting the parent dir [..] goes to the parent of the linked directory.

Both are minor issues and probably affects very few users (in fact I don't have links in my default rom dir, so it rarely bothers me too), but if it's simple enough it would be nice to fix at least **1.** 
With the links names displayed correctly, **2.** would became much less confusing and could just be left as is.
![senzanome](https://user-images.githubusercontent.com/24704739/42756377-182e381c-88fc-11e8-97ec-2da47b387c40.png)

**Comment by sa666666** [comment]
I suspect fixing 1 will automatically fix 2.  The launcher is storing directories/file-names in an FSNode class, which behind the scenes is essentially storing a string of the absolute path.  And when going to the parent, it simply backtracks along the string, looking for a parent '/' (for UNIX and OSX at least).

So for number 2, you're actually going to a different location (at least the code thinks so).  Then when you go to the parent, it correctly finds the parent _of the current path_.  This part is working fine, so nothing needs to be done there.

If 1 was fixed, and showed the actual linked path, the the parent part would automatically work.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/64fd3f50f9026f73dfd3b4b515c5cf39c3d29184.
