### ISSUE TITLE
Display current settings in "Commands" dialog

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#326]
I think replacing the buttons for the switches with a toggle button which indicates the current setting would make this dialog more accessible (someone at AA suggested this).

Additionally e.g. the current TV format, palette and the current slot number could be displayed.

And following the discussion in #297, we might want to add more commonly used buttons here too.

**Comment by sa666666** [comment]
Maybe also at some point make this dialog look more like a 2600 console, with the button images themselves indicating the state (something similar to the Javatari interface).

Not a priority to do this part, just maybe something to think about for the future.

**Comment by thrust26** [comment]
Good idea. For a start we could just rearrange the buttons. But I suppose that would make the dialog too wide. So we definitely need some other kind of display for achieving that goal. Maybe multi-line labelled buttons? Or we could use the icon buttons we already have.

**Comment by thrust26** [comment]
Something that bothers me for a while now: The order of Stella's hotkeys is different to the console's order.

- Stella: Power (ESC), Select, Reset, B/W, Left Diff, Right Diff
- Console: Power, B/W, Left Diff, Right Diff, Select, Reset

I suppose we don't want to change Stella's established order (taken from z26 IIRC). 

So then the question is: For ordering the 'Commands' dialog, which order should we follow? It seems more adequate to follow Stella's order, but then we have no option for a graphical console interface.

Thoughts?

**Comment by thrust26** [comment]
![image](https://user-images.githubusercontent.com/24360774/43925883-e0f75320-9c28-11e8-95f3-f1607f0f6c1a.png)
First draft, 3-5 buttons free. What should be there? Zoom++, switch phosphor, switch fullscreen, TV mode++ (Blargg), enable/disable sound, switch game info, left/right controller++...?

**Comment by thrust26** [comment]
@sa666666 Which functions should we add to fill the gaps?

**Comment by thrust26** [comment]
I think we can close this one.
![image](https://user-images.githubusercontent.com/24360774/52935265-3709b600-3359-11e9-8a67-cf95e9249c25.png)
