### ISSUE TITLE
7800 pause key doesn't work in "player" mode

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#328]
As the title says, the 7800 pause key only works if you set the console type to "atari 7800" in "developers settings", while it doesn't if you do the same in "player settings".

**Comment by thrust26** [comment]
How did you test this?

**Comment by ale-79** [comment]
> How did you test this?

I just tried with some of the early games that have a different B/W palette to see how they react to the pause key. 

I recompiled with the fix and it works fine now :thumbsup:
