### ISSUE TITLE
Add global 'stereo' option

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#332]
The new sound core allows mono/stereo switching at runtime.  Also, many people have requested a way to select 'stereo' all the time, but without having to edit properties for every ROM.  I propose to add a "Stereo" option to AudioDialog, with three options:
- Mono
- Stereo
- By ROM

The last one will use whatever is specified by the ROM properties; the first two override ROM properties.  The last one will be the default, so behaviour from previous versions is maintained.

Note that the actual text for the option name and its choices is up for debate.  I only mention the intent of the option here.  More discussion probably required.

**Comment by thrust26** [comment]
We should align the label to `GameInfoDialog` (Stereo sound) and _By ROM_ being the default should be the first option. Else I am fine.

**Comment by thrust26** [comment]
I updated the dialog, now this needs to be used by the sound system.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/2db48ae38b648087c535ba306a1be63b4fe7cc77.

**Comment by thrust26** [comment]
Is the change immediate already? Or will @DirtyHairy  take care of that?

**Comment by sa666666** [comment]
Seems immediate to me, in my testing.  All paths eventually call `initializeAudio()` which in turn calls `Console::createAudioQueue()`, and inside this method the `AudioQueue` is contructed new each time.  So it takes all current settings into account.

I'm still not sure about fragment size and playback rate being dynamic.  They're set inside the `SoundSDL2` c'tor, but I don't see where they're being reset to something else.  I guess the stereo vs. mono setting is working dynamically since the sound system is _always_ opened in stereo mode, and we just change how data is sent to it to simulate mono mode.

@DirtyHairy will have to chime in on this WRT frequency and sample rate.

**Comment by thrust26** [comment]
@sa666666 I remembered that we had a similar option for phosphor. There it was named "Per-ROM", here we use "By Rom". Which is better?

**Comment by sa666666** [comment]
Behind the scenes, the actual text saved is named 'byrom'.  For the UI, we can call it whatever you want.  I leave it up to you to fix one or the other (whatever, as long as it's consistent).   Maybe 'per' makes more sense??

**Comment by thrust26** [comment]
>Behind the scenes, the actual text saved is named 'byrom'. 

We should try to keep the UI and CLI parameters aligned. And yes, there are already some deviations for "historical reasons". But we should avoid creating new where not necessary.

> Maybe 'per' makes more sense??

You are the native speaker! 😆
