### ISSUE TITLE
Make GameInfoDialog change settings dynamically

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#337]
This requires work all across the codebase, since some of the code wasn't designed for properties to change during runtime.  It will be much more convenient if it did so, though, since options could be tested without having to restart the ROM.  One particular use-case is a game that can use different controllers during the same program run.

**Comment by thrust26** [comment]
While we are at it, we should check other non-immediate settings in other dialogs (e.g. Audio, UI) too.

**Comment by thrust26** [comment]
Except for bankswitching type (and start bank, where it would make no sense), everything is now changed immediately.

Shall we make the bankswitching effective immediate too? Would that make sense at all?

Else we can close this one.

**Comment by sa666666** [comment]
I don't really see a use-case for dynamically changing BS type.  So we can close if you like.

**Comment by sa666666** [comment]
Closing for now, as I don't see a point of making BS changable dynamically.  If the need arises, we can open this again.
