### ISSUE TITLE
Condition breakpoint message in debugger is corrupted

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#338]
I haven't tested this extensively yet, but setting a CBP (say, on a specific scanline in the TIA output area) enters the debugger with a message that has $FFFF appended to the end.

Don't know what other conditions cause this to happen, but it seems to be a regression since 5.1.

**Comment by thrust26** [comment]
@DirtyHairy I think this is a result of your refactoring. Address is read as uInt16, but checked as int. And the -1 becomes $ffff.
