### ISSUE TITLE
Static sound in Pitfall!

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#340]
When you start Pitfall!, there is a static sound (most likely more games are affected).

Even though AUDV0/1 are set to 4, AUDC0/1 are 0 and therefore we should not hear anything.

**Comment by DirtyHairy** [comment]
This is an artifact from Laczos resampling that appears when running a constant (nut nonzero) signal through the resampler.

a4d923cb fixes this by running the signal generated by the TIA through a high-pass filter (with cutoff 10Hz). This causes the constant part of the signal to decay sufficiently fast to be unnoticeable, at least for my ears.
