### ISSUE TITLE
Launcher Font Size not Changing

### ISSUE THREAD

**Issue by kdgarris** [stella-emu/stella#344]
In Stella 6.0 pre1 on Mac OS X, the launcher font size setting appears to have no effect, even after relaunching the emulator.

**Comment by sa666666** [comment]
Working for me in Linux.  I won't be able to test on an OSX machine until later this evening.

To be clear, only the font in the ROM filename area will change; the font on the right side of the screen (ROM properties area) is determined by the size of the snapshots.

**Comment by kdgarris** [comment]
I'm not sure what I did differently, but when I tested again, it worked for me.  Probably a user error.  :-)

**Comment by sa666666** [comment]
This wasn't mentioned in the original thread on AtariAge, but keep in mind that switching back to Stella 5.1 after testing Stella 6.0_pre1 can revert some of your settings, since some of them have changed names slightly.  Maybe this is what happened??

**Comment by kdgarris** [comment]
Yes!  That is the difference.  I went back to 5.1 to do some UI comparisons, so that must have been why it happened.
