### ISSUE TITLE
request: less forgiving player settings

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#351]
IMHO the default player settings are currently too "lax" and I suggest to have randomization of RAM and CPU enabled instead, as it was in older Stella versions.

While those settings are easily configurable, almost all players (and, apparently, also some developers) don't seem to ever play with them, and when testing the games on real hardware the rom is usually loaded from the menu of Harmony and other flashhcarts, so with ram and cpu in a non random state. 

Having more strict default settings might reduce the number of buggy roms floating around that, for example, don't initialize ram or the decimal flag and therefore won't work reliably when put on cart, and possibly in future flashcarts too if they initialize the console differently.

I think that enabling those two settings shouldn't affect any original rom, nor any homebrew ever released on cart. IIRC, there are a few old demos or test roms from the stellalist that might fail (because they were only tested on a supercharger and/or 7800 DevOS at the time), but I think it should be better to just release patched roms for those. And it is always possible to disable the settings if one wants to run the original versions.

**Comment by thrust26** [comment]
Are you sure we had RAM and CPU randomization enabled by default. I have to check, but IIRC they were disabled.

Also, more strict default settings will probably only cause more blaming on Stella. We have to be careful here.

**Comment by ale-79** [comment]
I think that at least the 3.9.3 build had cpu randomization enabled, as the annoying guy on AA (you know who I am talking about :wink:) reports that his games randomly fail with the last r77 community build. And he doesn't initialize the decimal flag in any game that I checked.

**Comment by sa666666** [comment]
Personally, I don't mind enabling those two by default, since by all accounts that's how a real system works anyway.  I would still have the SP default to $FD (ie, not be random), based on research done elsewhere and an issue we already addressed.

Basically, only the things that are still not 100% researched and decided should be off by default for player settings.  So bank randomization is definitely off, since we haven't definitively determined which schemes it is relevant for.  But RAM and CPU should be fine.

**Comment by sa666666** [comment]
I don't care about the village idiot on AtariAge.  We're trying to determine how real (released by Atari) hardware works, not his broken code or borked consoles.

**Comment by sa666666** [comment]
Yep, and that's why bank randomization can probably never be the default.

**Comment by thrust26** [comment]
For sure.
