### ISSUE TITLE
Dynamic ROM viewer size list

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#353]
The list values should be adjusted based on the size of the launcher.

**Comment by sa666666** [comment]
Do you mean the size of the font?

**Comment by thrust26** [comment]
No, the size of the ROM viewer window. If you select 2 and the launcher is too small, Stella will use 1. That's not very intuitive.

**Comment by sa666666** [comment]
Oh, you mean to not show '2' at all when the dimensions wouldn't allow it?  If so, then yes, that's a good idea.  But internally the code will still 'bump' 2 down to 1 when necessary.  Keep in mind that the UI is not the only place that this setting can be changed (commandline, from within the `Settings` derived classes, etc).

**Comment by thrust26** [comment]
The change will only be for the UI.

**Comment by thrust26** [comment]
@sa666666 Add and removing items to the `ContextMenu` does not work well. I am getting a "write access violation" in `FBSurface`. I suppose I have to resize or recreate the surface, but I yet have to find out how to do that. Can you help me?

**Comment by sa666666** [comment]
I will look into it tomorrow.  Absolutely beat from all the work today, so I'll try to get to it after lunch tomorrow.  Logging off for the evening now.

**Comment by thrust26** [comment]
This is nothing that needs any hurry. Just icing in the cake. :smile:

**Comment by sa666666** [comment]
@thrust26, do you still need the functionality "Add and removing items to `ContextMenu`"?  Because if not, we can close this.  If so, give me a use case somewhere in the code so I can experiment and get it working.

**Comment by thrust26** [comment]
I am still looking for a solution here.

The example is the `myRomViewerPopup` in `UIDialog` (see `handleRomViewer()`).

**Comment by sa666666** [comment]
OK, it's the next thing on my TODO list.

**Comment by sa666666** [comment]
@thrust26, this functionality is now available.  Feel free to continue working on `UIDialog` as you were.  I've added a comment indicating such, which you can remove when you are done.

Then you can close this one at your convenience.
