### ISSUE TITLE
Power-On buttons not released

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#354]
The held down switches and buttons are not automatically released. 

Bug exists since 5.1.

**Comment by thrust26** [comment]
I think #209 was closed too fast. I don't see that we agreed on not to release the buttons at all.

**Comment by sa666666** [comment]
I'm in the process of developing a general timer/callback mechanism that duplicates what `SDL_AddTimer` did, but without actually using SDL functions for it.  It's code I found online, and will use C++11 proper, with threading and lambdas.  So we can bring back the functionality if we want.

I agree that we closed the issue too soon.  It fixed the actual bug report, but broke something else.

**Comment by thrust26** [comment]
Works for Windows.

**Comment by sa666666** [comment]
We just need feedback from @DirtyHairy now for OSX.  Or I can do it myself, but it will be very late tonight (at least 8-9 hours from now).

**Comment by sa666666** [comment]
Code works in OSX as well.  If we're all content with this, I will go ahead and close it.
