### ISSUE TITLE
Error messages in debugger prompt not red anymore

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#355]
Still working in 5.1.3

**Comment by sa666666** [comment]
Maybe related to the int -> ColorID changes I made; I will research it.

**Comment by sa666666** [comment]
This is much worse than I thought.  I didn't write this code, so the following is only my interpretation.  It seems that the color information is encoded inside the string, and is also dependent on the number of characters in the font set.  So the entire thing is very fragile.  I suspect with @thrust26 adding new characters to the fonts, and extra colors to the palette has broken this code.  Note that the design is already basically broken; what @thrust26 did just exposed it.  Consider the string printing in `PromptWidget`:
```
  if (c == '\n')
    nextLine();
  else if(c & 0x80) { // set foreground color to TIA color
                      // don't print or advance cursor
    _textcolor = ColorId((c & 0x7f) << 1);
  }
  else if(c && c < 0x1e) { // first actual character is large dash
    // More colors (the regular GUI ones)
    _textcolor = ColorId(c + 0x100);
  }
  else if(c == 0x7f) { // toggle inverse video (DEL char)
    _inverse = !_inverse;
  }
  else if(isprint(c))
  {
    buffer(_currentPos) = c | (_textcolor << 8) | (_inverse << 17);
    _currentPos++;
    if ((_scrollLine + 1) * _lineWidth == _currentPos)
    {
      _scrollLine++;
      updateScrollBuffer();
    }
  }
  setDirty();
```
I don't even know where to begin :cry:.  The only place that uses this functionality is PromptWidget.  And that class has been on my list for a partial rewrite for some time.

Arrgh. :angry:

**Comment by thrust26** [comment]
Ouch! :zap:

And yes, the `PromptWidget` has some really ugly code.

So how to we proceed? Shall we try to simply fix the bug for 6.0? Or do we ignore it and wait for refactoring?

**Comment by sa666666** [comment]
I can't make a suggestion either way until I dig into it a little more.

**Comment by thrust26** [comment]
The bug is in these lines:
```
 else if(c && c < 0x1e) { // first actual character is large dash
    // More colors (the regular GUI ones)
    _textcolor = ColorId(c + 0x100);
```
Before `kDbgColorRed` which is used for error messages was 280, which is 0x100 + 0x18, the latter being smaller than 0x1e.
I guess I can hack a preliminary fix by just changing the value for `kDbgColorRed`.

**Comment by thrust26** [comment]
Closing the bug and opening an enhancement issue for this class.
