### ISSUE TITLE
Unnecessary memory fetch during JSR

### ISSUE THREAD

**Issue by rbairos** [stella-emu/stella#358]
noticed an unexpected memory fetch during JSR 

File: M6502.ins

// JSR
case 0x20:
{
  uInt8 low = peek(PC++, DISASM_CODE);
  **peek(0x0100 + SP, DISASM_NONE);**                   <- is this true to the 650x behavior? value not used.

**Comment by rbairos** [comment]
Possibly related:

//////////////////////////////////////////////////
// RTS
case 0x60:
{
  peek(PC, DISASM_NONE);
}

**Comment by rbairos** [comment]
// RTI
case 0x40:
{
  peek(PC, DISASM_NONE);
}

**Comment by thrust26** [comment]
I have too look into it, but I am pretty sure this is just another 'ghost' read. There are many of those, especially during indexed memory access.

**Comment by DirtyHairy** [comment]
Check http://nesdev.com/6502_cpu.txt --- the write is valid :) The 6502 executes a bus access every cycle, including "ghost" reads whose result is discarded.

**Comment by rbairos** [comment]
Great link. Thanks for clarifying!
