### ISSUE TITLE
TIA hotkeys in debugger 

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#359]
Certain hotkeys, especially for enabling/disabling TIA objects and debug colors should work in the debugger too.

**Comment by sa666666** [comment]
There is still an issue here.  When the `PromptWidget` is focused, press Alt-_key_ will display _key_ in the console.  Also pressing Alt-_z_ will perform the action, but also display 'z'.

This is not easily solved.  It seems that when text input is enabled (as it is in UI modes), then Alt+some key is used for Unicode input.  The same is not true for the Control key, so Ctrl+some key works as normal, and does _not_ show the key.  However, if we disable key input, then the UI won't receive any text events at all!

The ideal fix would be to somehow just not use Unicode at all.  The built-in fonts, etc don't support it, so we're paying the price for nothing.

Fixing this is non-trivial, and may not even be possible.  It has to happen in SDL itself, before the events even reach the app.  I suppose we _could_ hack `PromptWidget` to recognize when Alt or Ctrl is pressed, and ignore the corresponding key.  But that is hacky, and `PromptWidget` is already hacked enough.  And it still wouldn't solve the problem in other `EditableWidget`s.

**Comment by thrust26** [comment]
> There is still an issue here. When the PromptWidget is focused, press Alt-key will display key in the console. So pressing Alt-z will perform the action, but also display 'z'.

Does not happen for me. Maybe an OS related issue?

**Comment by sa666666** [comment]
This bug only appears in Linux, so we will leave the commit in, and fix the Linux issues.

**Comment by thrust26** [comment]
Since it seems to be only a Linux problem, will we solve by conditional compile? Or should I remove it?

**Comment by sa666666** [comment]
Like I said above, leave it in.  I will either document the issue or somehow work around it for Linux, but there's no reason to remove it entirely.

**Comment by sa666666** [comment]
Moving this to 6.1

**Comment by thrust26** [comment]
Shouldn't we add a conditional compile then?

**Comment by sa666666** [comment]
I'm inclined to leave it as-is for now.  At least the feature now works in all ports; the text appearing is more a cosmetic issue than anything else.

**Comment by sa666666** [comment]
I'm going to go ahead and close this one.  If we get reports on this for Linux, I can recreate an issue specifically for that.  This issue itself is now solved.
