### ISSUE TITLE
System log improvements

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#366]
@DirtyHairy IIRC you wanted to add more details to the audio logging. The current values do not seem right.

Also: Sound gets logged very frequently, even if nothing has changed, but other changes don't get logged.

To stay consistent, IMO we should either only log settings at the start or always when something has changed.

**Comment by sa666666** [comment]
I can partly take care of the sound stuff wrt multiple logging.  I can introduce an `about()` method like from `FrameBuffer`, and only log it if it changed from the previous setting.

As for logging the overflow/underrun, I leave it to @DirtyHairy to discuss and decide how to proceed.

**Comment by thrust26** [comment]
As discussed, no logging for buffer issues.
