### ISSUE TITLE
System log open error for aspect ratio > 1

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#367]
As soon as aspect ratio is larger than 1, you cannot open the `LoggerDialog` anymore.

**Comment by sa666666** [comment]
Not just `LoggerDialog`, but also `BrowserDialog` (the one you get when selecting file/folder locations).  The commonality here is that those are dynamically sized, based on the current window size.  So I suspect it's all the same issue.

At least we now get a message saying "Unable to show dialog box; FIX THE CODE".  :smile:   Previously the code would just crash.

**Comment by sa666666** [comment]
Also not able to open any of those dialogs in the ROM launcher at all.

**Comment by thrust26** [comment]
The problem is in using the result from `getResizableBounds(w, h)`. Because that takes the current frame buffer size and multiplies it with the aspect ratio. 
@sa666666 Do you know why the latter is done?

**Comment by sa666666** [comment]
Yes, that's what I'm fixing right now :smiling_imp:   You will probably have to back out the previous 2 commits, since I'm fixing it at a lower level.

I suspect it's currently done this way because of obsolete code, that took the aspect ratio into account in the various dialogs.  We no longer need to do this, so I will refactor it.

**Comment by thrust26** [comment]
There are two other problems with aspect ratio. 
- PAL aspect ratio is based on the colors (should be frequency)
- PAL is wider than NTSC, actually PAL should be less high instead.

**Comment by sa666666** [comment]
These latter problems really should be in a separate issue.  Also, you can go ahead and revert your last two changes now, as I will be fixing the problem elsewhere.

**Comment by thrust26** [comment]
Reverted. 

Please make the maximized dialogs 95% in size.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/a2d7ac188b3e6a625a32edc5a8d3b4b71f8f92a1.

**Comment by thrust26** [comment]
I wanted 95%. :smile:

**Comment by sa666666** [comment]
Oops, missed that part of the message.  I can easily change it to 95% if you like.

**Comment by thrust26** [comment]
Yes, please

**Comment by sa666666** [comment]
OK, done.
