### ISSUE TITLE
Improve information saved as TEXT blocks to PNG snapshots

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#370]
This started wrt a thread on AtariAge: http://atariage.com/forums/topic/282435-stella-database-switch-off/?hl=%2Bstella#entry4102705.  The user requested to store actual filename instead of properties name in snapshot files.  For now, I will fix this to honour however the snapshot is actually being named (ie, if real name is to be used, use it _both_ as the name and in the text block in the PNG).

However, this could be expanded on in the future.  We could offer which text to save to the files, or none at all for that matter.  That part will have to wait for 6.1.  I can fix the initial bug for 6.0

**Comment by thrust26** [comment]
It makes sense to use the correct name. If it is wrong in the database, IMO it should be corrected there.

But probably some people do not like the format, so I am fine with that change.

**Comment by sa666666** [comment]
First part is implemented in https://github.com/stella-emu/stella/commit/b32c71d6f46bb9abe483090e5bf1988eb480279b.  Second part will be for 6.1.

**Comment by sa666666** [comment]
I think what we've already implemented solves the problem that the user first reported.  So I will close this now.
