### ISSUE TITLE
Allow complete sound disabling again

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#373]
Stephen wrote:
> I'd like the SOUND_SUPPORT define to be honoured by the new sound core. So when we disable sound support, we disable it completely. The reason for this is that some 3rd-parties are using Stella in experiements, and try to get as fast a framerate as possible, and turn off sound to do so. ALE (Arcade Learning Environment) is one such group, that uses AI to run 2600 games.

**Comment by DirtyHairy** [comment]
Implemented in 28f8dcc3
