### ISSUE TITLE
Separate fullscreen option for UI

### ISSUE THREAD

**Issue by kdgarris** [stella-emu/stella#374]
I would love to have the option of having Stella emulate games in fullscreen mode, but keeping the UI itself in windowed mode when it is not currently emulating a ROM.

**Comment by thrust26** [comment]
What would be the benefit?

**Comment by kdgarris** [comment]
> What would be the benefit?

I don't know if it would be something others would want or not, but I only really need to be in full screen when I'm running a rom.  When I'm just doing stuff in the GUI, full-screen is just an inconvenience, and doesn't really provide any benefit visually.  Just an idea; feel free to close it if it's too obscure.  :)

**Comment by thrust26** [comment]
I think I will follow your suggestion. :Smile:
