### ISSUE TITLE
Stella crashes when using 720x480

### ISSUE THREAD

**Issue by SpiceWare** [stella-emu/stella#376]
User's encountering a crash when running Stella on a display set for 720x480 on a Windows machine, but only for games with extra RAM.  Same games play OK when set to 640x480.

He reported it on SARA games, I had him try a few others that used different types of added RAM. Also had him try the current beta build.

Shot in the dark - maybe something to do with the integrated debugger and the Cartridge RAM tab.

http://atariage.com/forums/topic/282692-bizzare-stella-bug-with-sara-chip-roms/

**Comment by sa666666** [comment]
I'll try to look into this before the 6.0 final release.

**Comment by thrust26** [comment]
Weird problems in `StringParser`, line 69:
1. `size_t spos = line.find_last_of(' ', beg+len);` returns -1, which is interpreted unsigned. 
2. beg = 0, len = 4, line = "$F000 - $F07F used for Write Access", so there are spaces to be found. Why -1 then?

**Comment by thrust26** [comment]
Missing string::npos check. I briefly (string.find, find_first_of, find_last_of) checked the other code for more missing checks, but that looked fine to me.
