### ISSUE TITLE
Add game property for startup bank

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#378]
E.g. Arkology only starts correctly in a certain bank. This is set by the hardware of the board used.

And we already have some carts behaving like that in `CartF8`.

**Comment by sa666666** [comment]
This requires changes to several files outside Stella code itself, particularly in the Perl code is `src/tools`.  I am not opposed to adding it, but I will probably have to work with you on this, since you may not be familiar with code, nor have Perl installed in Windows to run it.

**Comment by ale-79** [comment]
Is this an option needed for other schemes as well?. If it's only for F8, what about just adding an alternate F8 scheme that starts in the other bank?

It might also work as a temporary solution, until a more general way to configure the starting bank for each scheme is implemented.

**Comment by sa666666** [comment]
I don't know if it's needed for anything else.  Perhaps AR/Supercharger, where we always use 0 for now.  But TBH, if we are adding it, then I want it there for all types, so that this issue can be put to bed for good.  It can default to 'auto', which will use whatever it currently uses, and bank randomization will of course override that option.

It's not difficult to add this.  We already have the infrastructure for it; we just need to add it to the properties, and have `Cart` recognize and use it.  More a slight reorganization of the code than anything else.

**Comment by sa666666** [comment]
First part is in https://github.com/stella-emu/stella/commit/5bc84bca520a09557a68cc646841576c45449e25.  Second part will have Stella actually use the info (coming soon).

**Comment by sa666666** [comment]
@thrust26, yes, you can go ahead with the UI.  You should be able to get the number of banks from a method in the `Cart` class, which you can use to enumerate the bank numbers to use.

I don't know what to do about the 'weird' schemes, where the startup bank is not a set number.  Perhaps I will add another method to `Cart` that the UI will consult to see whether the UI element should be disabled in such a case.  But that can come later.

**Comment by sa666666** [comment]
Maybe a `virtual bool Cart::startBankIsChangable()` or something, which is set to false for those schemes where we absolutely don't want to give the user an option to change it??

**Comment by thrust26** [comment]
Thinking a bit more about it, I wonder how much complexity we want to expose in the UI. Maybe we should only allow setting this via command line and property file? E.g. in case of Arkology almost no normal user would have found out on his own. And this is just one bank. With more slices, it will become exponential unlikely to find out just by trial and error.

**Comment by sa666666** [comment]
We can easily leave it as a property only.  As long as it can be changed without recompiling Stella.  I leave it to you to consider the UI stuff.  Or perhaps we can wait until after 6.0 to decide on that part.

As for the ROMs that depend on slices, I was just going to disallow them from being changed at all.  Basically, if `Cart::startBankIsChangable()` is false, then nothing happens, and you wouldn't even need to populate the UI with entries; just disable the UI element completely.

The stuff I'm working on is quite separate from the UI, so we can think about that later.

**Comment by thrust26** [comment]
> Basically, if Cart::startBankIsChangable() is false, then nothing happens, and you wouldn't even need to populate the UI with entries; just disable the UI element completely.

That won't work with "Auto-detect". Currently I am more for leaving that out of the UI.

**Comment by sa666666** [comment]
It will if you don't populate the dropdown box until the dialog opens (in `loadConfig`).  At that point the cart type _is_ known, and you can do it.  Of course that only works when in emulation mode, not from the ROM launcher.

In any event, it's OK to leave it out of the UI entirely too.

**Comment by DirtyHairy** [comment]
Another route (that I have been having on the radar for 6502.ts for quite some time now) would be a generic mechanism for managing additional settings per cartridge type. So, for example, you could query the cartridge class for a list of additional settings which are defined by type (int, bool, etc.), valid range and a description text.

The UI could then render the settings dynamically, depending on the selected cartridge class.

**Comment by sa666666** [comment]
This is also another option going forward (post-6.0).  There are some things that are definitely for only certain BS schemes, and I don't want to pollute the database by adding an entry for every little thing that can be changed, but only applies to a small subset of ROMs.

**Comment by sa666666** [comment]
Second part is now done in https://github.com/stella-emu/stella/commit/31f6dba87d78077041f66dd95bcf2f3a16ea7904.
