### ISSUE TITLE
Minimize save state files

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#380]
The files contain the results of name(), probably once intended to allow backward compatibility.

Unless we can use the names for this, we should remove them.

**Comment by sa666666** [comment]
Names are removed from all state files.  Since this is a general enhancement, I will leave it open for now, as we may find other places for optimization.

**Comment by thrust26** [comment]
@sa666666 Now that 6.0 is released with a new format, shall we close it?

**Comment by sa666666** [comment]
I guess we don't need it listed specifically as an enhancement.  I will minimize the files where possible anyway.
