### ISSUE TITLE
Changing ystart does not persist

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#381]
This seems to be broken already in 5.1

EDIT: It seems that this works randomly... ?!

**Comment by ale-79** [comment]
Confirmed: it saved the setting once in maybe 40 tries for me, and then I wasn't able to set it back to auto and I had to manually delete the entry from stella.pro

**Comment by thrust26** [comment]
@DirtyHairy The problem were the changes in 2f9fc4f. I have fixed that problem with my commit. Please double check.

But I have to reopen #297 again. 😒
