### ISSUE TITLE
Top row worm unfair

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#387]
It can happen, that a worm arrives at the entry hole the moment the Aardvark's trunk goes down too. So then there is no chance to evade it and the player loses a life. This must be prevented.

Potential fixes:
- delay the worm
- adjust worm's speed 
- allow a short initial grace period

**Comment by sa666666** [comment]
Hmm, not sure what this has to do with Stella?? :confused: :question:

**Comment by DirtyHairy** [comment]
Sounds like a case of "wrong project" 😛

**Comment by thrust26** [comment]
Eventually this **had** too happen. :laughing:

**Comment by sa666666** [comment]
When I checked my emails this morning, first thing I read is "top row worm".  And then I think, what the heck is going on with Stella now :laughing:

**Comment by thrust26** [comment]
At least you got a laugh from it. :smile:

BTW: Is GitHub currently dead slow for you too?

**Comment by sa666666** [comment]
I'm on an extremely slow system at work in the lab, so I wouldn't know either way.  These are like Core2Duo machines or something :(
