### ISSUE TITLE
Choking on GCC 7.3.0

### ISSUE THREAD

**Issue by shentino** [stella-emu/stella#390]
[build.log](https://github.com/stella-emu/stella/files/2488736/build.log)

**Comment by skitt** [comment]
You’re building an old release; current versions of Stella build fine with GCC 7. (I think this was fixed in Stella 5.0.)

**Comment by sa666666** [comment]
Yep, Stella 5 (soon to be 6 in about a month or so) has this fixed for quite some time.  Please upgrade the version in Gentoo.
