### ISSUE TITLE
unbundle zlib, yacc, and libpng

### ISSUE THREAD

**Issue by shentino** [stella-emu/stella#391]
would it be a good idea to unbundle these?

Gentoo prefers to have it link against the original upstream versions of those and at any rate unbundling would reduce your burden keeping it in the repo.

**Comment by skitt** [comment]
> Gentoo prefers to have it link against the original upstream versions of those and at any rate unbundling would reduce your burden keeping it in the repo.

Regarding zlib and libpng, if the relevant development headers are found by `./configure`, the system copies are used instead of the bundles copies. (That’s how the Debian build works.)

Regarding yacc, it isn’t yacc which is bundled, but the result of processing `src/yacc/stella.y`.

**Comment by shentino** [comment]
Actually this information is useful as well, thanks for telling me.

**Comment by sa666666** [comment]
Realize this is already closed, but the included zlib and png stuff is absolutely necessary for compiling in Windows and OSX.  So it cannot be removed.  However, as already stated, the Linux builds can ignore it completely if desired.
