### ISSUE TITLE
TIA objects access tracking incomplete

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#397]
`SET_LAST_POKE` sets the last data address, which is used to mark playfield and sprite graphics in the disassembly. So that's how the debugger and DiStella can 'draw' the graphics in the output.

In `6502.ins`, `SET_LAST_POKE` is only defined for STA/STX/STY, so if a TIA register is updated e.g. via PHA this is missed.

**Comment by sa666666** [comment]
Are we sure these are the only opcodes that are relevant?  I only did it for STx, but never researched all the other ones.  Sure, PHA is needed, but are the others too?

**Comment by thrust26** [comment]
Theoretically all writing opcodes could be used. But for kernels I don't think there are many cases where other opcodes are being used.

**Comment by sa666666** [comment]
But wouldn't it make sense to be complete and include _all_ such opcodes?  Or are there other issues with including extra ones; are there side effects, etc?

If there are no other issues with including all such opcodes, I'd rather do it and have this issue **really** closed for good.  So we never have to revisit it again.

**Comment by sa666666** [comment]
I guess that's just a long way of saying we shouldn't close the issue until it is complete.

**Comment by thrust26** [comment]
I am not sure if the effort and overhead(?) is worth it. 

Also the current tracking is imperfect and would need quite some changes. E.g. `LDX var1... DEX` still tracks `var1` while X has changed in between. How would you track that?

**Comment by thrust26** [comment]
A shortcut would be to invalidate all modified registers.
