### ISSUE TITLE
Focus issues

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#399]
While looking at the 2nd point of #287, I noticed some oddities in the focus handling of our dialogs:
1. For most dialogs (e.g. Input, User Interface, Game Properties, inside debugger) the last tabs are remembered, ~~but not for Video~~. ~~Also not for dialogs without tabs (e.g. Audio).~~
2. ~~Inside each tab, the focus of the last field is usually remembered, except for~~
    - ~~the focused tab~~
    - ~~Video/TV Effects~~
3. The last tab and focus are tracked **separately** (why that?) for launcher, emulation and debugger.  

I suppose, if we fix 1.+2. the problem in #287 would be solved too. And usability would increase a bit. The same for 3. (slightly).

**Comment by thrust26** [comment]
The partial fix only works if the tab is changed back and forth after focusing a widget. It seems as if something is persisted when the tab is changed, but not when it is closed.

**Comment by thrust26** [comment]
cd8d749 fixed the Video dialog issue (the dialog was recreated every time)

**Comment by thrust26** [comment]
b1811f5 fixed the focus for dialogs without tabs.

**Comment by sa666666** [comment]
Is this one relevant any longer?  It seems we've taken care of most (all?) focus issues.

**Comment by thrust26** [comment]
There are some minor issues left which I want to fix first.

**Comment by thrust26** [comment]
Done.
