### ISSUE TITLE
Retron 77 refreshes at 30Hz

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#409]
The Retron 77 refreshes at 30Hz. This can be seen prominently in Stay Frosty 2 --- there is only one flame visible on the title screen. This is not an issue of the video stack, but a temporal aliasing artifact: if speed is set to 99%, skipping every even and odd frame alternates with displaying both frames over time, and the pattern of visible flames changes as A -> A+B -> B -> A+B -> A -> .... At the same time, the real FPS (note that this is different from the value in the stats widget which takes in account all frames, including dropped ones) alternate between 60Hz and 30Hz in the same pattern.

I suspect that this is an issue with the current timing code that is triggered by the way the Mali driver blocks on buffer swap and / or the high load of the emulation worker. As such this may affect other systems as well. This could be a genuine bug or a peculiarity of the current algorithm that could be avoided by rearranging the various steps in the main loop. In any case, research is required to understand what is really happening here.

**Comment by sa666666** [comment]
Is this only for TV effects enabled, or all the time?  Because if it's the former, then I say we just don't enable those effects unless/until the problem is fixed.  If it's the latter, then we have much more work on our hands :<

**Comment by DirtyHairy** [comment]
This happens without (and with I think) TV effects. I don't think that the problem is directly related to the R77; I rather suspect that it is the timing on the R77 (blocking during buffer swap + emulation worker load) that causes the dispatch algorithm to enter this state. I am pretty confident that this issue can at least be mitigated by adjusting the algorithm, but I do not know for sure until I do more debugging to really understand what is going on in detail.

**Comment by thrust26** [comment]
> The Retron 77 refreshes at 30Hz. 

Since when? Is this with the new build? I don't remember it did this before. 

And I am not sure if I understand why we are getting into these problems.  The CPU seemed to be strong enough, no? So is this a result of the new Mali driver? Maybe a setting? Before we try to adjust Stella, IMO we should try to fix the driver behavior.

**Comment by DirtyHairy** [comment]
@thrust26 I don't think this is an issue with the R77, but I think this is an issue in the scheduling code 😏 It may be triggered by the timing on the R77, but I want to understand where it is coming from and whether it can affect other systems, too.

**Comment by thrust26** [comment]
You know your scheduling code much better than anyone else. But how could this be the result of scheduling? Is your scheduler really dropping frames? If so, why can I set emulation speed to 1000% and get about 600%. I would have thought that frames would be permanently dropped then. But if that is possible, why do I not get 1000% then?

**Comment by DirtyHairy** [comment]
If I crank up speed, my machine maxes out ~10x speed (600 generated frames per second). As my display continues running at 60Hz, it will only display about every 10th frame. This is how it works: the emulation tries to run at precisely the correct speed, and if it generates more frames than the hardware can handle, those will be dropped.

**Comment by thrust26** [comment]
So, why is my machine limited to 600% (or ~360 fps) then?

**Comment by DirtyHairy** [comment]
Presumably the worker thread maxes out one core at 600%.

**Comment by DirtyHairy** [comment]
After some investigation, it turns out that, depending on the exact timing w.r.t. vsync, the Mali driver blocks in `SDL_UpdateTexture` for a full frame, during which it seems the texture is still locked in the rendering pipeline.

f511f9fbe7d342 fixes this by alternating between two textures.
