### ISSUE TITLE
RetroN 77 enhancements

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#411]
Which existing features could be supported by RetroN 77?
- TV effects (via dialog, maybe only presets)
- Phosphor (via dialog, less granular)
- Sound settings (via dialog, less granular)
- Controller settings (via dialog, maybe remove e.g. CompuMate, Keyboard, Paddle Axis)
- ~Bankswitch type settings (via dialog, remove all experimental ones plus rare ones which can be auto detected safely)~ (done via extension when necessary)
- Multiple state slots (button combination)
- TimeMachine (also e.g. for instant replay of the last 30 seconds) (button combination)
- Pause emulation (button combination)
- Frying (just because it was meant to be there) (button combination)
- ...?

**Comment by sa666666** [comment]
Arrgh, not more issues; I'm trying to decrease them, not add more :smiling_imp: 

OK, more seriously, all of these could technically be supported (except possibly Blargg if we don't get that issue fixed).  The main problem is how to toggle them.  We have one joystick with one Fire button, and all combinations are typically used in a game.  And we have 3 buttons on the back, with one of them dedicated to Color/BW.

So the main issue is how to get input into the system on such a device.  I guess that's one of the reasons AtGames has extra buttons on their joysticks.

**Comment by thrust26** [comment]
I have some ideas here already:
- all buttons react to **releasing** them (the Harmony menu works like that)
- that way, we can create all kind of console button combinations
- and we could combined console buttons with controller input

**Comment by sa666666** [comment]
I don't think we need bankswitching at all.  I'm fairly confident that the current support is robust enough that we don't need it.  And if it _is_ ever needed, one can give the ROM a filename extension to force it.

Time Machine and Pause are very nice to have (the former will not be configurable though, just make it 30 seconds).  And multiple save slots (with pictures of each one) would be nice too.  But again, how to get input into the system for all these things??

**Comment by thrust26** [comment]
So for changing the save slot, you would e.g. hold the Load button and press the Save button. Each press of the latter moves one slot forward. Or you hold the Save button and press the Load button to move backward one slot. The current slot is displayed on screen.

**Comment by thrust26** [comment]
> I don't think we need bankswitching at all. I'm fairly confident that the current support is robust enough that we don't need it. And if it _is_ ever needed, one can give the ROM a filename extension to force it.

Works for me.

**Comment by sa666666** [comment]
The load/save functionality I mentioned above should really be put into a separate issue first, and developed independently of R77.  That needs to be done in mainline, regardless of R77 support or not.

Also, when you say "hold the Load button and press the Save button", where are these buttons actually coming from? :smile:

**Comment by thrust26** [comment]
> The load/save functionality I mentioned above should really be put into a separate issue first, and developed independently of R77. That needs to be done in mainline, regardless of R77 support or not.

Not sure which issue you are talking about.

> Also, when you say "hold the Load button and press the Save button", where are these buttons actually coming from? 😄

The RetroN 77 has these buttons. And unlike most other buttons (e.g. Reset, Select...), they are only emulator specific, so they cannot be used by any game directly. That allows us to use them as we like. Same for the fry button and maybe others too.

**Comment by sa666666** [comment]
The part where I say "a little picture should pop up" showing a screenshot of the saved state file.  That itself can be a separate issue.  Or perhaps just ignore that entirely; we already have enough to do.

OK, I see what you mean about the buttons.  Haven't used the R77 for months, and beginning to forget what it looks like.  As for long/short presses, combination presses, etc., the current core doesn't handle that, so we need to address that first.

**Comment by sa666666** [comment]
Have to leave to do some work now ...

**Comment by thrust26** [comment]
> The part where I say "a little picture should pop up" showing a screenshot of the saved state file. That itself can be a separate issue. Or perhaps just ignore that entirely; we already have enough to do.

We can always open a low prio, separate issue, so it does not get lost.

> OK, I see what you mean about the buttons. Haven't used the R77 for months, and beginning to forget what it looks like. 

I had to do the same. :smile:

> As for long/short presses, combination presses, etc., the current core doesn't handle that, so we need to address that first.

Shouldn't be too complicated, right?

**Comment by sa666666** [comment]
> Shouldn't be too complicated, right?

Famous last words? :smiley:   Seriously, this involves changes to the UI part of the code, some of which I didn't write, and it may not have been designed for it.  I guess we won't know until we try, but I can't say for certain right now how hard it will be.

**Comment by thrust26** [comment]
I though it would be all in the `EventManager` which you had refactored lately. :smile:

**Comment by sa666666** [comment]
Maybe that will be all there is to it.  I don't actually know what's involved until I dive into it, TBH.  And that will have to happen _after_ I complete the 3 other issues I absolutely need to get done for 6.1

**Comment by thrust26** [comment]
I am just collecting ideas. Absolutely no reason to hurry. ☺️

**Comment by thrust26** [comment]
Though the default mapping seems to work, maybe this requires fixing #413 first.

**Comment by thrust26** [comment]
The code is already able to differentiate between key pressed and key release. There is a `state` variable, which is set to 1, when a key is pressed, else 0 (`EventHandlerSDL2::pollEvent()`). So we could react differently here already.

**Comment by thrust26** [comment]
Here is the (current) plan for the R77 buttons: 
- The right two keys (Skill P1 and P2) act as modifier keys (think of `Control` and `Alt`). So they add up to 3 more key layers to the left four keys. And the three keys in the back if we want to utilize them.
- The modifier keys will react on key **release**. This allows to use them alone and as modifiers.
- Without any modifier key pressed, the functionality will be as currently and printed on the device.

Here is how it might look like (unmodified, `Control`, `Alt`, `Control+Alt`):
- Save state, next state slot, Pause, 16:9
- Load state, next TV mode, increase scanline intensity by 10%, increase (global) phosphor by 10%
- Reset, exit to Launcher, Rewind 10 seconds (and pause?), Fry
- Mode (Select), B&W/Color, Command dialog, Settings dialog

I tried to assign the functions so that they fit together and to the original key. Note that all functions from the back buttons are at the front now too. If required, we could add another 9 functions to the back.

Thoughts?

**Comment by thrust26** [comment]
Suggestion for R77 key event mapping in menu mode:
```
F9 = Up   | F11 = Previous Item | | F6 = Select
F2 = Down | F1  = Next Item     | | F8 = Settings
-------------------------------------------------------------
F4 = Power-On Options | F13 = Page Up | Backspace = Page Down
```
Question: Are the page up/down buttons (launcher only) more important or the next/previous item (dialogs only) ones? Currently I have page up/down at the back buttons.

BTW: How can I map F13 without a F13 button on my keyboard???

**Comment by DirtyHairy** [comment]
Looks fine to me.

**Comment by thrust26** [comment]
@sa666666 I don't think the key handling enhancements are really urgent anymore. R77 at least works pretty well without it. 

What's not working is advanced joystick navigation, e.g. opening dialogs in the launcher or moving between tabs in dialogs. But that's nothing serious IMO.

**Comment by thrust26** [comment]
Everything left to do is in #307
