### ISSUE TITLE
Key combination display and mapping buggy in UI

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#413]
Unlike other keys, the mapped decrease and increase volume keys are not displayed in the UI mapping dialog initially. Nevertheless they still work. 

If you map them to single keys, the keys show and work. But you cannot map them to ALT, CTRL etc. + key combinations. *Reset* also doesn't work at all for these two keys.

**Comment by thrust26** [comment]
After further investigation, it seems to be a problem with key combinations. E.g. *Quit* (Ctrl+Q) also behaves odd. 

1. If you map a new key, this is only added to Ctrl+Q 
2. Reset doesn't do anything.
3. Erase only erases an additional key, but not Ctrl+Q

**Comment by sa666666** [comment]
Mapping is only to single keys, not to combinations (Ctrl, Alt, etc).  This has been a limitation in the core since the very beginning.  So it's not so much a bug as a missing feature (ie, it has _never_ been possible to do this).

**Comment by thrust26** [comment]
That's what I thought too. Still the odd display for *volume* and *quit* is irritating.

**Comment by sa666666** [comment]
Yes, they're all bugs to some extent.  It's just that the single-key one is an unimplemented feature, while the others are true bugs.  All of them have to be fixed at some point.

**Comment by thrust26** [comment]
If you ever change volume up/down keys, there is no way to reset them to the defaults.

**Comment by thrust26** [comment]
@sa666666 I just committed 2d0221a, which partially fixes the problems in the `InputDialog`. The hard coded keys are now marked with "(*)". 

But I have a problem with some keys (e.g. Backspace and Tab). When I reset them, the key is added twice (e.g. "Backspace (*), Backspace". I cannot find any rule, why some keys appear that way and some not. E.g. Tab is duplicated in Emulation tab, but not in UI tab. Do you have an idea what's going on?

**Comment by ale-79** [comment]
I'm not sure if this should go in a separate issue:
In latest beta, with default settings, Backspace doesn't work for me to go to parent directory.
It works if I map it again so that the mapping is duplicated ("Backspace (*), Backspace"), as in the "Emul. Events" tab.

Works fine in 6.0
Tab works fine everywhere, even if it is duplicated in the Emulation tab but not in the UI one.

**Comment by thrust26** [comment]
The backspace issue got fixed with in acbe9b267.

**Comment by thrust26** [comment]
Fixed with several commits over the last week
