### ISSUE TITLE
Pixel Pos displays unsigned value in debugger

### ISSUE THREAD

**Issue by baconpizza** [stella-emu/stella#414]
Pixel Pos used to show as a signed number in version 5.1.3. It now shows as an unsigned value that is unintuitive.

For example, the left most position used to show a signed value of -68 (%10111100) that was a pixel offset from the 1st on-screen pixel. It now shows 188 (%10111100).

Version 5.1.3:
![stella-debug-5 1 3](https://user-images.githubusercontent.com/14867638/52815472-a038b300-3053-11e9-91ef-f9d52b2fb403.png)

Version 6.0:
![stella-debug-6 0](https://user-images.githubusercontent.com/14867638/52815505-af1f6580-3053-11e9-93c8-f33955db197f.png)

**Comment by thrust26** [comment]
@sa666666: Bug introduced by 9037af61 in `Base.cxx` line 66.

**Comment by sa666666** [comment]
Yep, added code to get rid of a warning; I'll have to do it a different way.
