### ISSUE TITLE
Load/Save TimeMachine states

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#417]
While testing Aardvark, Alex suggested to load and save all states of the TimeMachine at once. That way it would become easier to reproduce bugs.

**Comment by thrust26** [comment]
Implemented with 67db29e

**Comment by ale-79** [comment]
Are there commands to load and save all states from the debugger prompt? I don't see it mentioned in the docs. 
If not, could this be added?

**Comment by thrust26** [comment]
Shouldn't be too complicated.

**Comment by thrust26** [comment]
Implemented with 0112b89
