### ISSUE TITLE
Restructure logger to work everywhere, and gracefully handle shutdown

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#430]
Currently there is a `StaggeredLogger` class that handles coalescing continuously logged info (from Sound code, mostly).  There is also a logging facility in `OSystem`.  These are not tightly integrated.

We need to design one logging subsystem as a global singleton, that works in all cases.  Furthermore, when the app is shutting down, there must be an ability to disable logger output, so we don't get d'tors attempting to log information and trying to use objects that no longer exist.  This is the cause of issue https://github.com/stella-emu/stella/issues/416.

**Comment by DirtyHairy** [comment]
Implemented in 8e22dc52.
