### ISSUE TITLE
Controller settings not persisted

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#475]
When changing the controller used setting via Basic or Advanced settings, these are lost when the console is restarted. Instead auto detection is always used.

**Comment by thrust26** [comment]
@DirtyHairy Any idea? The code looks good.

**Comment by fluxit1** [comment]
This has been confirmed to be an issue on the beta 2 build, correct?  It's 100% consistent here AFAICT.  I just tried to toggle Astroblast from paddles to joystick and it just wont stick.

**Comment by DirtyHairy** [comment]
I think the per-game controller setup is saved as a per-game preference, and I am pretty sure those are only actually saved on shutdown, which never happens on the R77.

**Comment by thrust26** [comment]
Oh, I thought sqlite was already included. No?

**Comment by fluxit1** [comment]
Killing the stella process does cause game specific settings changes to be saved to /mnt/stella/stella.pro on beta 2.

`~ # cat /mnt/stella/stella.pro
"Cart.MD5" "5e43c0391f7412ae64fae6f3742d6ee9"
"Cart.Manufacturer" "Thomas Jentsch"
"Cart.Name" "Thrust (v1.27)"
"Cart.Rarity" "New Release"
"Controller.Left" "JOYSTICK"
"Display.PPBlend" "0"
""`

**Comment by sa666666** [comment]
Also confirmed for TV.format saving to stella.pro.  Looks like saving properties is partly borked.
