### ISSUE TITLE
HiDPI not correctly checked when adding dialog

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#479]
In `DialogContainer::addDialog` the `imageRect` returned is scaled by "HiDPI" while `GuiObject.getWidth()` and `.getHeight()` are not.

**Comment by thrust26** [comment]
Not THAT serious. :smile:

**Comment by sa666666** [comment]
Intentional, not a bug :smiling_imp: All internal dimensions are in actual pixels, while the HiDPI mode affects only the _scan-out_ resolution.  That's why I only need to change various `dstRect` objects to get HiDPI mode 'for free'.

**Comment by thrust26** [comment]
OK, but to make the code in question work correctly, you have to scale somewhere.

**Comment by sa666666** [comment]
In `Dialog::open`:
```
  // Take hidpi scaling into account
  const uInt32 scale = instance().frameBuffer().hidpiScaleFactor();
  _surface->setDstSize(_w * scale, _h * scale);
```

**Comment by thrust26** [comment]
OK, I will fix this one.
