### ISSUE TITLE
"Frying" effect issue

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#480]
I'm experiencing a bug related to the "frying" function. It doesn't show always, but often enough that It can be replicated easily in a few tries. 
Happens with two different PCs, both with Stella 6.0 and with the current "master" branch.

Seems to only happen if frying a game causes emulation to stop and the debugger pops up with the "Fatal error - invalid instruction" dialog.

In that case, usually, every rom you try to start (after returning to the launcher by clicking "exit rom" in the dialog) appears to be "fried", even if you don't press the backspace key.

Try for example with "Artillery Duel" either PAL or NTSC version, which often trigger the "invalid instruction" dialog when fried.

The "frying" function is not something I really use, but got intrigued by [this post on AA about frying "Asteroids"](http://atariage.com/forums/topic/278236-frying-and-the-glitching-effects-in-2600-games/#entry4276920) and I was curious to see if it was possible to replicate the "white asteroids" condition in Stella consistently.
It is, actually (when the above bug doesn't happen, of course).

**Comment by thrust26** [comment]
The frying flag is not reset when a new game is started. We should check if any other variables are affected too.
