### ISSUE TITLE
missing stella.pro database entries

### ISSUE THREAD

**Issue by funbars** [stella-emu/stella#483]
Not found: Stay Frosty 2, Draconian, Space Rocks.

**Comment by funbars** [comment]
Conquest of Mars: database has 2007 final version (rev 1).

New final? rev2 2009~2010 is available.
http://atariage.com/forums/topic/138010-conquest-of-mars-revision-2/

**Comment by funbars** [comment]
Missing: Squish 'em (homebrew)
https://atariage.com/forums/topic/117452-squish-em-for-the-2600-done/

**Comment by sa666666** [comment]
At least a few of these don't have a final ROM release, and we don't add it until it does.  Otherwise we'll have the database being littered with alphas and betas.  I will look into the other ones, though.

And with the much-improved autodetection in Stella over the past several releases (TV format, bankswitching type, controller type, etc), the need for an immediate addition to the properties is lessened.  That's another reason why there's no rush to get the info added.

**Comment by funbars** [comment]
Oh, okay. Saw so many game entries and was wondering. But they all work great with Stella.

**Comment by thrust26** [comment]
Lets keep it open and post missing final versions and properties here.

**Comment by funbars** [comment]
Alien Attack (2018) = could be real final
https://atariage.com/forums/topic/277154-alien-attack-4k-final-cartridge-version/#entry4003717

**Comment by funbars** [comment]
Space Cactus Canyon (2018) = labeled final
https://atariage.com/forums/topic/261911-space-cactus-canyon-beta/

**Comment by funbars** [comment]
Pac-Man 4K (Debro) = says final, unsure if same as store
https://atariage.com/forums/topic/81989-pacman4k/

**Comment by funbars** [comment]
Space Treat Deluxe (2003-05-02). Final Source + Binaries released May 21, 2003.
https://atariage.com/2600/archives/source/SpaceTreatDeluxe_source/

Stella:
```
"Cart.MD5" "562acb1b7ff182aba133bda8e21ad7c1"
"Cart.Name" "Space Treat Deluxe (08-03-2003) (Fabrizio Zavagli)"
```
2003-03-08. Older.

**Comment by funbars** [comment]
Star Fire (2003-07-10). Final source + binaries 2003-07-27.
https://atariage.com/2600/archives/source/StarFire_source/index.html

Not in Stella.

**Comment by sa666666** [comment]
Updated the following:
- Conquest of Mars
- Squish 'Em
- Alien Attack
- Space Cactus Canyon
- Space Treat Deluxe
- Star Fire (plus removed a crapload of associated WIPs)

**Comment by sa666666** [comment]
All items in this issue have been addressed.  If any more stella.pro deficiencies are found, please notify in a new issue, or send me the data directly.
