### ISSUE TITLE
Some libretro ports no longer compile because of fopen_s call

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#485]
Hi there developers,

would just like you to know that due to a recent change in RewindManager.cxx, Stella no longer compiles for some of the libretro targets (such as OSX and iOS).

fopen_s is the problem -

../common/RewindManager.cxx:236:19: error: use of undeclared identifier 'fopen_s'
    errno_t err = fopen_s(&fp, buf.str().c_str(), "w");
                  ^

You can view the compilation logs below -

<retrobot> stella: [status: fail] [recipes/apple/cores-osx-x64-generic] LOG: http://p.0bl.net/128699 Last good build: N/A
<retrobot> stella: [status: fail] [recipes/apple/cores-ios-generic] LOG: http://p.0bl.net/128700 Last good build: N/A
<retrobot> stella: [status: fail] [recipes/apple/cores-ios9-generic] LOG: http://p.0bl.net/128701 Last good build: N/A

Hopefully we can find a solution here that benefits us both.

**Comment by sa666666** [comment]
Yep, working on this right now.  Will have it fixed in a little while.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/98cb5a4ecdbf417346f94a8dc2250740b07e37d2.

**Comment by twinaphex** [comment]
Thanks, much appreciated!
