### ISSUE TITLE
LDA #$06 fails to set register

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#489]
Eshu's slideshow demo at [AtariAge](http://atariage.com/forums/topic/181816-bigger-bitmaps-with-dpc/?p=2278902) is broken in Stella. From looking at the debugger, NUSIZ0/1 are not set correctly.

Weird enough, if I enter the debugger, do a `reset` and then hit `run` again, the demo displays correctly. If I aunch the debugger immediatelly on Startup via `-debug`, the glitch is present; stepping shows that the `LDA #$06` at `$F099` fails to set the register correctly --- A is still at zero after the opcode has executed.

**Comment by thrust26** [comment]
Is the DPC+ mode somehow enabled?

**Comment by DirtyHairy** [comment]
Ah. Yes, that's most likely what's causing it --- I guess DPC+ starts with fast fetch enabled.

**Comment by sa666666** [comment]
Should it start out disabled?  If so, that seems pretty easy to fix.

**Comment by thrust26** [comment]
I dunno. Is this defined somewhere? 

Also, we should check when and why the behavior was changed.

**Comment by thrust26** [comment]
Hm, what else could cause lda #06 to result into A = 0?

**Comment by sa666666** [comment]
More precisely, it happened between 5.0 (works) and 5.1 (doesn't work).  So I guess we should look at all changes to `CartDPC+` in that timeframe.

**Comment by sa666666** [comment]
My mistake; fast fetch mode **is** enabled when it shouldn't be.

**Comment by sa666666** [comment]
About to fix this; it is a simple re-initialization error after running the emulation during startup for autodetection.
