### ISSUE TITLE
Gunfight doesn't always work and will result in black screen and audio noise

### ISSUE THREAD

**Issue by mi7chy** [stella-emu/stella#491]
Happens intermittently with both 64 and 32-bit Stella-6.0.1-windows.zip on Windows 10 Pro x64 and Gunfight NTSC from the link provided below.  For comparison, wasn't able to replicate the issue with z26 3.02.01 for Windows.

https://www.atariage.com/software_page.html?SoftwareLabelID=1627

**Comment by sa666666** [comment]
Not entirely sure if this is a bug in emulation yet, since it also happens in Stellerator.  More research is required.

**Comment by thrust26** [comment]
That's because of the "copy protection" in the ROM which assumes that the carry flag is clear. 

Disable randomizing CPU "PS" register in "Developer settings" and the "bug" is gone.

**Comment by mi7chy** [comment]
Can confirm thrust26's suggestion seems to have fixed the issue.  Much appreciated.
