### ISSUE TITLE
First key press in CompuMate wrong

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#493]
The very first pressed key is interpreted as if 'Func' (Ctrl) is pressed too.

Note: This is an old bug, not related to the latest refactoring.

**Comment by sa666666** [comment]
Are we sure this isn't the correct behaviour?  I have a CompuMate, but it's a PAL model and I can't use it in NTSC-land.  So I can't test for myself.

Granted, it's unlikely that this is the correct behaviour, but I'd rather know for sure before I dive into the code, attempting to fix something that isn't broken.

**Comment by sa666666** [comment]
Well, holy crap.  You learn something new every day.

I just plugged in my CompuMate, on the off chance that I could see enough onscreen to determine the correct behaviour for the above issue.  And it seems the LCD TV I bought a few months ago allows to view PAL ROMs!  It even comes up and says "PAL" when I switch to that input.  The video cuts out every so often, and it looks to be in BW mode (colour-loss, I guess).  But it works (sort of).

Anyway, I can confirm that the first time a key is pressed, it does indeed use the 'Func' version.  So it looks like Stella is behaving correctly here.

BTW, do you know where I can get an NTSC version?  I can then donate the PAL one I have to one of you guys??

**Comment by thrust26** [comment]
Better sell it, the prices are going high. Maybe you get/buy one following the ZPH fund raising.
