### ISSUE TITLE
Different colors in fullscreen vs windowed

### ISSUE THREAD

**Issue by kdgarris** [stella-emu/stella#498]
It is possible that this is a driver issue on my system, but I was asked to submit an issue for it.

I have noticed that some colors appear different in fullscreen vs windowed modes on my MacBook with Stella 6.0.  The colors appear more vivid in Windowed mode, and more washed-out in fullscreen mode.  Saved screenshots for each mode appear the same, so I have taken pictures of my laptop screen to demonstrate.

![65494414_890775507940486_6447934028099092480_n](https://user-images.githubusercontent.com/4992162/60451846-071dc980-9bfb-11e9-817b-14cb2078608a.jpg)
![65520571_341108406586357_8587804996890787840_n](https://user-images.githubusercontent.com/4992162/60451848-071dc980-9bfb-11e9-9e42-2f5a803d7b7a.jpg)

**Comment by thrust26** [comment]
Looks more like a hardware issue than something Stella creates. Some questions:

1. Have you tried different renderers?
2. Does this happen only with this game?
3. Are you using TV effects? What happens when they are disabled?

**Comment by kdgarris** [comment]
1) When I tried different renderers, I detected the issue for all of them except for "metal".
2) I haven't noticed it with other ROMs so far.  I can try experimenting with more "standard" games to find another example if that might help.
3) No TV effects.  I was using phosphor for all ROMs, but disabling that did not seem to make a difference.

This isn't a big issue, but I thought it might be useful to know in case there were others that saw it as well.

**Comment by thrust26** [comment]
@kdgarris "metal"? Is that a renderer displayed by Stella? If yes, then it seems like a problem outside of Stella. 

Please reply so that we know if we can close this issue.

**Comment by kdgarris** [comment]
Yes - metal is an Apple technology supported by SDL2, and is an available Renderer for Stella on Macs. The colors are correct with this renderer, but not the others. If that proves it is not a Stella issue, then that's fine.

**Comment by sa666666** [comment]
I think this is outside Stella, but we can still potentially mention it in the docs since it's now a known issue.  Then we can close this one.
