### ISSUE TITLE
ROM with NTSC and PAL compatibility not working in PAL mode

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#501]
Issue is mentioned on AtariAge:  https://atariage.com/forums/topic/269701-nyan-cat-game-work-in-progress/?do=findComment&comment=4310215.

ROM is here: [nyancat.zip](https://github.com/stella-emu/stella/files/3408751/nyancat.zip)

Basically, holding down Reset on powerup is generating PAL signals, but the video is in NTSC (rolling screen).

**Comment by thrust26** [comment]
There seems to be another (unrelated) bug which occurs with this ROM:

Steps to reproduce:
- start the ROM
- enter debugger
- enter "reset"
- step (CTRL+S)

This causes an assertion in Rect.hxx for the ROMListWidget.

**Comment by snes2600** [comment]
That seems like a pain to fix. Because when the game detects the soft-reset button, it jumps back to the PC entry point @ $1000 (bank 0).

Stella would have to run its Console auto-detect format again to keep detecting the NTSC / PAL switches; I couldn't figure out an easy way to force this. But it could do an accidental double detect this way too (one at constructor, one at start).

**Comment by thrust26** [comment]
> Because when the game detects the soft-reset button, it jumps back to the PC entry point @ $1000 (bank 0).

Where did you see that? For me it only stores the initial state of Reset in 0x81 and works with that from then on.

**Comment by thrust26** [comment]
I think the problem is, that `EventHandler::handleConsoleStartupEvents()` is not called before `Console::autodetectFrameLayout` is executed.

@DirtyHairy Can you have a look at this? I would try to fix it myself, but the system obviously has no console, which is just in creation at that moment. So the necessary riot updates must fail.

**Comment by DirtyHairy** [comment]
I'll take a look.

**Comment by snes2600** [comment]
> Where did you see that? For me it only stores the initial state of Reset in 0x81 and works with that from then on.

I put a breakpoint on $1000 start. Waited for in-game to display. Held down F2 Reset and then pressed F1 Select. And it triggered the debugger at that spot again.

But I'm basically a newbie when it comes to 2600 debugging. And naive. So beware what I write. I'm just interested to learn more on average. :)

**Comment by thrust26** [comment]
Ah, that's a 2nd scenario: Switching the format after Stella is already long running.

This is a general issue, not only with this ROM, but for all ROMs which switch from NTSC to PAL (e.g. Boulder Dash) format. Stella would have to become able to switch formats permanently.

@DirtyHairy Would this be possible? Stella should know the number of scanlines. So when they go above or below a threshold, the format could change automatically.

**Comment by DirtyHairy** [comment]
@thrust26 With the current setup of autodetecting PAL and NTSC *and* ystart, I think this is too complicated. Once we eliminate ystart autodetection in favor of constant value, this should be viable.

**Comment by thrust26** [comment]
That was my hope.

**Comment by DirtyHairy** [comment]
@thrust26 I have made an attempt of a slightly less appalling fix in 09bd0f817 . However, I am not really happy with it either, but I don't think we can manage anything better at this time. Feel free to revert and replace with your solution if you prefer it 😏

**Comment by sa666666** [comment]
I would like to get the autodetect ystart removed for 6.1, and with it fix a few other issues.  @DirtyHairy, is this feasible?  Should we create an issue for that one, or is is assumed we all know it has to be done??
