### ISSUE TITLE
Variable DPC Pitch

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#502]
To emulate the differences between Pitfall II carts, allow changing the pitch.

**Comment by thrust26** [comment]
Implemented in audio dialog with 61d9f26

**Comment by ale-79** [comment]
There's some info about the oscillator in a Pitfall II cart in the "Atari 2600 Mappers" document by kevin Horton (an updated version of the old "sizes.txt"):

> There's been some discussion about the pitch of the music generated by this chip,
> and how different carts will play the music at different pitches.  Turns out, on the
> cart, the frequency is determined by a resistor (560K ohms) and a capacitor integrated
> onto the die of the DPC chip itself.  The resistor is a 5% tolerance part, and the
> process variations of the DPC itself will control the frequency of the music produced
> by it.
> 
> If you touch the resistor on the cartridge board, the music pitch will drastically 
> change, almost like you were playing it on a theremin!  Lowering the resistance makes
> the music pitch increase, increasing the resistance makes the pitch lower.
> 
> It's extremely high impedance so body effects of you touching the pin makes it 
> vary wildly.
> 
> Thus, I say there's really no "one true" pitch for the music.  The patent, however,
> says that the frequency of this oscillator is 42KHz in the "preferred embodiment".
> The patent says that it can range from 15KHz to 80KHz depending on the application
> and the particular design of the sound generator.  I chose 21KHz (half their preferred
> value) and it sounds fairly close to my actual cartridge.  
> 

The full document can be found here:
[http://blog.kevtris.org/blogfiles/Atari%202600%20Mappers.txt](http://blog.kevtris.org/blogfiles/Atari%202600%20Mappers.txt)

The patent for the DPC chip which the doc refers to is number 4644495

**Comment by thrust26** [comment]
So that 5% tolerance means, that the current range of 10,000..30,000 is more than large enough.

**Comment by ale-79** [comment]
That's what I think too.
