### ISSUE TITLE
Feature request: add a way to show long filenames that don't fit in the launcher width

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#503]
Long filenames (e.g. those in Romhunter's rom collection) can be truncated in the launcher when using low resolutions. It would be nice to have a way to show the complete name if it doesn't fit in the launcher width, e.g. by scrolling the text (only for the highlighted file).

**Comment by sa666666** [comment]
That's actually useful to have in other parts of the UI too.

**Comment by thrust26** [comment]
IMO scrolling text doesn't work well for a completely static UI.

In case of the launcher, we could either use the ROM Info area (usually plenty of space there) or add a new field e.g. below the list.
Mouse over info might work too, but only when you use a mouse.
In the Harmony menu I use a long button press to show an alterative screen, maybe this could be adapted for Stella too. Best case it should work with all kind of inputs.

**Comment by thrust26** [comment]
The ROM info viewer can now display multiple lines per entry. So if the Stella defined name or the file name is too long to be fully displayed in the launcher's file list, one can lookup the full name in the ROM info viewer.

@ale-79 If that is ufficient, we can close this issue.

**Comment by sa666666** [comment]
@thrust26, ooh, I didn't know that was present now.  You're adding new features so fast over the past few weeks that I don't even have time to play with them before a new one comes along :smiley:

**Comment by sa666666** [comment]
I agree with @thrust26 that making a scrolling textfield is beyond the limits of the UI code we're using, and adding that functionality will take a lot of time.  Being able to see the full name in the info viewer is a nice compromise, so unless I hear back from either of you in the next day or so, I will go ahead and close this one.

**Comment by ale-79** [comment]
Hi! Sorry for the late reply, I'm on vacation and I'm currently not connecting to the internet and checking emails very often.

I understand that adding scrolling to the UI would be a complex task and I think the info viewer will do the trick just fine, thanks!

**Comment by sa666666** [comment]
OK, then since we are satisfied, I will close this one.
