### ISSUE TITLE
Framebuffer width needs to be 32-bit aligned

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#504]
Recent changes to the TV effects have made the framebuffer no longer be 32-bit aligned (aka, a multiple of 4).  This has weird effects on some systems, notably Android and PSP that use OpenGLES in libretro.

More information is here: https://atariage.com/forums/topic/286333-stella-60-released/?do=findComment&comment=4316050

I think a pretty easy for the TV effects code is to simply make the width be a multiple of 4, then fill with black where necessary.  The normal framebuffer is fine already (160 pixels wide).

**Comment by snes2600** [comment]
https://ci.appveyor.com/project/snes2600/stella/builds/26254818/artifacts

This Android buid has that 1 line changed.
https://github.com/snes2600/stella/commit/6439893a5bdcfae1a2ce2c2ce9299c1edacf3f99


Did not have time to test to see if it affects libretro Windows.

**Comment by snes2600** [comment]
Minimal changes needed for Windows to work:
https://github.com/snes2600/stella/commit/0de63e11bd7e4203022aafb81c7a9227d552ca40

Android tests will be here in 20+ minutes later
https://ci.appveyor.com/project/snes2600/stella/builds/26275372/artifacts

**Comment by snes2600** [comment]
Android builds here. Unsure if GLES is fixed.
https://ci.appveyor.com/project/snes2600/stella/builds/26276998/artifacts

**Comment by sa666666** [comment]
OK @snes2600, can you forward this to someone who can test it?  It would be great if we know for sure this is the issue, and we can go ahead and fix it properly.

**Comment by snes2600** [comment]
Only person I (indirectly) know is Shannon from AtariAge. No else wants to try. 😆

**Comment by sa666666** [comment]
OK, please follow up with him if you can; I really want to get this taken care of and fixed for good.

**Comment by snes2600** [comment]
Shannon confirms last build is good. Games work perfectly.

**Comment by sa666666** [comment]
OK, we'll look into it from here.

**Comment by thrust26** [comment]
I just committed a fix which needs good testing,

**Comment by sa666666** [comment]
Ooh, crashes immediately on switching to phosphor mode.  I've never seen Linux crash like that before; it required a complete reboot to get back in.

**Comment by thrust26** [comment]
Hm, then you have to debug yourself, because it works on my side.

**Comment by sa666666** [comment]
It's the '+ 2' at two places in the patch.  I'll look into it later today, when I find some extra time.

**Comment by thrust26** [comment]
Alternatively we can could change the original +5 into 4 (instead of 8). That would only cost one pixel for bad TV effects. And then we would not need the +2 anymore.

**Comment by sa666666** [comment]
Don't know; have to experiment.

**Comment by sa666666** [comment]
In Windows at least, toggling phosphor is chopping off part of the bottom of the image.  So while it's not crashing like in Linux, it's still not fully correct.

**Comment by thrust26** [comment]
I was able to fix the problem when TV effects are disabled in `TIASurface.hxx`:
~~~
uInt32 myRGBFramebuffer[AtariNTSC::outWidth(TIAConstants::frameBufferWidth+8) *
                            TIAConstants::frameBufferHeight];
uInt32 myPrevRGBFramebuffer[AtariNTSC::outWidth(TIAConstants::frameBufferWidth+8) *
                             TIAConstants::frameBufferHeight];
~~~
But we would have to do the same for other buffers too. And I am afraid that this will require digging deeper into the Blargg code. So I would opt to go with +4 instead +8. 

What do you prefer?

**Comment by sa666666** [comment]
I don't see why the offsets need to propagate throughout the code.  `AtariNTSC::outWidth` should return a value that is a multiple of 4, and the buffers that use it should just work, and not care what is happening inside the buffer.  Then we do all the work in `AtariNTSC`, to center the image horizontally.

**Comment by sa666666** [comment]
My original hack made `AtariNTSC::outWidth` return 568 (instead of 565), and other than the right area of the Blargg output being wider than the left, everything else worked fine.  When that method returned the original 560, all other buffers were fine with it.  When you changed it to 565, they were still fine.  So changing it again to 568 shouldn't cause an issue now.  The only issue is in `AtariNTSC`, so we should fix it there.

**Comment by thrust26** [comment]
Nope, phosphor did not work with your hack. Neither with or without TV effects,

**Comment by thrust26** [comment]
There is one problem left when enabling TV effects: The left two pixels are not cleared.

**Comment by sa666666** [comment]
OK, this fixes the crash in Linux, and overall seems to be working fine.  Very strange that it caused a crash, though.  I guess it was writing past the end of a buffer or something.

Thanks for getting to this.  There's just a small fix I need to make in the libretro code, and we should have this one nailed for good.

**Comment by thrust26** [comment]
I wish this would crash in Windows too. Then I would have less broken commits.

**Comment by sa666666** [comment]
@snes2600, I think this is now fixed.  Please test and ask Shannon to do so too.

**Comment by snes2600** [comment]
Tried all modes and all looks dandy on Libretro Windows. Informed Shannon about the fix, who is waiting for buildbot to go live. Then we'll know if the mystery PSP thing is fixed.

**Comment by snes2600** [comment]
Shannon's message:
> I am happy to report that the fix works well on the Sony PSC.  No graphical issues at all.  Although it does appear to cause a slight framerate drop on DPC games?  Not as bad as using the TV filters.  But it is there.  I noticed it most on the Galaga demo.

**Comment by sa666666** [comment]
Thanks for the feedback.  I don't see how it would cause noticeable slowdowns; we're moving from a 565-pixel wide buffer to a 568-pixel one.  That's only a ~0.5% increase, so I don't think one would see it.  It's more likely that the Galaga demo is using more features of ARM emulation, and causing a hit that way.

Or TBH, it may be that the emulation speed is marginal on this hardware, and any small change is enough to push it over the edge and lose a frame or two.  But that is probably a separate optimization issue, which is not part of this issue.  I will close this now, confident that we have fixed this issue.
