### ISSUE TITLE
suggestions for "TIA display" and "TIA zoom" views in debugger

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#505]
Just a small thought, but since currently there's nothing associated to left-click in the TIA view in the debugger, I think that "set zoom position" would work nicely there, instead of picking it from the right-click context menu. 
Even if activated by mistake it wouldn't have any ill effect.

EDIT:
Thinking more about it, "fill to scanline" and "toggle breakpoint" would be useful to have in the zoom view too. It's easier to pick the exact spot there.

**Comment by thrust26** [comment]
Good ideas. I will look into them.

**Comment by thrust26** [comment]
Implemented with c53fb6ab
