### ISSUE TITLE
Add support for "$2A0/$2C0" bankswitching used in some brazilian carts

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#506]
More info here:
[https://atariage.com/forums/topic/103737-2600-rom-comparisions-and-dumps/?do=findComment&comment=4317367](https://atariage.com/forums/topic/103737-2600-rom-comparisions-and-dumps/?do=findComment&comment=4317367)

**Comment by thrust26** [comment]
That's almost identical to UA bankswitching ($220, $240), I suppose we should use abstract classes here.

**Comment by ale-79** [comment]
I attach here the (unaltered) roms, so they are all in one place:
[brazilian_roms.zip](https://github.com/stella-emu/stella/files/3437342/brazilian_roms.zip)

**Comment by thrust26** [comment]
I wonder about the swapped banks/hotspots in Mickey. 

Bank0 is using $Fxxx adressing, while bank1 is using $Bxxx. That makes me assume that the banks where swapped when dumping the cart.

**Comment by ale-79** [comment]
> That's almost identical to UA bankswitching ($220, $240), I suppose we should use abstract classes here.

Actually, it turns out this **IS** the UA bankswitching!

Pictures and layout of the board from which the last 2 games were dumped has been posted on AA:
[https://atariage.com/forums/topic/293883-did-i-miss-something-while-doing-this-dump/?do=findComment&comment=4318061](https://atariage.com/forums/topic/293883-did-i-miss-something-while-doing-this-dump/?do=findComment&comment=4318061)

So I could use those to draw a logic diagram of the bankswicthing circuit, which consists of 2 off-the-shelf ICs (74LS10 Triple 3-input NAND gate), and I think this is the same circuit used for the UA games:
![UA_diagram](https://user-images.githubusercontent.com/24704739/62002634-2596b800-b108-11e9-972b-d23b446d9653.jpg)


As can be seen from my crude diagram, it takes 4 address lines (A12, A9, A6 and A5) as inputs from the Atari and outputs the BANK value (that is, the A12 address on the eprom). (The /OE signal in the diagram isn't part of the bankswitching logic, that's just the inverted Atari A12 that's used as a chip select for the eprom)

Any address with **A12=0, A9=1, A6=0, A5=1** cause a switch to **bank 0**
Any address with **A12=0, A9=1, A6=1, A5=0** cause a switch to **bank 1**
Any address with **A12=0, A9=1, A6=1, A5=1** correspond to the "**undefined**" state of a NAND SR latch, so it may or not cause a bankswitch.

So generalizing the UA scheme according to this, will make these new roms work, except for "Mickey" that, assuming it is a good dump, has the hotspots  swapped.

I think it's possible that boards using inverted hotspots exists: in the diagram, you obtain that by swapping A5 and A6, or (which is the exact same thing!) by using the inverted output of the latch (/Q) as the BANK bit.

There's no way to know if that's a bad dump or not, so you could just patch the rom by swapping the banks or add this "inverterd UA" scheme to run it as is. 
I (slightly) prefer the second solution.

**Comment by thrust26** [comment]
So you mean A7 can be ignored, right? Then the hotspots would be identical, yes. But ignoring A7 would lead to other implications.

**Comment by thrust26** [comment]
Adapted UA bankswitching to 3 (of 4) new Brazilian carts with bd39c08

**Comment by ale-79** [comment]
> So you mean A7 can be ignored, right? Then the hotspots would be identical, yes. But ignoring A7 would lead to other implications due to the way Stella is set up. Hm...

A7 is actually connected to the reamaining NAND gate (there are 6 in total, 3 per each 74LS10 IC). In that area of the board there are a few solder jumpers; the board layout posted by cetics on AA shows some of those jumpers open and some closed. With that configuration, which is what I used to draw the diagram above, that gate is isolated from the circuit, and so A7 doesn't have any effect. 
![A7](https://user-images.githubusercontent.com/24704739/62004122-4a4b5980-b121-11e9-9d56-5a47ea6022e6.jpg)

The presence of those jumpers suggests that the board can be configured for a different bankswicth, for which the value of A7 does matter.

**Comment by thrust26** [comment]
Fully implemented with db7def8
