### ISSUE TITLE
Distribute Stella in a Flatpak

### ISSUE THREAD

**Issue by LeandroStanger** [stella-emu/stella#508]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by sa666666** [comment]
Not opposed to the idea, but also don't currently have a lot of time.  We would welcome any help you can provide in this area.

**Comment by sa666666** [comment]
Nobody has come forward to volunteer to work on this, and unfortunately we don't have time to do it.
