### ISSUE TITLE
Debugging for the colourblind

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#511]
I have one question/request - when debugging in standard theme I get green text on red background like the image. This is totally unreadable for me, even with the screen a few inches from my face. Very difficult anyway. But other than that, I like the theme colours. The "light" theme makes everything readable but is otherwise ugly as. Would it be possible to address the contrast in this red/green area and perhaps consider alternate colours? Yellow on blue is readable. White on red is probably readable. green on red... isn't!  Of course I may just be colourblind :P

<img width="293" alt="Screen Shot 2019-08-10 at 11 43 20 pm" src="https://user-images.githubusercontent.com/16424075/62822878-f5055280-bbcc-11e9-8236-a86dccfe181d.png">

**Comment by andrew-davie** [comment]
https://uxmovement.com/content/why-you-should-never-pair-green-and-red-on-the-web/

**Comment by thrust26** [comment]
I will make it yellow.
