### ISSUE TITLE
Debugger doesn't exit from 'Fatal error' dialog correctly

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#513]
In a few cases, when the debugger is entered with a 'Fatal error' and 'invalid instruction', clicking "Exit ROM" seems to simply close the dialog but not actually exit the ROM.  The only way to continue is to quit Stella entirely.

**Comment by thrust26** [comment]
Same problem with "exitrom" which currently does nothing.

**Comment by sa666666** [comment]
Narrows it down at least.  The same logic is being 'mis'-used.

**Comment by thrust26** [comment]
I have to reopen it, the original problem reappeared.

**Comment by sa666666** [comment]
Yep, meant to mention I was noticing this again with a few bad ROMs that immediately jump to the debugger.
