### ISSUE TITLE
"Illegal" ZIP files behave differently

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#514]
While trying to crash the emulator, I found that the behavior for ZIP files has changed. When I now try to start a ZIP file which does **not** contain a valid ROM, Stella crashes in the emulator. Previously it threw an exception in `OSystem` (*ERROR: Couldn't create console (File not found/readable)*).

[empty.zip](https://github.com/stella-emu/stella/files/3501003/empty.zip)

Is that due to the new ZIP handler accepting different ZIP formats? And what would be the correct behavior

**Comment by sa666666** [comment]
This is related to the `FileListWidget` stuff that I'm currently working on but not yet finished.  Definitely a regression that I need to get fixed.  It will have to wait, though.  More infrastructure is needed before I can fully fix it.

**Comment by thrust26** [comment]
@sa666666 This can be closed now, right? The bug is gone.

**Comment by sa666666** [comment]
I haven't tested in Windows yet, and I never did see the crash in Linux.  So I will test Windows first, and close when I confirm this is actually fixed.

**Comment by thrust26** [comment]
I did and for me the bug is gone. :smile:

**Comment by sa666666** [comment]
OK, I will close then.
