### ISSUE TITLE
Compilation issue - Libretro - Emscripten

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#515]
http://p.0bl.net/151620

I believe this issue could be fixed simply by casting the second parameter of the function call to 'Logger::Level'.

**Comment by twinaphex** [comment]
Similar errors too for all iOS/OSX builds and Android -

http://p.0bl.net/151589

**Comment by sa666666** [comment]
Yep, this is a WIP, and not all of the method calls have been converted yet.

**Comment by thrust26** [comment]
Shall we now fix score for platforms maintained by others too?

**Comment by sa666666** [comment]
If it's minor and because of an API change _we_ make, then I think yes.  Also, this affects @DirtyHairy SQL stuff too.  Will commit a fix IAM.
