### ISSUE TITLE
Prevent repeated windows closing

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#516]
When exiting a dialog or window with e.g. the ESC key, this key might be repeated when hold too long. SDL2 provides a repeated flag, which helps detecting such repeats. 

However this does **not** work between (e.g. Debugger and Emulator) windows. There SDL2 does not report the next key press as repeated. And then the following window will be closed unintentionally.

Also see [this ](https://github.com/stella-emu/stella/commit/950068ba603901d07ca29d0ab07abf0b25cf120e#commitcomment-34688991)discussion.

**Comment by f21red** [comment]
Could manually doing key polling and debouncing flag checking help?
http://wiki.libsdl.org/SDL_GetKeyboardState

Or some combination of SDL_PollEvent together with GetKeyboardState?

**Comment by thrust26** [comment]
Partially fixed with 6c2cbf3
