### ISSUE TITLE
Make paddle input configurable

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#522]
The range of the Atari's paddle input is very small and positioning also varies from game to game. So other analog input (e.g. joystick hats) do not fit well to that. The sensitivity is usually too high and auto centering controllers put the paddles way off center in neutral position. 

So we some user configurable parameters which allow adjusting the response. 

For correct centering we probably need game specific parameters and for sensitivity they might have to be controller and axis specific. This adds some complexity, but Stella should not become overly complex for the user here. 

So this needs much testing of various controllers (including Stelladaptors) and some thought on how to design the UI.

**Comment by pupypup** [comment]
Hey i want this. Like ive been googling and yeah i want this. Im not using an actual paddle controller, but i am using a handheld wheel controller, its made for racing games but i imagine it could work as a paddle. Problem is that when i map it to the analog it is to the left when centered and only goes to the right, turning it left does nothing.

**Comment by thrust26** [comment]
I have a first shot at this committed with 4ad5978.

For now, there are only **global** settings for paddle center and sensitivity. This seems not sufficient, each game seems to need its own center. Also vertical and horizontal sensitivity could be different too. Between games and even within the same game.

**Comment by thrust26** [comment]
Done with 6741cb4
