### ISSUE TITLE
Z26 palette - luminance

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#523]
I had been using the Z26 palette. I am submitting this "bug" to question if the luminance on the Z26 palette is handled correctly?  In particular, the darker shades are barely noticeably different to the lighter ones. The standard palette shows a broad range of luminance, the Z26 seems to show almost none at all. I attach screenshots from the latest Stella build (today) to show the difference.

My view is that the Z26 palette colours are fine, but the luminance range is not. I'm just checking - is this how it is meant to be?  I would have expected the darks to be much darker.
<img width="641" alt="Z26_Palette" src="https://user-images.githubusercontent.com/16424075/63391530-1862a580-c3f6-11e9-94ed-134e193bd811.png">
<img width="644" alt="Standard_Palette" src="https://user-images.githubusercontent.com/16424075/63391531-1862a580-c3f6-11e9-96f9-5521fe42f873.png">

I realise this may not be a bug. Just submitting to make sure it's OK.

**Comment by sa666666** [comment]
Hmm, pretty sure the code we're using to generate the z26 palette comes directly from z26.  I would have to follow up on this, since I don't use that palette, and haven't played with that part of the code in some time.

**Comment by thrust26** [comment]
The colors are 100% identical.
