### ISSUE TITLE
MacOS stella icon

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#524]
My local build does not have the pretty stella icon in the taskbar.
Is it possible to have the build include the correct icon?
Screenshot shows old/new side by side, both running on MacOS.
<img width="258" alt="Screen Shot 2019-08-21 at 9 21 23 am" src="https://user-images.githubusercontent.com/16424075/63391613-67a8d600-c3f6-11e9-9b15-151fa6e1dcf8.png">

**Comment by sa666666** [comment]
This might be a consequence of building the 'Linux' way vs. using Xcode.  I will look into it and let you know.

**Comment by sa666666** [comment]
It shows the 'pretty' icon for me in macOS.  But I built with Xcode, not on the commandline.  I would guess this is the reason.  Going forward, perhaps we can extend the 'Linux/UNIX' build to work the same as the Xcode one.

**Comment by DirtyHairy** [comment]
Yeah, I am afraid this is one of the limitations of the CLI build. Basically, it behaves just like a standard CLI Linux / UNIX application and lacks all MacOS-isms. In the XCode build, the icon is configured in the corresponding plist file and becomes part of the application bundle.

I'll do a bit of research, but I guess that that is something we won't be able to work around in the CLI build.

**Comment by sa666666** [comment]
Closing this as a problem with how the builds are done.  I do the release builds with Xcode, so this will never happen for most users.  For those using interim builds, this is the price of admission :smiling_imp:
