### ISSUE TITLE
UI consistency in debugger

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#526]
In the debugger, Thomas has mentioned that the default radix is hexadecimal, and decimal numbers are prefixed with '#'. That's fine, but it does need to be used consistently.
It's a bit 'all over the place' at the moment. For example, in the command entry window, hex is assumed and output without prefix $. But in the cartridge3E tab all hex numbers are marked with $ and decimal numbers have no prefix. Droplists for bank numbers are in decimal. In the disassembly, everything is hex, no $ (as it should be). Frame number, colour clock, etc., are all in decimal. Yet the registers are displayed in hex. The "TIA" tab appears to be all decimal, the I/O tab is a random mix (for example, divider is decimal, intim is hex. Yet no indicator which is decimal or hex, you just want to be lucky the number displayed is obviously hex. And the "Audio" tab.... looks like hex. Yes/no/maybe your guess is as good as mine.  Perhaps different fonts could be used for hex/decimal?  Or colours?  Something to guarantee there's no confusion. Perhaps always use leading zeroes for hex numbers. Or, more to the point, be consistent with the use of base identification. If any number is decimal, precede it with '#' including droplists. OR, use hex (no prefix).

So, a couple of suggestions...
* clearly mark the boxes/fields of numbers with shading according to their base
* use different fonts for hex numbers
* use leading zeroes for hex numbers and binary numbers
* always always use # when showing decimal numbers, and no prefix for hex numbers

**Comment by thrust26** [comment]
We can fix the output for individual numbers (e.g. in the prompt). But prefixing them overall would break the current UI as it would require a lot of extra space. And I don't like using a different font (that wouldn't work in the prompt window anyway). 

So maybe we can add some '#' here and there (else hex would be assumed). That's the best we can offer for now. There is just too much, IMO more relevant work on our list. 

But of course everyone is welcome to help us. :smile:

**Comment by thrust26** [comment]
And another level of complexity: The `base` command, which changes the default format, but only for some parts. 

That's quite a lot of work required to fix with IMO rather little improvement. So this will most likely stay at low priority for a long time.

**Comment by thrust26** [comment]
Most inconsistencies have been removed now, based on the following rule:
- hex: no prefix
- decimal: # prefix
- binary: % prefix

Known exceptions:
- TIA info tab (all decimal, but no # prefix)
- I/O Tab, binary switch values in data grid (no % prefix)
- Cartridge tabs (hex prefixed with $)
