### ISSUE TITLE
Improve TIA interpolation in order to reduce blurriness

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#529]
Currently, TIA interpolation enables bilinear texture filter in SDL. The result is a blur radius of approx. one TIA pixel, independent of the dimensions of the target texture.

This can be improved by first scaling the image to the closest integer factor in both vertical and horizontal direction using nearest-neighbour interpolation and then scaling to the final dimensions using bilinear filtering. See also the discussion on #525.

**Comment by thrust26** [comment]
Maybe SDL knows how to do that? Have you checked?

**Comment by thrust26** [comment]
Maybe we need two types of interpolation, a sharp one and a blurry one (especially for TV effects enabled).

**Comment by DirtyHairy** [comment]
> Maybe SDL knows how to do that? Have you checked?

I haven't checked extensively, but nothing that I have seen points to anything like this. I am not surprised, though, this is outside SDLs domain as I understand it --- SDL is more of a HAL than of a video library.

> Maybe we need two types of interpolation, a sharp one and a blurry one (especially for TV effects enabled).

I have been thinking the same. There is not "good" way to do scaling, and plain bilinear filtering may be preferred by some.

**Comment by thrust26** [comment]
There is a name for this. :smile:

https://www.pcworld.com/article/3435843/intel-adds-retro-scaling-to-ice-lake-cpus-to-make-pixel-art-games-look-more-crisp-on-modern-display.html

**Comment by DirtyHairy** [comment]
😛  There's nothing new under the sun

**Comment by DirtyHairy** [comment]
Implemented as QIS (quasi integer sacling) in c38febc2c.

QIS:
<img width="1028" alt="Bildschirmfoto 2019-12-17 um 17 19 26" src="https://user-images.githubusercontent.com/2444224/71014463-3f09c200-20f2-11ea-882a-ff326ef700b4.png">

Soft (= bilinear):
<img width="1072" alt="Bildschirmfoto 2019-12-17 um 17 19 45" src="https://user-images.githubusercontent.com/2444224/71014466-416c1c00-20f2-11ea-809a-995f5204e886.png">

No interpolation:
<img width="1072" alt="Bildschirmfoto 2019-12-17 um 17 19 55" src="https://user-images.githubusercontent.com/2444224/71014478-45983980-20f2-11ea-9b74-9469f584b2e7.png">
