### ISSUE TITLE
Top is cut off on Stella on Retropie

### ISSUE THREAD

**Issue by SkUNT85** [stella-emu/stella#530]
I didn't know who to contact so I decided to leave it here.  I currently have a Stella on 4.5.1 of Retropie on a Raspberry Pi 3.  Specifically when I play on a CRT on Warlords the top is cut off on the CRT.  If there was some way of fixing this that I knew about (since I am not a programmer) - I thought I would reach out to you guys - So maybe I would know.  Thanks.

**Comment by thrust26** [comment]
I don't know about that release, but in the "normal" Stella there is a `Game Properties` dialog where you can change `Y-Start`

**Comment by thrust26** [comment]
If game properties do not help, then I suppose this cannot be fixed by us. On other platforms the display is fine.
