### ISSUE TITLE
Various multi-monitor issues

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#531]
Over the past year, I've received reports from users with multi-monitor setups.  There have been various issues:
- split windows, incorrect vsync settings, opening in the wrong monitor, etc (no source right now, lost the messages)
- minimizing windows in unexpected ways (https://atariage.com/forums/topic/286333-stella-60-released/?do=findComment&comment=4339242)
- others, as I remember them ...

I don't personally have such a system, but I guess I will have to look into getting another monitor at some point.

**Comment by sa666666** [comment]
Second monitor is on order; will look into it then.

**Comment by thrust26** [comment]
Another potential problem resulting from different monitor resolutions 
- allowed zoom levels
- UI sizing
- available full screen resolutions and refresh rates

See also #285

**Comment by thrust26** [comment]
I just created another issue (#786) for this.

**Comment by thrust26** [comment]
@sa666666 Are the (known) issues (still) reproducible for you?

**Comment by thrust26** [comment]
Looks fine by me. 

But I was never able to reproduce the "minimizing windows in unexpected ways" though. Did you look into this? Maybe we should ask Darrell?

**Comment by sa666666** [comment]
I cannot reproduce either.  Not sure if it's even still present.  I guess we can ask James about it.

**Comment by sa666666** [comment]
OK, I guess we can close this.
