### ISSUE TITLE
Scrolling in ROM listing sometimes causes crash 

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#532]
This happens very irregularly, so far I have no pattern found.

This is the usual crash location in `Rect.hxx`:
`Rect(uInt32 x1, uInt32 y1, uInt32 x2, uInt32 y2) : top(y1), left(x1), bottom(y2), right(x2) { assert(valid()); }`

Steps to reproduce:
1. Load the attached ROM (make sure it is detected as F8)
2. Enter debugger
3. Scroll up to the beginning of the bank using the mouse wheel

The problem here is in `RomListWidget::getEditRect()`, where `_currentPos` (1) is larger than `_selectedItem` (0). And this results into a negative `yOffset` (-15, depends on font) which then results into a negative `y1`. 

Note: This is not only one scenario where this happens. I remember similar crashes in the middle of a bank.

[Thwocker_fixed.zip](https://github.com/stella-emu/stella/files/3562160/Thwocker_fixed.zip)

**Comment by thrust26** [comment]
Here is a more common way to reproduce the crash:
1. start any ROM
2. enter debugger
3. click on the topmost row in the ROM list (this sets _selectedItem)
4. scroll down with mouse wheel (one step is enough)
5. scroll one line down with scrollbar arrow)
6. scroll up with mouse wheel

There seems to be a general inconsistency hiding somewhere. Either in the `RomListWidget` or in the scrollbar code itself.

**Comment by DirtyHairy** [comment]
@thrust26 After your fix, is there anything left to do for this ticket?

**Comment by thrust26** [comment]
I found not more issues, but we haven't analyzed if the problem potentially affects other code too.

**Comment by thrust26** [comment]
Closing this for now. We can reopen if we should find another occurrence of the bug.
