### ISSUE TITLE
MacOS build - broken?

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#535]
Following the instructions at...

https://stella-emu.github.io/development.html

I have tried an XCODE build on MacOS.
Firstly, it is not clear - the SDL file should be copied to /Users/((you))/Library/Frameworks, not /Library/Frameworks as suggested in the instructions. Otherwise the build gives a "not found" warning.  But, on fixing that, I get a bunch of errors, all related to BreakpointMap.  Perhaps I don't have a full copy of the code....?

Edit: a command-line build via 'make' works.

**Comment by thrust26** [comment]
@DirtyHairy 

Following your latest commint, can this be closed now?

**Comment by DirtyHairy** [comment]
Closed with ba3015a8f . Sorry, I am one the train with bad connection 😏
