### ISSUE TITLE
(Libretro) Build failures - OSX/iOS

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#540]
Hi there,

there are some build issues that have started happening as of today I think on OSX and iOS.

See the logs posted below -

stella: [Status: start] [recipes/apple/cores-ios9-generic] [Started: 2019-09-16 22:45:59.265884+00:00]
stella: [Status: fail] [recipes/apple/cores-ios9-generic] [Finished: 2019-09-16 22:46:37.852463+00:00] [http://paste.libretro.com/161260]

URL: http://paste.libretro.com/161260

stella: [Status: start] [recipes/apple/cores-osx-x64-generic] [Started: 2019-09-16 22:49:29.807161+00:00]
stella: [Status: fail] [recipes/apple/cores-osx-x64-generic] [Finished: 2019-09-16 22:50:34.972244+00:00] [http://paste.libretro.com/161262]

URL: http://paste.libretro.com/161262

stella: [Status: start] [recipes/apple/cores-ios-generic] [Started: 2019-09-16 22:53:57.405496+00:00]
stella: [Status: fail] [recipes/apple/cores-ios-generic] [Finished: 2019-09-16 22:54:36.691198+00:00] [http://paste.libretro.com/161263]

URL: http://paste.libretro.com/161263

**Comment by sa666666** [comment]
Closing this, since I think it was fixed in the last set of updates.
