### ISSUE TITLE
Libretro compilation failure since today

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#545]
Hi there, the libretro builds on our buildbot are currently broken due to recent changes.

stella: [Status: fail] [recipes/apple/cores-osx-x64-generic] [Finished: 2019-11-02 12:24:37.690832+00:00] [http://paste.libretro.com/170146]

stella: [Status: fail] [recipes/apple/cores-ios9-generic] [Finished: 2019-11-02 12:33:45.450231+00:00] [http://paste.libretro.com/170148]

stella: [Status: fail] [recipes/linux/cores-linux-x64-generic] [Finished: 2019-11-02 13:34:59.276512+00:00] [http://paste.libretro.com/170153]

**Comment by sa666666** [comment]
The missing files (CartFC and friends) is fixed in a recent commit.  I can't duplicate the errors in the macOS builds, so I'm unable to fix those.  They don't happen on any other system, and I've tried 4 OS's and 7 different compilers.
