### ISSUE TITLE
Libretro build failure on linux

### ISSUE THREAD

**Issue by Sanaki** [stella-emu/stella#549]
No commits have been buildable on linux starting with ec35026329825755069eed714d2777be0587fc68. I'd imagine this is just a transitional issue, but if you need any further info I'd be happy to provide it.

Build error:
`make: *** No rule to make target '../emucore/tia/frame-manager/YStartDetector.o', needed by 'stella_libretro.so'.  Stop.`

**Comment by twinaphex** [comment]
Wanted to confirm this -

http://paste.libretro.com/180398

**Comment by sa666666** [comment]
Fixed in 578c19a5889f14fa4246b87d503fd228c16ab05c.
