### ISSUE TITLE
(Libretro) Build failures (iOS/OSX/Android)

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#551]
Some new build failures, this one for OSX x64 -

http://paste.libretro.com/180774

And also for iOS -

http://paste.libretro.com/180776

**Comment by twinaphex** [comment]
Android -

http://paste.libretro.com/180809

**Comment by sa666666** [comment]
Fixed in 6ec46b9836fd1f44ab6d5d3c75a1c4c2278d788e.
