### ISSUE TITLE
Bugs in joystick handling code

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#552]
@thrust26, I've found several issues in the new joystick handling code.

Analog sticks are no longer recognized in digital mode.  This is related to code in `PhysicalJoystickHandler::handleAxisEvent`:
```
// Check for analog events, which are handled differently
// A value change lower than ~90% indicates analog input
if(abs(j->axisLastValue[axis] - value) < 30000)
{
  Event::Type eventAxisAnalog = j->joyMap.get(EventMode::kEmulationMode, button, JoyAxis(axis), JoyDir::ANALOG);

  myHandler.handleEvent(eventAxisAnalog, value);
}
```
It seems this code disallows using an analog axis as a digital input.  So this axis can no longer be used to map to joystick directions.

Also, hat handling seems to be broken.  The events in the UI for Joy0 _do_ include the hat ones, but the hat/dpad doesn't work on my controller.  If I manually map them in the mapping UI, they _do_ work, but then upon exiting and restarting Stella, the mappings are broken again (but again, still listed correctly in the mapping UI).  So there seems to be a discrepancy between what the UI says is being mapped, and what is actually being done when controller input is received.

I refer this to you, since you reworked most of this code.

**Comment by thrust26** [comment]
Where your hats too broken before you changed the code?

**Comment by sa666666** [comment]
Yes, I tried it before I changed to `vector`.  The hat issues were still there.

As for the the analog vs. digital axes, the old code allowed an analog axes to be used as a digital one where the user wanted to.  Consider the case where a user has only an analog stick; they won't be able to use it in Stella (for the most part) at all!

**Comment by sa666666** [comment]
I would have to go back a few rev's to see where it started.  When was the last time you were you working on this part of the code?

**Comment by thrust26** [comment]
Not sure if this related to the problem, but for some days, noticed a broken keyboard mapping too. E.g. Ctrl+R opened the time machine dialog. I always defaulted all keys and then it worked again. Next time I will analyze the problem.

Analog vs. digital: I get you, but do you have an idea how to fix that? Also, how was what you describe possible before?

**Comment by sa666666** [comment]
I suspect the mapping is the problem.  When I manually add a mapping for hats, it works fine.  Until I close and restart Stella, and it's broken again.

Previously, analog axis could emulate digital one, since all digital input was detected if the value was greater than 32000 (I think that was the value).  A digital axis always works, since it swings from 0 to 32768, and the analog one would work when you swung it from 0 to the max in whatever direction you want (so it was guaranteed to go above 32000).  Long story short, there was a check for >32000 in the code.

OK, I will have to look at the git logs and try to trace back from there.

**Comment by thrust26** [comment]
I remember that check and it is still there for the UI. 

If you look through the logs, I had to remove existing mappings happening on the same axis for the other type (analog or digital) during mapping. The current code identifies analog input (during emulation only) at run time. So one can have both types of input mapped.

It never occurred to me, that someone would want to create digital events with an analog device during emulation.  So maybe we have to revert the last "enhancement" and live with the mapping limitations. Unless you have a better idea.

**Comment by thrust26** [comment]
Or (I currently cannot test this) we check (`eventAxisAnalog`) if an analog event is mapped for the current analog input . If not we continue with the digital events.

**Comment by sa666666** [comment]
I think this last one is a better approach.  We only need to treat an analog input as actually being analog if it is being mapped to an analog event.  Otherwise we treat it as digital.  I believe this is the way the old code worked.

**Comment by thrust26** [comment]
I cannot test until Sunday, so if you want to try yourself, let me know.

**Comment by sa666666** [comment]
I will leave it to you, if you don't mind.  You wrote the code, so you are more familiar with it.  Also, I'm working on other parts of the code ATM.

**Comment by thrust26** [comment]
Fine by me.

**Comment by thrust26** [comment]
@sa666666 Both issues seem to be fixed now. Can you please double check?

**Comment by sa666666** [comment]
Seems to be working for me.  Unless there is anything else, I guess we can close it?

**Comment by thrust26** [comment]
Yes
