### ISSUE TITLE
(OSX/iOS) Libretro build failure

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#554]
OSX -

http://paste.libretro.com/181845

iOS -

http://paste.libretro.com/181846

**Comment by sa666666** [comment]
I think this is fixed in 0a9b289b446a7e9fc467365c88ffb5b16eef32cb.  Also, there are constantly errors in the OSX/iOS builds that are using valid C++11/14 code.  Perhaps you could upgrade the compilers to a more standard version??
