### ISSUE TITLE
Permission to add Stella to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#558]
Hi there,

we would like to seek your permission to include Stella as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by sa666666** [comment]
As long as it abides by the GPLv2, then I have no issue with it.

**Comment by twinaphex** [comment]
Thank you, this is indeed the intent. 

So the approval is granted, or is there a secondary opinion necessary by someone else on the team?

**Comment by thrust26** [comment]
> or is there a secondary opinion required by someone else on the team?

Not necessary (or even possible), that's why there is the GPLv2 license. :smirk:

**Comment by sa666666** [comment]
I appreciate the forward notice and asking, but again, as long as you abide by the GPLv2, you don't actually need permission.  But asking is still appreciated.

**Comment by twinaphex** [comment]
Alright, closing this then. Thanks a lot guys, and we'll keep you posted as we draw closer to a release!

**Comment by DirtyHairy** [comment]
👍
