### ISSUE TITLE
Wrong default initializers for arrays (was: Fire button broken)

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#560]
Between 0a9b289 and 54de341 the following ROM's behavior changes, the fire button seems constantly pressed
[Thrust+ (v1.28 Gen).zip](https://github.com/stella-emu/stella/files/4057979/Thrust%2B.v1.28.Gen.zip)

It seems that INPT0 bit7 is set now initially. Note: The game also supports Boostergrip and Genesis.

**Comment by thrust26** [comment]
Adding these lines to the `Cartridge` constructor fixes the problem:
```
   setPin(DigitalPin::Six, true);
   setPin(AnalogPin::Nine, MAX_RESISTANCE);
```
It seems like the default member initialization is not 1:1 equal to the constructor initialization. Which makes me wonder what else might be broken now.

**Comment by sa666666** [comment]
Yep, I misread the docs on this one :cry: But it's not too hard to fix; I will look into it.

**Comment by sa666666** [comment]
I just did a quick grep on the code, and those two are the only ones that are relevant.  I just missed that one.  Default initialization will zero-initialize the remaining items if the first is zero'ed.  So I don't think I misread the docs after all, just copied/pasted this one incorrectly.

**Comment by thrust26** [comment]
That would be good news. But I found more changes e.g. `Paddles::myCharge`, are you sure these are not relevant?

**Comment by sa666666** [comment]
There are about 40 places where this occurs.  I will go over each one to make sure they're all fixed.

**Comment by sa666666** [comment]
Pretty sure I got them all now.  The only two were the ones you found, where the initialization was non-zero.  The rest are either zero-initialized, or have full initializer lists already.  So unless you find another one, I will close this one.
