### ISSUE TITLE
Detect TV type from filename

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#561]
It is impossible for Stella to detect why TV type a game is meant for except by checking the scanlines it produces. So e.g. PAL-60 and NTSC will always be auto detected as NTSC. 

The idea is to define the TV type in this order:
1. command line
2. game's properties
3. game's filename
4. auto detection

**Comment by sa666666** [comment]
All PAL60 ROMs currently (or should) have '(PAL60)' in the filename, at least if you use ROM audit and rename them according to RomHunter database.  Searching for 'PAL60' (case insensitive) should suffice for this.  I think NTSC50 and the SECAM varieties are rare enough that we probably don't need to care, but I guess looking for those strings is possible too.

**Comment by sa666666** [comment]
One other thing; to be consistent we need to consider the bankswitch scheme extension too.  In that case, it overrides the game properties and autodetection.  So filename contents should be checked first, then game properties, then autodetect.

**Comment by thrust26** [comment]
When does it make sense to override properties?

**Comment by sa666666** [comment]
OK, so maybe choosing the bankswitching scheme needs to be done the same way.  I suppose it doesn't really matter; I was just thinking of consistency.

**Comment by sa666666** [comment]
To add to this: I consider naming a file and using the commandline as an external action, done by the user.  So that should override anything built into Stella (so, it overrides ROM properties and autodetect).  That's why I place commandline and file naming as having higher priority.  That's how the BS scheme selection is done, but perhaps it doesn't make as much sense for the TV type?  Although I think they should be the same.

**Comment by thrust26** [comment]
Agreed, should be identical.

The command line is always user input, but the filename may originate from somewhere else. So IMO it is not exactly user input. That's why I would prefer properties over filename.

**Comment by sa666666** [comment]
OK, you can go ahead and implement it as you think is best, and I will update the BS stuff to match it afterwards.

**Comment by thrust26** [comment]
Will do.

One question: Should we update the game's properties from the filenames?
