### ISSUE TITLE
FileListWidget exception

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#562]
The `FileListWidget` sometimes throws an exception, when `selected().getName()` in `reload()` returns no result.

This happens when editing the filter might be related to ZIP files.

**Comment by sa666666** [comment]
Please try to provide an exact test case to illustrate this.

**Comment by thrust26** [comment]
I am trying to narrow the situation. But as of now I can only reproduce the problem within my Atari download folder which contains 100s of files.

**Comment by sa666666** [comment]
Nevermind, found the issue, and will commit the fix IAM.

**Comment by thrust26** [comment]
One bug less. 😄
