### ISSUE TITLE
Request - cycles between breakpoints

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#565]
For code timing, it would be **incredibly useful** if stella could display the # cycles since the last breakpoint. I could use this to time complex and variable code. Set a breakpoint at the start, one at the end. Run to the start breakpoint, then continue - and at the next breakpoint it displays the # cycles since the last breakpoint. It seems to me that implementation would be very simple, but the benefits when using for timed code would be significant.  So, that's my request - a cycle count displayed when a breakpoint is triggered.

**Comment by thrust26** [comment]
Good idea. Maybe we should extend that to cycles since the last stop of Stella. That way one can easily check e.g. subroutines too.
