### ISSUE TITLE
Highscore saving

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#570]
Allow Stella to save high scores for games which do not support this.

Ideas:
1. statistic code analysis (looking for typical code sequences), e.g. `\xf8.{0,20}\x85.{0,20}\x85.{0,20}\x85.{0,20}\xd8` is looking for 6 digits scores saved in ZP RAM
2. interactive: user provides current score (and maybe game variation too), result store in game properties
3. load from game properties (score addresses, variation address, format (BCD or Hex), other)

High scores would be presented in a new dialog (e.g. as popup dialog during emulation). Also the current high score could be displayed as message when a new game is started and also a another message when a new high score is achieved. Players might also want to add their initials to the score.

**Comment by DirtyHairy** [comment]
For Sokoboo running on Stellerator I implemented I way of communicating scores to the emulator by writing to `0x30` and `0x31`. Data is placed in a ring buffer by writing it to `0x30`, and writing a number n to `0x31` will dispatch the last n bytes from the buffer as a message. This might be a viable option for other homebrew and hacks, too, if we implement it in Stella (and it would be suitable for implementation in cartridge emulators as well).

**Comment by thrust26** [comment]
Sounds good, bit I think we should create a separate issue for this. Can you do that, please?`You know the details best.

**Comment by thrust26** [comment]
Further brainstorming:
- define a format for storing:
  - for each game (md5 sum)
     - for each variation (number)
        - score 
        - player initials
- extend game properties and dialog for direct editing the score relevant positions: 
  - variations
    - number of game variations
    - variation format (HEX or BCD, 0 based or not)
    - position of current variation in RAM 
  - players
    - number of players
    - player number format (HEX or BCD, 0 based or not)
    - position of current player in RAM 
  - scores
    - number of digits
    - score format (HEX or BCD)
    - position of score in RAM (for each player and for each byte, low to high)
- define a dialog which lets the user interactively find the bytes in RA;

**Comment by thrust26** [comment]
Try to detect game over and open the high scores dialog automatically.

**Comment by sa666666** [comment]
If we are bumping this, we need to remove it from the changelog.

**Comment by thrust26** [comment]
Yup.

**Comment by sa666666** [comment]
I just updated the changelog, moving this to 6.3.  @thrust26, is there anything we need to remove in the code, or is this not currently accessible from the UI anyway?

**Comment by thrust26** [comment]
This is still in a separate branch.

**Comment by thrust26** [comment]
Done with 6.5 release.
