### ISSUE TITLE
TimeMachine UI needs new hotkey

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#571]
'T' is used by the CompuMate and the new input mapping code blocks duplicate mappings (with controllers having priority). Therefore 'T' cannot be used for the TimeMachine UI as default.

I suggest either e.g. Shift+T or find a suitable single key which must not be used yet. 
@sa666666 Thoughts?

**Comment by sa666666** [comment]
I suppose Shift+T is fine.  Personally, I wonder if we need to access the TM that way at all.  I only ever access it by rewinding/forwarding.  So is there any use case for entering it without doing a rewind/unwind?

**Comment by thrust26** [comment]
You can load and store from there and also start/stop the TM. Quite useful if you don't have to remember all hotkeys.

**Comment by sa666666** [comment]
Just checked this out.  The problem is that the Compumate uses almost all keys on the keyboard (it _is_ emulating a keyboard, after all).  So Shift+T is not available either.  In fact, a lot of functionality isn't available in that mode for that reason.

**Comment by thrust26** [comment]
We have two options:
1. special handling for CompuMate which would allow us to use its keys (complex and limits CompuMate usage
2. new hotkey for TimeMachine UI.  Shift-T would work, except in CompuMate mode.
