### ISSUE TITLE
Disable user palette in UI if none is available

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#572]
n/t

**Comment by sa666666** [comment]
The problem here is that not only must the file be present, it must also be in the correct format.  So to be absolutely correct, that implies checking for its existence _and_ validity every time the dialog is loaded.

**Comment by sa666666** [comment]
The logic is already in `Console` to load and check whether an external palette file exists and is valid.  I suppose we just need to expose a method that the UI can query, to determine whether to show that option in the dropdown box.
