### ISSUE TITLE
Libretro build failure

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#573]
Libnx fails to build -

http://paste.libretro.com/191575

Linux fails to build -

http://paste.libretro.com/191533

**Comment by twinaphex** [comment]
I notice now there is a dependency on Launcher.hxx in HighScoreManager.cxx.

The libretro port does not use the GUI code at all, neither is it required.

@sa666666 Any input here?

**Comment by thrust26** [comment]
We will clean this up today.

**Comment by twinaphex** [comment]
Thank you.

**Comment by thrust26** [comment]
Should work again, please try and confirm. Thanks!

**Comment by sa666666** [comment]
I'm closing this, since it works in all my testing.  If the issue reappears, feel free to reopen the issue.
