### ISSUE TITLE
How to output an unscaled snapshot image

### ISSUE THREAD

**Issue by mslinklater** [stella-emu/stella#574]
Hi. Apologies if this isn't the correct place to ask this but is there a way to output an un-scaled snapshot image at the moment ? So the output image would by 160 pixels by whatever the vertical resolution is ? I'd like to look at accurate TIA timings and when the snapshot images are scaled to 4:3 aspect ratio this introduces an element of inaccuracy.

Thanks.

**Comment by sa666666** [comment]
Options -> Snapshots -> Ignore scaling (1x mode).  In that mode, it bypasses all filtering, scaling, etc, and outputs 160x_h_ images, where 'h' is typically from 240 to 300 or so.

**Comment by mslinklater** [comment]
Thank you
