### ISSUE TITLE
Overscan should not decrease saved launcher size

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#576]
While increasing overscan, the launcher size is reduced. When overscan is reduced later on, the launcher size will stay reduced.

The saved launcher size should not be affected by overscan settings.

**Comment by sa666666** [comment]
I can fix this one.

And to add to the description: Overscan should be applied to the UI res without changing the UI res that is stored.  So the changes must not propagate to the settings.

**Comment by thrust26** [comment]
I have a fix already. 😄

**Comment by sa666666** [comment]
OK, that works too :smiling_imp:

**Comment by thrust26** [comment]
What was your idea?

**Comment by sa666666** [comment]
I meant, you fixing it instead of me works too :smiley:
