### ISSUE TITLE
Maximum launcher height in windowed mode too large 

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#577]
When selecting the maximum launcher height, this fits for fullscreen mode. But in windowed mode, we have an additional title bar and then the bottom buttons become invisible.

**Comment by sa666666** [comment]
This is supposed to be fixed in the later versions of SDL.  For me at least in Linux, on a 2560x1440 desktop, the max selectable height 1396.  However, while it takes the size of the taskbar into account, it doesn't for the window title bar.

This is a bug in SDL.  We have no way in Stella of detecting what is on the screen, nor the size of it.  That falls directly to SDL, which has lower-level access to the windowing system.  And even _it_ seems to be getting it wrong here.

**Comment by thrust26** [comment]
At least for me `SDL_GetWindowBordersSize` seems to do the trick. It returns 26 for top and 3 for all other sizes. The problem is, that you have to create a window first.

**Comment by sa666666** [comment]
`SDL_GetDisplayUsableBounds` is used right now, and is supposed to do the job.  I would have to look into `SDL_GetWindowBordersSize`, and see why they aren't doing the same thing.

And there _may_ be a way of using this without creating a visible window.  I would have look into that too.

So according to what you say, `SDL_GetDisplayUsableBounds` accounts for the taskbar, and `SDL_GetWindowBordersSize` accounts for the titlebar.  We need to account for both.  So we either try to use both of these, or speak to SDL maintainers about a potential bug in `SDL_GetDisplayUsableBounds`.

**Comment by sa666666** [comment]
I just reported this on the SDL mailing list, looking for clarification on the interaction between these two functions.

**Comment by thrust26** [comment]
`SDL_GetDisplayUsableBounds` is only used for positioning the window. AFAIK we are not using it for size limiting.

**Comment by thrust26** [comment]
> So according to what you say, `SDL_GetDisplayUsableBounds` accounts for the taskbar, and `SDL_GetWindowBordersSize` accounts for the titlebar. We need to account for both. So we either try to use both of these, or speak to SDL maintainers about a potential bug in `SDL_GetDisplayUsableBounds`.

They are a bit different, IMO. `SDL_GetDisplayUsableBounds` get's the usable size for a new window, and `SDL_GetWindowBordersSize` gets the borders for an already **created** window. 

It seems like there is no way to find out the borders without creating a window first. Maybe that's an OS related restriction?

**Comment by sa666666** [comment]
It might be possible to create a window that is hidden initially.  If so, we can query it for the titlebar dimensions, then immediately close it.  Then proceed with normal startup.

**Comment by thrust26** [comment]
Yes. Someone suggested something like this for SDL 1 already. And since the problem has not been fixed by now, I doubt it will be changed soon. So your suggestion seems to be the right way to go.

**Comment by sa666666** [comment]
OK, I'll look into it.

**Comment by sa666666** [comment]
> At least for me `SDL_GetWindowBordersSize` seems to do the trick. It returns 26 for top and 3 for all other sizes in windowed mode and all 0 for full screen mode.

@thrust26, can you provide the code that gives you this info?  In my testing in Linux, all I get are 0's in either windowed or fullscreen mode.

**Comment by thrust26** [comment]
I simply added
```
      int top, left, bottom, right;
      SDL_GetWindowBordersSize(myWindow, &top, &left, &bottom, &right);
```
to `FrameBufferSDL2::setVideoMode`, after line 213

**Comment by sa666666** [comment]
I did exactly the same thing (even the same code!) at the end of the method, and it prints all 0's.

**Comment by thrust26** [comment]
Maybe it is not support for your system. What's the return code?

**Comment by sa666666** [comment]
0, meaning success.  Very odd that it wouldn't be supported in Linux, as most SDL development is done there.  I will check on other systems.  But even if it doesn't work in Linux, it still gives 0, which means I can still use a general formula to calculate the correct dimensions to use.

**Comment by sa666666** [comment]
I'm going to go ahead and commit the code for this.  If it doesn't do anything on some OS (ie, the function returns 0), then the end result is no different than what we have now.
