### ISSUE TITLE
Filter out paddles in UI

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#578]
When paddles are attached, they result into unwanted navigation events in the UI unless they are centered. These events should be filtered out.

**Comment by sa666666** [comment]
In the interests of not delaying the 6.1 release any further, I propose to just drop any axis input in `DialogContainer` if it has jitter.  That may also disallow remapping of paddle axes, but we can come back to that after 6.1, and perhaps think of a better long-term solution.

**Comment by thrust26** [comment]
This can wait for 6.2, IMO. Unless you want to tackle it before.

**Comment by sa666666** [comment]
Well, I thought it came up because of the bug reports on the R77, and that it absolutely needed to be fixed before 6.1.  If it isn't a blocker, and we can get real paddles working on the R77 right now, then I say leave this until 6.2.

**Comment by thrust26** [comment]
The bug was the missing default mapping of the paddles, because they were/are on different axis.

**Comment by sa666666** [comment]
OK, let's set it for 6.2 then.  And we can get the other issue fixed, and then do another RC to test the R77 fixes.
