### ISSUE TITLE
Close button no longer works in Windows port

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#579]
Don't know how long this has been, since I tend to use Ctrl-Q only.  The button in the UI works, as does the keyboard shortcut.  But not the X in the title bar.

**Comment by thrust26** [comment]
Hm, works for me.

**Comment by sa666666** [comment]
Sorry, this is a result of my testing in creating an invisible window 😊

**Comment by sa666666** [comment]
Too bad we couldn't fix all bugs that quickly.
