### ISSUE TITLE
"What's New?" popup

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#581]
When Stella is updated and started for the first time, a popup which briefly explains the most important changes should appear.

**Comment by sa666666** [comment]
Bumping this to 6.3, unless one of you guys wants to do it for 6.2.

**Comment by thrust26** [comment]
How do we want to do this? A simple popup with fixed text? Or something more sophisticated?

**Comment by andrew-davie** [comment]
I do not like/want this!  If I want to see what's new, then let me do it via a menu option, or RTFM.
This seems like extra programming effort for something that I already know, or can find out, from the web page.

**Comment by thrust26** [comment]
This is a **one** time popup whenever you update to a new version. Most people do not lookup the documentation, so this is our best chance to inform them about major changes.

**Comment by andrew-davie** [comment]
> This is a **one** time popup whenever you update to a new version.

Yes, I understood that.  Not for me.

**Comment by thrust26** [comment]
We can add a setting which suppresses the popup. This might become necessary during development anyway.

**Comment by andrew-davie** [comment]
Fire off a system URL load/call for the update page on first-time startup, if you really really want to do this.
That way, you aren't adding extra size to the binary, and you're not loading it with essentially one-time useless stuff.
That way, too, you can update the list/doc if you miss something.

**Comment by sa666666** [comment]
This is a good first start. I would suggest a few other things:

The info should probably be done as a StringListWidget, since sometimes the changelog is quite large.
There should be a button somewhere in the UI (perhaps in the 'About' dialog) that pops up this dialog too.

**Comment by thrust26** [comment]
IMO the what's new popup should not contain each an every change (like now), but only the most relevant ones. If the list becomes too long, the risk of missing the important changes increases. Personally I would perfer to limit the list to 5-8 points max.

I thought about that button too, but didn't know where to put it. The 'About' dialog seems like a good place.

**Comment by sa666666** [comment]
It needn't even be a button in the About dialog, but could perhaps be another 'page'.  In fact, if it was done that way, you could have co-opt'ed the `AboutDialog` to do this, and not needed a new dialog at all :smiling_imp:

**Comment by thrust26** [comment]
Yes, that was one of my ideas too. But I like it better this way. No idea why. :smile:

Also the `AboutDialog` is currently very hard to maintain.
