### ISSUE TITLE
A new storage format

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#584]
Currently we have ini and property files, which are partially hard to read and not well structured. For R77 we are using sqlite to store the information. 

The idea is to switch to a standard format (e.g. JSON or XML) and save the desktop data in sqlite instead of files too.

**Comment by thrust26** [comment]
One more idea:
The storage should support separate setting sets. So an additional column for specifying the set should be added. The user can then select what setting set he wants to use. This will allow easy switching between completely different settings very easily.

**Comment by thrust26** [comment]
@DirtyHairy What are your plans here? How much effort would this require?

**Comment by thrust26** [comment]
Brief summary of current discussion:
- we will use SQlite for  settings and „main“ properties
- use JSON for per-game properties
- think about a way to import/export to/from DB (for file exchange)
- probably use separate SQLite DB from built-in properties (allow easy update)
- anything I forgot?

**Comment by thrust26** [comment]
**stella.ini**
Starting with some details, how should we store the settings? Currently they allow key, value pairs only. This works for ~95% of the settings, but e.g. for key maps and a few other settings (e.g. 'cpurandom' and 'dbgcolors') a more structured approach seems much preferred. Also, if we want to store multiple sets of settings (e.g. one for development and one for gaming), we need more structure.

How about a table with the following columns: `Set`, `Key`, `Value`?

`Set` and `Key` are strings. `Value` would be in JSON format. So the values will allow simple strings, booleans and numbers (integer and float), but also objects and arrays. 

Another question is how we store the event mappings. Currently we use numbers only (e.g. "4:60,768" means event 4 is mapped to key 60 with modifiers 768). This is definitely not well readable for humans. It would be better to store something like "eventname", "keyname" and "modifiername[]". I found no easy way to stringify a constant name (we would have to use the preprocessor), so this would require some extra coding and increase maintenance effort too. Or we could try to work with DB views, which could translate magic numbers into better readable strings.

**Comment by DirtyHairy** [comment]
My play was to introduce another repository `ScopedKeyValueRepository` alongside the current `KeyValueRepository` in order to save "scoped" values like per game properties (scoped by ROM MD5). This would work nicely for the "plr" and "dev" settings, too.

As for key / event mappings, I was leaning to saving those JSON serialized in the DB. As an alternative, we could use a dedicated table. For the constant mappings, I would define a mapping in the code in the form 

`
Mapping mappings[] = {
   {.key = "constant1", .value = 1},
  // ...
}
`

From that, we can build a lookup map at runtime. Within DB, I'd use those constant names. I don't think we'd gain anything by moving this to DB logic.

@thrust what do you think would be an appropiate schema for saving the highscore data?

**Comment by DirtyHairy** [comment]
Concerning the JSON parser: that one is header only and looks good to me: https://github.com/nlohmann/json

**Comment by thrust26** [comment]
> @thrust what do you think would be an appropiate schema for saving the highscore data?

Do you mean the highscores themselves or the highscore definition data?

The highscores are currently saved with the following fields:
- version header (number)
- md5 of the game
- game variation (number)
- and then up to 10x
  - highscore (number)
  - special data (e.g wave) (number)
  - initials (string[3])
  - date (YY-MM-DD HH:MM)

So we probably will need two tables. One for game and variation and one for the actual scores.

1. `ScoreId` (primary key), `Version` (number), `MD5` (string), `Variation` (number)
2. `ScoreId` (foreign key), `Score` (number), `Special` (number), `Initials` (string[3]), `Date` (string or date)

**Comment by thrust26** [comment]
Done with 6.5 release.
