### ISSUE TITLE
R77 skipping frames

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#585]
Flickering sprites disappear when TV effects are enabled. It seems like the R77 is skipping frames.

**Comment by thrust26** [comment]
Looks like the frame skips have been eliminated in current uImage.

**Comment by thrust26** [comment]
@DirtyHairy Can we close this one now?

**Comment by sa666666** [comment]
I guess this is fixed.  Hopefully, since we just did the 6.1 release!
