### ISSUE TITLE
Score mode glitch emulation

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#587]
Stella is missing correct emulation for a score mode corner case.

Some info can be found [here](https://atariage.com/forums/blogs/entry/2254-matchie-and-pixel-795/). The attached ROM exhibits the problem on (some!) real hardware but not in current Stella.

[matchie1.zip](https://github.com/stella-emu/stella/files/4270058/matchie1.zip)

Note: The ROM has other problems when started from Harmony (which are understood), in this issue we concentrate on "pixel 79".

**Comment by thrust26** [comment]
@DirtyHairy Did you already have a loot at this?

**Comment by DirtyHairy** [comment]
Sorry, not yet.

**Comment by thrust26** [comment]
Current test results:
- Stephen's console (NTSC "Light Sixer", composite modded, LCD): no artifacts
- Christian's console (PAL Jr): blinking artifacts
- Thomas' console (PAL "Vader", composite modded, CRT): permanent artifacts

**Comment by thrust26** [comment]
More test results in my SIA thread at AtariAge:
https://atariage.com/forums/topic/307915-space-invaders-arcade/?do=findComment&comment=4567364
