### ISSUE TITLE
Screen (playfield) shaking with certain DPC+ ARM driver

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#589]
It seems we may have another ARM driver that should use the 'old' behaviour  (as defined in CartDPCPlus c'tor).  Relevant link is https://atariage.com/forums/topic/302951-text-adventure.

[text_adventure.bas.zip](https://github.com/stella-emu/stella/files/4293028/text_adventure.bas.zip)

I can confirm that using the old `myFractionalLowMask` in `CartDPCPlus` fixes this issue, but I want to be sure that is actually the issue, and not a bug in the code.  The same ARM driver works on Harmony, so I'm thinking it's *not* a bug in the ROM, but that we need to handle another ARM version in the c'tor.

**Comment by thrust26** [comment]
The ROM seems to work without problems on my hardware too.

**Comment by SpiceWare** [comment]
I did a preliminary investigation in this blog post:

https://atariage.com/forums/blogs/entry/16565-dpc-jitter

I plan to look into it some more to see if I can figure out which driver versions should exhibit the DPC+ jitter issue with the Fractional Data Fetchers.

**Comment by SpiceWare** [comment]
I've written a script to automate the discovery of DPC+ versions and creation of the test ROMs with each driver version.  I posted it in the comments of the above blog post.

To help find other driver versions I've put out a request on AtariAge for DPC+ game ROMs.
https://atariage.com/forums/topic/303575-need-help-with-stella-and-the-dpc-jitter-issue/

**Comment by sa666666** [comment]
Some fixes are already in, thanks to SpiceWare: 9ff00c3631e23e05317941f758eccf0e5b2acddf.

I'll leave this issue open until we take care of this for good.  I think we're pretty close now.

**Comment by sa666666** [comment]
I haven't heard anything else from @SpiceWare, so I guess we can close this one.
