### ISSUE TITLE
AtariVox comms baud rate incorrect on MacOS

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#594]
I have had failure with Stella in communicating with an AtariVox connected to my MacOS machine.
I am using a self-built "dongle" to attach the AtariVox to the USB port.
This consists of a YP-05 USB-serial converter. The only lines connected are GND, VCC (5V) and DATA.
When powering-on, I hear the bootup "AtariVox PLUS.... READY".  

When I try using "spell&speak" via stella to talk to the AtariVox, all I get are beeps and squeaks quite similar to R2D2 "talking". No words.

I put an oscilloscope on the data/GND lines and observed the signal was 0-5V, there were very clear square waves, but the width of a pulse was just over 100uS.  This suggests that the comms were actually 9600 baud (instead of 19200 baud, which would have pulses of 52uS).

Based on this measurement, I used (per RevEng suggestion) a terminal program to set the port baud rate to 19200 (after running Stella and loading the spell&speak ROM).  At that point, I was able to use the program properly - that is, the words I entered were correctly spoken by the AtariVox.

The conclusion - stella is not correctly setting the baud rate of the port, and it is still on its default 9600 baud.

**Comment by thrust26** [comment]
Do you have problems with loading and saving high scores too?

**Comment by andrew-davie** [comment]
> Do you have problems with loading and saving high scores too?

I don't know yet. I will report soon.

**Comment by DirtyHairy** [comment]
Are you using a Build generated via XCode (the releases are built this way), or are you building yourself via configure/make? The latter uses a different, generic codepath for serial I/O on UNIX, which may or may not work on MacOS.

**Comment by thrust26** [comment]
> The latter uses a different, generic codepath for serial I/O on UNIX, which may or may not work on MacOS.

Why is that so?

**Comment by andrew-davie** [comment]
> Are you using a Build generated via XCode (the releases are built this way), or are you building yourself via configure/make? The latter uses a different, generic codepath for serial I/O on UNIX, which may or may not work on MacOS.

My own build, actually. 
I will try a release version ASAP.

**Comment by DirtyHairy** [comment]
> Why is that so?

MacOS is UNIX, so you can build applications without ever touching XCode just the same way people have been doing it on UNIX for decades: compile with cc and link. I extended the configure script to support that on MacOS, too, as I find development with a terminal and make much more convenient than XCode. However, this was never meant for anything other than development, and while it sets a define to get the correct key mappings on MacOS, it uses the generic UNIX entrypoint to Stella, not the MacOS specific one.

I guess this could be refined to use the MacOS specific serial I/O implementation, but other things like the icon definitely require a XCode build.

```
pestix@bladehenge:~/git/stella$ ./configure
Running Stella configure...
Looking for C++ compiler... g++
Checking for compiler version... 11.0.0, ok
Checking hosttype... darwin19.3.0
Checking for zlib... yes
Checking for libpng... yes
Checking for SQLite... disabled

Summary:
   GUI enabled
   Sound support enabled
   Debugger support enabled
   Joystick support enabled
   Cheatcode support enabled
   PNG image support enabled
   ZIP file support enabled
   SQLite disabled
   Windowed rendering modes enabled
   Static binary disabled
   Profiling disabled
   Debug symbols disabled

Looking for sdl2-config... /usr/local/bin/sdl2-config
Creating config.mak

WARNING: plain UNIX-style builds on macOS without XCode are unsupported. Continue on your own risk...
```

**Comment by thrust26** [comment]
Makes sense. Maybe make the warning message sound more "dramatic".

**Comment by andrew-davie** [comment]
First test with official release 6.1 doesn't work at all.  Can't get aything out of AtariVox even when I try the "change baud rate manually" trick. Yes, I have configured 2nd joy to AtariVox and entered the device address.  Went back to the previous (local) version, and that's working OK (with the baud rate change manually).  Will report back.

**Comment by andrew-davie** [comment]
Can now confirm Stella 6.1 operating as expected - with AtariVox connected to YP-05 USB/serial converter on MacOS.  It's just the local (UNIX-style) build that's failing to set the baud rate correctly at startup. I guess I'm switching to the release builds...  thanks everyone for the help diagnosing.

**Comment by DirtyHairy** [comment]
> Can now confirm Stella 6.1 operating as expected 

Thanks for the feedback. I'll take a look at the different codepaths, maybe they can be unified.
