### ISSUE TITLE
Stella core does not work on Debian Buster

### ISSUE THREAD

**Issue by jstolarek** [stella-emu/stella#598]
Attempting to load a game with Stella core on Debian Buster (current stable version) results in a crash:

```
retroarch: relocation error: /dane/gry/retroarch/cores/stella_libretro.so: symbol _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev version GLIBCXX_3.4.26 not defined in file libstdc++.so.6 with link time reference
```
Debian Buster supports the following libstdc++:
```
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
```

Would it be possible to build against an earlier version or link statically against 3.4.26? Identical bug has been fixed in the Play! core with a trivial makefile modification:

https://github.com/jpd002/Play-/pull/865

**Comment by sa666666** [comment]
I will commit this conditionally for now, and see if works everywhere else.  If not, a better solution will be needed.

**Comment by jstolarek** [comment]
I can confirm that it now works. Thanks!
