### ISSUE TITLE
Special cases in player retriggering

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#6]
Andrew Towers' notes describe special cases in retriggering the play sprites that are connected to the state of the start signal decoding logic. These are currently not accounted for by the 6502ts core. More investigation is required for proper emulation.

**Comment by DirtyHairy** [comment]
This is partly fixed in 61155ac , but I am pretty sure that bugs are still lurking around, so I am going to keep this open for now.

**Comment by thrust26** [comment]
@DirtyHairy Is this still an issue?

**Comment by DirtyHairy** [comment]
The current implementation resets the decode counter if less than five clocks have passed since the decode has been triggered in order to account for the reset of the two-phase clock described by Andrew Towers. Since no bugs in retriggering have surfaced, this seems to be correct -> closing.
