### ISSUE TITLE
Feature request: ability to change font size in dialogs

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#600]
Would be useful when playing on TVs, where usually you sit farther from the screen compared to PC and laptop.

**Comment by thrust26** [comment]
TODOs:
- limit minimal launcher size based on font size
- limit minimal emulator size based on font size
- remove all magic numbers from dialogs and widgets
- add larger graphics for checkbox and radio button widgets
- adapt dialogs to varying widget sizes
- test all dialogs for all font sizes
- update documentation
- ...?

DONEs:
- enhance UIDialog
- add to font size settings

**Comment by thrust26** [comment]
Coding done, testing and doc left...

**Comment by thrust26** [comment]
Everything looks fine.
