### ISSUE TITLE
Feature request: default image in ROM info viewer, when no screenshots exist

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#601]
This is just cosmetic, but I think the launcher would look better if an image would be displayed when no screenshot is available for the current rom.
This could be a logo, or an Atari related picture, for example.

A contest where people might submit entries might be fun.

**Comment by thrust26** [comment]
@ale-79 This has been implemented now and will be part of release 6.5. Feel free to spread the word or ask people for their input. I am using this image:

![default_snapshot](https://user-images.githubusercontent.com/24360774/101341494-76342e80-3881-11eb-8a3c-a4ac2b8cae52.png)
