### ISSUE TITLE
final step in build app borked - are instructions correct?

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#608]
I finally decided to get xcode installed so that I can build stella as an app for my MacOS machine.
I followed the instructions at https://stella-emu.github.io/development.html
That worked, I have a complete build. Next, to make an app... it says run she Create_build.sh
So that's what I do....

```
boo@Andrews-MacBook-Pro macos % sudo ./Create_build.sh 'boo'
Creating Stella-boo-macos.dmg file ...
Mounting Stella-boo-macos.dmg file ...
/dev/disk2          	                               	/Volumes/Stella
Copying documentation ...
Copying application ...
cp: DerivedData/Build/Products/Release/Stella.app: No such file or directory
Updating modification times ...
Ejecting Stella-boo-macos.dmg ...
"disk2" ejected.
Removing duplicate image found on desktop ...
Compressing image, moving to Desktop ...
Preparing imaging engine…
Reading whole disk (Apple_HFSX : 0)…
..............................................................................
   (CRC32 $EEA5EF05: whole disk (Apple_HFSX : 0))
Adding resources…
..............................................................................
Elapsed Time:  55.854ms
File size: 144552 bytes, Checksum: CRC32 $61DB6D30
Sectors processed: 80000, 2793 compressed
Speed: 24.4Mbytes/sec
Savings: 99.6%
created: /Users/boo/Desktop/Stella-boo-macos.dmg
boo@Andrews-MacBook-Pro macos % 
```

Of course, this fails because there's no app at DerivedData/Build/Products/Release/Stella.app
In fact, the only place I can find it is at

```
/Users/boo/Library/Developer/Xcode/DerivedData/stella-explbirmrbmlldfdvmiwmzvpihpc/Build/Products/Debug
```

So, is this something that needs to be fixed in the instructions, in the shell script, in xcode/projecct, or on my system?  Ta for the help.

**Comment by sa666666** [comment]
You built the debug version.  Make sure to build the release version.  The 'Create_build' script has only ever been tested with release builds.  Also, you don't need to use `sudo`.

**Comment by andrew-davie** [comment]
Guessing that this might be a simple debug/release issue, I changed to a release build. Now there's a new Stella.app at /Users/boo/Library/Developer/Xcode/DerivedData/stella-explbirmrbmlldfdvmiwmzvpihpc/Build/Products/Release.  
Again, nothing like the path that is expected in the script shell.

**Comment by sa666666** [comment]
Also, technically you don't need to run the script at all; that's just used to create a DMG release that we can upload to Github.  If you can just find the `Stella.app` folder, then you have your build.  Copy it anywhere on your system after that.

**Comment by andrew-davie** [comment]
As a follow-up, if I change the path in the shell script to the absolute path to the aforementioned Release build directory I now have a working build. And thanks for the replies on this. I'm aware I don't need sudo but I was trying to figure out why I had no dmg and it's been there since. Also aware that I can copy the .app -- just thought I'd report this "issue". I'm good now, anyway. I think there's something slightly wrong with the dmg build script but anyway... moving on.

**Comment by sa666666** [comment]
There's supposed to be some setting in the Xcode project itself that instructs where to place the build files.  And it's supposed to match the path I'm using, not the one you're using.

Also, this script may not be getting much usage, since I'm the only person that does MacOS release builds from Xcode.  I suspect others are using the UNIX build, or maybe there aren't many other MacOS developers for Stella at all.

**Comment by andrew-davie** [comment]
Yes, all good. I'm new to xcode and I was just sharing my experience in case it helped.
Wasn't trying to come across as critical. Thanks for your rapid replies.

**Comment by sa666666** [comment]
Honestly, it's been so long that I set up MacOS and Stella from scratch, that I forget if I did something that's not currently documented.  I would have to create a new user, then download Stella and try it as a 'fresh' user.  Then we can see what needs to be updated in the instructions.

**Comment by andrew-davie** [comment]
I suspect it's as simple as you changed the build directory manually, because otherwise it's some randomly seeming directory name.

**Comment by DirtyHairy** [comment]
I don't know how Stephen does it, but you can just do `xcodebuild` from the command line; this will place the generated build in the `build` directory.

**Comment by andrew-davie** [comment]
Although I am now successfully able to build MacOS stella on my home machine, the one build I did try to use seemed to have a totally broken debugger, in that the disassembly stuff was completely different/unusable. I haven't checked this to confirm, as I was busy trying to fix something and have stuck with the release version ever since. But just a quick heads-up on this in case anyone has heard of it, too.

**Comment by thrust26** [comment]
Can this be closed?

**Comment by andrew-davie** [comment]
Yes, the debugger on a local build seems to be working well for me now.
There may still be config issues with xcode paths, but that can be posted as a separate issue.
Please close this issue.
