### ISSUE TITLE
Change default ROM path

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#610]
It would be very helpful if there is an easy way to change the default ROM path on-the-fly to the current dir.

**Comment by sa666666** [comment]
Hmm, I wonder if this needed a dedicated button on the UI?  This could also have been accomplished by going to the "Launcher" options in the main settings.  Is this operation done frequently enough to justify a dedicated button??

**Comment by thrust26** [comment]
During development and testing, I am saving a lot of time with. :smile:

If you don't like it, I could make it hidden by default.
