### ISSUE TITLE
Request: Keyboard focus active on debugger triggering

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#613]
It would be really nice, and save me a lot of time, if when the debugger is triggered, the keyboard focus is in the terminal/input window. Often I manually trigger the debugger (~) and then want to type something. I have to get the mouse pointer into the terminal window and select it before I can type. It's just a small thing, but would be really useful.

**Comment by thrust26** [comment]
Yes, the focus is an ongoing issue. I already tried to improve it, but the framework is not easy to handle here.

IMO most consistent would be, that the focus is where you left the debugger. This is not always the prompt.

**Comment by sa666666** [comment]
It's supposed to be the latter (focus remains on last focused item).  If that isn't the case, then it's a bug.  

Having it return to the prompt each time is easy, but that will change behaviour that other people are accustomed to.  Maybe it needs to be a setting?

**Comment by andrew-davie** [comment]
Easy test.  Hit {`}.  Debugger mode. Put focus on terminal. Type "run".  Hit {`}. Can't type.
So, it's a bug.

**Comment by sa666666** [comment]
It worked in 6.0.1, so a bug crept in for 6.1.

**Comment by thrust26** [comment]
> It worked in 6.0.1, so a bug crept in for 6.1.

No, it did not work. In 6.0.1 the focus was just always the prompt widget. And now it is always the disassembly.
