### ISSUE TITLE
Request: consistency in name for action in debugger

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#614]
In the debugger, if you want to continue, you either click the [EXIT] button, or type "run"
These would be better with the same name, I think.  I find myself typing "exit" occasionally.
My preference would be fore the "EXIT" button to be renamed [RUN]
Consistency makes a UI better. Currently these are inconsistently named, but I think they do exactly the same thing.

**Comment by thrust26** [comment]
Fully agreed. Thanks for pointing this out.
