### ISSUE TITLE
Input remapping not being saved

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#620]
There have now been several reports of remapped events not being saved between application runs.  This is a major feature, and hence a major bug that it isn't working.  It's easy to duplicate:
- start Stella, then assign 'Reset' to '1'
- play a game, noting that the mapping is working fine
- exit Stella and start again; the mapping is no longer present

**Comment by andrew-davie** [comment]
Yes, I have seen this too on MacOS.
I almost reported it yesterday but had issues with assigning to wrong control key so I wanted to make sure it wasn't something stupid I was doing.  In particular, I was also assigning to the reset key, where I tried to assign "S".  The mapping wasn't there on restart.
So, confirmed over here.

**Comment by sa666666** [comment]
OK, something is extremely borked here.  First I save the INI file as stellarc_v1.  Then I change the mapping as above, and save those settings as stellarc_v2.  Then when entering Stella again, the mapping is gone, and I save the settings as stellarc_v3.

At the end, the mapping is gone, but the INI files are different!  So stellarc_v1 and stellarc_v3 should be the same, since nothing has changed.

In fact, it's even worse.  When I start Stella and exit, the INI file is changed even if I don't change any settings!  The entries changed are always the joymap and keymap ones.  So this is a more widespread issue; config file shouldn't change when no settings have changed.  I think this may be related to using a hashtable for the entries, but if so, the hashtable should be doing the same thing on every run.  That could explain the breakage of the original issue above.

**Comment by sa666666** [comment]
Note that it isn't only 'Reset'; that was just an example.

**Comment by thrust26** [comment]
😠 This used to work. I will take care of it.

**Comment by sa666666** [comment]
Then perhaps we should consider an ordered map, if it doesn't give any worse time complexity (if it does, then I don't know what to do).  Having the INI values change even when no settings have change makes things extremely hard to debug, and also is an unexpected side effect.

**Comment by thrust26** [comment]
I am sorting the map when saving now. That doesn't affect run time.

**Comment by thrust26** [comment]
Still not fixed. 😒
