### ISSUE TITLE
Issue with adc not always being correct.

### ISSUE THREAD

**Issue by OverlordManny** [stella-emu/stella#622]
Not even sure this is a bug, it may be a user error on my end. I'm not a pro programmer, but I was playing with setting up a timer using the playfield and trying to learn about the VCS a bit. I encountered an error where it doesn't read the graphics correctly. It doesn't do this everytime and if I restart a few times it works fine.

It seems when I'm doing an adc the addition is sometimes incorrect.

Using Stella 6.1.2 the Accumulator is loaded with #$08, adding memory location $88 which is #$02 should give me #$0A, but it's giving me #$10.
![pre](https://user-images.githubusercontent.com/16061066/80525570-05807780-896c-11ea-899f-f399dcd9b915.jpg)
![post](https://user-images.githubusercontent.com/16061066/80525580-07e2d180-896c-11ea-9ce2-00dd7c953dff.jpg)

Using the same compiled code and the same emulator, it sometimes works correctly.
![pre2](https://user-images.githubusercontent.com/16061066/80525749-47a9b900-896c-11ea-9697-d83e174200c3.jpg)
![post2](https://user-images.githubusercontent.com/16061066/80525754-4a0c1300-896c-11ea-9f94-abcd933f0339.jpg)

I can escape out to the menu and reload the bin file and it has a chance of fixing itself. It doesn't require me closing Stella.

Just thought I would report it. I hope it helps you. I appreciate all of your hard work in making such a great emulator. Thank you.

I'll also attach the .bin and source for the program I was running.
[score.zip](https://github.com/stella-emu/stella/files/4547898/score.zip)

**Comment by sa666666** [comment]
I updated the above with the actual images and binaries.  When they're stored outside of Github, sometimes the website disappears and the issue then becomes very hard to read.

**Comment by OverlordManny** [comment]
I appreciate it. I'm not very familiar with github.

**Comment by thrust26** [comment]
The BCD flag is enabled is the cases where ADC seems to fail. BCD set means 6502 is in base 10 mode then, so 8 + 2 = 10.

**Comment by andrew-davie** [comment]
Yes, as Thomas says.  You need to put "CLD" at the start of your program, if you expect additions to be in binary.

**Comment by andrew-davie** [comment]
As a follow-up to this, look at the "flags" shown in the PS register in your screenshots. See that lower-case "d" when it works, and capital "D" when it doesn't?  This is showing the status of the decimal flag at that point. It should be "d" (via "cld") for binary additions/subtractions, and "D" (via "sed") for decimal additions/subtractions. If you never set or clear it, then it's in an indeterminate state when your program runs.

**Comment by OverlordManny** [comment]
Oh wow. I feel like a bonehead. sorry guys. I guess I never had to set that on my C64 because the kernal rom took care of it. Sorry for the false report.

**Comment by thrust26** [comment]
No problem.
