### ISSUE TITLE
Libretro Android build failure

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#627]
Hi there,

the Android build for Libretro is now broken.  See this log -

http://paste.libretro.com/204373

**Comment by sa666666** [comment]
Are you sure you have the latest source?  I already fixed this in another issue a few days ago.  How is the Android build being generated?

**Comment by sa666666** [comment]
Nevermind, I just found a typo in the fix I did a few days ago.  I will upload the new fix IAM.
