### ISSUE TITLE
current PC indicator in disassembly incorrect

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#632]
In stella debugger, if the code you are stepping through is not correctly disassembled, then when you step through it, stella (correctly) disassembles each line as you're stepping. But the current PC indicator is not positioned at the correctly disassembled line.  Video attached may be confusing, but basically it's showing stepping through a block of code that's not disassembled (yet). As I step, you see the instruction "popping up" correctly, and the PC counter correctly indicating where it's at. But the marker showing where the PC is... is not updated.

[debugstella.mp4.zip](https://github.com/stella-emu/stella/files/4608985/debugstella.mp4.zip)

**Comment by thrust26** [comment]
Yup, and just another symptom of #604.

Please reports your finding is this issue.
