### ISSUE TITLE
Disassembler failing on seemingly very simple cases

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#633]
I'm wondering why the disassembler is failing in this simple situation...

<img width="641" alt="Screen Shot 2020-05-11 at 11 04 04 pm" src="https://user-images.githubusercontent.com/16424075/81565257-654f3780-93dc-11ea-96fb-1db91319c281.png">

At the label "AddPiecePositionValue" we have a disassembly failure to detect a simple "cmp #128"
Here's the listing...

```
   357  4502		       c9 80		      cmp	#128	; black = CS
   358  4504		       29 0f		      and	#PIECE_MASK
   359  4506		       aa		      tax
   360  4507
   361  4507		       a9 c5		      lda	#EVAL
   362  4509		       85 3f		      sta	SET_BANK	;@3
```

Even above that, just before the 'rts' there's another simple example.
A straightforward "jsr" is not being detected as code.

Is there something with these that I'm missing? Can someone explain what's happening... thanks.

**Comment by thrust26** [comment]
That problem results from the DrawRow label. Which is most likely from another bank. And is just another symptom related to #604.
