### ISSUE TITLE
Debugger "Run to PC at current line" incorrect (?)

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#636]
I have just tried using this right-click menu option on the disassembly. It appears to be breaking in unexpected code. Could it be that "Run to PC at current line" is not keeping track of the bank it is supposed to be breaking in?

**Comment by thrust26** [comment]
That might be, because the number of instructions executed is limited by the size of the disassembly. (no clue why, probably for historical reasons).

**Comment by thrust26** [comment]
@andrew-davie I have committed a fix to master which lets the command run for much more instructions. This should help

**Comment by thrust26** [comment]
@andrew-davie Any feedback? Can we close this one?

**Comment by andrew-davie** [comment]
I am currently (and have been for a while) on branch refactor/cart
So since the fix is in master, I have not yet had a chance to test.
I'm not sure why I am on refactor/cart - something to do with the 3E+ implementation/refactor I think. Is it safe to switch over, I wonder.

**Comment by andrew-davie** [comment]
Have updated to master and confirmed this is working as expected.
TY. May be closed.  1000000 instructions **should** be enough, but that's only a few seconds worth of execution. Any reason for that particular value?

**Comment by thrust26** [comment]
It runs rather slow and you cannot interrupt. For anything lasting longer, you should use breakpoints.
