### ISSUE TITLE
Black screen with no games directory and no cart in slot

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#638]
https://github.com/DirtyHairy/r77-firmware-ng/issues/2#issue-619400781
> If the user doesn't create a /games directory, the R77 will work with physical cartridges, but instead of showing the launcher will simply generate a black screen(HDMI signal present) with the cart slot empty on the 6.1.1 firmware.

@DirtyHairy IIRC you wanted to look into this.

**Comment by sa666666** [comment]
As this is outside Stella, it's better for the environment to make sure the directory exists (ie, it should always be created when the image is created).

**Comment by thrust26** [comment]
IIRC @DirtyHairy said that he would just have to extend a script and make sure the folder exists.

**Comment by DirtyHairy** [comment]
What @thrust26 says. I want to make sure that the directory exists in the init script. It is a small change, but I have to test it, that's why I haven't done it yet. I'll try to get it  done this weekend.

**Comment by DirtyHairy** [comment]
Fixed in firmware release 6.1.2.

**Comment by thrust26** [comment]
Then we should close it. :smile:

**Comment by DirtyHairy** [comment]
Ups. My bad. Getting late, should go to bed 😏
