### ISSUE TITLE
A few suggestions about Stella

### ISSUE THREAD

**Issue by WhatDamon** [stella-emu/stella#639]
I feel that the 6.1.2 version of the game display is worse than the 6.0.2 version of the game display, in fact, I should add a selection of the game display in the options.
Of course, this content is also all translated, which may be a bit strange or not what I had in mind

**Comment by thrust26** [comment]
What in detail seems worse? What settings are you using?

**Comment by WhatDamon** [comment]
![Snipaste_2020-05-19_20-09-21](https://user-images.githubusercontent.com/59256766/82324844-e2963000-9a0c-11ea-82cb-2e6c33777ad5.png)

**Comment by WhatDamon** [comment]
The back of it also needs to be read.

**Comment by thrust26** [comment]
You have scanline emulation enabled. (Options/Video settings.../TV effects).

Disable them and you should be fine.

**Comment by thrust26** [comment]
Problem solved?
