### ISSUE TITLE
HMOVE -- behaviour?

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#641]
I have a binary where I'm trying to remove the HMOVE black bars by positioning the HMOVE on cycle 74. I am getting really strange behaviour - it looks like the incorrect HMP value is being applied, but ONLY when I push to cycle 74. When I do the HMOVE on cycle 73, all OK. On 75, all OK. But on 74, completely wrong. Is this something I don't understand about how HMOVE works, or is this a potential stella bug?

**Comment by andrew-davie** [comment]
A bit more info...  I now have a use-case where I can trigger failure (as I understand it) easily...

```
	;@57

	; this weird piece of code does a hmove shift for the INVISIBLE sprites
	; the sum of the shifts gets the player into the correct position after a whole 'band' worth

					lda TblHmpPly1,X				; 4
					sta HMP0						; 3
					lda TblHmpPly2,X				; 4
					sta HMP1						; 3
	;@71
					sta HMOVE						; 3
					sta WSYNC
```

In the above code, where I trigger the HMOVE at cycle 71 or after, I get the weird skewing of sprites. But if I swap the WSYNC and HMOVE around, all is perfect.  That is, if I move the HMOVE to cycle 3 (after WSYNC), all OK.

Two binaries attached -- _WH == wsync, then hmove, and _HW == hmove, then wsync

[soccer_HMOVE.zip](https://github.com/stella-emu/stella/files/4672751/soccer_HMOVE.zip)

I don't know this is a bug for sure. It's just something that is behaving weirdly that I don't quite understand, and according to my understanding of the code (not entirely mine) shouldn't be happening.

**Comment by andrew-davie** [comment]
Update: If I hardwire/write zero to both HMP0 and HMP1 in the code above, I *still* get skewed/shifted sprites.

**Comment by andrew-davie** [comment]
```
	;@71
		SLEEP 3
					sta HMOVE						; 3
					;sta WSYNC
```

In the above code (with the WSYNC removed), writing HMOVE on cycle 74 fails (skewed).
In fact, any write of HMOVE from cycle 71 to 74 inclusive fails.
From 75 onwards it's working as expected.


So, issues in my code...
a) doesn't matter what I put in HMP0 and HMP1 if...
b) HMOVE write occurs from cycle 71 to 74

**Comment by andrew-davie** [comment]
... even if I write to HMCLR just before writing HMOVE... I still get skewed sprites !! Unless I push that HMOVE to cycle 75 or later.

**Comment by andrew-davie** [comment]
A possible alternate issue...  I get different behaviour of HMOVE depending on the order in which I write to HMP0/1 and NUSIZ0/1. Is this correct behaviour?  Is the HMP offset "calculated" at the time HMOVE is triggered, or when HMPx is actually written? I would have assumed the former.
Maybe I'm not understanding how this is all supposed to work. Likely.

**Comment by andrew-davie** [comment]
I managed to get my hardware out of storage and tested.
It appears that stella and hardware are behaving the same, so this is not a stella issue AFAIK
Issue can be closed. Still, would love to understand what's actually happening!

**Comment by andrew-davie** [comment]
... and perhaps this is the issue...

"If you are wondering cycle 73 or 74 hmoves hide the black "comb" lines on in an Atari game. The consequence of using cycle 73 or 74 hmoves is that you can only fine position the object leftward."

My binary does rightwards-positioning. So, that's probably that!
I may be able to change it to leftwards-positioning - we shall see.

**Comment by ale-79** [comment]
> "If you are wondering cycle 73 or 74 hmoves hide the black "comb" lines on in an Atari game. The consequence of using cycle 73 or 74 hmoves is that you can only fine position the object leftward."

Technically the fine motion is always 0-15 pixels to the left, but as stated in Andrew Tower's "TIA hardware notes", bit D7 of the HMxx registers is wired in reverse "purely for the convenience of the programmer".

When you hit HMOVE as intended at the beginning of HBLANK, the HBLANK period is extended by 8 pixels and since the position counters are only running in the visible part of the scanline, the effect is that all moveable objects are shifted 8 pixels to the right.

So the resulting movement is the sum of these two: 0-15 pixels to the left (HMxx value) plus 8 pixels to the right (HMOVE bar).
If you remove the HMOVE bars, you don't have that right shift anymore, so you can only fine positioning 0-15 pixels to the left.

**Comment by DirtyHairy** [comment]
I like the resolution of  this issue 😛 As for the explanation: what @ale-79 says. A late HMOVE hits the register just in time to get the full 15 movement clocks during hblank, but early enough to have the "extended hblank" latch reset before movement starts --- you end up with up to 15 pixels of movememt to the left and no HMOVE bar.

As to when HMxy are evaluated: before each movement clock, a counter is compared to the value of the register (mind the inverted bit 4). If the value stops, the sprite stops receiving extra clocks until HMOVE is triggered the next time. This is also how the starfield trick works: the register is reset to a value that is lower than the current HMOVE counter, and the stop condition cannot be reached anymore.
