### ISSUE TITLE
Add TV Boy bankswitching

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#642]
The TV boy contains a menu, which lets the user select the game. Therefore it acts differently like other multi carts were the game is selected by reloading the ROMs in Stella.

**Comment by sa666666** [comment]
Do you have a ROM for this?

**Comment by thrust26** [comment]
Yup. I will upload to the test folder soon.

**Comment by thrust26** [comment]
BTW: The ROMs are 99% identical, only one game (91) has been replaced.

**Comment by thrust26** [comment]
Done with 4366244
