### ISSUE TITLE
Add mode for pixel-perfect snapshots

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#643]
This is in reference to https://atariage.com/forums/topic/304230-stella-61-released/?do=findComment&comment=4527111.

The idea is to extend '1x snapshot mode' to not be strictly 1x, but to instead do pixel-exact snapshots at whatever (integer) zoom level you want.  So the option is essentially ignoring post-processing filters, and getting the data directly from the TIA framebuffer.

**Comment by thrust26** [comment]
Probably we need another zoom slider there. I suppose only non-fractional values, right? So 1x, 2x, 3x etc. Also the wording of the current checkbox should be changed.

**Comment by sa666666** [comment]
Yes, there will need to be a slider.  I haven't worked out how it should look yet; need to find some time to work on it.

**Comment by sa666666** [comment]
I don't think I'll bother with a slider.  The current code/UI takes a snapshot at whatever the current zoom level is.  I will do the same for pixel-perfect mode, except use integer scaling only.  It doesn't make sense to have a zoom level for rendering the TIA image _and_ one in the snapshot dialog for generating snapshots.

**Comment by sa666666** [comment]
I guess "Ignore scaling (1x mode)" can change to "Create pixel-perfect images (integer scaling)".

What do you think of this text?

**Comment by thrust26** [comment]
It also ignores TV effects, right?

Are the images really pixel perfect? So each pixel has the same size?

**Comment by sa666666** [comment]
Here is what it will do; we can decide how to word it:
- no scanlines
- no Blargg effects
- no phosphor (still considering this one though)
- only integer zoom levels, based on current TIA zoom level (so if the current zoom is '4.5', it will use '4')

Basically, it will look at the TIA framebuffer instead of `TIASurface` for the data.  So yes, the pixels will all be the same size.  An NTSC image will be ~320x220, and PAL will be ~320x250.  It will do exactly what '1x' mode is doing now, except scale to integer zoom levels.

As for how to create a 1x image without a slider, I will be removing that functionality.  The snapshot will be created with the (integer) size of whatever zoom level is in effect.  So if 2x is the smallest you can have, then the snapshots will always be at least 2x.

**Comment by sa666666** [comment]
An even better explanation.  Look at the differences in output for NTSC vs. PAL in the debugger.  And then add the current zoom level to it.  _That's_ what the new feature will do.

**Comment by thrust26** [comment]
"Disable image post-processing"?

**Comment by sa666666** [comment]
I'll try to get to this over the weekend.  If it takes too long, I will bump it to 6.3.

**Comment by sa666666** [comment]
Bumping this to 6.3, as there's other considerations, and I don't have the time to think about it right now.

**Comment by sa666666** [comment]
That mode is already there, so I decided not to do anything further on this (other than modify the UI text to clearly indicate the functionality.  So this is now done.

**Comment by ale-79** [comment]
Following the last few posts in the AA thread, I tested the 1x screenshots, and it seems that if you have the TV effects enabled, there's some scaling occurring in the horizontal direction, which makes them not "pixel perfect" anymore.

with TV effect:
![Keystone Kapers (1983) (Activision)_1](https://user-images.githubusercontent.com/24704739/84860596-9d970500-b06f-11ea-8c4a-42429747f374.png)
detail:
![Keystone Kapers (1983) (Activision)_1_detail](https://user-images.githubusercontent.com/24704739/84860832-1302d580-b070-11ea-9149-615b56830b25.png)



and without:
![Keystone Kapers (1983) (Activision)_2](https://user-images.githubusercontent.com/24704739/84860618-a7206d00-b06f-11ea-9415-975741c7a68c.png)
![Keystone Kapers (1983) (Activision)_2_detail](https://user-images.githubusercontent.com/24704739/84860848-18f8b680-b070-11ea-9e0b-ed1fede20536.png)

**Comment by thrust26** [comment]
Definitely looks like TV effects are still enabled for 1x mode.

**Comment by sa666666** [comment]
OK, I'll look into it.
