### ISSUE TITLE
3E+ debugger UI not allowing RAM bank selection

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#645]
<img width="642" alt="Screen Shot 2020-05-26 at 10 23 28 pm" src="https://user-images.githubusercontent.com/16424075/82900287-a2502800-9f9f-11ea-8a84-8b6ddcfb47a0.png">

It appears that the debugger UI for 3E+ debugging does not allow correct RAM bank selection.
In particular, with a 24K ROM, the RAM bank # is limited to 0-23.  This is incorrect - in fact RAM bank selection should (I think) be allowed to be any value from 0-63. The RAM bank size is completely unrelated to the ROM bank size.
ROM banks are correctly limited to ROM bank size as a maximum

**Comment by thrust26** [comment]
@andrew-davie Do you have a test ROM?

**Comment by andrew-davie** [comment]
Yep. Load this ROM. It will black-screen or crash. That's OK.
Now go to the debugger, and try to switch a RAM bank in (say) slot 1 to something.
That is, set segment 1 to "RAM" (from ROM), and then choose the bank from the left.
You'll see that the avaialble RAM banks in the selection list are limited to the ROM size, not 0-63.
[test.bin.zip](https://github.com/stella-emu/stella/files/4682320/test.bin.zip)

**Comment by thrust26** [comment]
@andrew-davie Fixed, please test and give feedback.

**Comment by andrew-davie** [comment]
Works, but not quite what I expected.
Now, it allows 0-63 regardless of ROM size.
This means that if you load a 32K ROM, it actually lets you select bank 40 (for example) of that 32K ROM. Which, of course, is fairly meaningless.
In the prior version, it limited ROM to the available banks based on ROM size, and RAM to 0-63.
I think limiting ROM to the available ROM size is a good thing.

**Comment by thrust26** [comment]
It allows you to select e.g. bank 63, but as long as ROM is selected you cannot commit anymore.

If I limit the ROM list and you want to switch from ROM to large RAM bank, you have to go left to right: first switch to RAM and then change the bank. The current logic avoids that.

**Comment by andrew-davie** [comment]
Understood and already doing that (right to left, actually).
But I'm OK with what's there now, TY for the quick fix.

**Comment by thrust26** [comment]
Now I wonder if I should change the UI order. :smile:
