### ISSUE TITLE
3E+ incorrect ROM size detection

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#646]
Regardless of the sense in having odd ROM sizes, the 3E+ code currently incorrectly determines the number of banks in an odd-sized ROM.  Rather than dividing by 1024 and rounding UP, it appears to simply truncate. This means that the last bank in an odd-size ROM is inaccessible.
For example, in a ROM of size 24577 bytes, stella/debugger reports 24K ROM, when in fact there are 25 banks.  24577/1024 = 24.8798828125
I don't particularly want to argue the merits of having odd sized ROMs. I'm just interested in having stella handle the #bank calculation in a better way.

**Comment by thrust26** [comment]
I don't think odd sized ROMs are legit for the 2600. All other bankswitching types do not support them and I don't want to change that. 

What in the description of 3E+ makes you think that such sizes are supported? I will fix that in the description then.

**Comment by thrust26** [comment]
@andrew-davie Anything to add?

**Comment by andrew-davie** [comment]
I understand what you are saying, and that rounding up bank size calculation instead of truncating is not what you want to do. I think it's a shame because a simple change would increase functionality. But as I said... didn't want to get into an argument about rom sizes and reasons thereof. So, might as well close this issue.

**Comment by thrust26** [comment]
The change would be simple yes. But I don't even want to imagine what would break when we try to emulate or debug incomplete banks.
