### ISSUE TITLE
GHOST demo

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#65]
[GHOST.zip](https://github.com/DirtyHairy/stella/files/672020/GHOST.zip)

In the new core, there is garbage on the screen until the text draws over it and clears it again.  I suspect this is related to 'large' frames (as described in the old core; lines 610-640), whereby large scanline counts require the screen to be blanked, erasing any garbage left from the previous one.  Almost definitely related to https://github.com/DirtyHairy/stella/issues/37.

**Comment by DirtyHairy** [comment]
Fixed in a83e7eb . What happened was:

 * The demo terminates frames early by hitting VSYNC, leading to small frames that vary in height
 * Rendering terminates early, and, if the frame is smaller than the last, garbage will remain at the bottom

Above commit fixes this by blanking out those lines.
