### ISSUE TITLE
Change "re-disassemble" into "disassemble from current line"

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#652]
In the attached screen grab movie you can see me stepping through non-disassembled code.
I menu-select "re-disassemble" but it appears to have no function.
In fact, I don't think I've ever seen this menu option work.

[dis.mp4.zip](https://github.com/stella-emu/stella/files/4736483/dis.mp4.zip)

**Comment by thrust26** [comment]
The function does not work the way you are expecting it. It simply disassembles the current bank. 

If you want to disassemble a certain range, then you have to use the prompt ("disasm <addr>, <lines>").

Maybe it would make sense to add another option to the context menu, which disassembles from the current line.

**Comment by andrew-davie** [comment]
Perhaps the debugger could be changed to automatically disassemble the from current line *always*.  That is, every time you step, it disassembles. This would solve a lot of the non-disassembled areas (of previously unreached code, I assume) which seem to happen fairly often.

**Comment by thrust26** [comment]
Maybe. I never used the function as it is now. Did you?

**Comment by andrew-davie** [comment]
> Maybe. I never used the function as it is now. Did you?

I often **try** to get it to work, as I hate stepping through code that only disassembles once it's executed the line I'm looking at.  That is, I have a "non-disassembly" section which is actually valid code. I can't see what I'm looking at, basically, until I step. And then it shows me what it has just done. That's why I was trying to trigger "re-disassemble".
