### ISSUE TITLE
More ROMs causing crashes

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#654]
The attached ZIP file contains ROMs that cause Stella to crash.  The first one is an irregular size, so that may be part of it.  The others though are valid ROMs AFAICT, and they worked before the cart refactoring.

[crash_roms.zip](https://github.com/stella-emu/stella/files/4741122/crash_roms.zip)

**Comment by sa666666** [comment]
Some more info:
- Dark Mage Mod (AKA DM-FOOT) (PD).a26:  autodetects as 4K even though it's less than 4K in size.  This is potentially a bug in the 4K class, which should fill the remainder of the address space with 0's.
- megaboyEF.bin and megaboy_x07.bin:  same issue as the last reports of ROM crashes; attempting to do 'mod 0' since the bankcount was returning 0.
- boulderdash ROMs:  seems to be a problem creating the debugger; I haven't traced any further, but it's possibly related to the 3E reworking, since other 3E ROMs have stopped working too.

**Comment by andrew-davie** [comment]
> This is potentially a bug in the 4K class, which should fill the remainder of the address space with 0’s.
I agree — this is what I think all classes should do for ROMs which are not a “valid” size.

**Comment by thrust26** [comment]
The Megaboy and BoulderDash ROMs are working again. The problem was a wrong cast in the last fix. 😒 

As for Dark Mage I am not 100% sure how to fix its problem. The code evolves around `mySize` which is the actual ROM size. Should I only allocate more memory and keep `mySize` or should I fix `mySize` too? 

The bigger problem is that the ROMs memory is allocated in the default constructor and the ROM is copied there too. The bankswitching related calculations can only come afterwards. So when the ROM size is wrong, we cannot allocate it correctly initially. We would have to check later (`install`) and reallocate the memory there. This seems ugly, but I have no good idea how to to do that any better. At least no without some major refactoring.

@sa666666 What would you suggest here?

**Comment by sa666666** [comment]
I will look into the Dark Mage ROM issue in a moment ...

**Comment by sa666666** [comment]
OK, I just looked at the code, and _OOPs_, that's going to be a problem.  Due to the way the code is refactored, `mySize` is used through the class.  In the old code, the only time that variable was ever needed was (1) in the c'tor for initializing the buffer, and (2) in `getImage` method (that was only ever called when one wanted to save the ROM image back to disk).

So that unfortunately means that the problem is quite low-level as you say, since the variable now has a much wider scope than it was originally designed for.  It was never meant to be used in calculating stuff in the scheme (for the most part).  In fact, you can see that there are bugs in other classes too.  In `Cart2K`, the base c'tor takes the size and creates the buffer, but in the 2K c'tor, it changes the size __after the other c'tor has already created the buffer__!

Really, this is a problem of having one variable serving two purposes, and sometimes those two don't mean the same thing.  But the good news is the issue is happening at the interface between `CartXXX` c'tor and `CartEnhanced` c'tor, so that means the fix can happen there, and we don't need to change code anywhere else.

I think the easiest way to fix it is to pass some extra info to `CartEnhanced` c'tor that does the error checking, sets the correct ROM size, fills the extra (if any) with 0's, etc.  Each derived cart class knows these bounds for itself, so they simply pass them to `CartEnhanced` c'tor during its own initialization.

In any event, I think we have to bump the release from today :smiling_imp:

**Comment by thrust26** [comment]
Yes, the 2K class is already basically doing the ugly fix I described above. Which is not very nice.

**Comment by sa666666** [comment]
I don't understand how the fix is 'ugly'.  Or do you mean the reallocation part?  If so, then that's easy to fix in my proposed solution; all that logic moves into `CartEnhanced`.  And it will also take care of ROMs that are illegal size.  Basically, each c'tor will now pass two sizes: the current one (the actual ROM size), and the desired one (based on the class that is calling the base c'tor).  So for example, fixing the 4K class would simply change the code from this:
```
Cartridge4K::Cartridge4K(const ByteBuffer& image, size_t size,
                         const string& md5, const Settings& settings)
  : CartridgeEnhanced(image, size, md5, settings)
{
}
```
to this:
```
Cartridge4K::Cartridge4K(const ByteBuffer& image, size_t size,
                         const string& md5, const Settings& settings)
  : CartridgeEnhanced(image, size, 4_KB, md5, settings)
{
}
```
Note the `4_KB` in the second block of code.  It's a hint to `CartEnhanced` to use this size if the actual ROM size doesn't match it.

**Comment by thrust26** [comment]
Your suggestions works well with types with fixed sizes. But how about e.g. 3E? If e.g. a ROM with 30,000 bytes is loaded, this would be 14.something banks. So the code would have to roundup to 15 banks (30,720 bytes). Wouldn't it make sense to do these calculations in `CartEnhanced` too? 

Or how about storing the image and size only temporarily and allocate the correct size later on in `install`?

**Comment by sa666666** [comment]
My plan was to round up to the next power of two in that case.  So 30000 becomes 32_KB.

As for storing the image temporarily, it's passed in as a reference, and there's no guarantee that the reference exists later when `install` is called.  We would need to change to pointers for that, and that is much more work.  The way I'm suggesting is the least amount of work.

**Comment by andrew-davie** [comment]
> Your suggestions works well with types with fixed sizes. But how about e.g. 3E? If e.g. a ROM with 30,000 bytes is loaded, this would be 14.something banks. So the code would have to roundup to 15 banks (30,720 bytes). Wouldn't it make sense to do these calculations in `CartEnhanced` too?

In this case, it's an invalid ROM, because there would be no valid reset vectors (which are fetched from FFC or thereabouts in the last bank.  Perhaps you meant 3E+ (which has the reset vector in bank 0)?

**Comment by thrust26** [comment]
The next power of two will not work well for complex classes whose size is not a power of two.

@andrew-davie Yup, 3E+ would be a valid example.

**Comment by sa666666** [comment]
TBH, I'm more concerned that Stella doesn't crash when passed 'illegal' ROMs.  If it doesn't work as expected, well, the ROM was garbage to begin with anyway.  And then we follow the _garbage-in, garbage-out_ rule.

It's not Stella's job to try to figure out how an invalid ROM should work.  We're dealing with error cases here, so my main goal is for Stella not to crash.  If you want the ROM to work correctly, then create it correctly from DASM :smiling_imp:

**Comment by andrew-davie** [comment]
> The next power of two will not work well for complex classes whose size is not a power of two.



> TBH, I'm more concerned that Stella doesn't crash when passed 'illegal' ROMs. If it doesn't work as expected, well, the ROM was garbage to begin with anyway. And then we follow the _garbage-in, garbage-out_ rule.
> 
> It's not Stella's job to try to figure out how an invalid ROM should work. We're dealing with error cases here, so my main goal is for Stella not to crash. If you want the ROM to work correctly, then create it correctly from DASM 😈

If that was directed at me, I think you misunderstood what I was saying. I was saying that Thomas's example was an incorrect one. A 30000 byte 3E ROM can't ever work, full stop.

**Comment by sa666666** [comment]
No, it wasn't directed at anyone.  I'm simply saying that when a ROM is invalid (however we define 'invalid'), then by definition we are into _undefined behaviour_.  At that point, how do we recover?  My suggestion is that I don't want Stella to just crash.  But if the resulting ROM doesn't run correctly, then I say "How can we know what correct means; the ROM is already incorrect?".

I guess my overall position is if a ROM is invalid, I care more about Stella not crashing than about trying to figure out what _should_ have happened with the ROM.  The only way to conclusively fix the latter is to pass a valid ROM to Stella.

**Comment by sa666666** [comment]
Again, this is not directed, or a 'dig' at anyone.  Just an analysis that I think Stella should never crash on invalid data.  And in the end, the only way to get desired behaviour is to pass in valid data (aka, fix the ROM).

**Comment by andrew-davie** [comment]
I agree with all of that :)

**Comment by thrust26** [comment]
> As for storing the image temporarily, it's passed in as a reference, and there's no guarantee that the reference exists later when install is called. We would need to change to pointers for that, and that is much more work. The way I'm suggesting is the least amount of work.

My idea was to copy the image temporarily. And later on create a new buffer with the correct size which will be filled with the temporary copy.

**Comment by sa666666** [comment]
> My idea was to copy the image temporarily. And later on create a new buffer with the correct size which will be filled with the temporary copy.

Well, that's no different than creating it in one c'tor, then fixing it up later in another c'tor.  In both cases, we do allocations twice, some copies, etc.

My approach is doing almost exactly what you suggest, but instead of leaving it for `install`, it's doing it in `CartEnhanced` c'tor.  And we would still need to somehow pass in the 'size' hint from the derived classes, so we gain nothing from doing it later.

I think we're on the same page, just not agreeing with _where_ to do the work.

**Comment by thrust26** [comment]
I still don't understand how your idea would work for types with odd sizes? E.g. a 28K ROM. 

Would you always allocate 32K? Further on, what would be the size of the ROM which is used in calculations?

**Comment by sa666666** [comment]
OK, before we proceed, I think we need to agree on what our goals are.  That will then lead us to the correct direction for coding.  Here is my approach:
- I don't want Stella to crash (ABOVE ALL ELSE)
- If a ROM is not the correct size, then we are already in an error state
- In dealing with the error state, we make sure the buffers are of sufficient size that we don't get a crash

Now, in doing the above, perhaps we get a ROM that doesn't behave as we expect.  But I say that the ROM was in error in the first place, so how can we possibly know what is best.  We try to do as much as possible, but if the ROM is illegal, then we must potentially expect undefined behaviour.

**Comment by thrust26** [comment]
All fine by me.

**Comment by andrew-davie** [comment]
> * If a ROM is not the correct size, then we are already in an error state

I don't necessarily agree with this. It depends on what your definition of "correct" is.
If you define it as being able to fit onto a "standard" ROM chip, and it's an odd-size that doesn't match any ROM chip, fine. But why should available ROM chip sizes (typically multiples of powers-of-two) define "correct" as far as Stella goes? Some hobbyist might decide to make a homebrew core memory plane to put a '2600 ROM in, and then plug it into a '2600.  What's the "correct" ROM size then?  There's no reason, in my book, why a ROM can't be any size that actually runs on a '2600 - regardless of the type of hardware used to contain it.

So saying, "correct" size for me is really only a way of saying that the binary should never access a ROM address outside the binary itself.  One would expect any ROM which accesses non-existent memory to be "incorrect", and of course that can't really be determined in advance.

So saying, for me the only issue is making sure Stella doesn't crash if/when such an "illegal" ROM does access bad ROM space. And that comes down to "hardening" the access rotuines in Stella so that **regardless of the ROM size**, Stella's lookup/access classes are not making assumptions about size.

I'm not trying to be too pedantic here, but just take a step back for a minute. The issue to me isn't anything to do with the odd sizes, but is in fact related to calculations of bank count (which were, AFIK, truncated instead of rounded-up), and perhaps - at a guess - access to addresses in the allocated buffer which are beyond the size of the ROM/binary itself.  The proposed solution (allocate a bigger buffer) is really just a bypass of these assumptions to get it to work.

But I don't really have the headache of implementing this stuff, I acknowledge, and I guess I don't really mind which way it ends up - and that includes just saying "non-multiple-of-powers-of-two" ROMs are illegal and unsupported. But for me, that would break the "contract" that I understand Stella is offering - and that is, if it runs on a '2600, it will run the same on 'Stella.

**Comment by sa666666** [comment]
In the code I'm about to commit, the following is done (rough explanation, see the code for more details):
- If a ROM is smaller than the page size (64 bytes), round up to the closest power-of-2, then mirror within the 2K address space.  This is for the so-called 'Sub2K' ROMs.
- If a ROM is larger than what the bankswitch scheme supports, truncate/cap back to that size.  So for example, the recently released Pink Panther ROM was 8195 bytes.  The scheme supports 8192 bytes, so that's the size that's created, and the remaining 3 bytes are dropped.
- If a ROM is smaller than what the bankswitch scheme supports, then create buffer that is the next power-of-2 larger.  So in the previous crash report, we had a ROM that was 4094 bytes and detected as 4K.  We create a buffer of size 4096 and copy into it, aligned with the start of the buffer.
- If a ROM has variable size (3F, 3E, etc), simply use the next power-of-2 as the cap.  So if the ROM is 32K, use 32K as the cap.  If it's 33KB, use 64K as the cap.
- In all cases, the ROM buffer is initially filled with 0's, so that after copying, if there are 'holes' in the address space, they will reference 0.  This could be changed to $02 (to crash emulation), or whatever else we want.

This fixes all the bug reports, and also fixes any more going forward I think.

As for new ROM schemes that have differing sizes (not yet defined), we can deal with that as we develop the new bankswitching classes to support that scheme.

**Comment by sa666666** [comment]
I'll also add that in no case are we popping up a message saying "This ROM is invalid and won't run in Stella".  We will load it into the ROM buffer and attempt to run it, but how it runs will be dependent upon how the particular bankswitching scheme handles accesses that are outside what it expects.  But at least Stella will never crash in such a case anymore.

I will also log a message when some of these situations happen.  But Stella will still run and try to do its best with what it was given.
