### ISSUE TITLE
compiling version 6.2

### ISSUE THREAD

**Issue by JetSetIlly** [stella-emu/stella#655]
Have the compiler requirements changed? 6.2 does not compile after a successful configuration step. Full result of "./configure && make"

Running Stella configure...
Looking for C++ compiler... g++
Checking for compiler version... 6.3.0, ok
Checking hosttype... linux-gnu
Checking for zlib... yes
Checking for libpng... yes
Checking for SQLite... disabled

Summary:
   GUI enabled
   Sound support enabled
   Debugger support enabled
   Joystick support enabled
   Cheatcode support enabled
   PNG image support enabled
   ZIP file support enabled
   SQLite disabled
   Windowed rendering modes enabled
   Static binary disabled
   Profiling disabled
   Debug symbols disabled

Looking for sdl2-config... /usr/local/bin/sdl2-config
Creating config.mak
mkdir -p -p src/gui/.deps
mkdir -p -p out/src/gui
g++ -MMD -MF "src/gui/.deps/CommandDialog.d" -MQ "out/src/gui/CommandDialog.o" -MP -O2 -x c++ -Wall -Wextra -Wno-unused-parameter -Wno-multichar -Wunused -fno-rtti -Woverloaded-virtual -Wnon-virtual-dtor -std=c++14 -fomit-frame-pointer -DSDL_SUPPORT -D_GLIBCXX_USE_CXX11_ABI=1 -DUNIX -DBSPF_UNIX -DGUI_SUPPORT -DWINDOWED_SUPPORT -DSOUND_SUPPORT -DDEBUGGER_SUPPORT -DJOYSTICK_SUPPORT -DCHEATCODE_SUPPORT -DPNG_SUPPORT -DZIP_SUPPORT  -Isrc/emucore -Isrc/common -Isrc/common/tv_filters -Isrc/emucore/tia -Isrc/emucore/tia/frame-manager -I/usr/local/include/SDL2 -D_REENTRANT -Isrc/unix -Isrc/gui -Isrc/debugger -Isrc/debugger/gui -Isrc/yacc -Isrc/cheat -c src/gui/CommandDialog.cxx -o out/src/gui/CommandDialog.o
In file included from src/gui/CommandDialog.cxx:19:0:
src/common/PaletteHandler.hxx:128:21: error: enclosing class of constexpr non-static member function ‘float PaletteHandler::scaleFrom100(float) const’ is not a literal type
     constexpr float scaleFrom100(float x) const { return (x / 50.F) - 1.F; }
                     ^~~~~~~~~~~~
src/common/PaletteHandler.hxx:26:7: note: ‘PaletteHandler’ is not literal because:
 class PaletteHandler
       ^~~~~~~~~~~~~~
src/common/PaletteHandler.hxx:26:7: note:   ‘PaletteHandler’ has a non-trivial destructor
src/common/PaletteHandler.hxx:129:22: error: enclosing class of constexpr non-static member function ‘uInt32 PaletteHandler::scaleTo100(float) const’ is not a literal type
     constexpr uInt32 scaleTo100(float x) const { return uInt32(50 * (x + 1.F)); }
                      ^~~~~~~~~~
Makefile:250: recipe for target 'out/src/gui/CommandDialog.o' failed
make: *** [out/src/gui/CommandDialog.o] Error 1
steve@ezquerra:~/Source/2600/Tools/Stella/stella-6.2$ g++
g++: fatal error: no input files
compilation terminated.

**Comment by sa666666** [comment]
The lowest version I have on all my systems is GCC7.  And it compiles fine there.  I can try to install GCC6, but we may have to bump the required version if the changes are too invasive.

**Comment by sa666666** [comment]
OK, found the issue.  Here is a quick fix.  In `src/common/PaletteHandler.hxx`, change lines 128-129 to this:
```
    static constexpr float scaleFrom100(float x) { return (x / 50.F) - 1.F; }
    static constexpr uInt32 scaleTo100(float x)  { return uInt32(50 * (x + 1.F)); }
```
Note that we're moving to C++17 over the next release or two (which requires g++7), so I think we will just have to bump the minimum compiler requirements.

**Comment by sa666666** [comment]
I will consider fixing this for a 6.2.1 release, but over the next 6 months we're probably going to bump the required gcc version anyway.
