### ISSUE TITLE
3E+ reset comment/operation

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#662]
Referring to the 3E+ spec in Cart3EPlus.hxx...

```
The system requires the reset vectors to be valid on a reset, so either the
  hardware first switches in the first bank, or the programmer must ensure
  that the reset vector is present in ALL ROM banks which might be switched
  into the last bank area.  Currently the latter (programmer onus) is required,
  but it would be nice for the cartridge hardware to auto-switch on reset.
```

Since Stella's implementation specifically hardwires bank 0 to slot/segment 3, then the above does not seem to be applicable. There will ALWAYS be reset vectors present, and in fact the comment is totally wrong - it is the hardware (=Stella 3E+ implementation) which ALWAYS switches in BANK 0 on a reset.

I think the comment should be changed, as it's a neater implementation having the hardware init with bank 0--> slot 3.

A note about naming: I prefer to use the term "SLOT" because "SEGMENT" can be confused with the dasm SEGMENT pseudo-op and lead to confusion.

**Comment by thrust26** [comment]
> I think the comment should be changed, as it's a neater implementation having the hardware init with bank 0--> slot 3.

Will do.

> A note about naming: I prefer to use the term "SLOT" because "SEGMENT" can be confused with the dasm SEGMENT pseudo-op and lead to confusion.

The naming is taken from Kevin Horton's bankswitching documentation. Previously we had this naming all mixed (banks were called slot or segments and vice versa). So when refactoring I went through all files and made sure that the naming is consistent for 6.2 and aligned to Kevtris' documentation.
