### ISSUE TITLE
CartEnhanced::getBank() crashing sometimes

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#663]
It seems there's still some issues with `getBank` returning the wrong values sometimes.  In some cases this leads to a crash, perhaps since the index is out of range of the array inside that method.  Here's how to duplicate it:

- Open Stella to `test/roms/bankswitching/Sub2K`
- From the ROM launcher, select 'Debugger' from Power-on options
- Start a few ROMs at random; after 6 or 7 you will get a crash.

The problem started on commit https://github.com/stella-emu/stella/commit/5b634b99e7301ee53b2c5883dd599d63281be737 (when we reverted the odd sized ROM handling).

Here's a patch that selectively re-enables the commit, but also compares the results from 'crash' code and 'working' code.  If these values differ, then the error is output to the screen.
[crash.zip](https://github.com/stella-emu/stella/files/4767529/crash.zip)

Here's a sample output:
```
ERROR (bank)! crash: 1, working: 0
 ... repeated many times
ERROR (bank)! crash: 39, working: 0
 ... repeated many times
ERROR (bank)! crash: 15, working: 0
 ... repeated many times
ERROR (bank)! crash: 7, working: 0
 ... repeated many times
ERROR (bank)! crash: 3, working: 0
 ... repeated many times
ERROR (bank)! crash: 7, working: 0
 ... repeated many times
ERROR (bank)! crash: 15, working: 0
 ... repeated many times
ERROR (bank)! crash: 1, working: 0
 ... repeated many times
ERROR (bank)! crash: 39, working: 0
 ... repeated many times
ERROR (bank)! crash: 15, working: 0
-> seg fault
```
So a few things to note:
- We seem to have `romBankCount()` fixed; it never gives an error.  This makes sense, since we're now making sure that `mySize` and `myBankShift` are correct in all cases.
- The 'fix-up' code from the original commit does take care of the problem.  But I wonder if we can't deal with it by fixing the cause, and not simply treating the symptom.

@thrust26, please help me with this one, since you're more familiar with this part of the code.

**Comment by thrust26** [comment]
The root cause of the problem are ROMs < 4K which address above `0xF000` + `mySize`. Here the current codes assumes that ROM is segmented. But the fix is easy.
