### ISSUE TITLE
INPTx bit 6 incorrect

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#664]
The TIA always drives bit 7 and 6, and their value is 0 if unused by the register that is being addressed:

[https://atariage.com/forums/blogs/entry/4184-take-4/?do=findComment&comment=8586](https://atariage.com/forums/blogs/entry/4184-take-4/?do=findComment&comment=8586)

[https://atariage.com/forums/topic/182642-anomaly-in-conquest-of-mars/?do=findComment&comment=2293320](https://atariage.com/forums/topic/182642-anomaly-in-conquest-of-mars/?do=findComment&comment=2293320)

Stella doesn't emulate this correctly for the INPTx registers, where bit 6 takes the last value that was on the bus (or it's randomized if the "tiadriven" option is set). 
Bit 6 of INPTx must be 0 in both cases.

Moreover, the "tiadriven" option only randomizes bits if their last value on the bus was 0. 
With the option enabled, bits 0-5 should always be random, no matter what was on the bus.

Test rom:
[tiadriven_test.zip](https://github.com/stella-emu/stella/files/4771564/tiadriven_test.zip)

It displays the 16 TIA read registers as binary values. The last value on the bus before reading the registers alternates between $00 and $ff.
Try it with and without "tiadriven" to see the issues.

**Comment by sa666666** [comment]
@ale-79, please test this fix when you have time.  I think the code structure/comments now also clearly indicate what's going on.

**Comment by ale-79** [comment]
I just compiled and tested the current master build.
It's working as expected now.
:+1:
