### ISSUE TITLE
Option to disable aspect ratio correction

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#669]
There's been enough of a response on AtariAge to the 'pixel-exact' problem, that maybe we should consider a mode that turns off aspect ratio correction, and allows Stella to work as it did in the past.  Note that this would be inaccurate and off by default.  But there seems to be some corner cases that need it.

I propose adding a mode where there is no non-integer scaling vertically for aspect correction.  There are two things to consider:
- Create the framebuffer window at some size large enough to hold both NTSC and PAL output; for NTSC, obviously that will result in a lot a blank area at the bottom
- Adjust the output destination rectangle so that the TIA output is only scaled by integer zoom factors; so if the image is (say) 640x420, then those pixels are output into a 640x420 rectangle, with absolutely no loss of resolution

Honestly, I feel it's a regression to the work we've done, but there does seem to be several use-cases where this is relevant.

**Comment by thrust26** [comment]
I had mentioned that idea during our discussions. But I thought this would be useful for developers only and they can use the debugger window instead. Looks like I was wrong.

**Comment by sa666666** [comment]
I think the use-case that doesn't help with it wanting to record a video of Stella, external to Stella itself.  I'm thinking of the use-case that Nathan suggested.  If we can somehow satisfy that with your debugger suggestion, then I would be all for it.  Particularly since then we wouldn't have to add much more code.

**Comment by sa666666** [comment]
This is brought up again in https://github.com/stella-emu/stella/issues/680; please move all discussion there.
