### ISSUE TITLE
Blurred graphics in Direct3D

### ISSUE THREAD

**Issue by IPeluchito** [stella-emu/stella#673]
The graphics in **Direct3D** are not as sharp as in **Software** and **OpenGL** ...
On the other hand, is it possible to add **internal resolution multipliers** and real **32-bit** colors?

Thank you for your work!!!

**Comment by sa666666** [comment]
All colours internally are 32-bits.  And if Direct3D is not as sharp, it must be something on your system.  We don't do anything specifically with OpenGL or Direct3D; this is simply a flag passed to SDL (the underlying graphics library).  SDL is responsible for rendering, so if it acts differently, then it's something out of our control.

**Comment by IPeluchito** [comment]
I just discovered that the emulator has a problem with high resolution screen scaling in **Windows 8.1 at 3840 x 2160 and 250% scaling** ... I leave screenshot comparing how it looks by **default (LEFT)** and **disabling screen scaling on high DPI settings (RIGHT)**

![Shot](https://user-images.githubusercontent.com/64821708/86983966-e6b01580-c152-11ea-8123-d9b7e404781d.png)

**Comment by thrust26** [comment]
What are your exact video settings for the left shot?
