### ISSUE TITLE
Mac Fullscreen Snapshot Truncated

### ISSUE THREAD

**Issue by kdgarris** [stella-emu/stella#674]
When I take a snapshot via F12 on Stella 6.2.1 Mac OS while on fullscreen, the right part of the screenshot is chopped off. The snapshot is normal when taken in windowed mode.

![rcsumobots-2](https://user-images.githubusercontent.com/4992162/87468941-7852d380-c5e8-11ea-8224-9586bcd9c0e5.png)

![rcsumobots-2_1](https://user-images.githubusercontent.com/4992162/87468950-7c7ef100-c5e8-11ea-8af8-40702187866d.png)

**Comment by sa666666** [comment]
Confirmed in Linux too.  I will try to get to it soon.

**Comment by thrust26** [comment]
Not happening in Windows.
