### ISSUE TITLE
Pause toggle when window loses focus

### ISSUE THREAD

**Issue by chrisdwalton** [stella-emu/stella#681]
Stella appears to toggle the pause setting when changing window focus (on Linux with XFCE).    When developing, I often slow down the emulation and use pause to pinpoint the exact frame containing an issue.   Then I click on the editor window, and annoyingly the emulator un-pauses and the issue is lost!    It would be great if the pause toggle could be made optional.

Thanks - Chris

**Comment by thrust26** [comment]
So when the paused emulator loses focus, it continues to run? Weird.

That doesn't happen in Windows. I hope @sa666666 can reproduce the issue.

**Comment by thrust26** [comment]
@sa666666 Did you find the time to test this?

**Comment by thrust26** [comment]
@chrisdwalton @sa666666 Is this still an issue?

**Comment by thrust26** [comment]
No reply and not reproduceable.

**Comment by chrisdwalton** [comment]
Sorry for the delay - I am unable to reproduce the issue with the latest Stella

**Comment by thrust26** [comment]
All good. Thanks or letting us know.
