### ISSUE TITLE
Allow selecting audio devices

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#682]
Sometimes (rarely) it is required to select an audio device manually.

https://atariage.com/forums/topic/307760-stella-62-released/?do=findComment&comment=4578022

**Comment by sa666666** [comment]
Since SDL2 now exposes this info, I suppose it's easy enough to show a dropdown box to allow the user to select it.  SDL1 never supported anything like this, which is why the code works the way it currently does.

**Comment by thrust26** [comment]
Yup, already experimenting with it.

**Comment by thrust26** [comment]
There seems to be no way to find out the default audio device used by `SDL_OpenAudioDevice(nullptr,...)`. At least I found none. 

To fix this gap, we will need a "Default" device option, which would use `nullptr` instead of the device name.

**Comment by sa666666** [comment]
Makes sense, as this is what will be used 99.9% of the time anyway.  Simply store "default" in the Variant, and then check on applying if "default" has been passed.  If so, use `nullptr` instead.

**Comment by thrust26** [comment]
I have implemented the code and it seems to work. However I have only two devices, and only the 2nd one creates sound (I don't use SPDIF).
- 1: SPDIF Interface (TX1) (VIA HD Audio(Win 10))
- 2: Lautsprecher (VIA HD Audio(Win 10))

I decided to store the number in the settings and not the rather complex name. Makes things much easier (for me and the user). @sa666666 Fine by you?
