### ISSUE TITLE
(Libretro) Build broken because of recent changes

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#683]
Hi there,

the Libretro core now fails to compile across every platform because of the recent sound driver changes.

Here are some compiler logs -

Windows
http://paste.libretro.com/218979
OSX
http://paste.libretro.com/218975
Android
http://paste.libretro.com/219003

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/f3503d22d98e9e5ac8a2f7e24833f3e878d64a74.
