### ISSUE TITLE
Stelladaptor support broken

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#685]
I've tested Stelladaptor, original 2600-daptor, 2600-daptor II and 2600-daptor D9.  None of them are working in the latest version of Stella.  I went back though the releases, and it worked in 6.0.2 but not in 6.1.0-rc1.  So somewhere in between something was broken.

It's strange that nobody has reported this before now.  I guess not many people are using these devices with the later versions of Stella???

**Comment by sa666666** [comment]
Nope, starting without a settings file (so everything is at the defaults).  Still not working.

**Comment by thrust26** [comment]
IMO this must be an OS problem then.

**Comment by sa666666** [comment]
Well, if it was Linux only, I'd agree.  But the user on AtariAge tried Windows.  I will now test on other systems ...

**Comment by thrust26** [comment]
How come it works for me then?

**Comment by sa666666** [comment]
Not working for me in Windows either.

**Comment by thrust26** [comment]
Weird.

**Comment by sa666666** [comment]
OK, some more results.

**Windows**

Stelladaptor: working in latest Stella
2600-daptor: working in latest Stella
2600-daptor II: working in latest Stella
2600-daptor D9: not working

**Mac**

Stelladaptor: working in latest Stella
2600-daptor: working in latest Stella
2600-daptor II: working in latest Stella
2600-daptor D9: not working in latest Stella; pressing button seems to send 'Tab', and moving paddle right, back off, and then moving right again seems to send 'Backslash' (since the command menu is being toggled).

**Linux**

Stelladaptor: working up to 6.0.2, not working in 6.1.0_rc1
2600-daptor: working up to 6.0.2, not working in 6.1.0_rc1
2600-daptor II: working up to 6.0.2, not working in 6.1.0_rc1
2600-daptor D9: in 6.0.2, pressing button causes paddles to jump from left to right; paddle movement has no effect.  In 6.1.0_rc1, no response at all.

Concerning the D9, note that in Windows and Linux, when going to the joystick control panel of the OS itself, the device is not sending the correct events anyway.  So this may be a faulty unit, or may need to be reflashed.  Unable to test this in macOS, since I don't know of a joystick control panel utility there.  So we can discount that one for now.

The strange one is Linux.  The devices worked in 6.0.2, but not in 6.1.0_rc1.  This is the same OS, same kernel, same hardware, same SDL2, etc.  All that changed is Stella.  So that makes me look there first.  Also, the event mapping rework happened in this timeframe.  So I don't think it's a coincidence.

I will continue testing ...

**Comment by sa666666** [comment]
I got the D9 working.  I have 2 D9's, and it turns out I mislabelled them.  One is normal, the other is for flashing experimental firmware.  Of course I labelled them incorrectly and was using the latter one, and not the former.  So these are all now working fine in the latest version of Stella for Windows and Mac.  Still have to work on the Linux side ...

**Comment by sa666666** [comment]
OK, some more research.  I have the D9 working in the latest version of Stella in Linux now.  The problem seems to be that I had another joystick plugged into my Linux machine as well as the D9, and the other systems had only the D9.  I noticed that the joystick (an Xbox One controller) always had ID 0 in the logs, and the D9 always had ID 1.  Try as a I might, I couldn't get them to switch around.  Finally I unplugged the XBone controller, and let the D9 become ID 0.  And then it finally worked!

Now this is a bug, since the 2600-daptors are supposed to work no matter what IDs are assigned to them.  They're supposed to be treated as special by Stella, and **always work**, being completely plug and play.

So I moved back to my Windows machine, and tried plugging in a joystick and the D9.  But of course, no matter what USB port I used, the D9 always got ID 0, so that explains why it always works in Windows.  I'll bet if you could somehow get a joystick to have ID 0 and the D9 to have ID 1, that the same problem will happen in Windows.

**Comment by thrust26** [comment]
How about if you clear the joystick database and then add the other joystick first? Maybe that can reproduce the error.

IIRC we had the ID switching issue before.

**Comment by sa666666** [comment]
Tried that, couldn't get the ID to work the way I needed.  Maybe the rear USB ports are enumerated before the front ones?  Or maybe do it dynamically.  I tried plugging them both into different ports at the same time, before starting Stella.  Maybe starting Stella and plugging them in a different times will reproduce it.  If you have multiple controllers, feel free to give it a try too :smile:

**Comment by sa666666** [comment]
Adding this so I don't forget.  I think 'daptor controllers need to have their defaults automatically set for all virtual controllers they support.  It doesn't matter what ID is assigned.  If a "Left 2600-daptor" is detected, it needs to have its mappings assigned to _all_ left virtual controllers.  Same as "Right 2600-daptor" and right virtual controllers.  And perhaps the removal of a joystick from the joystick database removes all mappings for that controller too.

**Comment by thrust26** [comment]
Do you still think the title is correct?

**Comment by sa666666** [comment]
Well, it is related to 'daptor handling.  And I don't know what to change the title to until I look at the code to see what the problem is.
