### ISSUE TITLE
Height, Format display property ignored

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#69]
This is quite similar to https://github.com/stella-emu/stella/issues/31, except it's actually a little easier to code.  Essentially, there is a "Display.Height" property that defaults to 210 for NTSC, and 250 for PAL.  But there are some ROMs that need further tweaking, much like YStart needs to be tweaked in some cases.

I suggest that this could also be made 0 by default (or perhaps 'Auto'), and let the FrameManager select the correct height based on whether the property is non-zero (in which case it uses the height specified) or 'Auto' (in which case it looks at the ROM display type (NTSC, PAL) and uses the defaults mentioned above).

Implementation-wise, you'd simply need to store an extra heightOffset in FrameManager that either adds to or subtracts from the calculated height, and returns this new height.

This is also related to https://github.com/stella-emu/stella/issues/32, since if "Display.Format" properties say to use 'NTSC' and the ROM is actually 'PAL', it should do so (and then display the resulting rolling screen).  Finally, related to this is the issue that Stella actually has 7 different display types: AUTO, NTSC/PAL60/SECAM60 (60Hz NTSC timing with NTSC colours) and NTSC50/PAL/SECAM (50Hz PAL timing with PAL colours).  The colours are taken care of elsewhere, but there should be a way for FrameManager to interpret the different formats and act accordingly (right now, it's just doing AUTO).

**Comment by DirtyHairy** [comment]
Was the next thing on my imaginary list anyway :smirk:

**Comment by DirtyHairy** [comment]
Implemented in a6725f2 . I have taken the liberty to remove a piece of code that takes care of vertically centering the image if the frame height exceeds window height --- there is no simple way to get this to work with autodetection. In addition, I have made `TvMode` available and ditched `TIA::isPAL` in favor of `TIA::getTvMode`.
