### ISSUE TITLE
ARM developer options

### ISSUE THREAD

**Issue by chrisdwalton** [stella-emu/stella#690]
1) The "Randomize zero page and extended RAM" developer option is useful to ensure that the code does not depend on any initial values in RAM.   However, with CDFJ binaries this option is causing the initial values of global variables to be overwritted.   I suspect it is randomizing the ARM RAM, after the code has been loaded and initialized?    The behavior should be changed to randomize the RAM before the ROM has been initialized (so that the contents of the memory is random, but any globals variables that have been explicitly set should be preserved).

2) The "Randomize startup bank" option should be disabled for CDFJ binaries.   With CDFJ, the ARM code forces startup in the final bank so it is safe to assume the other banks will not be accessed.   This option is working as intended, but will always crash for CDFJ because the other banks normally contain C code.    Disabling this option for CDFJ would make it safe to have this option always enabled.

Chris

**Comment by thrust26** [comment]
The second point is easy to fix. 

For the first point I may need more info, especially because we have not written the `CartCDF` class. The main problem I currently see is, that e.g. on ROM reload (CTRL+R), the ROM is not loaded again. So if initial values are part of the ROM (correct?), these are not reset then.

**Comment by DirtyHairy** [comment]
The first point is interesting. The CDFJ cartridge emulation does not run any ROM bootstrap code, it just copies the driver to the first 2k. I can't see how global variables could be initialised in the first place.

**Comment by thrust26** [comment]
@chrisdwalton Any input from you side?

**Comment by chrisdwalton** [comment]
I have not been able to reproduce the first issue with toy examples (global variables are always set correctly), so I suspect there was some other issue with my code.    Feel free to resolve.

Chris
