### ISSUE TITLE
missing support for HID dial and slider

### ISSUE THREAD

**Issue by ulao** [stella-emu/stella#691]
Hi just noticed 6.x broke the controller HID for dial and slider.

When I go to map my device for a paddle it works in 4.x but not 6.x. Looks like stella is just not watching for DX slider and Dial.

**Comment by thrust26** [comment]
Have you tried to reset (default) the input settings?

**Comment by ulao** [comment]
in the GUI yes is there another way , like deleting an ini?

**Comment by thrust26** [comment]
The GUI should do.

Can you test some intermediate versions and maybe find out when the problem started?

**Comment by thrust26** [comment]
Missing feedback and information.
