### ISSUE TITLE
QuadTari support

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#693]
More info here: https://atariage.com/forums/topic/305226-quadtari/?do=findComment&comment=4618277

[multitap_test.zip](https://github.com/stella-emu/stella/files/5141347/multitap_test.zip)

**Comment by thrust26** [comment]
TODOs:
- implement and integrate new controller class
- enhance `GameInfoDialog`
- enhance `StellaSettingsDialog` (if R77 supports QuadTari)
- enhance `ControllerDetector`
- new debugger widget
- new events for 3rd and 4th joystick (and other controllers?)
- enhance `PKeyboardHandler`
- enhance `DefProps` generation
- ...?

If other or even multiple controller types per port are allowed, the might be more changes required.

**Comment by sa666666** [comment]
It seems to me the controller type for the port should be 'quadtari', and it should contain two other controllers as instance variables.  This is closely related to how the real hardware works, as it plugs into a port, and then other controllers plug into _it_.  And the 'quadtari' controller can issue commands/make changes to the underlying controller instances.

Of course, that brings up the issue of how to specify a controller, since technically when you say a 'quadtari' is plugged into a port, you really mean that two other controllers are plugged in too.  So we'd need a way of saying that both a quadtari is plugged in, _and_ a joystick/paddle, or joystick/AVox, etc, are plugged into that.

**Comment by thrust26** [comment]
Yup, that's where it starts getting complicated. We would have to e.g. enable QuadTari mode and then handle four ports instead of two. 

And I have to come up with a good idea for the `GameInfoDialog/Controller` tab which doesn't make it overly complicated. A sub dialog or something like that only for the QuadTari (plugged into one or both ports).

**Comment by sa666666** [comment]
Maybe the type could be defined as "quadtari_x,y", where 'x' and 'y' are one of the current controller types.  So "quadtari_joystick,paddles" uses joystick for 'left' controller (for that port), and paddles for the 'right' controller.  And by default, if one specifies only "quadtari", it really means "quadtari_joystick,joystick".

I don't doubt that other issues may pop up, but I don't see it requiring _major_ changes to the code.  I suspect the UI will be the hardest, in how we present the info to the user.  Also, we would need another set of events at least.

**Comment by thrust26** [comment]
Internally we could use such long definitions. But as you say, that's nothing for the UI.

**Comment by sa666666** [comment]
It would also be best that for one of the joysticks plugged into a quadtari, it would use JoystickZero events.  That corresponds to the case where JC said that if only one joystick is plugged into the device, it acts as if the joystick is plugged directly into the port.  The same would apply for the right port and JoystickOne events.

> Internally we could use such long definitions. But as you say, that's nothing for the UI.

Well, in the UI it could simply be checkboxes or something.  No matter what, it's going to require another dialog specifically for quadtari configuration.

**Comment by sa666666** [comment]
Also, I wouldn't worry about the dialog/configuration for now.  The more important part is making sure it's possible with the current framework, getting it working for at least the common cases: joystick/joystick, joystick/avox, etc.

**Comment by thrust26** [comment]
> It would also be best that for one of the joysticks plugged into a quadtari, it would use JoystickZero events. That corresponds to the case where JC said that if only one joystick is plugged into the device, it acts as if the joystick is plugged directly into the port. The same would apply for the right port and JoystickOne events.

Definitely. We then will have JoystickTwo and JoystickThree events. And if other controllers are supported even more of duplicated these events. 

> Also, I wouldn't worry about the dialog/configuration for now. The more important part is making sure it's possible with the current framework, getting it working for at least the common cases: joystick/joystick, joystick/avox, etc.

For a start we could only support joystick/joystick and call it QuadTari. And if other combinations are used **then** we enhance the GUI.

**Comment by thrust26** [comment]
> It seems to me the controller type for the port should be 'quadtari', and it should contain two other controllers as instance variables. This is closely related to how the real hardware works, as it plugs into a port, and then other controllers plug into _it_. And the 'quadtari' controller can issue commands/make changes to the underlying controller instances.
> 
> Of course, that brings up the issue of how to specify a controller, since technically when you say a 'quadtari' is plugged into a port, you really mean that two other controllers are plugged in too. So we'd need a way of saying that both a quadtari is plugged in, _and_ a joystick/paddle, or joystick/AVox, etc, are plugged into that.

I wonder how to define the ports/players of the two controller instances. We could extend the `Jack` enumeration by adding e.g. `left2` and `right2`. But there is a lot of code relying on the two existing `Jack` values and we might break or have to rewrite it with additional values. Alternatively a simple boolean (e.g. player 0 vs player 2) which is just used for the input mapping would do.

Both alternatives seem not to fit perfectly, @sa666666 what are your references?
