### ISSUE TITLE
CDFJ startup issue

### ISSUE THREAD

**Issue by chrisdwalton** [stella-emu/stella#697]
I think I have now found the issue with global variables previously discussed in:
https://github.com/stella-emu/stella/issues/690

The issue is the 0x80B PC start address in Thumbulator.cxx
```
    case ConfigureFor::CDFJ:
      reg_norm[14] = 0x00000800; // Link Register
      reg_norm[15] = 0x0000080B; // Program Counter
      break;
```

Looking at the CDFJ startup disassembly:
```
00000800 <Custom>:
 800:   e28f0001        add     r0, pc, #1
 804:   e12fff10        bx      r0
 808:   480b            ldr     r0, [pc, #44]   <-------- This line is skipped
 80a:   6802            ldr     r2, [r0, #0]     <--------- Startup here
 80c:   2a00            cmp     r2, #0
 80e:   d40c            bmi.n   82a <SkipCopy>
```

This corresponds to the following code:
```
  ldr     r0, =0x40000024    <------- Skipped line
  ldr     r2, [r0]

  /* Skip if data section already copied */
  cmp     r2, #0
  bmi     SkipCopy
```

Basically the location 0x40000024 is used to store a flag indicating if the BSS and data section (i.e. global variables) have been initialized, where a zero value means that these areas need to be initialized.

When the "randomize zero page and extended RAM" developer option in Stella is enabled, this flag will be assigned a random (non-zero) value and the global variables will not be copied.

I believe the fix is to change the program counter as follows:
`reg_norm[15] = 0x00000809;`
(the actual address is 0x808 but the lowest bit is set to indicate THUMB mode).

I don't have a dev copy of Stella so have not been able to validate this.   However, I have a test binary that crashes when the "randomize zero page and extended RAM" option is set and works otherwise.   If my analysis is correct this binary should always work after the fix regardless of this developer setting:

[global.zip](https://github.com/stella-emu/stella/files/5178279/global.zip)

Thanks
Chris

**Comment by chrisdwalton** [comment]
Note that the full code in Stella is:
```
    // future 2K Harmony/Melody drivers will most likely use these settings
    case ConfigureFor::BUS:
    case ConfigureFor::CDF:
    case ConfigureFor::CDF1:
    case ConfigureFor::CDFJ:
      reg_norm[14] = 0x00000800; // Link Register
      reg_norm[15] = 0x0000080B; // Program Counter
      break;
```
I have checked that this fix is safe for all the CDF and BUS types, i.e. they all use the same startup code.

I suspect the PC address for DPCplus should also be changed to 0xC09 but this will need to be carefully tested in case there are easly DPC+ games that have a different startup sequence:
```
    // future 3K Harmony/Melody drivers will most likely use these settings
    case ConfigureFor::DPCplus:
      reg_norm[14] = 0x00000C00; // Link Register
      reg_norm[15] = 0x00000C0B; // Program Counter
      break;
```

Chris

**Comment by thrust26** [comment]
I could do the change, but I have little to no clue what I am doing there. I suppose someone who did the original coding (@SpiceWare ) should make and test the fix.

**Comment by chrisdwalton** [comment]
> I could do the change, but I have little to no clue what I am doing there. I suppose someone who did the original coding (@SpiceWare ) should make and test the fix.

Thanks - I have asked Darrell to take a look.

**Comment by SpiceWare** [comment]
Hmm, I think Fred did the initial ARM implementation in Stella. I would have copied the existing logic and done a 1K adjustment to the addresses to compensate for the smaller BUS and CDF drivers.

My Stella setup is out of date, will do a get latest and see what happens if I change them to use xx09 instead of xx0b.

**Comment by SpiceWare** [comment]
@chrisdwalton ended up looking at this, he said:

> I tested the change to the PC value from 0x80B instead of 0x809 for CDFJ and it didn't work.   I then remembered that the PC value is +2 bytes ahead of the actual PC location because of pipelining, so the original value was correct after all!

**Comment by thrust26** [comment]
So where are we now? 😕

**Comment by SpiceWare** [comment]
The start address that Chris thought was wrong is actually correct, so the change of 0x80B to 0x809 should not be done.

Chris is working on a big update to CDFJ that also affects DPC+, BUS, and Thumbulator - in rereading the original post, I do not know if he looked into the initialization issue as part of what he's working on.

**Comment by chrisdwalton** [comment]
Closing the issue - the start address is correct.   I haven't found the cause of the crashes with the test binary, but will continue to investigate.
