### ISSUE TITLE
$FA0/$FC0 bankswitching support (new dumps from Brazil)

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#698]
See here:
[https://atariage.com/forums/topic/310947-please-help-with-2-in-1-8k-diy-cart/?do=findComment&comment=4625650](https://atariage.com/forums/topic/310947-please-help-with-2-in-1-8k-diy-cart/?do=findComment&comment=4625650)

**Comment by thrust26** [comment]
Should be easy to implement. I will look into it.

**Comment by ale-79** [comment]
I think it's legit. The board is similar in construction to other brazilian carts I've seen, which also use off-the-shelf ICs and EPROMS. The scheme itself is a variation of the "$2a0/$2c0" one (#506) documented last year, but this one uses a subset of hotspots, as it also checks A10 and A7.

I wouldn't be surprised if further variations come up in the future, given the great amount of small companies pirating games in Brazil back in the day.

**Comment by thrust26** [comment]
Maybe we can generalize the UA bankswitching, so that it covers all future variations?

**Comment by ale-79** [comment]
> Maybe we can generalize the UA bankswitching, so that it covers all future variations?

Sounds good.

> And how do you switch between the two games?

There's a 2 positions toggle switch that connects A13 of the EPROM to either ground or +5v. (it's visible in some of the pictures of the first post in the AA thread)
I think that supporting the split roms individually is more than enough, anyway.

**Comment by thrust26** [comment]
Which address ranges or bits make sense here? The current code does `address & 0x1260` and checks for 0x220 and x240. That should cover everything, no? Or do the other bits (e.g. A7 = 0x80) make any difference? For the previous Brazilian carts they did not.

**Comment by ale-79** [comment]
> Which address ranges or bits make sense here? The current code does address & 0x1260 and checks for 0x220 and x240. That should cover everything, no? 

Yes, I think it should.

The previous brazilian carts ("$2A0/$2C0) didn't care for A7 and A10 and used these addresses (in binary, x=don't care)

```
%0xx1xx01xxxxx	-> switch to bank 0
%0xx1xx10xxxxx	-> switch to bank 1
%0xx1xx11xxxxx	-> illegal (undefined behaviour)
%0xx1xx00xxxxx	-> no effect
```
So:
```
(address & 0x1260) == 0x220 -> bank 0
		   == 0x240 -> bank 1
```
The new board ("$FA0/$FC0") do use A10 and A7, so they respond to a subset of the previous addresses 

```
%0x11x101xxxxx	-> switch to bank 0
%0x11x110xxxxx	-> switch to bank 1
%0x11x111xxxxx	-> illegal
%0x11x100xxxxx	-> no effect

```
which means

```
(address & 0x16e0) == 0x6c0 -> bank 0
		   == 0x6e0 -> bank 1
```
The new roms should run with generalized "UA", unless they trip on some addresses which aren't hotspots in the more restrictive scheme, causing an unwanted bankswitch.


> In your RIOT memory map you write that A8, A10 and A11 are not connected. So the anding seems sufficient, right? How about A7? I am no hardware guy, so what does "A7 is connected to CS1 (Chip Select 1 - active high)" mean in detail?

I didn't write that memory map document: it's from Chris Wilkson ("cwilkson" on AA), you can find it [here](https://web.archive.org/web/20050321100824/http://web.mit.edu:80/~ecwilkso/www/VCS_hardware/).
All the chips select pins must be in their "active" state for the chip to be enabled. In case of RIOT there are two chip selects: one active low connected to A12 and the other active high connected to A7. Which means that the chip will respond to addresses with A12=0 and A7=1. Anyway, there's no relation between the RIOT (or TIA) memory map and the bankswitching logic, as they're on separate chips and don't interfere with each other, even if they respond to the same address. So A7 does matter for the RIOT, but not for the generalized "UA" scheme.

**Comment by thrust26** [comment]
Sorry for the confusion. 

The split 8K ROM are already working. I will now try to generalize the code then do some testing.

**Comment by thrust26** [comment]
@ale-79 Reopening this one because I found a 32K dump considered bad, which turned out to be a 16K overdumped ROM using another variation of UA bankswitching. I have attached the 16K ROM and also split it into 8K files. The latter work with UA bankswitching.
[UA+.zip](https://github.com/stella-emu/stella/files/7190707/UA%2B.zip)

The hotspots are a follows:
- Motocross: 0xEA0 and 0xEC0
- Pole Position: 0xFA0 and 0xFC0

So it seems that A13, A14 and/or A15 are used to determine further banks. What do you think? Which bit(s) is/are most likely triggering here?

**Comment by thrust26** [comment]
Nevermind, decided this must be a 2 in 1 using UA for each game. Adapted Stella in 18874da so that it can play it.
