### ISSUE TITLE
Slow controller and cart detection

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#706]
Especially the `ControllerDetector` is quite slow for large ROMs. Both detectors are using a naive string search algorithm which can be improved significantly. E.g. by using the Boyer-Moore search algorithm, which will search 3 bytes pattern (worst case) 3 times faster on average.

`std::search` supports a `boyer_moore_searcher` (C++17).

**Comment by sa666666** [comment]
I figured this would eventually become a problem, when I saw ROM sizes start to increase.

I have no issue with going to the search method you mention.  But it means enforcing C++17 as the minimum requirement to build Stella (currrently it's C++14).  There's no problem for Windows or Mac, but I'd need to check the Linux compilers/distro's that we would support.

Have you tested this yet?  Perhaps you could, to see if the change is warranted??  Long story short: I support it, as long as changes to requirements are justified by a performance increase.

**Comment by sa666666** [comment]
It looks like g++7 would be the minimum requirement for C++17 (or at least most of it, `filesystem` support still wouldn't work).

In release 6.2.1 I reverted a change that allowed gcc6 to suffice.  But I also noted that this wouldn't last long:
```The codebase now compiles under gcc6 again.  Future versions will require gcc7, though.```

I have no issue with going to gcc7.  I believe the R77 environment uses that as well.  But going beyond that would break R77 port, so that's probably as far as we can go for now.

**Comment by thrust26** [comment]
I wonder if there exist algorithms which search for multiple strings fast.

**Comment by sa666666** [comment]
Hmm, never really looked into it.  Some of the faster algorithms use the search key to build some sort of table to make the search work (I know KMP does that).  In those cases, it can't search for multiple things at the same time.

Also, if the multiple keys are 'sort of' the same, then perhaps a regex would suffice.  But then I don't know if building and processing the regex is slower than just doing the naive search.  For that matter, I don't know that `std::search` won't be slower on small ROMs.  So we may be trading fast search on large ROMs for slow search on smaller ones.  This can lead down a rabbit hole :smiling_imp:

**Comment by thrust26** [comment]
I doubt the slowdown for small ROMs will be noticeable. And if, then we could still switch back to naive search for these.

**Comment by sa666666** [comment]
I also wonder if the search is currently slow enough that you'll see it on larger ROMs too :smile: In any event, we need to test and measure, to make sure this work is justified.

**Comment by thrust26** [comment]
Yes, it is very slow. Just check the CDFJ+ 512K test ROM.

**Comment by thrust26** [comment]
This looks pretty good: https://github.com/cjgdev/aho_corasick

**Comment by sa666666** [comment]
I will have to leave it to you to take the lead on this.  On my system, I notice no slowdown whatsoever.  I believe you that it's there, but since I'm unable to duplicate it, I can't really help in development/testing.

**Comment by thrust26** [comment]
On my system, changing from "zev64.bin" to "red512.bin" in the launcher takes about two seconds.

**Comment by sa666666** [comment]
As usual, please do it in a branch first, if possible.  Also, if you need to add any files, they can go in `src/common`.  If it's going to be a lot of files (ie, from another project), please place in `src/common/NAME_YOU_PICK`.

On my system it's sub-second.  I don't know the actual amount, but I see no difference in the two CDFJ+ ROMs.  I'm on a fast system with an NVME SSD, so it's very hard to test these sorts of performance issues.

**Comment by thrust26** [comment]
Your different result made me wonder. Then I realized that I was in DEBUG mode. After switching to RELEASE mode, I get the same results as you do. So I suppose we should close this one. Agreed?

**Comment by sa666666** [comment]
Well, even if your CPU was half the speed (and it's not that slow), it still wouldn't account for the difference.  Debug mode definitely would though.

Since we no longer have an issue, I leave it to you to decide.  I have the same question; is the extra work in measuring/coding/testing/etc worth it for any speed increase we might get?  Since 512K is probably the largest ROM we have to worry about, I don't think we need to care right now.

**Comment by thrust26** [comment]
Agreed.
