### ISSUE TITLE
Enhancement Request: Initial Debugger Window Focus

### ISSUE THREAD

**Issue by kdgarris** [stella-emu/stella#709]
In my opinion, it would be much more useful to have the initial focus when bringing up the debugger window be on the debugger prompt tab. I find myself frequently typing as soon as I bring up the window, inadvertently hitting hotkeys in the process.

Of course, opinions may vary as to what default is more useful, but I thought I'd at least try.  :-)

**Comment by sa666666** [comment]
This is supposed to be the default.  At least it was in the past.  The first time the debugger is entered, the prompt has focus.  Thereafter, the focus is wherever it was the last time you were in the debugger (ie, it remembers from last position).  Are you saying you want focus on prompt _every_ time (ie, don't remember each time, and always go to prompt)?

**Comment by kdgarris** [comment]
> This is supposed to be the default. At least it was in the past. The first time the debugger is entered, the prompt has focus. Thereafter, the focus is wherever it was the last time you were in the debugger (ie, it remembers from last position). Are you saying you want focus on prompt _every_ time (ie, don't remember each time, and always go to prompt)?

It looks like you are right. I didn't realize that the focus defaulted to where it was last, though. Even knowing that, I'd personally prefer that it always default to the prompt, but I don't know if others would prefer the current behavior instead.

**Comment by thrust26** [comment]
That's how e.g. I prefer it. Bad luck. 😈
