### ISSUE TITLE
feature request: differentiate player/missile copies in "debug colors"

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#713]
The idea would be to use different shades of the same color (like it's currently implemented for the 3 playfield registers) to distiguish between the 4 possible player/missile copies:

"main"
"close" (2nd copy for NUSIZ="001" and "011")
"medium" (2nd copy for NUSIZ="010" and "110", 3rd copy for "011") 
"far" (2nd copy for NUSIZ="100", 3rd copy for "110")

**Comment by thrust26** [comment]
Interesting idea. 

I am not sure though about the shades. Why would you want four shades? Why not just three shades for 1st, 2nd and 3rd copy?

**Comment by ale-79** [comment]
That comes from the description of the Horizontal Position Counters in Andrew Towers' TIA HW notes (The 4 copies correspond to the 4 possible "START decode" states which are reached by the position counters. The 3 NUSZx bits determine if a copy will be drawn).

Anyway, having 3 shades denoting the "Nth" copy of the selected NUSIZx arrangement, would work equally well.

**Comment by DirtyHairy** [comment]
That's a pretty cool idea. Shouldn't be particularly hard to do, either.

**Comment by thrust26** [comment]
@DirtyHairy I have to leave that up to you (comments, you know... :wink:).

**Comment by sa666666** [comment]
Actually, the debug colours stuff was my area initially.  Of course if @DirtyHairy wants to work on it, then I won't object :)

**Comment by thrust26** [comment]
I would do it myself, but at least at first glance I wouldn't know how to find out which copy is currently displayed.

**Comment by DirtyHairy** [comment]
😏 I'll do it, I have a pretty good idea on how to do it...

**Comment by thrust26** [comment]
@DirtyHairy Please have a look at my code. It works, but it might not be optimal or missing something.

**Comment by DirtyHairy** [comment]
Looks good to me --- pretty much what I would've done as well 👍 Using `myCopy` is fine imo, too, as it does not increase the complexity of the hot code path in tick.
