### ISSUE TITLE
Rework continuous snapshot mode

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#714]
I just noticed a comment on AtariAge about a user seeing many hundreds (or thousands!) of snapshots being generated.  They didn't intentionally do it, but it looks like they mistakenly turned on continuous snapshot mode.

So a few issues:
- First of all, do we even need this any longer?  Is anyone actively using it?  I asked in the AtariAge thread, and await a response.
- Currently the functionality is not saved to the settings, so at least it won't continue when Stella restarts.
- It is enabled by hotkey only, making it relatively easy to activate by mistake.  A message appears for a moment telling the user, but I guess it could be missed too.

So I advocate one of two options:
- Maybe just kill the function entirely.  I'm always in favour of reducing code/complexity, so I would go with this one if nobody is using it.
- Otherwise, remove the hotkey for it, and expose it through the UI only.  At least that way it's much harder to accidentally activate.

Comments or suggestions?

**Comment by thrust26** [comment]
Couldn't we just (optionally, enabled by default) permanently display the "snapshot saved" message? Then the user would be aware of what is going on.

**Comment by sa666666** [comment]
Yep, that's another option I guess.

**Comment by thrust26** [comment]
And we could change the default hotkey from ALT+S into CONTROL+ALT+S.

**Comment by sa666666** [comment]
Sure, the more keys you have to press, the less likely it is to do it accidentally.
