### ISSUE TITLE
Stella 6.3 (on Win64) crashes when removing savekey_eeprom.dat for games that use Savekey

### ISSUE THREAD

**Issue by dionoid** [stella-emu/stella#715]
In Stella 6.2 (and older) on Windows 64-bits, I used to erase the emulated Savekey EEPROM by removing the %APPDATA%\Stella\nvram\savekey_eeprom.dat file, which would then automatically be recreated by Stella when a Savekey was configured for a specific rom.

In Stella 6.3, removing the savekey_eeprom.dat will crash Stella when trying to run a rom that uses the Savekey.

**Comment by sa666666** [comment]
Yep, that's already fixed in git, and the fix will be in 6.3.1.
