### ISSUE TITLE
The 'Erase EEPROM' button doesn't seem to clear savekey_eeprom.dat

### ISSUE THREAD

**Issue by dionoid** [stella-emu/stella#716]
In version 6.2 and 6.3 of Stella (on Windows 64 bits), clicking the 'Erase EEPROM' button doesn't clear the savekey_eeprom.dat file in %APPDATA%\Stella\nvram\savekey_eeprom.dat

**Comment by sa666666** [comment]
Will have to look into this one.  There was some issues with Savekey functionality that we fixed, so this may now be a duplicate.  In any event, it will be fixed for 6.3.1.

**Comment by sa666666** [comment]
Fixed in either https://github.com/stella-emu/stella/commit/e92a3882e7c39a0878c5536841a9308d4f83be68 and https://github.com/stella-emu/stella/commit/c462cc4680378ad654fbb15b200b9161f97eb4d4.  Will be present in 6.3.1 release.
