### ISSUE TITLE
Mouse grabbing only in paddle/trakball games

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#72]
I would be very helpful to limit the mouse grabbing option to games which can be controlled by the mouse. 

This feature also causes trouble during debugging, because it moves the mouse pointer after leaving the debugger. So when you step through various breakpoints, you always have to move the mouse back to the exit button or switch to using the keyboard.

**Comment by DirtyHairy** [comment]
That'd be a very nice feature.

**Comment by sa666666** [comment]
Very easy to fix.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/8b4096e1efa224fd60c68ae440255030a628520b.
