### ISSUE TITLE
Compiling 6.4 fails on armhf and arm64 Linux

### ISSUE THREAD

**Issue by SvOlli** [stella-emu/stella#722]
When trying to compile the 6.4 release as a deb package for Debian Stretch, I get the following error message:
```
src/emucore/QuadTari.cxx: In member function ‘std::unique_ptr<Controller> QuadTari::addController(Controller::Type, bool)’:
src/emucore/QuadTari.cxx:71:51: error: binding ‘const OSystem’ to reference of type ‘OSystem&’ discards qualifiers
   Controller::onMessageCallback callback = [&os = myOSystem](const string& msg) {
                                                   ^~~~~~~~~
```
I think the author might like to fix this, as errors like tend to pop up later in other configurations.

Side note: in debian/changelog, please do not add the "-1" to the version number as this is only used when the debian-folder is added using a patch or separate tarball. `dpkg-buildpackage -S` fails when "-1" is added.

**Comment by SvOlli** [comment]
Or could it be, that the compiler in Stretch (gcc-6.3.0) is tool old?

**Comment by thrust26** [comment]
I am the author. 😄 

I suppose removing the `const` in the constructor would solve the problem?

**Comment by SvOlli** [comment]
Just ran a test: removing const in the class constructor and the variable declaration seemed to fix the problem.

**Comment by DirtyHairy** [comment]
> Or could it be, that the compiler in Stretch (gcc-6.3.0) is tool old?

However, I wouldn't count on gcc 6.3 to continue working with Stella in the future 😏

**Comment by sa666666** [comment]
We're moving to gcc7 sometime in 2021.

Also, I'd like to look into this, and see if we can fix it without having to remove `const`.  In general, we should use `const` whenever possible.

**Comment by sa666666** [comment]
> Side note: in debian/changelog, please do not add the "-1" to the version number as this is only used when the debian-folder is added using a patch or separate tarball. `dpkg-buildpackage -S` fails when "-1" is added.

Please report this as a separate issue.  In fact, if you have some experience with the Debian build process, we would welcome patches to fix/extend this functionality.

**Comment by sa666666** [comment]
I'm going to close this one, since the code is correct in this case.  This is a reported bug in gcc6, and is fixed in gcc7.  And since we're moving to gcc7 in 2021 (probably January or February), it doesn't make sense to change this now.  And `const` is the correct approach here.
