### ISSUE TITLE
Building debian packages

### ISSUE THREAD

**Issue by SvOlli** [stella-emu/stella#723]
As requested in #722 here's a note on a smaller problem I encountered:

in debian/changelog, please do not add the "-1" to the version number as this is only used when the debian-folder is added using a patch or separate tarball. dpkg-buildpackage -S fails when "-1" is added.

The rest works fine in creating deb-packages for different distros.

Backstory: I'm running a small Debian/Ubuntu addon repo in which I include Stella for obvious reasons. It's available at http://deb.svol.li/ . Not all of the distros there are maintained actively, but most of them. I'm using some self-written scripts to build for all the different distros and architectures. They are not released because imho they lack a certain kind of stability, especially when it comes to creating and updating the several chroot-environments. (I'm willing to share, though.) Nevertheless, I got this error from the later Debian distributions.

**Comment by skitt** [comment]
I’ll sync the relevant changes from the current Debian packaging and adjust it for a native package.
