### ISSUE TITLE
Paddle buttons not working (well)

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#725]
There have been reports that paddle buttons either do not work at all or only randomly on R77 since 6.3.

Note: The buttons work in PC version (tested with keyboard, mouse and 2600-daptor).

https://atariage.com/forums/topic/313085-stella-64-released/?do=findComment&comment=4671124
https://atariage.com/forums/topic/289929-stella-6-on-the-r77-the-eagle-is-landing/?do=findComment&comment=4671694

**Comment by sa666666** [comment]
I'm researching a report that this is also happening with a Stelladaptor on a PC.  Will add more details when I have them.

**Comment by thrust26** [comment]
Do you have a link?

**Comment by sa666666** [comment]
No, email sent to me personally.  Will check back when I have more info, and can confirm or deny.

**Comment by thrust26** [comment]
@sa666666 I think we can close this one now.
