### ISSUE TITLE
Screensaver disabled in Windows

### ISSUE THREAD

**Issue by vitococl** [stella-emu/stella#731]
When Stella runs in Windows, the screen saver mode is disabled, which is fine, except when there is no emulation running. I couldn't find an option for this in the setup.

It could be great to restore the screensaver function while in the file explorer mode searching for a bin file.

Edit: Also when it is in pause mode or minimized.

Thanks!

**Comment by thrust26** [comment]
This is not under control of Stella, but an OS issue.

Probably a controller is creating events which keep the computer active.
