### ISSUE TITLE
Libretro build broken

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#736]
Hi there,

the Libretro build is broken with a recent commit. See this log for further details (this is for Windows, but it affects all versions) - 

https://git.libretro.com/libretro/stella/-/jobs/37708

**Comment by sa666666** [comment]
I will get to this later this evening.

**Comment by thrust26** [comment]
@twinaphex 
Is it solved now?

**Comment by sa666666** [comment]
This is now fixed.  Some of the other warnings I just fixed with a recent commit.  The remaining ones are a bug in gcc7, which was fixed in gcc8 and above.
