### ISSUE TITLE
(libretro) libnx build broken

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#739]
See the log here -

https://git.libretro.com/libretro/stella/-/jobs/40261

**Comment by thrust26** [comment]
See https://github.com/stella-emu/stella/commit/ad88f26c6103a43ddef63619885803ce646b271c

We switched to C++17.

**Comment by twinaphex** [comment]
Can you add the C++17 switch then to the static Makefile for libretro?

**Comment by sa666666** [comment]
I don't know where to add it for all the different architectures.  I did it for Windows and Linux, which is all I'm able to test.  We'll need someone who actually has these systems to make the change.  Pull requests are welcome.

**Comment by sa666666** [comment]
It might also be useful if the members of the Stella Team (currently just 3 of us) have direct access to the build logs for Stella, preferably to be emailed to us on each build.  That way we could see these issues ourselves, without requiring you to create issues each time.

**Comment by twinaphex** [comment]
I agree. I will try talking with some people about this to see if this can be made possible.

**Comment by twinaphex** [comment]
Hi there, so I talked about this with some people and they said that if it's just read access you want to the 'runner' bit, the page is public for everyone to see -

https://git.libretro.com/libretro/stella/-/pipelines

Let me know if this is satisfactory or if I misunderstood the request and you need more.  Thanks.

**Comment by thrust26** [comment]
Optimal would be a mail notification if a commit broke your build.

**Comment by m4xw** [comment]
https://git.libretro.com/libretro/stella/-/blob/master/src/libretro/Makefile#L106
Simliar to this I guess:
![image](https://user-images.githubusercontent.com/13141469/102801901-2cd1fc00-43b6-11eb-9698-b3954605af95.png)
You guys will need to give me your mails, then create your gitlab acc on our Infra.
Then I can assign you maintainer rights to the Stella repo and you will get notifications

**Comment by m4xw** [comment]
Tho I guess the underlying issue is that the libnx target clears cxx flags `CXXFLAGS := `

**Comment by sa666666** [comment]
I don't think any of us will have a problem giving emails or setting up a Gitlab account (although I can't say when it will happen, as we're very busy right now).

The main issue is that none of us has access to all these other platforms, so some of these things need someone very familiar with how libretro works.  If a piece of code breaks, then we can generally fix it.  But the build system itself for libretro is outside our experience.  I wouldn't even know where to start editing it to add C++17 support, nor if some of the platforms even support it.  That will need someone experienced with libretro build system setup.

**Comment by m4xw** [comment]
grep -lir libnx .
?

**Comment by m4xw** [comment]
Also no hurry on the emails, it fits me better if we can arrange it after the holidays/before new years

**Comment by thrust26** [comment]
I already have a GitLab account. How can I send you my mail address?

**Comment by m4xw** [comment]
Its independent on our infra, so your other account wont carry over.
You can post it here or send it to m4x a/t m4w (.) net

**Comment by m4xw** [comment]
*hope you see the edit :P

**Comment by thrust26** [comment]
Sent

**Comment by m4xw** [comment]
Done, check your spam folder, assign a pw.
You should have access granted

**Comment by thrust26** [comment]
I have. Now, how can I setup notifications for failed builds?

**Comment by thrust26** [comment]
And how can I login? Do I need a new user/password? The linked page doesn't let me sign in.

**Comment by m4xw** [comment]
You set the pw on the linked page and then you can login here https://git.libretro.com/users/sign_in
I set your username same as github

**Comment by m4xw** [comment]
Also check if you got the notifcation just now

**Comment by m4xw** [comment]
Your own specific notification settings are here https://git.libretro.com/-/profile/notifications

**Comment by thrust26** [comment]
Sorry, the linked page is https://git.libretro.com/libretro/stella. How and where should I set a password without being signed in?

**Comment by m4xw** [comment]
Via the invite that you just got via mail lol

**Comment by m4xw** [comment]
I think you are just looking at the notification when i set your repo rights lol

**Comment by thrust26** [comment]
Bahnhof

**Comment by m4xw** [comment]
One earlier mail

**Comment by m4xw** [comment]
Happens all the time with self hosted webservers lol

**Comment by thrust26** [comment]
OK, I found the notification settings. But I don't see an option to follow the (failed) builds only.

**Comment by m4xw** [comment]
Already turned it on for you, so you should get the failures now (tho the runner is very busy rn).
You should add the gitlab server to your contacts so it wont end up in spam
![image](https://user-images.githubusercontent.com/13141469/102805525-a02a3c80-43bb-11eb-9621-1c136158330d.png)

**Comment by m4xw** [comment]
> I set up 'Custom' for failed and fixed pipeline. That should do, no?

Yep

**Comment by thrust26** [comment]
OK, from now on I will get informed when our code breaks your build. After you have fixed the current problem that is...

**Comment by m4xw** [comment]
https://github.com/stella-emu/stella/blob/master/src/libretro/Makefile#L104 `:` -> `+`

**Comment by thrust26** [comment]
Sorry, make files mean little to nothing to me. :smile:

**Comment by m4xw** [comment]
Just change that char and it should work

**Comment by thrust26** [comment]
If you say so. 😆  Committed.

**Comment by thrust26** [comment]
How long until it shows up here?

**Comment by m4xw** [comment]
It will probably take a hour since i am currently running over 1000 jobs for our static platforms, afterwards it will be near instant again

**Comment by thrust26** [comment]
Do I really need maintainer right just for notifications? I don't plan to ever touch your code.

**Comment by m4xw** [comment]
@thrust26 Sure, changed it to reporter.
Double check your notifications settings and if they are still in place :P

**Comment by thrust26** [comment]
all still fine

**Comment by m4xw** [comment]
Seems to still be missin a include or smth
https://git.libretro.com/libretro/stella/-/jobs/51629#L39

**Comment by sa666666** [comment]
Honestly, I think the better approach here is if we roll our own compare function, rather than detecting the system (Windows, Linux, other, etc) and using non-standard functions like `strcasecmp` or `_stricmp`, etc.  That way, whatever new systems pop up in the future, we don't have to worry about this problem again.

**Comment by sa666666** [comment]
I'm working on redoing these functions to use C++17 string_view and comparing ourselves, and moving away from `stricmp` and `strcasecmp`.  This will fix the problem for good.

**Comment by thrust26** [comment]
Hm, now that the build got fixed, I would have expected a notification mail. But nothing arrived. 😒

**Comment by m4xw** [comment]
Actually... I didnt get a notification either this time...
Wonder if we broke some configuration...

**Comment by m4xw** [comment]
I will let a tester confirm the produced build, we may close the issue afterwards

**Comment by m4xw** [comment]
I got confirmation that it works on a quick test. This issue can be closed.
I will look into the notifications when i find some spare time.
@thrust26 You could try making a branch where you break the build on purpose

**Comment by thrust26** [comment]
Did not need a branch, I broke the main build. But no message.

**Comment by m4xw** [comment]
![grafik](https://user-images.githubusercontent.com/13141469/102920903-c6b7a880-448b-11eb-8468-18be0f1e5ef2.png)
They passed here fwiw.
Dunno how i couldve broken the notification tho, i guess i will bump you to developer for a test

**Comment by sa666666** [comment]
Game properties fall under `GUI_SUPPORT`, which isn't compiled into the libretro builds.  So that breakage wouldn't be seen there.

**Comment by thrust26** [comment]
Should we make a test and break the right code intentionally?

**Comment by sa666666** [comment]
Up to you I guess.  Change something in `bspf.hxx`; that's guaranteed to affect every port.

**Comment by thrust26** [comment]
Build failed but no notification. 😒

**Comment by m4xw** [comment]
So.. apparently only the Pipeline author gets the notifications for fixed/broken pipelines
This is stupid, lol.
I always got them bcz stuff uses my token but currently they go to our admin dummy acc for pull sync..

I will need to figure smth...
Thanks for your effort tho

**Comment by m4xw** [comment]
Link for ref https://docs.gitlab.com/ee/user/profile/notifications.html

**Comment by thrust26** [comment]
I just tried something...

**Comment by thrust26** [comment]
didn't work too

**Comment by sa666666** [comment]
Can we close this now?  Is the libnx build now working??

**Comment by m4xw** [comment]
>  This issue can be closed.

**Comment by sa666666** [comment]
OK.  I will look into getting added to the notifications sometime in the new year.  @thrust26 has already done it, so we can use his experiences here.
