### ISSUE TITLE
Effective address/value display

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#74]
It would be very helpful to display the effective address from a current indexed access (e.g. abs, x or even more (zp),y) before executing. It is displayed at the top besides the registers, but only for loads and only after execution. Also the value at that address would be very helpful before execution.

For ZP-Ram this address could be also marked before changing it. And maybe the same for TIA registers, maybe with an option to automatically switch to the relevant tab. Thinking about it, this would be nice even for non-index access. :)

**Comment by sa666666** [comment]
Pushing this to post-5.0 release, so we can get the 5.0 release done soon.

**Comment by thrust26** [comment]
That should do.
