### ISSUE TITLE
Open Stella documentation from Stella

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#740]
For providing help, it would be nice if we could add links in Stella, which open e.g. the documentation in a browser.

`SDL_OpenUrl` is in the [making](https://hg.libsdl.org/SDL/rev/7d7a72e4f9b6).

We could e.g. support pressing F1 in a dialog and/or add a '?' icon to a dialog's title bar.

**Comment by ale-79** [comment]
Nice! Hopefully this will cause more people to actually read the manual.

I don't know if it's worth opening an issue for this, so I add it here as it's loosely related...

What about a "url" field in the game properties?
In case the field exists for the selected game, a button could be displayed in the info viewer that will open the browser. The link could point e.g. to the personal page of the author, or to the AA store, to a page containig a scan of the manual, etc.

**Comment by thrust26** [comment]
> Nice! Hopefully this will cause more people to actually read the manual.

And ask less questions, that's the plan. 😈 

I like the URL idea. Though probably the links would age quite fast. @sa666666 What do you think about it?

**Comment by sa666666** [comment]
We have a few entries now that contain links.  Star Castle comes to mind.  The idea is fine, but as you say, the links can disappear.  I guess we can do it, and just update the links as appropriate.

This will have to be after the 6.5.3 release though; I am preparing for that now.

**Comment by thrust26** [comment]
> In case the field exists for the selected game, a button could be displayed in the info viewer that will open the browser. The link could point e.g. to the personal page of the author, or to the AA store, to a page containig a scan of the manual, etc.
