### ISSUE TITLE
Log triggered traps/break to file

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#741]
Instead of interrupting emulation, it sometimes might makes sense to log into a file instead.

Svolli:
>While thinking about how I can solve a problem very easily, I stumbled over the following feature request in the Stella Debugger: I would like to log into a file automatically when one or more specific TIA registers are written to. So it's like a trap/watch function that logs away:
>
> Frame: 12, Line: 78, Cycle: 100, GRP0: $00

**Comment by sa666666** [comment]
I guess sort of like the functionality from z26, where it did all its debugging to file instead of a debugger?

**Comment by thrust26** [comment]
Yes, but filtered to certain events.
