### ISSUE TITLE
Switch from Travis CI to GitHub Actions (or equivalent)

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#742]
It seems that Travis CI has had a change of policy, and as of Nov. 2 the Stella builds aren't being checked anymore.  Preliminary research has indicated that many projects are moving from Travis CI to GitHub Actions.  So I guess we need to do the same.

Ideally, I'd like to hear from someone that has actually done this before, to make the transition easier.

**Comment by KomeilParseh** [comment]
Hi, if you want, I can do it. I just had a few questions.
1. Is the compilation command different for each operating system?
2. Zip the output or push the binary file?

**Comment by sa666666** [comment]
Still looking for help/guidance on this.

**Comment by sa666666** [comment]
Thanks to @skitt for implementing this :+1:
