### ISSUE TITLE
macOS in dark mode makes About dialog hard to read

### ISSUE THREAD

**Issue by jschrab** [stella-emu/stella#748]
This is a VERY minor issue.
![Screen Shot 2020-12-25 at 9 09 38 AM](https://user-images.githubusercontent.com/1646232/103137749-61350900-4691-11eb-82e4-afd9dd68cd25.png)

Using macOS Catalina - 10.15.7 (19H2)

**Comment by sa666666** [comment]
Yep, noticed it over the past few releases, but forgot to add an issue, and hence forgot to look into it. :smiling_imp: We should be able to get it fixed for the next release.

**Comment by thrust26** [comment]
Hm, the dialog looks completely different in Windows. And well readable. Is that some built-in functionality in macOS?

**Comment by sa666666** [comment]
It's a Mac-specific thing.  In fact, I'm not even sure how you're viewing it in Windows. :question:

**Comment by thrust26** [comment]
![image](https://user-images.githubusercontent.com/24360774/103138745-e17d5d80-46d5-11eb-9108-30cb3f59efe8.png)

**Comment by sa666666** [comment]
OK, I see what you mean.  No, the one presented in the first post is something accessible from the Mac menu.  You only see it on the Mac; it's part of the native UI.

**Comment by DirtyHairy** [comment]
Yes, it's part of the Mac build. I can look into fixing it on dark mode when we do the next release, it should be trivial.

**Comment by thrust26** [comment]
Too late. :wink:

**Comment by sa666666** [comment]
Not really too late.  The fix I provided only works on 10.14 and up.  It's my understanding that there's a better way to do it, but I don't know enough about the Mac toolkits or Objective-C to look any further.

**Comment by thrust26** [comment]
Then maybe we should keep this issue open?

**Comment by sa666666** [comment]
I will tentatively assign @DirtyHairy to this.  If he feels he wants to re-open and work on it, then he can.  Otherwise we will consider it done for now.
