### ISSUE TITLE
Update FE to SCABS

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#753]
Following an Interview with Davie Crane the bankswitching should be renamed and update (swapped ROMs seem to have reversed banks) .
https://atariage.com/forums/topic/315497-david-crane-talks-about-his-scabs/

SCABS = Subroutine Controlled Automatic Bank Switching

**Comment by thrust26** [comment]
@sa666666 Shall we:
1. rename for 6.5.2?
2. wait?
3. not rename at all?

**Comment by andrew-davie** [comment]
It is known to most everyone who uses it, and certainly for at least the last 20 years, as "FE"
Yes, I understand DC called it SCABS but changing the name would just introduce confusion.
I am very much against renaming!!

**Comment by anonymous7002** [comment]
Why not call it "FE / SCABS" ?

**Comment by andrew-davie** [comment]
Haha yes OK, sorry you're right. But the issue literally says "Update FE to SCABS", so I had good cause.
