### ISSUE TITLE
Jakadapter not handled correctly

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#754]
The [Jakadapter](http://kair.us/projects/jakadapter/index.html) reports a Stelladaptor, but Stella can handle it only partially.

https://atariage.com/forums/topic/313085-stella-64-released/?do=findComment&comment=4720591

**Comment by sa666666** [comment]
It works in Linux for me, but confirmed to misbehave as described in Windows.  It's complaining about invalid mappings or something (with a fresh install).  Perhaps @thrust26 can follow up on this when he gets his Jakadaptor.  No testing done in Mac yet.  Upgraded to latest SDL 2.0.14 to eliminate any potential SDL issue.

**Comment by fdr4prez** [comment]
I have also noticed that this issue exists when using the Ultimate Flashback Interface adapter in Windows.

This is a single USB adapter that has two of the 2600-daptor D9 on it

**Comment by sa666666** [comment]
Yep, it's definitely an issue of one USB plug with two devices.  Works fine in Linux, so we need to concentrate on the Windows side. It may end up being something in SDL behaving differently in Windows.

**Comment by fdr4prez** [comment]
Thanks.

Just let me know if i can be of any further assistance - best reached via PM in AA

And a side note, my windows testing was in Win7 Ultimate

Once something is ready for testing or released, then i can test in Win7 and Win10 Pro

**Comment by sa666666** [comment]
I'm using Windows 10, so I don't think the version of Windows matters; it's happening in both.  I will follow up with you directly in PM if necessary.  We (the developers) will continue our discussion here, so we can all see it.

**Comment by thrust26** [comment]
Since it worked until 6.0.2 it cannot be Windows (only). Something in our code must have changed there too.

**Comment by sa666666** [comment]
It works as expected in Linux.  The first detected one is 'left', and the second is 'right'.

**Comment by thrust26** [comment]
It works in Win10 too. No problem with playing e.g. Combat. 

However the display in the joystick database is only partially correct, same for the System log.

![image](https://user-images.githubusercontent.com/24360774/118378240-ab803d80-b5d2-11eb-98e1-009e6ccbc2eb.png)
![image](https://user-images.githubusercontent.com/24360774/118378310-35c8a180-b5d3-11eb-9749-124d770bf878.png)

![image](https://user-images.githubusercontent.com/24360774/118378263-d8345500-b5d2-11eb-8c13-47bba1d5cd26.png)
![image](https://user-images.githubusercontent.com/24360774/118378272-e7b39e00-b5d2-11eb-830b-653a55da442c.png)

**Comment by sa666666** [comment]
Confirmed that the sticks themselves are working in Combat and River Raid.  But the labeling is incorrect.

After clearing the joystick database, plugging in the device, and starting Stella (in debug mode in Windows), the following text appears:
```
ignoring invalid joystick event
invalid controller mappings found for unknown joystick
```
However, the sticks still work.  After starting Stella a second time, the message no longer appears, but the sticks continue to work.

I agree it has to do with the order of enumeration, and I guess it always works in Linux just by chance.

**Comment by thrust26** [comment]
Yes, I saw this text too. 

However, the root problem is that we are swapping the SaveKey ports. Especially the code in `PhysicalJoystickHandler::add` is not prepared for this.
