### ISSUE TITLE
"Saverom" creates wrong file size with CDF(J) roms

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#756]
If you try to save a CDF - CDFJ rom with the "saverom" command from the debugger, the resulting file is 512Kb in size, with the actual rom in the first 32Kb and the rest filled with zeroes.

**Comment by sa666666** [comment]
Confirmed.

**Comment by thrust26** [comment]
The problem is the `CartridgeCDF` class, which always allocates 512KB, no matter how big the ROM is.
