### ISSUE TITLE
Quadtari support

### ISSUE THREAD

**Issue by mohhingman** [stella-emu/stella#758]
Hi, thanks for the new release.

Is there a reason why under Game Properties->Controllers that Quadtari is no longer in the list?

![quadtari](https://user-images.githubusercontent.com/8744551/105841337-29b6d500-6020-11eb-8902-3b6c073b31cf.png)

**Comment by thrust26** [comment]
The root cause was an undetected problem with the merge of the highscores branch with the master. Which worries me a bit.
