### ISSUE TITLE
Real Driving controller support broken

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#760]
With switching from 6.0  to 6.1 we broke the Driving controller support.

**Comment by thrust26** [comment]
Trakball/mouse are also not working via 2600-daptor. The reason is clear.

Now I wonder if it makes sense to create events in `PhysicalJoystickHandler`. Wouldn't it more sense to forward e.g. the axis input to the controller classes so that they can decide how to handle the correctly?

**Comment by sa666666** [comment]
Sorry, haven't had time to look into this.  Will try to find some time tomorrow, else over the weekend.

**Comment by thrust26** [comment]
No need to hurry, nobody complained for **years**.

**Comment by thrust26** [comment]
Some analysis of `PhysicalJoystickHandler::handleAxisEvent`:
- until Stella 6.0: Different cases for regular and Stelladapter (SA) joysticks. 
  - for regular joysticks, paddle events are mapped into dedicated SA events. 
  - other create joystick events (using ` Joystick::deadzone()`)
  - SA controllers create dedicated SA events (left/right controller, X/Y axis)
- since Stella 6.1: doesn't differentiate between regular and SA controllers
  - auto detects paddle input by value changes < 30000 (note: driving controllers create +/-32K, 0 and **+16K** values!)
  - other create joystick events (using ` Joystick::deadzone()`)

Note: `handleBtnEvent` also creates dedicated SA events in Stella 6.0, `handleHatEvent` does not.

In both versions: for dialogs joystick input (using ` Joystick::deadzone()`) is always assumed.  

Todo: How is a trackball/mouse via SA is handled?

**Comment by sa666666** [comment]
The reason this worked before is that 'daptor devices were being handled differently.  That's exactly why there was an enumeration type for each joystick; to determine whether a stick was 'REGULAR' or '_DAPTOR'.

And previously, these sticks couldn't be remapped.  My idea was that Stelladaptor, 2600-daptor should be completely plug and play, and not be remappable.  So they would act _exactly_ like a real system.  And because they were being handled differently, they completely bypassed the remapping system.

I don't think we can simply do a revert here; too much has changed since then.  We need to work out how to handle these types differently, within the current framework we have.

**Comment by thrust26** [comment]
That type numerations still exists. But I am not sure if we need it here.

The old code used `switch(myOSystem.console().leftController().type())` to handle controllers differently (or assumed joysticks). If we don't do that, we would have to transport the input into the dedicated controller classes and evaluate only there. Any mappings should be done there too. 

Maybe we should use `setEvent` instead, similar to what the old code did? Or we generally use dedicated axis events like the old SA axis events? Or we only remove the deadzone check (must done in the joystick classes instead) and create events as of now?

Else we would have to put more controller type specific code into `PhysicalJoystickHandler` and differentiate between analog, joystick and driving controllers before we create the events. Not sure if that's a good idea.

As you probably can see from my writing above, I have no clear cut idea how to handle this. Also I am quite unsure if I have gotten all details yet. The code is pretty convoluted here.

**Comment by sa666666** [comment]
I'm pretty sure that's why I initially had 'daptor stuff separate from mapping.  The mapping is at a higher level, but the 'daptor stuff was separate.  And I'm not sure this is a clean way to integrate them.

**Comment by thrust26** [comment]
But why was the 'daptor' stuff separate from regular joysticks then?

**Comment by sa666666** [comment]
> But why was the 'daptor' stuff separate from regular joysticks then?

For exactly the issue you're seeing now.  Stelladaptor support does 'weird' things, different from a normal joystick.  Its axes events needed to be processed differently, so they had to go to the `Joystick` class directly, rather than be pre-processed by the mapping subsystem.

Or maybe I'm mis-remembering how this worked?

**Comment by thrust26** [comment]
Then maybe the SA should become the norm, no? 

Anyway, I still have to figure some stuff to really understand this. E.g. why does the driving controller use **two** axis events plus direction events. Or what is the booster grip doing with the "half move" stuff???

**Comment by sa666666** [comment]
Some of it is probably documented in z26 code.  Stelladaptor support was added for z26 first, and adapted for Stella later.

**Comment by sa666666** [comment]
Maybe something useful here too:
http://www.grandideastudio.com/wp-content/uploads/stelladaptor_manual.pdf

**Comment by sa666666** [comment]
I just quickly looked through the relevant z26 code, and I can't find reference to this 'half-axis' idea.  So honestly I forget where it came from :anguished: 

I think we need to go back to the beginning here, and determine exactly what the Stelladaptor is outputting.  Then we can fix the code.

**Comment by thrust26** [comment]
Do you have all these controllers?

**Comment by sa666666** [comment]
Yep, pretty sure I have them all.  Except for Mindlink, KidVid and an NTSC Compumate (I have a PAL one), I think I have everything.  And also a Stelladaptor and all versions of 2600-daptor (v-I, v-II, D9).

The 2600-daptor developer (Tom) is very helpful, and I'm sure we can get the info from him.  It's just finding time to do it is the problem, for me at least.

**Comment by thrust26** [comment]
I will write him a mail.

**Comment by thrust26** [comment]
Got feedback from Tom. He says the besides the half-moves (which are only used when left/right or up/down are pressed simultaneously) there is nothing special.

Meanwhile I refactored the `Joystick` class and derived `Booster` and `Genesis` from it. Makes things a bit more clearly laid out.

**Comment by thrust26** [comment]
I decided to revert some changes. There will be separate handling between regular and Stelladaptor joysticks again.

**Comment by sa666666** [comment]
As long as we do some extensive testing.  I'm always a little afraid of changing code that hasn't been touched for years.  Sometimes _there be dragons there_.

**Comment by thrust26** [comment]
I can only test so much. You have to make the other tests with the other adapters and controllers.

**Comment by thrust26** [comment]
The last commit fixes the driving controller issue. In the end I reverted the code for the DC only, because it is the only exception required. All other controllers should work the normal way.

@sa666666 Can you test the Booster (is the Genesis supported yet?) and Keyboard controllers via SA, please?

**Comment by sa666666** [comment]
Sorry, only getting back to this now.  Exactly what do you need me to test again?  Driving, Booster, Keyboard with Stelladaptor, is that all?

**Comment by thrust26** [comment]
I tested Driving myself already. But Genesis needs testing too.

**Comment by sa666666** [comment]
Confirmed, tested Driving, and it's working fine for Stelladaptor, 2600-daptor.

**Comment by sa666666** [comment]
Keyboard works on a 2600-daptor D9.

**Comment by sa666666** [comment]
I don't actually have a Genesis controller.  Thought I did, but it's actually one for a Sega Master System.

Having trouble getting the 2600-daptor D9 to recognize a BoosterGrip controller.  This is outside Stella; I can't get the adaptor itself to see it.  I have to speak to Tom about that one.

**Comment by thrust26** [comment]
Can we close this one?
