### ISSUE TITLE
Birthday Mania B/W not skipping the intro

### ISSUE THREAD

**Issue by anonymous7002** [stella-emu/stella#761]
"1. This is a paddle game (left port)
2. Left difficulty switch in A=narrow blast, B=wider blast
3. Reset starts new game
4. Select not used
5. B/W switch, Color position shows and plays Happy Birthday screen, **B/W position skips intro screen**
6. Right difficulty switch in A=single blow mode, B=continuous blow mode
7. The game pauses between waves and only starts the new wave when the fire button is pressed or if it is being held down.
8. Enjoy!"

When I set TV setting to B/W position in Stella, and reset the game with Ctrl+R, the intro screen is still there.

Also, it says "Pause pushed". Is this intended?

[Birthday Mania (USA).zip](https://github.com/stella-emu/stella/files/5897526/Birthday.Mania.USA.zip)

**Comment by thrust26** [comment]
When you reload a game with Ctrl+R, the default switches defined for the game are loaded. Be default this is Color for the Color/B&W switch. If you want to skip the intro screen permanently you have to change the default in Game Properties.

When does the game say "Pause pushed"? I suppose you mean the pause mode in Stella which displays "Paused"? Which is intended when you press the pause key.

**Comment by anonymous7002** [comment]
When I press the Color/B&W button, it says either "Pause pushed" or "Pause released".

**Comment by anonymous7002** [comment]
https://user-images.githubusercontent.com/57062013/106351137-07081300-62e3-11eb-9ce9-cdd548feb499.mp4

**Comment by anonymous7002** [comment]
https://user-images.githubusercontent.com/57062013/106351164-3ae33880-62e3-11eb-9d31-eb58e6f067eb.mp4

**Comment by thrust26** [comment]
Which OS are you using? Or are you on a R77? 
And which button are you pressing?

Looks like you have selected to use the 7800 console. See Options/Developer Settings/Emulation/Console, change to 2600.

**Comment by thrust26** [comment]
@anonymous7002 Is this still an issue?

**Comment by anonymous7002** [comment]
No.
