### ISSUE TITLE
"None"-option for controller port settings

### ISSUE THREAD

**Issue by anonymous7002** [stella-emu/stella#764]

**Comment by sa666666** [comment]
Why would this be necessary?  Joysticks are the default if nothing is specified, so why would an empty port be needed?

**Comment by anonymous7002** [comment]
When playing, you may accidentally hit Player 2 buttons if there's no option to disable it.

**Comment by thrust26** [comment]
Hm, I thought either the games (or variants) are two player or the input for the 2nd player is ignored.

Can you give an example where what you describe can happen?

**Comment by thrust26** [comment]
@sa666666 I think we can close this one.

**Comment by sa666666** [comment]
Yep.
