### ISSUE TITLE
Unable to map gamepad analog stick in Input settings

### ISSUE THREAD

**Issue by anonymous7002** [stella-emu/stella#767]
I'm unable to map my Logitech F310 sticks. It just says "Select action for 'event' event"
I'm still able to map buttons of the gamepad.
When I reset the inputs the default, the sticks get mapped. Stick inputs still work in games.

**Comment by thrust26** [comment]
Have you tried both settings of the gamepad?

**Comment by anonymous7002** [comment]
I tried both. Not working.

**Comment by thrust26** [comment]
Which actions do you want to map? And with which input of the controller?

**Comment by anonymous7002** [comment]
Wait, could it be because the analog stick is not reaching the exact full range?

**Comment by thrust26** [comment]
It has at least to exceed the joystick deadzone value set in Options/Input/Devices &Ports.

**Comment by anonymous7002** [comment]
That was the case. I set the deadzone to 5200 and now it works.

**Comment by thrust26** [comment]
Thanks for reporting back.
