### ISSUE TITLE
Add support for KidVid controller

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#77]
There is already a partial implementation in the current code, but it doesn't really do much (in particular, it doesn't play any music).  Much of the current implementation is from a C-code port of z26.  The original was in assembly, so I can't be sure if the C code is even working correctly.

**Comment by thrust26** [comment]
Back then, I worked very closely with Eckhard on this. Maybe I can remember.

**Comment by thrust26** [comment]
@sa666666 If KidVid works in the latest z26, then its C-code should work well too.

**Comment by sa666666** [comment]
Potentially, but I haven't tested recently.  But in z26, the code isn't as abstracted, and KidVid and sound code is mixed together.  Also, it would need testing, and you already pointed out that you found it _very_ annoying :anguished:

**Comment by thrust26** [comment]
> ...you already pointed out that you found it very annoying

If you test a game, you will soon find out why. 👿

**Comment by thrust26** [comment]
BTW: Kid Vid can be autodetected easily (lda #$03, sta SWACNT), but I suppose since there are only two ROMs, it is not worth the effort.

**Comment by thrust26** [comment]
It just occurred to me that, if we get this going (and maybe make it a bit more flexible), people could write games for the 2600 with a synced, high quality soundtrack. 

At least in Stella, for the console some extra hardware would be required.

**Comment by thrust26** [comment]
I had a closer look at the existing code. It seems like signalling back doesn't work and the "tape" continues to run after a song is over.

**Comment by sa666666** [comment]
There was never any attempt to get this working in Stella, so it doesn't surprise me.  I just converted the z26 C code to C++, and left it as-is.  There's likely more work to do there, other than what you suggest.

**Comment by thrust26** [comment]
The z26 code is pretty easy to understand. And the converted code should do the same. IMO we are pretty close.

**Comment by sa666666** [comment]
My main issue at the time was how to integrate the songs into the TIA sound core, just as you mention.  In z26 it's sort of hacked into in the sound core directly, but I'd rather use a better approach here.

**Comment by thrust26** [comment]
Sure, me too.

**Comment by thrust26** [comment]
> The z26 code is pretty easy to understand. And the converted code should do the same. IMO we are pretty close.

Success, the games can now really be played **without** the tapes (**waaay** more pleasant, IMO 😆)

So, the last (and big) ToDo is to add the tape sound.

**Comment by thrust26** [comment]
We could play the WAV files directly via SDL2 or sample them ourselves (like z26). The former should be easier, but syncing might be a problem.

BTW: There can be TIA sound and WAV files simultaneously.

**Comment by sa666666** [comment]
Should we add an option to disable playing the WAVs with these ROMs?

**Comment by thrust26** [comment]
Just remove the WAV files if you feel annoyed. 😈

**Comment by sa666666** [comment]
Not for me, for the end user.  Something similar to the frequency toggle for Pitfall II.  Or we can just add it to the manual, to remove the WAV's if you like.

BTW, now that we (or more specifically, you) are working on esoteric controllers, want to look at Compumate next? :smile:

**Comment by thrust26** [comment]
> Not for me, for the end user. Something similar to the frequency toggle for Pitfall II. Or we can just add it to the manual, to remove the WAV's if you like.

The latter. I think we have to explain where to put the WAV files anyway.

 > BTW, now that we (or more specifically, you) are working on esoteric controllers, want to look at Compumate next? 😄

Definitely not.

**Comment by sa666666** [comment]
OK, it was worth a try :smiling_imp:
