### ISSUE TITLE
Ebivision Pac-Man gets corrupted after loading a game in the same directory

### ISSUE THREAD

**Issue by anonymous7002** [stella-emu/stella#770]
This persists until the emulator is closed.
https://user-images.githubusercontent.com/57062013/107234936-d9327500-6a2c-11eb-800e-cfd3b648bc3b.mp4
http://www.atarimania.com/game-atari-2600-vcs-pac-man_13367.html

**Comment by thrust26** [comment]
Do you have any special settings? Anything different from default?

BTW: The launcher looks odd. No title bar and no buttons. What OS are you using?

**Comment by anonymous7002** [comment]
I had the footage cropped because the folder had my name in it, and cropping it was the easiest solution.

**Comment by anonymous7002** [comment]
The game only gets corrupted after loading the game from the **same** directory. After the corruption has happened, loading the game from a different directory does not fix it.

**Comment by thrust26** [comment]
That is Stella version 6.5.1, right?

**Comment by thrust26** [comment]
That's a bug in the game itself. During initialization it does not clear the decimal flag. 

I only wonder why this only happens when you load another game before. Chances should be 50:50.
