### ISSUE TITLE
Libretro core broke down (3c188fbb9)

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#771]
Hi there,  the libretro core builds appear to be broken after this commit -

https://git.libretro.com/libretro/stella/-/commit/3c188fbb9a84818896171b89d516f8eef46d4301

https://git.libretro.com/libretro/stella/-/pipelines/13827

**Comment by thrust26** [comment]
Hm, is that the leading `const` in `Thumbulator::stats()`?

**Comment by sa666666** [comment]
I think the line should be `const Thumbulator::Stats& stats() const`.  But I don't see why it would cause an error.  It gives me a warning if I don't use the line above.

**Comment by sa666666** [comment]
Correction: the above fixes it (ie, remove the `CartridgeCDF::` from before `stats()`.

**Comment by thrust26** [comment]
Grrr, I really, really, **REALLY** wish VS would catch this.
