### ISSUE TITLE
VSYNC & RSYNC manipulations

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#775]
https://atariage.com/forums/topic/224946-smooth-scrolling-playfield-i-think-ive-done-it/?do=findComment&comment=2988451

To our understanding this trick works by shaping the TV signal using timed VSYNC and RSYNC writes. Emulating this would require a simulation of the TV signal generation and decoding, and we don’t think this is worth it.

**Comment by andrew-davie** [comment]
The challenge now is to write some games that Stella can't run :)

**Comment by DirtyHairy** [comment]
Do I hear someone volunteering to rewrite Stellas screen rendering code and add a TV simulation? 😛

**Comment by andrew-davie** [comment]
I do understand the Stella team's position on this.
I'll just close by saying that the latest Gopher2600 emulator appears to be emulating this perfectly.
The binaries posted, in other words, are working as advertised.

**Comment by andrew-davie** [comment]
To be clear I appreciate Stella and all that it does. I agree that this is a marginal case and not worth pursuing, given the amount of work involved. The point of posting about Gopher2600 was more my incredulity that the author implemented it in a day, so it might be worth checking out how that was done.
