### ISSUE TITLE
Feature request: Star Raiders Video Touch Pad Control 

### ISSUE THREAD

**Issue by Cibomatto2002** [stella-emu/stella#776]
Will the Star Raiders Video Touch Pad Control ever be added?

**Comment by thrust26** [comment]
AFAIK that is the same as a Keypad, which is already supported

**Comment by sa666666** [comment]
Yes, various games called it Touch Pad, Keypad and Keyboard controllers.  It's all the same thing, and has been emulated for ages (15+ years).  In the Stella UI it's called 'Keyboard' controller.

**Comment by Cibomatto2002** [comment]
oh ok thanks is it in Retroarch to?

**Comment by sa666666** [comment]
That part I cannot say.  I don't maintain the RetroArch port.  But it would be easy enough to have their maintainers add it, I think.

**Comment by Cibomatto2002** [comment]
ok i will go there and ask them bout it thanks for your time. :)
