### ISSUE TITLE
Stella.ini

### ISSUE THREAD

**Issue by github-fanuser** [stella-emu/stella#782]
I am using version 6.5.2. I have the Windows zip format. I run the 64 bit version.

I just discovered that the Stella.ini file in AppData > Roaming > Stella is no longer used. I delete the Stella folder and Ran Stella. It recreated the folder, but the .ini file does not exist? Where does Stella store the settings?

i look at version history on the webpage, but saw no mention of this change. What version introduced this change?

**Comment by thrust26** [comment]
The INI file got replaced by an SQLite database. Please have a look at the documentation for more info.

Changes are documented in the file "Changes.txt" which comes with every download.
