### ISSUE TITLE
Truncated view of RAM during debug of E7 cart

### ISSUE THREAD

**Issue by vitococl** [stella-emu/stella#784]
The Cartridge RAM view includes 3 sections: RAM size, Description and data grid.

The data grid has a vertical control to change between memory pages (00xx to 07xx), but the grid is missing its last line (yyFx).

![image](https://user-images.githubusercontent.com/14372100/113289390-89528a80-92c6-11eb-907d-3f0669fede1b.png)

I guess that the Description section changes its size depending on the banking scheme, and E7 seems to have a long description, making the data grid to move down with part of it out of screen.

To fit the data grid in the screen, I'd suggest to limit the Description section up to a maximum height and allow it to have a vertical scroll control.

Thanks!

**Comment by thrust26** [comment]
Have you tried to change the debugger windows size? Or a smaller font?

**Comment by vitococl** [comment]
The debugger is of a fixed size. I cannot even maximize to the whole screen using Windows controls.

I tried the small font, but it only changes the dialogs in the game view. The debug window seems to not be affected by that setting.

Might I be looking at the wrong place?

**Comment by thrust26** [comment]
You have to look under Developer settings.

**Comment by vitococl** [comment]
OK, I found it.

The height was at the maximum of 739, which is less than 770 that is is shown in the docs. (*)

Changing the font size to Small allowed me to see (after a restart) a 4th section: Label.

(*) Where the window size limits are got from? Main/default system display? Current display? Might it be an issue here?

Thanks...

**Comment by thrust26** [comment]
The maximum height is taken from your display's vertical height. What resolution are you running?

**Comment by vitococl** [comment]
I have 3 screens:

1: 1366x768 (notebook's screen)
2: 1024x768 (VGA port)
3: 1600x900 (HDMI port)

I'm running Stella in screen 3. It is where it opens when I double click on a .BIN file. Might it took the screen size from the first time I run it and not the current one?

If this matters, the screens are not vertically aligned... the total screen size is 3990x1132.

**Comment by thrust26** [comment]
739 could fit to the notebook, I suppose it shows a taskbar?

When you go to the settings, the screen size is checked. Is the debugger also running on the 3rd screen?

**Comment by vitococl** [comment]
The task bar in the main screen is not at the bottom but at the right side (for easy access from the 3rd screen).

![image](https://user-images.githubusercontent.com/14372100/113301582-8e6b0600-92d5-11eb-9495-8bc42a44412c.png)

Both Stella and the debugger are running on the 3rd screen.

BTW, can both be run at the same time on different displays instead of to jump from one to the other on every change between run and step modes at a breakpoint?

**Comment by thrust26** [comment]
> BTW, can both be run at the same time on different displays instead of to jump from one to the other on every change between run and step modes at a breakpoint?

No. Currently Stella only allows one surface at a time.

**Comment by sa666666** [comment]
It would be nice to add something like this in the future, but right now, there are just too many other things having higher priority.

**Comment by thrust26** [comment]
I still don't have an idea why the vertical size is limited to 739.

**Comment by vitococl** [comment]
Reading the docs, I found that what I proposed in my original post (add a vertical scroll control in the description object) already exists, at least for other banking schemes:

https://stella-emu.github.io/docs/graphics/debugger_ram-f8sc.png

BTW, I tried some command line options to force a higher resolution, unsuccessfully.

**Comment by thrust26** [comment]
Ok, I found the reason (max. size always taken from 1st display) and will create an issue (#786).
