### ISSUE TITLE
URL in Game properties

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#788]
In case the field exists for the selected game, a button could be displayed in the info viewer that will open the browser. The link could point e.g. to the personal page of the author, or to the AA store, to a page containig a scan of the manual, etc.

_Originally posted by @ale-79 in https://github.com/stella-emu/stella/issues/740#issuecomment-822447986_

**Comment by thrust26** [comment]
@ale-79
Now that this has been implemented, we need some more links. 😈

**Comment by ale-79** [comment]
I'll try to compile a list of possible links.
For homebrews, a link to the AA store (or other site if they're sold elsewhere) might do in most cases.
A link to "AtariProtos" would be nice for prototypes.
I'm not sure it's worth adding URLs for the all the original games (e.g. to Atarimania), as it would be a huge list to maintain up to date.

**Comment by thrust26** [comment]
> For homebrews, a link to the AA store (or other site if they're sold elsewhere) might do in most cases.

Maybe Albert supports affiliate links. 😆

**Comment by sa666666** [comment]
I guess this one can be closed now?  The functionality is there; we just need people to submit info to add to the properties.

**Comment by thrust26** [comment]
I want to keep it open until we have at least an initial list of URLs.

**Comment by ale-79** [comment]
So far I added URLs to the homebrews which already have entries in Stella.pro.
[stellapro_urls.zip](https://github.com/stella-emu/stella/files/6420303/stellapro_urls.zip)

**Comment by thrust26** [comment]
Now we can close this. 😈

**Comment by sa666666** [comment]
We can ask for more on AtariAge too.

**Comment by ale-79** [comment]
Added links to AtariProtos.com in this one:
[stellapro_protos_urls.zip](https://github.com/stella-emu/stella/files/6429306/stellapro_protos_urls.zip)

**Comment by thrust26** [comment]
Cool. Will add them too.
