### ISSUE TITLE
Enhance StaticTextWidget for URLs

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#789]
> Probably easiest to extend StaticTextWidget with a 'clickable' option, and then draw it differently (perhaps with an underline or something). We can have it change colour when entering or exiting, and respond to the click. All that functionality is already there.

We should to consider mixed texts too, where the URL is only part of a longer text.

**Comment by sa666666** [comment]
Hmm, getting dangerously close to implementing a mini-HTML parser.

**Comment by thrust26** [comment]
Yes. But else it won't be very easy to use.

**Comment by sa666666** [comment]
I suppose it's not _that_ bad.  We already do something similar for printing text in different colours; the colour is embedded in the string itself.  We just need to add 'tags' around what we want as a link.  Same idea, really.

**Comment by thrust26** [comment]
Yup. And we have to detected where the link starts and ends.

**Comment by sa666666** [comment]
No, we can't use that code directly.  I meant that we're already doing _something_ like what is required.  So it won't be _too_ hard to add.  We have a very good idea how it will work.

**Comment by thrust26** [comment]
@sa666666 
I am implementing this with two options, one where the link is displayed as is (www.google.com) and one where the link is displayed as a label ([Google](www.google.com)). Which one would you prefer for the `AboutDialog`?

**Comment by sa666666** [comment]
The links in `AboutDialog` are doing the former (listing the entire address).  So I guess we can stick to that.

**Comment by thrust26** [comment]
I know, I just wanted to know if you prefer something different now that it is possible.

**Comment by thrust26** [comment]
Done
