### ISSUE TITLE
Switching renderer blanks screen

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#794]
This once used to work. 6.5 breaks it.

**Comment by sa666666** [comment]
Yep, I've seen that at some times.  It has to do with updating the textures on a video change.  I meant to report it, but I forgot :frowning:

**Comment by thrust26** [comment]
While testing I also got flickering video, where the dialog was displayed enlarged on the emulation surface. Maybe there is some initialization missing?

**Comment by sa666666** [comment]
I know how to fix this; there is only one last thing to figure out.  I have the diff here, from Feb. 21.  I was supposed to come back to it after the 6.5 release, but I completely forgot about it.  My memory is not what it used to be.  Can you wait on this one, until I'm ready to come back to it?  Or is it delaying you working on something else?

**Comment by thrust26** [comment]
No problem, go ahead as you like.

**Comment by thrust26** [comment]
@sa666666 I cannot reproduce the issue. Did you fix it?

**Comment by sa666666** [comment]
I think I fixed it when I reverted back to storing a list of surfaces in `FrameBuffer` instead of using RAII and letting each surface clean up after itself.  I can no longer reproduce it either.

**Comment by thrust26** [comment]
Then we can close this one.
