### ISSUE TITLE
Stella 6.5.3 Wizard of Wor homebre controls not work

### ISSUE THREAD

**Issue by Augusto7743** [stella-emu/stella#795]
Stella 6.5.3 64 bits Linux works correctly for several games.
Wizard of Wor homebrew demo 20190812 controls left not work.
That homebrew use savekey.
I not known if others games using savekeys are with same problem.

**Comment by Augusto7743** [comment]
Using keyboard.
Other games control left works.
In libretro stella also galagon controls not work , but in Stella bin works.
That's a bug.

**Comment by thrust26** [comment]
Do you mean:
- controls for left player?
- control + left key?
- left control key?

Also: please post the ROM here.
