### ISSUE TITLE
Make port naming consistent, always use left/right

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#796]
Instead of using P0, P1... for events, we have to align the naming to other parts of Stella (left/right).

@DirtyHairy Migration is yours. 😈

**Comment by twinaphex** [comment]
Hi there, I believe this commit broke the libretro port.

See here for more details -

https://git.libretro.com/libretro/stella/-/pipelines/24595

**Comment by sa666666** [comment]
Yep, working on it.

**Comment by twinaphex** [comment]
Thanks.

**Comment by thrust26** [comment]
@sa666666 Thanks, but shouldn't I fix it?

**Comment by sa666666** [comment]
Already done.  I fixed it, since I'm able to test the libretro port much easier than you can, I think.

**Comment by thrust26** [comment]
true

**Comment by twinaphex** [comment]
Thanks, seems all fixed now.

**Comment by thrust26** [comment]
TODO: Migration from old to new event names.
