### ISSUE TITLE
suggestion: zoom options

### ISSUE THREAD

**Issue by shentino** [stella-emu/stella#801]
I'd like to suggest the following options be implemented:

* Ability to preserve a 1:1 aspect ratio of X vs Y
* Ability to restrict zoom factor to an integer, to avoid interpolation and fuzzy edged pixels
* Ability to automatically select the zoom factor based on the window/screen size, with or without enforcement of option 2 of integer zoom factor
* (assuming this is already the case)  Automatic centering of the rendering area within the window

My personal ideal:

Fullscreen, square pixels, zoomed out as far as possible while preserving an integer zoom, centered with the "slack space" painted black.

**Comment by thrust26** [comment]
This is e.g. Combat with square pixels. Why would you want that?

![image](https://user-images.githubusercontent.com/24360774/120095182-d2875500-c124-11eb-98c0-49df01e0b597.png)

**Comment by shentino** [comment]
by square pixels I mean a 1:1 aspect ratio

**Comment by thrust26** [comment]
Stella does 1:1 aspect ratio by default.

**Comment by shentino** [comment]
cool ^^  what about the rest of the idea, with the integer zoom and auto centering and auto zoom?

They're fairly orthogonal and mutually optional

**Comment by thrust26** [comment]
- Correct 1:1 aspect ratio and no interpolation are mutually exclusive. 2600 pixels are not square, they are about 1.6:1. You can disable correct 1:1 aspect ratio in the video settings.
- You can zoom to integers yourself, just skip the intermediate ones.
- You can get to maximum zoom if you use fullscreen mode.
- Fullscreen is centered automatically

So everything is just already there. Have a look into the docs and play with the settings.

**Comment by shentino** [comment]
oooh, thanks I wasn't aware of that.

I guess I have a fixation on how fceux does it.  Though they do allow a window to be maximized without going into full screen mode, which does preserve access to the frame
