### ISSUE TITLE
Option "Drive unused TIA pins randomly..." breaks Centipede

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#81]
With this option enabled, Centipede detects a VSYNC at $d864 (multiple PLA/PHA).

I am not sure how the option works here, the bug looks more like the stack pointer handling error.

Codebreaker is affected too. Here it also breaks the debugger, e.g. rewind not possible. Here INC $40 (VSYNC|$40) is the reason.

**Comment by ale-79** [comment]
Other original and homebrew games that are broken or show glitches with the "tiadriven" option are:

Dodge' em
Haunted House
Berzerk
Chetiry GB ([https://atariage.com/forums/blog/107/entry-8063-chetiry/?st=20](https://atariage.com/forums/blog/107/entry-8063-chetiry/?st=20))

In these games the problem is a bug in the code and not in Stella (zero page loads instead of immediate).

**Comment by thrust26** [comment]
Its a bug which is incorrectly emulated. Which is a bug. :)

**Comment by ale-79** [comment]
It doesn't happen on real hardware most of the time, but it could for example (see here: [http://atariage.com/forums/index.php?automodule=blog&blogid=142&showentry=2715](http://atariage.com/forums/index.php?automodule=blog&blogid=142&showentry=2715)).

I think the "tiadriven" option the way it is implemented now is a useful debugging tool. It just should be left off by default.

**Comment by DirtyHairy** [comment]
My understanding of `tiadriven` is precisely this: a debugging tool that helps in detecting invalid reads Turning it on will differ from the behavior of real hardware by definition :smiling_imp:

**Comment by thrust26** [comment]
OK, if we agree that it is a debugging tool, we can close this one. 

It should be mentioned in the debugger manual.

**Comment by sa666666** [comment]
I forget who asked me to add this, but it was indeed meant to be a strictly debugging tool, and to be disabled by default.  I think the original idea was that a game should work whether it is enabled or disabled, and you could use it to check whether new code is working correctly.  But there are _many_ old ROMs that break with this turned on, which IMO indicates improper programming (but nothing we can do about it now).

So, the fact that it breaks old ROMs indicates a potential bug in the ROM programming, not in the tiadriven option itself.  It is mentioned in the manual, but perhaps not in as much detail as I just stated.  I will update the manual accordingly.
