### ISSUE TITLE
Stella crash when exiting to launcher (was: Stella possibly preventing other applications from using keyboard input)

### ISSUE THREAD

**Issue by splendidnut** [stella-emu/stella#810]
After I've used Stella for a bit and then left Stella open on the menu screen, other programs are prevented from receiving keyboard input.  This has happened numerous times with a few different applications being affected, so it seems this is an issue with either Stella eating keyboard input, OR something weird is going on with my setup.

This is happening on a relatively new Windows 7 64-bit install with Stella 6.5.3.  I'll try switching back to an older version to see if the problem still occurs.

**Comment by thrust26** [comment]
Can you give examples? Which programs are not receiving input while they are focused?

**Comment by splendidnut** [comment]
CLion and Notepad++ are the two applications where I run into the issue the most.  When it happens, if I close Stella, functionality is restored.  It only seems to occur after Stella has been running for a while and I've switched back and forth between Stella a few times.

**Comment by thrust26** [comment]
I have Notepad++, but I cannot reproduce your problem.

In which mode is Stella running? Fullscreen or not, in game, dialogs or launcher? Or everything mixed?

**Comment by splendidnut** [comment]
Stella is running in windowed-mode, usually just sitting at the launcher when it happens.  When switching apps, I'm not sure whether it's occurred only when I've Alt-Tabbed or when I've used the mouse to switch.  I typically use either one depending on what I'm doing.

It only happens on rare occasions so it's really hard to reproduce on purpose.  I've tried the last 15 minutes or so and haven't been able to.

**Comment by thrust26** [comment]
Thanks! Please let us know when you spot a pattern.

**Comment by DirtyHairy** [comment]
I'm pretty sure that this is an SDL issue, maybe a conflict with some other program. Iirc we never explicitly grab the keyboard in Stella. Do you have some other service running that may be tampering with keyboard I/O?

**Comment by splendidnut** [comment]
I mainly have just a couple of editors open.  Though I do occasionally remote into this PC from another using Remote Desktop, which may be setting me up for failure.

Not sure if this would be related, but I just had a crash using the Escape key, trying to exit a ROM:

![image](https://user-images.githubusercontent.com/61911172/126910763-d177ece0-b1dd-4527-bf91-7b274e5fe7d2.png)

**Comment by DirtyHairy** [comment]
Hm, I can't image how the crash would be related, but is there perchance a stack trace hiding further down that dialog?

**Comment by splendidnut** [comment]
No stack trace, just some additional info (potentially useless?)

  Exception Code:	c0000005
  Exception Offset:	0000000000001214
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	46ba
  Additional Information 2:	46ba7189f11e243c121242d121a3c511
  Additional Information 3:	d5a0
  Additional Information 4:	d5a04a96bbd9424227756b771ee94fd0

**Comment by thrust26** [comment]
Theoretically it should be possible to track down the source code for this. But since the error happens in MSVCRT.DLL, I suppose this not the place of the root cause of the problem. For that we would need a stack trace.

**Comment by thrust26** [comment]
@splendidnut It the problem still there? Or did you maybe find a pattern that causes the bug?

**Comment by thrust26** [comment]
Ok, thanks. I will try if I can replicate the crash. Let us know when you spot a pattern.

And I will rename the issue.

**Comment by thrust26** [comment]
@splendidnut Any update? The crash never happened to me.

**Comment by splendidnut** [comment]
I haven't really run into this issue with 6.7.  It's probably safe to close this.
