### ISSUE TITLE
Highscores auto save

### ISSUE THREAD

**Issue by mowses** [stella-emu/stella#813]
Hello everyone

I am just trying to implement a highscore auto save for every time a game session finishes.
The problem is how do I know when the game finishes? I searched through Stella source code and did not find anything. Then it made me believe that the emulator never knows about such event since it is a "ROM thing".
For such situation I am thinking out of the box, trying to make my way to it. So I came with the Idea of testing some sort of flag/memory address which could tell me: "the session is over, the user is no longer playing the game"...
My first guess was to search for player collision flag because in many games this flag is disabled when the ROM is in the "auto play" mode (despite de fact this is not 100% true for a lot of games either).

So before I get dive in such endeavor I would like to ask you guys for your ideas.
I appreciate any feedback.

**Comment by thrust26** [comment]
Do you want to extend the existing high score saving feature in Stella? While implementing it, I also wondered if it would be possible to detect a game over state. But every game is different here, often it is not just one flag, but a combination of flags. It could be e.g. a bit set or cleared or a life counter reaching zero or -1. Anyway, it became to complicated, so I decided to let the user define when the game is over by manually pressing a hotkey.

**Comment by andrew-davie** [comment]
Maybe it would be possible for a sort of "training" mode for games.
In stella you play a game, and then manually type in the score it shows. Do that once or twice and perhaps Stella can isolate the particular bytes (and format) of the score.  It might be BCD, or binary, or decimal -- but having a couple of instances to compare visible score against internal state might allow this simple process to create a registry entry for each game that allows Stella to monitor high scores and for new games to easily be analysed/updated. I'm assuming it would work; certainly would be reliable for most of my programming efforts.  Stella wouldn't need really to know the end-game state, just monitor the highest value these watched bytes reach. Of course there's the issue of overlapped variables, but again that might be possible to find with a sort of guided-yes/no training session.  Just some thoughts.

**Comment by thrust26** [comment]
I even failed when trying to create something semi-automatic for the High Score properties dialog. 😈 

![image](https://user-images.githubusercontent.com/24360774/129362617-aa668128-54d8-4420-a4de-40af22dc00e0.png)

**Comment by mowses** [comment]
I managed to do it, but instead of trying to detect game end state, I just bound an interval timer which saves/updates the player's score, and it does automatically without interrupting the gameplay.
Every time the game is reset, it finishes updating the score of the previous game, and then add a new row in the sqlite database for the new game session.
It works perfectly, but I did not used the best programming practices. shame on me 😳

You can look at diffs here https://github.com/mowses/atari-stella/commit/86bb32139e4b29d6bd889ad7c93332226b39bcd0#diff-507f63eefdd111cd2aa7a2affe3a87e646ea2369ab9e556fd692712d2d4d68ee

I will close this issue for now. Thanks for your replies guys!
