### ISSUE TITLE
Homebrew title screen jitters on hardware, but not Stella

### ISSUE THREAD

**Issue by kdgarris** [stella-emu/stella#816]
The image for the title screen for the beta version of Robot Zed jitters when displayed on hardware, but the issue does not show on Stella, despite developer settings being set, and "jitter" effects being enabled. The issue does show on Javatari, however.

The underlying issue in the ROM that caused the jitter was found and fixed, but the issue I'm reporting is Stella not showing the problem.

Note that the ROM that shows this issue is not public, and I have permission from the game developer to share it privately with a member of the Stella dev team if someone wants to take a look at this issue.

**Comment by thrust26** [comment]
Sure, you can send it to me: tjentzsch at yahoo dot de

**Comment by thrust26** [comment]
Seems to be a varying cycle when enabling VSYNC, right? Did you fix by adding a WSYNC before?

**Comment by kdgarris** [comment]
I guess I did, but I didn't realize that was what fixed it. I switched the
VSYNC portion of the title screen code to use the VERTICAL_SYNC macro
instead of the timer approach that the code used before, so in the process
I think that added a WSYNC before enabling VSYNC that wasn't present in the
previous code.

**Comment by thrust26** [comment]
Ok, then I will close this one as duplicate now.
