### ISSUE TITLE
(Libretro) Possible regression Android - crashes when trying to start a game

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#818]
Hi there,

I got a report by an Android user that in the latest builds of Stella, the following issue might exist -

```
With the latest build, the Atari 2600 emulator Stella crashes anytime you try to run a game. I am on a Google pixel 4a.
````

Is this reproducable to anyone? If need be I can try testing it myself on one of our own devices.

**Comment by sa666666** [comment]
Yes, I'm aware.  I'm working on it.

**Comment by twinaphex** [comment]
Thank you!

**Comment by twinaphex** [comment]
Just for checking up, is this still an ongoing issue?

**Comment by sa666666** [comment]
Yes, didn't have time to look into it before now.  Hope to find some time today to fix it.

**Comment by sa666666** [comment]
The crash is fixed for now, but in the process it disables rewind support.  I need to research further why this is happening.  But at least it isn't crashing.

**Comment by twinaphex** [comment]
If it disables rewind support, it means that something is wrong with the serialization of the state now. This would also affect runahead reliability, which is important for a lot of people to drive latency down.

**Comment by sa666666** [comment]
Yes, this isn't permanent.  I've created a separate issue to deal with the serialization not working.  I figured a segfault is worse than rewind not working, so I fixed that first.
