### ISSUE TITLE
Libretro rewind support not working

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#820]
This is related to https://github.com/stella-emu/stella/issues/818.  Rewind support was causing a segfault on startup, so I disabled it.  Until I get this issue fixed, rewind support is broken.

**Comment by thrust26** [comment]
Which line creates the problem?

**Comment by sa666666** [comment]
Yep, working on it.  I made some pretty extensive changes in the `Serializer` class for the Moviecart branch, and it broke state saving for libretro.  But not for any other system.

The error is ```https://github.com/stella-emu/stella/issues/818```

It seems to be related to what's described at https://github.com/fmtlib/fmt/issues/1666.
