### ISSUE TITLE
TV type detected wrong

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#831]
The attached two ROMs are detected as PAL, but they are definitely NTSC (262 scanlines).

[PAL.zip](https://github.com/stella-emu/stella/files/7229995/PAL.zip)

**Comment by sa666666** [comment]
These ROMs have 'PAL' in the filename, so they are forced to be PAL.  When I remove the PAL from the filename, the detection is working correctly.  This is intended behaviour; 'hints' in the filename override auto-detection.

**Comment by thrust26** [comment]
Your are absolutely right.

**Comment by ale-79** [comment]
Would it be possible to check for "PAL-M" in the filename and force NTSC mode in that case? 

There have been quite a few new dumps from Brazil lately, and I think there are good chances to find more roms that will be incorrectly forced in PAL mode for the same reason.

**Comment by thrust26** [comment]
Good idea.
