### ISSUE TITLE
Renderer memory leak

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#834]
I wanted to do some testing with Stella's MVC test directory and watched the memory consumption in Windows' Task-Manager.

- At startup Stella consumes 42 MB in the launcher. And this does not change if I browse the MVC files.
- When I launch any ROM, memory will decrease by ~4-8 MB.
- When I exit the ROM, the memory will **increase** by another ~8-16MB. About twice as much as the decrease before.
- The same overall increase of ~4-8MB happens for each file I open. Even just briefly and even it is the same file again and again. Happens in `FBSurfaceSDL2::render()` in `myBlitter->blit(*mySurface)`
- This happens for each file type, e.g. even a 4K ROM.

The memory increase happens in `OSystem::createLauncher` when `createFrameBuffer` is called. And it seems like this memory is not fully released when the launcher is closed.
And the same happens when you enter and exit the debugger. If you repeat that multiple times, you can watch the memory increasing each time.

After further investigation, I think this a problem of the emulation surface. The memory even increases if you just change the zoom factor back and forth. Even each message displayed slightly increases the memory.

IMO this shows that there is a serious memory leak.  The bug is not new, but it got more pronounced between 6.4 and 6.5.2. In 6.4 the memory **decreased** when switching to the debugger, with 6.5.2 it **increases** instead.

BTW: I noticed that 6.5 uses a lot of extra memory when starting emulation. This is not the case in 6.4 and 6.5.1. Maybe the fix for this had some negative effect?

**Comment by thrust26** [comment]
Will do.

Meanwhile I got at least the address sanitizer working. And it found a wild pointer in `FBBackendSDL2::createRenderer` line 435: `myRenderer = SDL_CreateRenderer(myWindow, -1, renderFlags);`. This bug only happens when switching zoom multiple times.
> Address Sanitizer Error: Deallocation of non-allocated memory

**Comment by sa666666** [comment]
The comments above the code you mention above state that:
```
  // A new renderer is only created when necessary:
  // - new myWindow (force = true)
  // - no renderer existing
  // - different renderer flags
  // - different renderer name
```
So maybe we don't need to do it for a new window.  We obviously need to do it if no renderer exists.  But the last two also require clarification; if the flags change, do we need to recreate it?  I think so based on the SDL docs, but now I'm not so sure.

**Comment by thrust26** [comment]
Forget my post above, both are bad. Not in Direct3D but in OpenGL (I have to check this later).

**Comment by sa666666** [comment]
Yep, exactly the code I was working on now :smiley:

**Comment by thrust26** [comment]
OK. 

I suppose my fix will invalide your planned work. Because I am going to destroy the renderer when the window is destroyed.

**Comment by thrust26** [comment]
Done. 

There still is a small memory leak somewhere. I will try to find this one next.
