### ISSUE TITLE
Add Bezels

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#839]
In fullscreen mode (and on R77) wide screen displays show black bars left and right of the screen. We could (optionally) replace them with bezels. ~670 bezels can be found [here](https://github.com/thebezelproject/bezelproject-Atari2600):

Examples:
![River Raid (USA)](https://user-images.githubusercontent.com/24360774/141741521-1e3e7961-783c-423e-915c-246386182dc2.png)
![Asteroids (USA)](https://user-images.githubusercontent.com/24360774/141741585-04827006-b595-4ae6-a3dc-5e0dad4387be.png)

**Comment by StormedBubbles** [comment]
This would also be useful for Sinden Lightgun usage. The border could be applied as a bezel (.png) with transparency where needed:


<img width="410" alt="1642538838856-border-example" src="https://user-images.githubusercontent.com/80055191/150363500-becc26be-135a-4ace-a80f-f422b8814db5.png">

**Comment by thrust26** [comment]
I played a bit with the bezel graphics. Here are some mockups:
![image](https://github.com/stella-emu/stella/assets/24360774/df20e328-1a3e-4925-99d7-5f222ab35e43)

![image](https://github.com/stella-emu/stella/assets/24360774/077d7fff-5d43-430d-88b6-fb828850e30f)

![image](https://github.com/stella-emu/stella/assets/24360774/7b3c3592-4d47-438a-941c-ca997e384a19)

**Comment by thrust26** [comment]
> This would also be useful for Sinden Lightgun usage. The border could be applied as a bezel (.png) with transparency where needed:
> 
> <img alt="1642538838856-border-example" width="410" src="https://user-images.githubusercontent.com/80055191/150363500-becc26be-135a-4ace-a80f-f422b8814db5.png">

I will create a separate issue for this.

**Comment by thrust26** [comment]
Done (incl. Lightgun support option) with adc7a3ce

**Comment by thrust26** [comment]
@StormedBubbles The Lightgun should work with the next release. Below is a simple (invisible 😈) example bezel.

![Sentinel (USA)](https://github.com/stella-emu/stella/assets/24360774/574bb695-68b0-48a8-8a2f-44bc17299e2d)

**Comment by StormedBubbles** [comment]
Thanks so much!

**Comment by thrust26** [comment]
@StormedBubbles Now that Stella 7.0 got released, could you test the Lightgun for us?
