### ISSUE TITLE
Video Chess - Early RESM0 

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#84]
In Video Chess the marks at the top left from the old core are gone. On my PAL TV, I can see a **different** mark (extending the blue area by 2 pixel into the left HMOVE black area) at the same scanline. The code has a RESM0 directly after WSYNC here.

http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-3#entry3675176

Note: In 4.7.3. the debugger shows a blue mark on the very left (probably from M0) even after RESM0 has been removed. This mark miraculously disappears a few debugger steps later.

**Comment by DirtyHairy** [comment]
Interesting. What happens is that RESM0 hits exactly one sprite counter clock before the missile starts rendering (hblank is irrelevant when it comes to sprite counter clocks, so the RESM0 might as well have happened on the last clock of the previous line. It seems that, in this case, two pixels are gobbled for 8 pixel missiles. This might be connected to the way different signals are combined to form the whole missile (as explained in ATs notes :smirk).

This is trivial to implement, but I'd like to clarify several things in a test:
 * Does this affect only RESMx during HMOVE? I suppose not, but you never know...
 * What does this mean for 4 and 1 pixel missiles? I suppose those are unchanged.

@thrust26 , the following picture is what I get when hacking in my conclusions, and it seems to match my PAL TV. Do you agree?

![video chess 1979 atari _1](https://cloud.githubusercontent.com/assets/2444224/22129998/bbc4ef88-dea9-11e6-9137-04aefd4076df.png)

**Comment by thrust26** [comment]
Yes, that matches what I see.

**Comment by DirtyHairy** [comment]
Fixed in f1d503a .
