### ISSUE TITLE
Feature Request Add a autofire button

### ISSUE THREAD

**Issue by Augusto7743** [stella-emu/stella#843]
Autofire with hz value was added for joystick button.
Thanks very much for add that feature.
Have games in few moments need button without autofire and in others moments autofire is very good, but need changing values several times.
Another button to autofire is good and avoid disable or changing autofire values.
Thus the user choice in game controller a button to joystick button and another button for autofire.

**Comment by thrust26** [comment]
@Augusto7743 That's doesn't fit to Stella's current general behavior 

How about mapping the 2nd button to toggling auto fire on/off instead?

**Comment by Augusto7743** [comment]
Map the button 1 to
a button. Not has autofire.
another button having autofire.

Having another button on controller mapped to Atari joystick button being autofire is better than changing autofire on with hz values and after disabling

**Comment by thrust26** [comment]
> Map the button 1 to
a button. Not has autofire.
another button having autofire.

That would require a lot of redundant mapping for each Atari controller type and also bloat the code. Therefore we decided for a toggle button.

> Having another button on controller mapped to Atari joystick button being autofire is better than changing autofire on with hz values and after disabling

I hope it works for you. Please let us know after the next release.
