### ISSUE TITLE
potential ARM timing binary for checking

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#846]
The attached binary shows scanline inconsistency in stella, and is stable on gopher.
I'm not setup for hardware at the moment, but I am reasonably confident this should not be unstable.
I thought I'd submit it in case it would be useful in adjusting/checking ARM cycle counting.

In the 6507 kernel, both the vertical blank and overscan have calls to ARM code. These calls are my "idle" loops, inside which parts of the cube are drawn. Each draw takes a variable amount of time -- and the idle loop checks INTIM to see if there's enough time left to do another call to the draw. In other words, it's a dynamic "can I do more?" idle loop.

Because this relies on correct ARM cycle counting to work, stella needs to run this in developer mode (I think). In any case, when it's running at "correct" speed, there is the aforementioned scanline jump. I suspect this is due to inaccuracy in the ARM cycle count. At the very least, both gopher and stella should be displaying the same thing, and they are not.  I will submit this to the gopher author as well, for review.

[cubiks.zip](https://github.com/stella-emu/stella/files/7615454/cubiks.zip)

**Comment by thrust26** [comment]
What are the ARM settings you are using (see 'States' tab in debugger)?

**Comment by andrew-davie** [comment]
Still at default...
<img width="657" alt="Screen Shot 2021-11-29 at 5 22 58 pm" src="https://user-images.githubusercontent.com/16424075/143824931-ef9f5b21-5f21-4b4a-9c20-26ea2bf9f4bd.png">

**Comment by thrust26** [comment]
I can only see changes between 262 and 261 scanlines, which indicates an unfavorably timer value. Even a single cycle difference can cause a scanline change then.

**Comment by andrew-davie** [comment]
I do not believe this is an issue related to timer values.
Nonetheless, here are some more clues...

If I change "cycle factor"in the "States" tab to 106%, then the problem disappears.
If I add extra 6507 cycles (e.g., 20 cycles) to overscan and vblank, then the problem **remains** and the scanline count is still toggling between 262/261.

Those together have firmed my belief that this is an ARM cycle count issue.

**Comment by thrust26** [comment]
> If I change "cycle factor"in the "States" tab to 106%, then the problem disappears.

Which confirms the timer issue.

> If I add extra 6507 cycles (e.g., 20 cycles) to overscan and vblank, then the problem remains and the scanline count is still toggling between 262/261.

Did you reset the factor to 105% before testing this one? 

> Those together have firmed my belief that this is an ARM cycle count issue.

How could a varying cycle count cause a **shorter** frame?

**Comment by andrew-davie** [comment]
> > If I change "cycle factor"in the "States" tab to 106%, then the problem disappears.
> Which confirms the timer issue.

Perhaps I misunderstood what "106%" means.
In any case - yes, I did reset to 105% in my tests of the additional cycles.

According to an analysis from Gopher author...

"In the worst case, it looks to me like you have 9 scanlines of overhead in the VBLANK kernel (at worst). And in the overscan kernel you have 10. I wouldn't consider that to be a borderline case. It should be comfortably inside the VBLANK and overscan times you've set yourself."

**Comment by thrust26** [comment]
Ok here we go: 

- set a breakpoint in bank6, @$f13c. 
- In frames with 261 scanlines, the break happens in scanline 37, cycle ~60..65. The code returns from the subroutine $f050 in $f05a. Which is **before** the timer runs out.
- In frames with 262 scanlines, the break happens in scanline 39, cycle 15. The code in the subroutine returns normal, the timer interrupt is set, the timer read at $f061 is $cf. 

Your (convoluted) timer check code is the problem.
