### ISSUE TITLE
Virtual dirs not showing up for regular user in linux?

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#848]
As title says, the virtual directories "Favorites", "Recently Played" and "Most Popular" are not displayed when running Stella as a regular user. 
I can add games to favorites, and the icon changes to a star, but I cannot see the "Favorites" directory even if I select "reload listing" or by restarting Stella. 
Similarly, even after playing some games, the "Most Popular" and "Recently Played" dirs do not show up. 

I tried deleting the "stella.sqlite3" file, but it didn't help.

Everything works as expected if I run Stella as root. The virtual dirs appear in my rom directory, as soon as I play some games, or if I add them to favorites.

I tested on 2 different PCs, both running [Arch Linux](https://archlinux.org/), with the same results.

**Comment by thrust26** [comment]
Thanks for the report. As of now of cannot test myself, so I might need help from e.g. @sa666666.

The virtual directories only exist inside Stella memory, and I did not change any OS specific code. So there must be a difference between OS functions already existing in our code.

**Comment by thrust26** [comment]
@ale-79 Can you try with my latest commit, please?

**Comment by ale-79** [comment]
Same as before. 
I can mark roms (and now directories) as favorites, but the virtual dirs only show up if Stella is running as root.

**Comment by ale-79** [comment]
Ok, I might have found a clue:

My roms are in a subdirectory of my home dir (/home/alex/data/atari/roms), and I configured that dir for both the root used and my regular user to be used as the rom path in Stella.

When running as root, Stella displays the path as above, while when using my user, the /home/alex part is replaced with the '~' symbol indicating my home dir.

Now, I created a link called 'atari_roms' in my filesystem root dir, pointing to /home/alex/data/atari/roms, and configured Stella to use /atari_roms as the rom path instead.

After restarting Stella, the virtual dirs are correctly displayed!

So maybe it has something to do with the '~' instead of the home dir used in the path string?

**Comment by thrust26** [comment]
That's a convincing finding and might very likely be the reason. Then the ROM paths stored in the database would become invalid when switching from admin to user.

But that would also mean, that before my changes Stella did not remember the romdir and the last ROM played correctly when switching from admin to user afterwards. Can you confirm that?

**Comment by ale-79** [comment]
> But that would also mean, that before my changes Stella did not remember the romdir and the last ROM played correctly when switching from admin to user afterwards. Can you confirm that?


No, it remembered the path and last rom just fine.
The sqlite files are separate for root and my regular user (they're in "/root/.config/stella" and "/home/alex/.config/stella" respectively).
I can set the rom path (and any other setting) separately for each user and Stella uses the correct one each time.

**Comment by thrust26** [comment]
Ah, separate SQLite files. Do you have 'DB Browser for SQLite' (or similar)? Then you could look into the database.

I am interested into what is stored in "settings.romdir" and "settings._favoriteroms" in user mode. Both should use "~" (without the link you created).

**Comment by ale-79** [comment]
Only "romdir" uses the tilde symbol, "_favoriteroms" uses the full path
![romdir_sqlite3](https://user-images.githubusercontent.com/24704739/144580490-ab9419f8-c7f9-4817-b07a-479f6abb3b4c.png)
:
![_favoriteroms_sqlite3](https://user-images.githubusercontent.com/24704739/144580517-95643fe2-c1f0-4027-b560-737f07b819f2.png)

**Comment by thrust26** [comment]
Thanks, that's what I had expected. Now I have to find out why this happens.

**Comment by ale-79** [comment]
BTW, manually changing 'settings.romdir' with the full path "/home/alex/data/atari/roms" makes the virtual dirs appear in the launcher.

**Comment by thrust26** [comment]
Looks like the OS virtual paths are causing the problem.

**Comment by thrust26** [comment]
Looks like the Linux code is looking for an environment variable named "HOME" to replace '~' with it. Is that variable set on your system?

**Comment by thrust26** [comment]
And can you also test the following in user mode: Create a zip file containing two or more ROMs, put it into your games folder, open it and briefly play one of the contained ROMs. Then restart Stella. Does it crash?

**Comment by ale-79** [comment]
> Looks like the Linux code is looking for an environment variable named "HOME" to replace '~' with it. Is that variable set on your system?

Yes, it's set to "/home/alex"

> Create a zip file containing two or more ROMs, put it into your games folder, open it and briefly play one of the contained ROMs. Then restart Stella. Does it crash?

Yes if I select "Follow Launcher path". I usually don't have that option enabled.

**Comment by thrust26** [comment]
Thanks. I think I found this fix for this issue and will commit soon. Please let me know if that helps.

For the ZIP crash I will create a new one.

**Comment by ale-79** [comment]
> Please let me know if that helps.

Yes, it's working fine now! 
The "Home" button is very useful to have too. :+1:
