### ISSUE TITLE
Changing ENAxx in debugger only temporary

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#85]
When I change the state of ENAM0/1 and ENABL in the 4.7.3 debugger, the old state is restored with the next step.

**Comment by sa666666** [comment]
@thrust26, can you test the latest pre-release and determine if this is still the case?

**Comment by thrust26** [comment]
Still there in pre6. 

Testing is simple: Load a game (e.g. H.E.R.O) and enter the debugger. Click on e.g. M0 _Enable_ and then e.g. _Step_. M0 gets disabled immediately. 

The same happens vice versa (disabling and enabled particle)

**Comment by sa666666** [comment]
Since this functionality will change in pre7, I guess you should check again after that release (soon).  But now that I know what to look for, I guess I can check it myself.

**Comment by thrust26** [comment]
Fixes in pre10
