### ISSUE TITLE
Some more virtual dir issues

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#850]
I have done some testing, and found a weird issue.  It happens in both Linux and Windows.  If you manually select a favourite, or remove one, etc, the change only 'sticks' if you exit from Stella with the "Quit" button.  Pressing Ctrl-Q or the 'X' in the window titlebar doesn't work.  It seems that exiting via "Quit" saves to the database, but exiting in other ways doesn't.  So perhaps this isn't a virtual dir bug per-se, but it indicates something else is going on.

Also, a feature request: the right-click menu in 'Popular' and 'Recently played' should have an option to remove _all_ ROMs, instead of having to remove each one individually.  And finally, I think we should offer an option to disable this functionality entirely, for those that may not want it.  But it should be enabled by default.

**Comment by thrust26** [comment]
> So perhaps this isn't a virtual dir bug per-se, but it indicates something else is going on.

Good finding. Not sure if it was a bug, because all setting were saved correctly before (immediately when getting changed). So there was no need for executing `safeConfig` before (and the call in `kQuitCmd` was superfluous). But I do not want to save everything immediately, so I am going to try to change this.

I agree with the option to disable favorites in general. But What is the use case for removing all files from 'Popular' and 'Recently played'?

**Comment by sa666666** [comment]
> I agree with the option to disable favorites in general. But What is the use case for removing all files from 'Popular' and 'Recently played'?

Perhaps the user just wants to start fresh.  It's easier to have a menu item to remove all the entries, rather than having to remove each one individually.

**Comment by thrust26** [comment]
Maybe. But it bares the risk to accidentally remove all. Therefore there must be a popup to confirm the choice, IMO. Currently the context menu does not support that.

**Comment by sa666666** [comment]
I should clarify how this is all supposed to work, since with the previous issues in Linux, it wasn't working correctly for me.  Is the intent to have popular and most recently played ROMs persist across multiple program runs?

**Comment by thrust26** [comment]
For sure!

Which previous issues?

**Comment by sa666666** [comment]
Well, the biggest previous issue was that I couldn't see the virtual dirs at all in Linux :smiling_imp:   Now that they're visible, I can do more testing.

**Comment by thrust26** [comment]
Why didn't you report?

**Comment by sa666666** [comment]
I noticed Alex-79 already did, so I didn't think it was necessary.  And by that time, you'd already fixed it.  Too fast for me, I guess.

**Comment by thrust26** [comment]
All done with 7485ee5
