### ISSUE TITLE
Compiling fails

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#856]
After deleting the object files with "make clean", current master does not compile for me today, nor does a previous commit which I had successfully built a few days ago.

Here's the output:
```
src/gui/LauncherDialog.cxx: In member function 'void LauncherDialog::addRomWidgets(int&)':
src/gui/LauncherDialog.cxx:270:13: warning: unused variable 'lineHeight' [-Wunused-variable]
  270 |   const int lineHeight   = Dialog::lineHeight(),
      |             ^~~~~~~~~~
src/gui/NavigationWidget.cxx: In member function 'void NavigationWidget::PathWidget::setPath(const string&)':
src/gui/NavigationWidget.cxx:157:13: warning: unused variable 'lineHeight' [-Wunused-variable]
  157 |   const int lineHeight = _font.getLineHeight();
      |             ^~~~~~~~~~
/bin/sh: line 1: MMD: command not found
make: [Makefile:282: out/src/sqlite/sqlite3.o] Error 127 (ignored)
/usr/bin/ld: cannot find out/src/sqlite/sqlite3.o: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:203: stella] Error 1
```
commit [143cf9f](https://github.com/stella-emu/stella/commit/143cf9fa13a07b827de7065a5e919631406b0941)  is the one when the issue starts.
Commenting line 902 in 'configure' allows me to build the current master.

Is this a problem on my end?

**Comment by thrust26** [comment]
So your build fails due to a **warning**?

**Comment by thrust26** [comment]
I miss understood the problem. The real problem is the change for #854.

**Comment by ale-79** [comment]
Yes, the warnings weren't the problem, sorry if I wasn't clear. 
I just redirected stderr to a file and posted the entire thing, which includes errors and warnings.

**Comment by sa666666** [comment]
If you comment out line 902 in `configure`, does it then work?  Because that's all that was changed. Specifically, the line `CC := $CC` was added.

**Comment by ale-79** [comment]
Yes, it works if I comment out that line.

**Comment by sa666666** [comment]
OK, now at least I have somewhere to work from.

**Comment by sa666666** [comment]
Also, you can set CC in your bash aliases somewhere, and it will then work with the new code.  I guess we need a conditional there, to only change CC if it already exists.
