### ISSUE TITLE
Stella 6.6 Ubuntu 20.04 deb file not working with Ubuntu 20.04.3

### ISSUE THREAD

**Issue by Augusto7743** [stella-emu/stella#857]
Ubuntu 20.04.3 Stella 6.5 installed using deb work.
stella_6.6_amd64.deb install without issues , but when selecting Stella exe link not start Stella.
If installing stella_6.6_ubuntu-18.04_amd64.deb install correctly and Stella start working.

**Comment by sa666666** [comment]
I think I used the wrong compile flags in the build environment.  I just uploaded a fixed version.  Please download again and try it out.

**Comment by Augusto7743** [comment]
New deb is working.
Thanks.

**Comment by sa666666** [comment]
OK, good to hear.
