### ISSUE TITLE
Title Match Pro Wresting - scanline corruption

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#87]
http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-4#entry3676297

There are even more corruptions, e.g. when standing at the right and making a punch. There is a change in NUSIZx from single to double sized player. 
![title match pro wrestling 1987 absolute _18](https://cloud.githubusercontent.com/assets/24360774/22167773/cca0443c-df68-11e6-85f2-02e9d59cbdd0.png)

**Comment by DirtyHairy** [comment]
Fixed by 6070291 , see comment in #82.
