### ISSUE TITLE
Crash on Pink Panther ROM

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#878]
The commit https://github.com/stella-emu/stella/commit/0ef0636eb98f6bdac7389bbdbf9ee3c3bbc18006 breaks the attached Pink Panther ROM.  I've tested this on Linux/Mac/Windows.  I'm assigning this one to you, Thomas, as it's your code.

[Pink-Panther-fixed.zip](https://github.com/stella-emu/stella/files/8126549/Pink-Panther-fixed.zip)

**Comment by sa666666** [comment]
I'm not sure if any other ROMs are affected; it was just a fluke that I found this one.

**Comment by thrust26** [comment]
@sa666666 How does it break the game? It works for me.

**Comment by sa666666** [comment]
Sorry, should have included that info.  Enter the game from the launcher.  Then immediately exit with Escape, back to the launcher.  Gives a segfault on Linux, and a similar error in Mac and Windows.

**Comment by thrust26** [comment]
Do you have a stack trace?

**Comment by sa666666** [comment]
In Linux, it's crashing on the deletion of a `_next` widget in the `Widget` d'tor.  But I'm sure the problem is much higher-level than that; that's just a symptom of whatever is going wrong.

**Comment by sa666666** [comment]
Now it's crashing when saving the keyboard mappings.  And after another run, it's crashing on a `~ContextMenu` d'tor.  So it's all over the place; likely a threading issue somewhere.

**Comment by sa666666** [comment]
Not using developer mode.  Turned off all such settings in normal mode.  But whatever settings I use, it works before the commit I mentioned in the first post, and not after.

**Comment by thrust26** [comment]
> Now it's crashing when saving the keyboard mappings. And after another run, it's crashing on a `~ContextMenu` d'tor. So it's all over the place; likely a threading issue somewhere.

So it cannot be due to the changes you mentioned. Probably it is something else, right?

**Comment by sa666666** [comment]
I can say that it is initiated by that commit.  The commit before that one works, after applying it, it crashes.  It's only a one-line patch.  I basically did a git bisect, only manually.  So I know that the commit is what breaks it.  Now, there may be underlying reasons *why* it's breaking, but it is definitely related to https://github.com/stella-emu/stella/commit/0ef0636eb98f6bdac7389bbdbf9ee3c3bbc18006.

**Comment by thrust26** [comment]
OK, got you. It might explain why it crashes for PP, because that one triggers a lot of read from write ports. The fix obviously triggers the detection and that's why the error is exposed. But I am pretty sure the root cause is something different.

**Comment by thrust26** [comment]
I think I got it fixed. Please double check.

WD bankswitching is a bit special, because it is one of the very few, where the write port is in the upper address range. PP is writing a lot of data to read ports, so the error was triggered frequently. And there was the bug.

**Comment by sa666666** [comment]
Confirmed in Linux for me, and I assume Windows for you.  I will check Mac later, but I assume it is fine there too.  Good catch.

**Comment by thrust26** [comment]
I have to revert blaming PP. The writes to read ports happen during indexed writes. And these cause intermediate peeks which always trigger a ghost write. So no coding bug, just the normal 650x stuff happening. 😄 

```case 0x9d:
{
  uInt16 low = peek(PC++, DISASM_CODE);
  uInt16 high = (uInt16(peek(PC++, DISASM_CODE)) << 8);
  peek(high | uInt8(low + X), DISASM_NONE);    // <-- HERE!
  operandAddress = (high | low) + X;
}
{
  poke(operandAddress, A, DISASM_WRITE);
}
```

**Comment by sa666666** [comment]
But your latest fix is still required, correct?

**Comment by thrust26** [comment]
Yes, definitely.
