### ISSUE TITLE
Incorrect horizontal offset of "nose" of player cars in games 21-27 of Street Racer (Speedway II)

### ISSUE THREAD

**Issue by colinhowell** [stella-emu/stella#889]
(Apologies if this is missing useful information, as this is the first time I have ever filed a bug report on Stella.)

For the cartridge Street Racer (Atari model number CX2612, named Speedway II by Sears), which was one of the original nine cartridges for the VCS's 1977 launch, there is a graphics glitch on current Stella, version 6.6, in how it draws the player cars in some games. Specifically, in games 21-24 (Number Cruncher) and 25-27 (Scoop Ball), the nose of each player car is drawn one X position to the right of where it should be—it should be perfectly aligned with the car body. Turning on debug colors reveals that the offset car "noses" are drawn as missile objects, separate from the main player car bodies.

(Because of this, I also checked games 17-20 (Jet Shooter), the only games on this cartridge which have actual player missiles. These missiles too are drawn one X position to the right of being aligned with the player's "jet" body. In this case, however, I am not sure whether this is actually wrong. For that game I may see a similar offset glitch in actual console recordings; it's kind of hard to be sure with the limited recordings I have.)

This affects both the NTSC and PAL versions of the cartridge. This bug affects 6502.ts as well, but it is also present in Stella 4.7.3, before the changeover to the 6502.ts TIA core.

(I encountered this bug on the macOS version of Stella 6.6, but I don't think it depends on the host system, since I've also seen it in Twin Galaxies videos recorded with various Stella versions on Windows.)

For the way things are supposed to look, see the videos under individual record links for the following Twin Galaxies "tracks" for NTSC Street Racer [game 21](https://www.twingalaxies.com/game/street-racer/atari-2600-vcs/ntsc-game-21-difficulty-b-points/page/1?ref=fbshare), [game 22](https://www.twingalaxies.com/game/street-racer/atari-2600-vcs/ntsc-game-22-difficulty-b-points/page/1?ref=fbshare), [game 25](https://www.twingalaxies.com/game/street-racer/atari-2600-vcs/ntsc-game-25-difficulty-b-points/page/1?ref=fbshare), and [game 17](https://www.twingalaxies.com/game/street-racer/atari-2600-vcs/ntsc-game-17-difficulty-b-points/page/1?ref=fbshare), and for PAL Street Racer [game 21](https://www.twingalaxies.com/game/street-racer/atari-2600-vcs/pal-game-21-difficulty-b-points/page/2?ref=fbshare), [game 22](https://www.twingalaxies.com/game/street-racer/atari-2600-vcs/pal-game-22-difficulty-b-points/page/2?ref=fbshare), [game 25](https://www.twingalaxies.com/game/street-racer/atari-2600-vcs/pal-game-25-difficulty-b-points/page/2?ref=fbshare), and [game 17](https://www.twingalaxies.com/game/street-racer/atari-2600-vcs/pal-game-17-difficulty-b-points/page/2?ref=fbshare). Since these videos were recorded with actual consoles, they are at least a guide to proper behavior, even though the video quality sometimes leaves something to be desired.

**Comment by ale-79** [comment]
Interesting.
I guess something is wrong in emulating RESMP0/RESMP1 behavior with player/missile sizes other than 1 clock?
Gopher2600 shows the same bug (1 pixel offset to the right). Javatari is incorrect too (the offset is 2 pixels here).

**Comment by thrust26** [comment]
I suppose I have to write some test code to find out if the player and/or the missile size is relevant here.

**Comment by sa666666** [comment]
> (Apologies if this is missing useful information, as this is the first time I have ever filed a bug report on Stella.)
> 
> For the cartridge Street Racer (Atari model number CX2612, named Speedway II by Sears), which was one of the original nine cartridges for the VCS's 1977 launch, there is a graphics glitch on current Stella, version 6.6, in how it draws the player cars in some games. Specifically, in games 21-24 (Number Cruncher) and 25-27 (Scoop Ball), the nose of each player car is drawn one X position to the right of where it should be—it should be perfectly aligned with the car body. Turning on debug colors reveals that the offset car "noses" are drawn as missile objects, separate from the main player car bodies.

Thanks for the detailed report.

**Comment by thrust26** [comment]
I have written my own little test program. Attached you find a Stella PAL-60 screenshot and one from my PAL CRT.

![RESMPx](https://user-images.githubusercontent.com/24360774/164508841-1beeaf04-a630-4cd2-8e65-32df45fe538d.png)
![RESMPx](https://user-images.githubusercontent.com/24360774/164508866-be3062ff-3cd8-4e44-8f51-b326f680f022.jpg)

Single and quad-sized players look fine, only for double sized players, the missiles seem off by one pixel.
[RESMPx.zip](https://github.com/stella-emu/stella/files/8532818/RESMPx.zip)
