### ISSUE TITLE
Disassembly of code running in ZP ram not showing up in debugger

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#890]
The PC is correct and you can step through the code, but the disassembly tab shows unrelated code in ROM.
Try e.g. [RAM Pong](https://atariage.com/forums/topic/143075-ram-pong/?do=findComment&comment=1746442)

It still works in 6.6.

**Comment by thrust26** [comment]
Looks like I broke it with my fix for #568. 😒
