### ISSUE TITLE
Unable to jump to directory with numbers in it

### ISSUE THREAD

**Issue by zeropagehomebrew** [stella-emu/stella#891]
I'm able to jump to a directory by starting to type the directory with letters while holding down the shift key but it doesn't work for directories that start with a number or have numbers anywhere in the name of the directory.

**Comment by thrust26** [comment]
That's a tricky one, because the chars above the digits depend on the keyboard language.

**Comment by zeropagehomebrew** [comment]
That makes sense why it was not implemented, thanks!
