### ISSUE TITLE
[RPi4/RetroArch] Setting Core Console Display to "Auto" causes video of several NTSC games to visually 'roll' making games unplayable

### ISSUE THREAD

**Issue by roslof** [stella-emu/stella#900]
[SAMPLE VIDEO](https://user-images.githubusercontent.com/6511782/174019722-8c698cae-9528-42dc-8c70-60d01c860803.mp4
)

**Test Setup:**
- Raspberry Pi4B (2GB)
- RetroArch 1.10.0
- lr-stella build 6.7 4c7384f82 (final release)

**Repro Steps**
1. Ensure Stella's RetroArch Core Option Console Display is set for "Auto"
2. Restart
3. Play various NTSC games. Here are several that exhibit the issue:
       3D Tic-Tac-Toe (NTSC)
       Acid Drop (NTSC)
       Asteroids (NTSC)
       Astroblast (NTSC)
4. Observe results

**Results**
Several NTSC games visually 'roll' making games unplayable when Console Display Core Option is set to "Auto".

**Note**
Setting these games to NTSC immediately resolves the issue.

**Additional Notes**
There are some NTSC games that do not exhibit this issue, such as:
       Actionauts (NTSC)
       Adventure (NTSC)
       Air Sea Battle (NTSC)

**Final Note**
This is a fairly new issue, and does not occur with lr-stella 6.7pre 65f8823)

**Comment by roslof** [comment]
Good day, @thrust26 
Would you mind pointing me to the correct place to report this? The issue is newly introduced and should not be related to my configuration.
Thank you, and cheers!

**Comment by sa666666** [comment]
Are you able to create your own builds?  If so, perhaps try https://github.com/stella-emu/stella/commit/eb6d85459992675827cf8d3446d1c1a87dbaa03e.  This was the commit just before the new jitter code.  At least that will help narrow down the problem.

**Comment by thrust26** [comment]
> Good day, @thrust26 Would you mind pointing me to the correct place to report this? 

Sorry, but I know **zero** about these builds.

**Comment by roslof** [comment]
Yes, no trouble. Done, and everything looks good with eb6d854.

**Comment by sa666666** [comment]
I will try to look into it when I find some time.  But I've tested the libretro builds in Linux, and don't see this behaviour.  So it may be very hard to trace why it's happening.

**Comment by thrust26** [comment]
Somehow TV jitter must have been set to high sensitivity.

**Comment by sa666666** [comment]
> Somehow TV jitter must have been set to high sensitivity.

Yeah, my first thought was to set the sensitivity to the lowest possible value.  Since there's no 'knob' in libretro to set this anyway, it's best to just set it low enough that it's essentially disabled on that platform.

**Comment by thrust26** [comment]
Well, there also is a switch to disable it completely.

**Comment by sa666666** [comment]
> Well, there also is a setting to disable it completely.

Yep, probably better to wrap in an `#ifdef` a call to disable this on libretro.

**Comment by sa666666** [comment]
@roslof, in the file `src/emucore/Settings.cxx`, please try applying the following patch:
```
diff --git a/src/emucore/Settings.cxx b/src/emucore/Settings.cxx
index 2045ea9f4..57d3cc5ff 100644
--- a/src/emucore/Settings.cxx
+++ b/src/emucore/Settings.cxx
@@ -231,6 +231,9 @@ Settings::Settings()
 #ifdef GUI_SUPPORT
   setPermanent("plr.tv.jitter_sense", JitterEmulation::PLR_SENSITIVITY);
   setPermanent("plr.tv.jitter_recovery", JitterEmulation::PLR_RECOVERY);
+#else
+  setPermanent("plr.tv.jitter_sense", JitterEmulation::MIN_SENSITIVITY);
+  setPermanent("plr.tv.jitter_recovery", JitterEmulation::MIN_RECOVERY);
 #endif
   setPermanent("plr.debugcolors", "false");
   setPermanent("plr.console", "2600"); // 7800
@@ -254,6 +257,9 @@ Settings::Settings()
 #ifdef GUI_SUPPORT
   setPermanent("dev.tv.jitter_sense", JitterEmulation::DEV_SENSITIVITY);
   setPermanent("dev.tv.jitter_recovery", JitterEmulation::DEV_RECOVERY);
+#else
+  setPermanent("dev.tv.jitter_sense", JitterEmulation::MIN_SENSITIVITY);
+  setPermanent("dev.tv.jitter_recovery", JitterEmulation::MIN_RECOVERY);
 #endif
   setPermanent("dev.debugcolors", "false");
   setPermanent("dev.tiadriven", "true");
```

**Comment by roslof** [comment]
Thank you @sa666666
I attempted the patch. Fails with declares:
```
../emucore/Settings.cxx: In constructor 'Settings::Settings()':
../emucore/Settings.cxx:235:39: error: 'JitterEmulation' has not been declared
   setPermanent("plr.tv.jitter_sense", JitterEmulation::MIN_SENSITIVITY);
                                       ^~~~~~~~~~~~~~~
../emucore/Settings.cxx:236:42: error: 'JitterEmulation' has not been declared
   setPermanent("plr.tv.jitter_recovery", JitterEmulation::MIN_RECOVERY);
                                          ^~~~~~~~~~~~~~~
../emucore/Settings.cxx:261:39: error: 'JitterEmulation' has not been declared
   setPermanent("dev.tv.jitter_sense", JitterEmulation::MIN_SENSITIVITY);
                                       ^~~~~~~~~~~~~~~
../emucore/Settings.cxx:262:42: error: 'JitterEmulation' has not been declared
   setPermanent("dev.tv.jitter_recovery", JitterEmulation::MIN_RECOVERY);
                                          ^~~~~~~~~~~~~~~
make: *** [Makefile:634: ../emucore/Settings.o] Error 1

```

**Comment by sa666666** [comment]
Sorry, I will post a working patch in a moment.

**Comment by sa666666** [comment]
OK, try this one:
```
diff --git a/src/emucore/Settings.cxx b/src/emucore/Settings.cxx
index 2045ea9f4..339ea26ad 100644
--- a/src/emucore/Settings.cxx
+++ b/src/emucore/Settings.cxx
@@ -231,6 +231,9 @@ Settings::Settings()
 #ifdef GUI_SUPPORT
   setPermanent("plr.tv.jitter_sense", JitterEmulation::PLR_SENSITIVITY);
   setPermanent("plr.tv.jitter_recovery", JitterEmulation::PLR_RECOVERY);
+#else
+  setPermanent("plr.tv.jitter_sense", 1);
+  setPermanent("plr.tv.jitter_recovery", 1);
 #endif
   setPermanent("plr.debugcolors", "false");
   setPermanent("plr.console", "2600"); // 7800
@@ -254,6 +257,9 @@ Settings::Settings()
 #ifdef GUI_SUPPORT
   setPermanent("dev.tv.jitter_sense", JitterEmulation::DEV_SENSITIVITY);
   setPermanent("dev.tv.jitter_recovery", JitterEmulation::DEV_RECOVERY);
+#else
+  setPermanent("dev.tv.jitter_sense", 1);
+  setPermanent("dev.tv.jitter_recovery", 1);
 #endif
   setPermanent("dev.debugcolors", "false");
   setPermanent("dev.tiadriven", "true");
```

**Comment by roslof** [comment]
Patch isn't taking. Investigating.

**Comment by thrust26** [comment]
I would suggest to set "plr.tv.jitter" and "dev.tv.jitter" to false. Then the other settings become irrelevant.

**Comment by sa666666** [comment]
@roslof, please ignore my patch and try what @thrust26 says instead.  If that works, that's the best way to go.  I will then commit it.

**Comment by roslof** [comment]
@sa666666 Simple enough.
I re-cloned, altered Settings.cxx as @thrust26 described and recompiled.
Seems perfect.

Cheers to both of you! Feel free to hit me up if you ever have libretro testing needs. The audience is growing.

**Comment by sa666666** [comment]
OK, this is fixed in https://github.com/stella-emu/stella/commit/e253be49d5ec0c29ebc622749fb45dcc4564cbf6.   Ideally, someone will come along eventually and do more work on the libretro port, exposing more of this core functionality to the libretro UI.

**Comment by thrust26** [comment]
I still wonder why their compile defaulted to maximum TV jitter sensitivity.

**Comment by sa666666** [comment]
The setting wasn't being set to anything in `Settings`.  So I guess it was defaulting to a large, garbage value.  In my testing, it's likely that the numbers were defaulting to 0, so I never saw the issue.  So a simple non-initialization error, I guess.

**Comment by thrust26** [comment]
How can we avoid this in the future?

**Comment by sa666666** [comment]
Diligence, I guess.  And running the code through various linters (cppcheck, clang-tools, MSVC, coverity, etc) would probably have caught it.  I added that ifdef pretty late in the release, and didn't have time to check the code.
