### ISSUE TITLE
Trying to autodetect the correct palette 

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#901]
Note: This might turn out to be impossible or not reliable enough to be useful. 

Currently Stella cannot autodetect if a game is e.g. NTSC or PAL60. The idea behind this enhancement is, that a statistical approach of the color values used, might provide a strong enough indication. E.g. $1x, which is yellow in NTSC, is gray in PAL. But there also are $0x, $Ex and $Fx which also produce grays in PAL. One assumption would be, that games converted from NTSC to PAL would use NTSC's gray $0x. And therefore the use of $1x, $Ex and $Fx would hint at a NTSC palette. Also certain colors are more frequently used than others. E.g. violet and pink seem pretty rarely used. So if game uses a color code which represents a rare color in one palette and a more frequent one in the the other palette, this is a hint for the latter.

The first step would be to analyze the use of color codes for **many** existing games (the more the better). This could be either simply counting the color writes or (probably better), the area which each color covers. Maybe only the high nibble of the color value would be of interest here. Or maybe some colors are more frequently used bright than others? The analysis will find out. The color counting should be done over the first n-frames only, since the palette autodetection should also not take too many frames.

With that data, we would be able to calculate the probability of the palette for each game. Based on the the default palette assignment (NTSC for 60Hz, PAL for 50Hz), and only if the deviating palette probability is strong enough, Stella would chose the other palette instead.

Of course this autodetection option would have to be configurable and have the lowest priority (after properties and file names).

**Comment by andrew-davie** [comment]
I'd be interested to see if a statistical analysis purely of the luminance might provide a reliable differentiation between NTSC and PAL60. The reason I suspect this might be the case is that in testing of my current project by someone in PAL-land, the colours chosen are signifcantly darker (in terms of luminance) than the colours I use in my NTSC variant. In other words, I am just wondering if it's as simple as NTSC uses (on average) higher luminance values than PAL.

**Comment by sa666666** [comment]
It would also have to be reasonably fast.  We don't want to slow down starting a ROM, just to do a lengthy statistical analysis.  As you say, spreading over the first few frames would be required.  But would that be enough to get the info we need?

**Comment by thrust26** [comment]
> It would also have to be reasonably fast. We don't want to slow down starting a ROM, just to do a lengthy statistical analysis. As you say, spreading over the first few frames would be required. But would that be enough to get the info we need?

I think this should be done in parallel with the current frame rate autodetection. If that doesn't provide enough information in general, then we cancel this idea.

**Comment by thrust26** [comment]
After a lot of analysis (~400 ROMs) I found a way make use of it. See commit 1a8971e6.
