### ISSUE TITLE
7800 Pause Key event not working

### ISSUE THREAD

**Issue by dionoid** [stella-emu/stella#905]
In 7800 mode, the '7800 Pause Key' emulation event (by default mapped to Alt-F3) is not working correctly anymore.
It used to work in 6.0, but stopped working from 6.1 onwards

[edit: Attached a test rom which should turn the screen to green when the pause key was pressed on a 7800]
[7800-pause-pressed-test.zip](https://github.com/stella-emu/stella/files/8985335/7800-pause-pressed-test.zip)
.

**Comment by thrust26** [comment]
Actually it works, but you have to set console to 7800 in developer settings.

**Comment by ale-79** [comment]
It doesn't seem to work for me, even with console set to 7800 in the developer options.
E.g. try "Secret Quest". During the game pressing ALT-F3 displays the "pause pressed" message, but nothing happens, while the game should display the status screen, as it does if you press F4 and then F3.

**Comment by dionoid** [comment]
> Actually it works, but you have to set console to 7800 in developer settings. See _Console_ setting [here](https://stella-emu.github.io/docs/index.html#DeveloperEmulator).
> 
> I will update the hotkey documentation to make this more obvious better.

For me it doesn't work when setting the console to 7800. It did work in Stella 6.0, but from 6.1 onwards it stopped working for me. I'm using Windows 11 btw.

**Comment by thrust26** [comment]
You are both right, this is definitely a bug.
