### ISSUE TITLE
RESMx during draw / decode

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#91]
This should be investigated and the emulation updated accordingly. Related to #84 .

**Comment by DirtyHairy** [comment]
I've run a series of tests: [testcases.zip](https://github.com/stella-emu/stella/files/733966/testcases.zip). The source can be found in the [6502.ts repo](https://github.com/6502ts/6502.ts/tree/master/aux/2600/resx_during_draw).

The tests are all setup to first align a RESM1 with the first draw counter decode cycle of missile 1 (yellow) and then move missile 1 to the left, clock by clock, during the next lines, repeating the same test for all possible states of the draw decode counter and the drawing process. As a reference, missile 0 (white) can be toggled with the color switch and is positioned just as missile 1, but without the final RESMx.  The results are implemented in 863a006.

For a missile positioned somewhere in the middle, the result looks like this (`missile.bin`):
![missile_1](https://cloud.githubusercontent.com/assets/2444224/22356083/fe4a9d3c-e42e-11e6-814e-2183a12b7908.png)

If the missile is positioned exactly on color clock 0 (and thus RESM1 during hblank) (`missile_hblank.bin)`, the result is this:
![missile_hblank](https://cloud.githubusercontent.com/assets/2444224/22356112/3de746d4-e42f-11e6-8cae-f3926b6dc814.png)

If the hblank is extended by a hmove (`missile_late_hblank_75.bin` and friends), the result depends on the exact cycle of the RESM0. If it happens on color clock 75, we get
![missile_late_hblank_75_1](https://cloud.githubusercontent.com/assets/2444224/22356151/7f47b744-e42f-11e6-91a8-a070d208a6d0.png)

For all other color clocks during late hblank, we get 
![missile_late_hblank_72_2]
![missile_late_hblank_72_3](https://cloud.githubusercontent.com/assets/2444224/22356211/de374d00-e42f-11e6-89e4-97ac58b94c64.png)

This behavior is the reason for #84 which is fixed now. @sa666666 , @thrust26 , I am aware that the TIA in my Jr. is somewhat special. Could you try those tests on your machines and check whether you can reproduce my results?

**Comment by sa666666** [comment]
I'm unable to test these ROMs since they're in PAL mode, and I only have NTSC hardware.

**Comment by DirtyHairy** [comment]
Ouch, of course, sorry. I'll try to prepare NTSC versions.

**Comment by thrust26** [comment]
Confirmed. They seem (see below) to look the same on my TV.

Can you post the bins with more contrast? I can hardly make out the difference between bright orange and bright grey on my TV. And I am too lazy to change all the source codes. :)

**Comment by DirtyHairy** [comment]
:smile: Will do so

**Comment by DirtyHairy** [comment]
[testcases.zip](https://github.com/stella-emu/stella/files/737902/testcases.zip) This version uses different colors (contrast is slightly better on my LCD), and TV mode can be switched between NTSC and PAL via P1 difficulty. In order to fit the tests on both NTSC and PAL displays, I have distributed the wide (8/4 pixel) and narrow (2/1 pixel) cases between two different kernels that are selected via difficulty p0. However, nothing functional has changed, so I didn't prepare any new screenshots :)
