### ISSUE TITLE
Images should also be searched by filename

### ISSUE THREAD

**Issue by Augusto7743** [stella-emu/stella#911]
Hello.
I has all roms inside one zip file. That file load correctly, but the screenshots not are showed even using correct naming.
Which file image formats are allowed ?

THANKS VERY MUCH FOR ADDING OPTION TO TOGGLE AUTOFIRE =)
Have an nice week.

**Comment by thrust26** [comment]
Stella uses the PNG image file format. For me it shows all screenshots, even if the ROMs are in a zip-file.

If that answers your question, please confirm.

**Comment by Augusto7743** [comment]
Thanks for your reply.

Stella browse an Roms.zip (inside all roms).
In Stella launch is listed the roms.zip file.
Select roms.zip is loaded an list of all files inside, but not show the screenshots even if the screenshot file is png using correct naming.

The path for screenshots use space.
/Disc/Games/Stella Atari 2600/Images/R1

**Comment by thrust26** [comment]
Did you setup Stella to use that path? Option/User Interface/Launcher/Image Path

**Comment by Augusto7743** [comment]
Thanks for reply.
Yes. Used the correct path in Launcher image path.
Screenshots not are showed in stella launcher even using correct naming png.

**Comment by Augusto7743** [comment]
[ROMs 1.zip](https://github.com/stella-emu/stella/files/9049714/ROMs.1.zip)

**Comment by thrust26** [comment]
Works for me.
![image](https://user-images.githubusercontent.com/24360774/177419735-ce945b33-3adf-40f5-9245-1afbd65ada57.png)

Two more questions:
- Do ROMs outside a ZIP file display the screenshots?
- Which OS are you using?

**Comment by sa666666** [comment]
> Works for me.

For me too.

One other thing to consider.  The PNG snapshots have to be named as they are in the Stella internal database.  So if you name them as they are in the file list above, then Stella can't find them.

I recommend to download them from https://stella-emu.github.io/downloads.html.  The link is near the bottom of the page.

**Comment by Augusto7743** [comment]
@thrust26
"Do ROMs outside a ZIP file display the screenshots?"
Not

"Which OS are you using?"
Lubuntu (Ubuntu using LXQT) 20.04.4

@sa666666
"The PNG snapshots have to be named as they are in the Stella internal database. So if you name them as they are in the file list above, then Stella can't find them"
I has loaded an game and done an screenshot and after moving the file png to launcher image path.
Not show any screenshot.

If load Enduro-NTSC.rom the correct is show screenshot if have Enduro-NTSC.png in launcher image path.
If Stella load Enduro-NTSC.rom and not is in "internal database" even if the rom is an good dump not is possible show screenshots ?
I use emulators for an long time and is the first time I see an emulator requiring screenshots to be named using "internal database" instead rom name. If it is the because not show any screenshot the emulator need allow show any screenshot not using "internal database".

**Comment by thrust26** [comment]
> "Do ROMs outside a ZIP file display the screenshots?"
Not

OK, then the issue is **not** related to ZIP files.

> I has loaded an game and done an screenshot and after moving the file png to launcher image path. Not show any screenshot.

This works for me. And if I e.g. take "Asteroids (1981) (Atari).bin", rename it into "123.bin" and put a screenshot named "123.png" into the image path, Stella will display this PNG.

**Comment by thrust26** [comment]
> - use roms using internal naming without naming details for show screenshots, but if the rom not is in internal database not will show any screenshot.
> - use roms using TOSEC or Nointro with more naming details, but not will be showed any screenshots because Stella not allow it.

This is not correct. I tested your example. Stella does the following:
- If the ROM is known in the database, Stella searches for a PNG with the database name
- If the ROM is unknown in the database, Stella searched for a PNG with the ROM name

So, if you want e.g. "Activision Decathlon, The (USA).a26" to show an image, use the database name for the image. You can name your ROMs as you like.

**Comment by thrust26** [comment]
Agreed. We will enhance Stella to first search for the internal name and then for the ROM name.

**Comment by Augusto7743** [comment]
Thanks very much.
I has several custom png files (game box and cartridges) from Atariage.
Would be good to see Stella allowing configure 3 paths for launcher screenshots view :
- game box png path.
- cartridge png path
- gameplay screenshot png path
In Stella launcher in screenshot area having an gui buttons to alternate what screenshot path will be used to launcher screenshot view.

MAME has option to configure flyers, cabinets, gameplay screenshots and etc. MAME gui in screenshot area has buttons to alternate what type of screenshots (flyers, cabinets, gameplay screenshots and etc) will be showed and works very well.
That feature is an good improvement for Stella.

**Comment by thrust26** [comment]
Good suggestion.

The problem is, that we would need support here. We do not have the resources to create and maintain the additional images. And without images provides, this makes little sense.

**Comment by Augusto7743** [comment]
I have roms named TOSEC and images of game box and cartridges from AtariAge both named using exact rom naming.
It is more of 100 MB total size.
If Stella devs allow I can to look both types of roms (TOSEC, Nointro and Stella database) and the chosen type will be named image file of both gamebox and cartridges. Then the images files can be uploaded for Stella devs see if are good.
Stella rom database use Atarimania rom naming ?

**Comment by thrust26** [comment]
> Stella rom database use Atarimania rom naming ?

More or less, yes.

**Comment by thrust26** [comment]
> Seems pretty easy to fix.

Yup! 😄

**Comment by Augusto7743** [comment]
Thanks very much !
