### ISSUE TITLE
Libretro build failure

### ISSUE THREAD

**Issue by LibretroAdmin** [stella-emu/stella#912]
Hi there, it seems this commit (1a8971e6) caused a regression for the libretro core - all the libretro cores now fail to compile -

https://git.libretro.com/libretro/stella/-/pipelines/122039

**Comment by sa666666** [comment]
Inadvertently fixed in 5ad9c0e5ce206faa7b5185ac952bc2529633e110. :smiley:

**Comment by LibretroAdmin** [comment]
Thanks - problem is indeed resolved as seen here -
https://git.libretro.com/libretro/stella/-/pipelines/122048
