### ISSUE TITLE
libretro unplayable games

### ISSUE THREAD

**Issue by AngelofMe** [stella-emu/stella#915]
because the emulator's code contains these files
these games are meant to be run by emulators

stella/src/emucore
AmigaMouse
AtariMouse
AtariVox
Booster
CompuMate
Driving
Genesis
Keyboard
KidVid
MindLink
Paddles
QuadTari
SaveKey
TrakBall
Joy2BPlus

**Comment by thrust26** [comment]
Sorry, I do not understand.

**Comment by thrust26** [comment]
@AngelofMe  ???
