### ISSUE TITLE
Pi4 make and libretro make broken?

### ISSUE THREAD

**Issue by theflyingape** [stella-emu/stella#917]
FYI, **Raspberry Pi4** on Bullseye - running configure from the top-level to build standalone `stella` fails from a "bad" g++ compiler (version 10). Modifying the failure check to `pass` regardless compiles & works.  :+1: 

First, `cd src/libretro` and running `make` fails to compile/link `stella_libretro.so` -- my source hacks to address missing `HighScoreManager` does produce the binary and it works. :thinking: 

Also, can Stella implement RetroArch `retro_message` with target for OSD? It would be so much more friendlier to have the OSD popup notification whenever the Stella core Difficulty switches between A/B and TV switches between B&W/Color.

**Comment by thrust26** [comment]
As for the compiling error, I have no clue: @sa666666 Can you answer this?

Regarding libretro and RetroArch, I suppose there is not much we can do here. Other platforms other than PC and R77 are beyond our knowledge and resources. You have to seek for support there directly.

**Comment by thrust26** [comment]
@sa666666 @theflyingape Is this still an issue?

**Comment by sa666666** [comment]
The build bug has not received any feedback, so I'm closing this one.  The request for OSD should be a separate enhancement request.
