### ISSUE TITLE
Add JPG support to Stella

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#918]
For displaying scans and photos JPG is much more efficient than PNG. This will become relevant when the Launcher supports multiple images (see #916).

**Comment by Augusto7743** [comment]
Have any development version for test ?

**Comment by thrust26** [comment]
Nope,. Please remember that we are actually taking a longer break from development. So this may take a while.

**Comment by thrust26** [comment]
Or not. 🙂
