### ISSUE TITLE
Libretro build broken

### ISSUE THREAD

**Issue by LibretroAdmin** [stella-emu/stella#919]
Hi there,

The Libretro core currently fails to compile.

See details -

https://git.libretro.com/libretro/stella/-/pipelines/129851

**Comment by sa666666** [comment]
It compiles locally for me.  The build scripts on your build servers likely need to be updated, since `src/libretro` is now `src/os/libretro`.  No other changes should be required.

**Comment by LibretroAdmin** [comment]
https://github.com/stella-emu/stella/blob/master/.gitlab-ci.yml

Can you update the paths here? That's the file the buildbot uses.

**Comment by thrust26** [comment]
Why is the file not in the Libretro folder?

**Comment by thrust26** [comment]
Static builds are working now, shared ones not. Did I miss something?

**Comment by sa666666** [comment]
I didn't create this 'yml' file, so I'm not sure how to fix it either.  But I will have a look at it.

**Comment by LibretroAdmin** [comment]
It seems all platforms now build except for Android -

https://git.libretro.com/libretro/stella/-/jobs/2383673

I think you will have to make some necessary path changes in https://github.com/stella-emu/stella/blob/master/src/os/libretro/jni/Android.mk as well.

**Comment by LibretroAdmin** [comment]
It might work if you change this line in Android.mk:

> include $(CORE_DIR)/os/libretro/Makefile.common

to

> include $(LOCAL_PATH)/../Makefile.common

**Comment by sa666666** [comment]
OK, done in e67b88d35f5f2b2ef2cd846ee4e86f4b6ad9840d.

**Comment by trotsky40** [comment]
The iOS core for RetroArch is not building either.

**Comment by LibretroAdmin** [comment]
Android builds unfortunately are still broken because of whatever moving around of files got done.

https://git.libretro.com/libretro/stella/-/jobs/2391808

**Comment by sa666666** [comment]
We will need someone familiar with the libretro build files and environment.  As I said above, I didn't create this file, nor am I able to duplicate the issue on my local system.

**Comment by LibretroAdmin** [comment]
Hi there, someone will send a PR for this fixing this in a bit.

**Comment by thrust26** [comment]
That did it.
