### ISSUE TITLE
where's the power switch? libretro Space Shuttle

### ISSUE THREAD

**Issue by soundsnow** [stella-emu/stella#922]
switches are used to play activision game
![o_SpaceShuttle_1](https://user-images.githubusercontent.com/109885044/186164883-5c955303-d2b1-4748-9077-fd8c1a13728a.jpg)

[Space Shuttle: A Journey into Space](https://en.m.wikipedia.org/wiki/Space_Shuttle:_A_Journey_into_Space)

1977–1980 VCS

All six console switches on the front panel.

power(on/off)|tv type(color/bw)|left difficulty(a/b)|right difficulty(a/b)|select|reset

1980–1983 VCS and 2600

The difficulty switches were moved to the back of the console, leaving four switches on the front.

power(on/off)|tv type(color/bw)|select|reset

**Comment by thrust26** [comment]
This is not the right place to address Libretro problems. Look [here](https://github.com/libretro).
