### ISSUE TITLE
Refactor sound code

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#925]
1. Currently the `Sound::mute()` method is either meant to mute the sound or to pause it. In the future there should be two distinct functions for muting and pausing. 
2. `Console::initializeAudio()` is closing and opening the sound. Besides initial initialization, the method is also used for multiple purposes (update sound parameters) where there is no need to close and reopen the sound. Therefore it should be refactored too.

**Comment by sa666666** [comment]
@thrust26, is this still required?  Because it seems you've taken care of it in `SoundSDL` with your recent commits.

If there is still work required here, I will wait until you finish your WAV rework.  So that we're not working on the same part of the codebase at the same time.

**Comment by thrust26** [comment]
Its not required for my needs. But the code is still not  good here. IMHO..

**Comment by sa666666** [comment]
OK, I will work on it, but after you've finished working on `SoundSDL`.

**Comment by thrust26** [comment]
Go ahead now.

**Comment by sa666666** [comment]
This is now finished with 7de717114cff4013d2427989adb3366ebdbca49e.
