### ISSUE TITLE
Debugger stops tracking lines in segment 0 on Cartridge3E+

### ISSUE THREAD

**Issue by mzxrules** [stella-emu/stella#928]
When stepping through code in the debugger, Stella won't follow the pc into any address in segment 0.

I believe the regression was introduced here: 
https://github.com/stella-emu/stella/commit/06f42252fafa5307c3a423486d891b685fb0137e

Since myDisassembly.list is no longer cleared before calling `disassemble`, the first call to `disassemble` results in addrToLineList beginning with first line after the previous myDisassembly.list

**Comment by thrust26** [comment]
Thanks for pointing out, especially for providing the commit number. 

The disassembler needs some major rework. Every time I fix something, there is a high risk something else breaks. So fixing this may take some time.

**Comment by thrust26** [comment]
Seems to be fixed with cd24689b20 too.
