### ISSUE TITLE
Unified high score center

### ISSUE THREAD

**Issue by eclenaeu** [stella-emu/stella#929]
I don't know if there is another place to comment this, but since no one informed me, I would like to know if there is a place to send the files with the contribution of the high scores of the games that are not yet in the list of supported games with high score

**Comment by thrust26** [comment]
Do you mean the properties for the games?

**Comment by eclenaeu** [comment]
[Highscores.zip](https://github.com/stella-emu/stella/files/9658449/Highscores.zip)

I hope it can help..., but does anyone analyze these files to see if they are correct?

**Comment by thrust26** [comment]
Thanks. I suppose you already tested them, no? 

And I will test them too.
