### ISSUE TITLE
Debugger freezing due to invalid .cfg file

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#931]
During development of a 4K ROM, the debugger suddenly started freezing right at the start. Something in the ROM code causes this. This is no new bug, all Stella versions (tested down to 4.7.2) crash. DiStella runs endlessly.

**Comment by thrust26** [comment]
Not reproducible anymore. But the bug was real. Also the disassembly partially failed. Something in `Distella` is buggy.

**Comment by thrust26** [comment]
Meanwhile I found out, that the `myAddressQueue` virtually explodes in size. No clue why, though.

Attached is an example ROM.
[The_Core.zip](https://github.com/stella-emu/stella/files/10429536/The_Core.zip)

**Comment by thrust26** [comment]
Found the problem: I had an old .cfg file with a matching name stored in Stella's `cfg` folder. After removing it, everything is fine. 
[test.zip](https://github.com/stella-emu/stella/files/10433263/test.zip)

But even an invalid .cfg file should not freeze Stella. Nevertheless, I reduced the priority.

**Comment by sa666666** [comment]
So this cfg file fails only with the ROM posted in the previous comment?

**Comment by thrust26** [comment]
Not only with this file. I had the problems long before. 

If the ROM has the same name as the config file, then Stella loads the directives. And if these directives conflict with the ROM's code, then DiStella loops endlessly.

**Comment by thrust26** [comment]
Minimized the directives in `test.cfg` into:

```
ORG f000
ROW f4b9 f4b9
ROW f787 f787
```
Debugger still freezes.

**Comment by thrust26** [comment]
Disassembled addresses not marked as `CODE` will be pushed to the address queue and marked as `CODE`. However, if the address has a directive, then the directive has priority over the code marking. Then the address would be pushed over and over to the address queue. To avoid this, there is a check at the beginning of `DiStella::disasmFromAddress`. This check was lacking `ROW` and that caused an endless loop if the `ROW` directive pointed to a jump/branch address.

**Comment by thrust26** [comment]
Fix breaks finding 'tentative code'.
