### ISSUE TITLE
Regression in scanline counts

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#934]
I've tested two ROMs; undoubtedly there are more examples.  I've tried Yars Revenge (NTSC), and the Yahtzee homebrew.

Stella 6.6:
- Yars is fine
- Yahtzee has unstable counts, but the display is stable

Stella 6.7:
- Yars is fine
- Yahtzee now has unstable display (with unstable counts)

Current:
- Yars detected and displayed as PAL
- Yahtzee detected and displayed as PAL, and still unstable display

So it seems that between 6.6 - 6.7 and again between 6.7 - current, the scanline calculations have changed, making ROMs that worked in older releases no longer stable.  Still researching what actual code changed to do that.

**Comment by sa666666** [comment]
It seems that 3beb5599e2dd029b7fc7f702f59e3a4d9668981c is where the problems first appear.  @thrust26, do you have any advice here?

**Comment by thrust26** [comment]
A stupid "unsigned" mistake by me. Should be fixed now. Can you confirm?

**Comment by thrust26** [comment]
Yahtzee has an unstable display due to the unstable counts. The Jitter sensitivity is set to 3 by default and this picks up the unstable counts. It gets slightly better with sensitivity 2 and stable with 1.

**Comment by sa666666** [comment]
Thanks, both games are fixed.  I will close this now.
