### ISSUE TITLE
Carrot Kingdom dies: paddle I/O in absence of controller

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#94]
Carrot kingdom (homebrew, see [thread](http://atariage.com/forums/topic/243605-carrot-kingdom-work-in-progress-16k-new-demo-2-14-2017/page-1)) exposes an inaccuracy in paddle I/O emulation.

For some reason (I'll have to ask Jinroh about that, propably a addressing mode typo), the game reads INPT2 by doing 

    LDA $0A
    STA $F2

when scrolling to the right. On a real console, `LDA $0A` will always read as `$0A` as the circuit is severed and the capacitor does not charge at all. In old stella, this is represented by a resistance of 0x7FFFFFFF which has the same effect. In the new core, this value just translates into a very large resistance, and charge slowly builds up. Once the trip point is reached (a minute or so), the read will yield `$8A`. This will cause the code to go beserk and overflow subsequent indexed writes, effectively crashing the game.

This behavior can be observed by either playing in stella 5 for a minute or so, or by plugging paddles into the second port on real hardware (or stella 4).

The failure image looks like this (with phosphor turned on)
![carrot_kingdom_demo_7g_46](https://cloud.githubusercontent.com/assets/2444224/23103116/ef8719c6-f6b5-11e6-8263-3d6554c66423.png)

This image exposes another bug: the current logic for clearing excess lines after a frame completes does not take double buffering into account, and the result in this case is the last valid image being retained and alternated with garbage generated after the crash :smile:

**Comment by thrust26** [comment]
Is it LDA $02 or LDA $0A?

**Comment by DirtyHairy** [comment]
`LDA $0A` :smirk: Thanks, @thrust26

**Comment by thrust26** [comment]
$0A is a mirror of INPT2.

**Comment by thrust26** [comment]
That's a cool bug. :)

**Comment by DirtyHairy** [comment]
It decidedly is --- the type that gets you debugging desparately at first and then smiling once you start to understand what's going on :smirk:

I think the relevant code was intented to read

    LDA #$0A
    STA $F2

instead as `$F2` is used as a loop counter lateron.

**Comment by DirtyHairy** [comment]
75bd732 fixes the double buffering, 39f756f fixes spurious charging.
