### ISSUE TITLE
WLA-DX compiled ROMs start at registers

### ISSUE THREAD

**Issue by Pokeman2003** [stella-emu/stella#941]
Whenever you attempt to run a ROM compiled with the assembler suite [WLA-DX](https://github.com/vhelin/wla-dx) release version 10.3 on Stella release version 6.7, Stella identifies as the ROM starting at address $0000-$07ff(on a 2K ROM), instead of starting at $f000 like it should. See below, left is Pacman, right is my ROM.
![image](https://user-images.githubusercontent.com/83632748/201841294-10545b00-aa4d-4e77-92cb-e466b3ddefb0.png)
This causes Stella to try to read the registers as if it was ROM data, which unsurprisingly, doesn't work in the slightest. However, Stella is definitely loading the ROM. Manually setting the program counter to F000 does cause the ROM contents to show up.
![image](https://user-images.githubusercontent.com/83632748/201852292-fd687c99-6f26-4d65-8e76-1d05f8ae0ffc.png)
[Here's a copy](https://github.com/stella-emu/stella/files/10010114/Test.Package.zip) of my ROM, my object file, my linker, my assembly code, and my buildscript. It does not include WLA-DX.

**Comment by thrust26** [comment]
This is a coding bug. Your code (and the ROM) are missing the start-up vector at $xffc.

**Comment by thrust26** [comment]
For 2K ROMs the start-up vector would be at $x7fc.

**Comment by Pokeman2003** [comment]
Thanks a lot! I guess I should've expected that it'd be at the end of the ROM. Have a great day!

**Comment by thrust26** [comment]
No problem.
