### ISSUE TITLE
The pre7.0 core does not allow in-game input in aftermarket game Elevator Agent

### ISSUE THREAD

**Issue by n1ghttrap** [stella-emu/stella#949]
You can start the game, but as soon as the game begins you can't move or fire.  I don't have a similar stand alone binary to compare it to, as 7.0 can't be easily found and I'm not sure where one would go to compile it, but the game works correctly in the 6.7 derived core from the stable 1.10.3 core pack and the 6.7 standalone.  Not sure if this is a new core bug or a new Stella bug.  Thanks in advance.

**Comment by thrust26** [comment]
Works for me. 

Where did you get 7.0 if you cannot compile it yourself? And which platform are you using?

**Comment by n1ghttrap** [comment]
Apologies if this is not the correct place to report it, but I'm using the Retroarch core. There is no issue tracker on https://github.com/libretro/stella, and the link at the bottom's issue tracker points to this project.  The current core from the repo is labeled pre7.0.  If the core isn't supported I suppose I will make a general libretro/Retroarch ticket.

**Comment by thrust26** [comment]
Yes, this is not the right place to report. I will ask the Libretro project to fix their links.
