### ISSUE TITLE
Init stack pointer with $FD on reset

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#95]
See the AA [thread](http://atariage.com/forums/topic/261488-reset-sp/)

**Comment by sa666666** [comment]
Shouldn't we just change the code specified in the thread from 0xFF to 0XFD?

**Comment by DirtyHairy** [comment]
Indeed --- done in b173da0 :smirk: I guess opening the ticket was overkill, considering that it took longer than the actual fix :smile:
