### ISSUE TITLE
Continuous climbing/leakage of RAM on *NIX

### ISSUE THREAD

**Issue by MotoLegacy** [stella-emu/stella#952]
Built the latest 7.0 pre-release (9d46bb6) from source on my Arch install and have noticed memory usage continues to climb aggressively while running any ROM (a pretty consistent ~300kBps according to KDE's System Monitor), but is stagnant when in the UI. It seems to enjoy capping out at ~85mB total memory usage, oddly.

I am using GCC version 12.2.0 if that is helpful.

Attached is my configure.mak. Happy to provide any other details required to further the diagnosis.
https://hatebin.com/myhqqooqid

**Comment by thrust26** [comment]
Is the time machine enabled?

**Comment by thrust26** [comment]
@MotoLegacy Waiting for your happy feedback. 😃

**Comment by thrust26** [comment]
@MotoLegacy 2nd Bump

Please reply, else we will close this one.
