### ISSUE TITLE
Odd control problem in Libretro

### ISSUE THREAD

**Issue by IdiotBlueMage** [stella-emu/stella#953]
I encountered an issue that only happens in the current Libretro core, this does not exist in any other version of Stella.  In Wizard of Wor Arcade (by Champ Games), I can start the game.  That's about it, directional inputs and fire buttons do not respond.  This same thing happens with Zoo Keeper

I was doing a bit of research to see what could be the issue, and I came across a report for the Stella core found in RetroArch's issues for some reason.  It appears to be related to how Quadtari is detected: https://github.com/libretro/RetroArch/issues/12467

**Comment by thrust26** [comment]
Yes, this is related to the QuadTari detection. However I figure, it has to be fixed on the Libretro side. Please report there.
