### ISSUE TITLE
Disassembly view lost after trap

### ISSUE THREAD

**Issue by mohhingman** [stella-emu/stella#955]
In 6.7, when using the trapwrite command, the assembly view is "lost" when entering the debugger after triggering the trap. Although the game does continue executing fine, it's not possible to see where the execution is, even after using the step and trace buttons . Spotted when working with game with E7 bankswitching and trapping writes to RIOT RAM, but may affect others too. After disabling the trap, restarting execution, and then using tilde to return manually to the debugger, the dissasembling view seems to be back on track.
This doesn't happen in version 6.6.

**Comment by thrust26** [comment]
Thanks for reporting. This has already been fixed for 7.0.

**Comment by mohhingman** [comment]
wow, glad I reported it now :) thanks
