### ISSUE TITLE
Pharaoh's Curse bug?

### ISSUE THREAD

**Issue by soundsnow** [stella-emu/stella#956]
I used another port of Stella
I'm not sure, bug?
Pharaoh's Curse (USA)
Pharaoh's Curse (Europe)
I played USA ROM
![2-16-23 20 22 19](https://user-images.githubusercontent.com/109885044/219364546-2661a2f7-d322-40a3-98e3-3964fbd29335.png)

**Comment by thrust26** [comment]
We need much more details, please. 

E.g. which Stella port are you playing? Which ROM exactly (please post it here)? Is the screen stable or rolling? Do you have any settings changed from default?

**Comment by thrust26** [comment]
No feedback.

**Comment by RingtailRaider** [comment]
I'm encountering the same issue on 7.0. It's the US rom, checksum matches no-intro. The Europe version seems to work fine. The screen is vibrating slightly up and down when standing still, and starts rolling wildly up and down when moving. As far as I know no settings besides controller input have been changed. I found [a post](https://forums.atariage.com/topic/229999-pharaohs-curse-flicker-problem/) talking about this same issue from 2014. Additionally every online streaming emulator of this game I've found seems to have this same issue. No idea if it was originally broken on hardware too, as far as I've seen every other game I've tried works fine

**Comment by thrust26** [comment]
I suppose you are using a ROM hacked into NTSC (like the attached one). Else post yours please.

This is no Stella bug. The ROM is behaving that badly, because of a timer overrun.

[Pharaoh's Curse (Unknown).zip](https://github.com/user-attachments/files/19703873/Pharaoh.s.Curse.Unknown.zip)
