### ISSUE TITLE
Stelladaptor-clone driving controller issue

### ISSUE THREAD

**Issue by arpruss** [stella-emu/stella#964]
I have a DIY USB arcade spinner that I am trying to use as a driving controller for Indy 500. I set it up to function like a Stelladaptor (sending gray codes encoded into y-axis values). Stella recognizes it as a Stelladaptor just fine. But the problem is that as I rotate my spinner, I just get a few random-looking jerky rotations of the car. But I found a workaround. If I go to Game Properties and change the controller from Driving Controller to Joystick, then everything works great.

Here is what I think is happening. If Stella is set to Driving Controller in the game properties, it is treating my Stelladaptor-clone as if it was a joystick, and Stella is emulating a Driving Controller. But when I change the controller to Joystick in Game Properties, then the Driving Controller emulation is no longer on, and Stella just takes the data from my device, decodes it to pin values, and everything works great.

I don't know if the problem is with Stella or with my device somehow not telling Stella that it's a DC. Any suggestions would be welcome.

**Comment by thrust26** [comment]
I suppose you are using version 6.7? Then this is a known (and now fixed) bug. See #951.
