### ISSUE TITLE
PlusRom support for E7 bankswitching

### ISSUE THREAD

**Issue by mohhingman** [stella-emu/stella#965]
I've made a homebrew with the E7 bankswitching scheme that uses the PlusCart high Score club feature. It currently works on PlusCart and Gopher2600 emulator with the ROM. I'm not sure how much work it would be to get it to work with Stella, but that would be awesome if it could be supported. A test ROM can be found here:

https://forums.atariage.com/topic/349506-kovi-kovi-for-atari-2600/#comment-5227852

**Comment by thrust26** [comment]
@mohhingman 

I suppose you are referring to Kovi Kovi, right? The ROM works for me. What's your problem?

**Comment by mohhingman** [comment]
Yes, it runs fine on Stella. I was referring to the transmission of the High Score data. I'm yet to see it work. Mind you, I'm still using Stella 6.6 as 6.7 had some issues with E7.

**Comment by thrust26** [comment]
Looks like E7 bankswitching doesn't support PlusROMs. Probably I forgot to add it. I will fix this now...

**Comment by mohhingman** [comment]
Thank you very much.
