### ISSUE TITLE
“Stella” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by allamiro** [stella-emu/stella#968]
Getting this message on Mac OS Apple M1 Max Version 13.3.1 (22E261) Ventura 

“Stella” cannot be opened because the developer cannot be verified.

![Screenshot 2023-04-28 at 4 33 07 AM](https://user-images.githubusercontent.com/279790/235040635-ae057214-4d53-4aec-99bc-da7e1afc12c0.png)

**Comment by ckrokosh** [comment]
Right click the Stella icon and select open. This only has to be done once. After that it should open normally. Believe it has something to do with the app not being "signed" by apple.

**Comment by DirtyHairy** [comment]
You can also go to Settings -> Security after closing the warning dialog. There, you'll find that an option appeared (pretty far down, near app sources) that you can confirm to open Stella nevertheless. On the second attempt, you can now choose to open Stella despite the missing signature, and MacOS will not bug you again.

The warning indicates that Stella was not signed with a developer certificate and has not been verified by Apple, and MacOS tries to prevent you from accidentally opening it.
