### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#971]
Compiling fails for me (see attached stderr dump).

[stderr.txt](https://github.com/stella-emu/stella/files/11645969/stderr.txt)

I tried going back to a previous commit that I already successfully compiled, but failed in the same way, so I guess some update to my system that happened in the meantime broke it.

Adding `#include <cstdint>` in "src/lib/tinyexif/source/TinyEXIF.h" fixes the issue.

**Comment by sa666666** [comment]
I already addressed this in https://github.com/stella-emu/stella/commit/db7fe478c528349093b4470f860915e1ac3b9481, I think.

**Comment by ale-79** [comment]
I'm getting the error above with an up to date master branch. I just tried again cloning the repository in a new dir. 
It doesn't work unless I also include cstdint in addition to cstdlib in TinyEXIF.h. 

gcc version is 13.1.1.
