### ISSUE TITLE
allow roms with gzip compression

### ISSUE THREAD

**Issue by zkarj** [stella-emu/stella#973]
stella worked with gzipped rom since 3.4, but as of now, it only works with zipped rom.

It would be nice to get ROM.gz working again.

**Comment by sa666666** [comment]
I will consider it, depending on how complicated it will be to accomplish with the new filesystem code (ie, the reason it was removed).

**Comment by sa666666** [comment]
Unfortunately, re-adding GZIP support no longer fits with how the current code is structured.  I suggest to convert your gzipped files to ZIP.  You can even put them all in one ZIP file, as Stella supports that.
