### ISSUE TITLE
BUG - Fire button not working

### ISSUE THREAD

**Issue by xXRaptorSc0pezXx** [stella-emu/stella#976]
No matter what I do or what key I map the fire button to it does not work, making most games completely unplayable. All the movement keys work, it is just the fire button that does not.

**Comment by thrust26** [comment]
@xXRaptorSc0pezXx Since you are the first and only one reporting this major issue, can you provide some more details please? 

- Which version of Stella are you using? 
- Which OS? 
- Which controller are you using?
- Have you tried a different controller?
- Did the button work before? (e.g. before updating Stella)
- Are only joystick games affected or e.g. paddle games too?

**Comment by thrust26** [comment]
No feedback

**Comment by xXRaptorSc0pezXx** [comment]
Which version of Stella are you using? - Latest Stable ZIP.
Which OS? - Windows 11
Which controller are you using? - USB Xbox One Controller
Have you tried a different controller? - Yes
Did the button work before? (e.g. before updating Stella) - No, this is my first time using Stella.
Are only joystick games affected or e.g. paddle games too? - I have no idea.

**Comment by thrust26** [comment]
@xXRaptorSc0pezXx 

- Just to be sure: Does the fire button **not** work on the different controller(s) you tried, too?
- Can you try a paddle game that uses the fire button, e.g. Night Driver, please?

**Comment by thrust26** [comment]
@xXRaptorSc0pezXx I am closing this now. If you return to discussion with details, I will reopen.

**Comment by xXRaptorSc0pezXx** [comment]
Does the fire button not work on the different controller(s) you tried, too? 

- Yes it does not work with any of the other controllers.

Can you try a paddle game that uses the fire button, e.g. Night Driver, please?

- Just tried Night Driver and I can't get the game to do anything. I load it up and just see the little car or whatever going back and forth but can't control it. Not sure if I set the paddle control binding right but either way when I press the button I set to be the fire button nothing happens.

This bug makes pretty much every game except Pac Man unplayable lol. It's weird becaause when I press the fire button to start the game, it works for Pac Man and the game starts but them if I load up Space Invaders and press the fire button nothing happens. Movement works in both games, but pressing the fire button only works correctly in Pac Man. Is there something I am doing wrong? This is so incredibly frustrating lol.

**Comment by xXRaptorSc0pezXx** [comment]
Same thing with Haunted House. If I load up the game and move my joystick I can see the eyes of the player character moving in response to the joystick. When I go to press the fire button (I have it bound to A on my controller) however, nothing happens and I cannot actually start playing the game.

**Comment by sa666666** [comment]
Some (most?) games require you to press Reset (F2) before you can start playing a game.  Pressing Fire works for Pac-man,   but not the other games you listed.  Those need F2 first.

**Comment by sa666666** [comment]
This is also listed in the https://stella-emu.github.io/faq.html, under "I've located some ROMs and can get them to start in Stella, but I don't know how to actually start/play the game."

**Comment by sa666666** [comment]
OK, then we can close this.
