### ISSUE TITLE
Defender III ROM not working

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#98]
More details at http://atariage.com/forums/topic/262864-defender-iii-atari-flashback-portable/#entry3709415.

The page notes that the ROM works on real hardware but not Stella.  I will test on Harmony soon.

**Comment by DirtyHairy** [comment]
I think that this an issue connected to the initial state of CBS and RIOT RAM (and thus propably not an emulation issue). In this case, testing on harmony won't get much closer to real hardware as CBS RAM is emulated there, too. In fact, if I remove CBS RAM randomization in 6502.ts, I get very different results, so CBS RAM is definitiely involved here :smirk:

**Comment by sa666666** [comment]
Confirmed.  If I turn off 'Randomize zero-page and extended RAM' in the I/O tab of the debugger and restart, the ROM seems to work fine.  So I'm guessing the ROM is not zeroing RAM itself, and hence not working in emulation.  I'm going to close this one as non emulator related.
