### ISSUE TITLE
Center screen ...

### ISSUE THREAD

**Issue by MarcyBesky** [stella-emu/stella#982]
Hello everybody, I am currently unable to center the screen horizontally no matter what options I use. Am I missing something or is this just not incorporated?

Checking Altirra emulator, the screen is centered.

![Stella-Center](https://github.com/stella-emu/stella/assets/139846289/cdcf15d9-0ee3-4274-9441-5523751a7c0d)

**Comment by thrust26** [comment]
The screen **IS** centered. The right black area is programmed into the game. It is typical for Activision games.

If Altirra is removing the black area, then it is modifying the original output. Stella is focusing on exact emulation.

**Comment by MarcyBesky** [comment]
Ok, I understand. Good one.
