### ISSUE TITLE
FSNodeWINDOWS::rename() returns false in case of success

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#988]
I noticed this while playing with the `RomAuditDialog`. The counter for renamed files always stayed at 0.

I think the problem is that in `setFlags()` `const DWORD fileAttribs = GetFileAttributes(_path.c_str());` is still using the old filename, while the file is already renamed.

It works in 6.7, so I figure it must be due to your file handling changes.

**Comment by sa666666** [comment]
Not happening in Linux, but honestly, based on your description, it should be happening there too.  I will research this a little more.
