### ISSUE TITLE
Debugger commandline arguments inconsistent (incorrect help, ambiguity between commands, crashes, etc)

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#99]
Stella 4.7.3 (Linux) crashes when I specify an address range with  trap|trapread|trapwrite in the debugger. (e.g: "trap f000 to f0ff")

this is the error I get on the terminal:

> terminate called after throwing an instance of 'std::out_of_range'
>   what():  bitset::flip: __position (which is 65536) >= _Nb (which is 65536)
> Annullato (core dump creato)

Also, is the address range supposed to work with the trap**m**|trapread**m**|trapwrite**m** commands?
When I try, the emulator doesn't crash, but I get an error in the debugger prompt.
E.g. the command "trapm f000 to f0ff" returns "Address 61440 is outside range"

All traps command works fine if I specify a single address

**Comment by sa666666** [comment]
You don't use the word 'to'.  So the command should be "trap f000 f0ff".  Admittedly, it should fail in a better way than simply crashing the app.  The commandline parsing hasn't seen some love in quite some time, and needs to be updated.  I just noticed that the help implies to use 'to', but the code does not allow it :frowning_face:.  Obviously this needs to be fixed.

For now, the 'm' versions of the command don't work with a range, but the non-m versions do.  Again, a discrepancy.

**Comment by sa666666** [comment]
Also, as has been suggested by @thrust26, I'm not sure we need the non-m versions at all.

**Comment by ale-79** [comment]
Thank you! That was it.
I agree that the non-m versions could be dropped.

**Comment by thrust26** [comment]
IMO the non-m versions should become what the m versions are now.

**Comment by sa666666** [comment]
Yes, that's what I plan to do.

**Comment by sa666666** [comment]
The 'help' command has been improved in https://github.com/stella-emu/stella/commit/96bbba223a207d065da00015320fe4b3501a5cff; it now offers extended help on commands.  Also, the 'cls' command is improved, and tab completion works better in various cases.

**Comment by sa666666** [comment]
A 'palette' command is now available, showing color swatches of the TIA palette currently in use:
![screenshot_20170406_193958](https://cloud.githubusercontent.com/assets/16061066/24777640/d64ae1ee-1b00-11e7-8fdb-d137e37cb17a.png)

**Comment by sa666666** [comment]
The various trap commands now work like both the 'm' and non-'m' versions (non-'m' versions were removed).  They now allow to trap on all mirrors, as well as accept a range of values to trap on.  Implemented in https://github.com/stella-emu/stella/commit/4e794ba778c2b81457e68385a510ed3ed749927f.

**Comment by sa666666** [comment]
I believe this has been addressed with various commits, so I will close it.
