### ISSUE TITLE
Stella 6.7 - Driving Controller not working with Stelladaptor/2600daptor device

### ISSUE THREAD

**Issue by dualcam** [stella-emu/stella#992]
Car just randomly jumps around in Indy 500 when turning the controller.  Saw another bug report that claimed this was a known bug in 6.7 and fixed - but still present in the 6.7 I just downloaded off https://stella-emu.github.io/

Tom
2600-daptor.com

**Comment by thrust26** [comment]
It got fixed, but the fix will be in the next released version.

**Comment by thrust26** [comment]
closed
