### ISSUE TITLE
New Feature Request for Stella - Random Game Generator

### ISSUE THREAD

**Issue by HelloWorld732** [stella-emu/stella#995]
Hello coders,
I'm just a Stella enthusiast. (I play Atari.) I'm not a coder.
Can I make a new feature request?
In a future version of Stella, could there possibly be a prominent button somewhere to click to let Stella choose a **random game** for you to play from among those available in your ROMS folder?
Would be a great way to explore some of those many great Atari games that you've never tried before.

Thanks for making Stella. It's a great Atari 2600 emulator. I love using it!

(I had previously posted on Oct. 7 in Discussions.  Now posting in Issues.)  
https://github.com/stella-emu/stella/discussions/991

**Comment by HelloWorld732** [comment]
Thank you, Thomas!  I received the email notification and I came here.  Looks great!  When can I start using it?

**Comment by thrust26** [comment]
No schedule for 7.0 yet.

**Comment by HelloWorld732** [comment]
You mean we must be patient and wait for Stella 7.0 release?

**Comment by thrust26** [comment]
Yes. Stella has no automated builds.

**Comment by HelloWorld732** [comment]
Okay, I'll just wait for the release of 7.0.  Thanks so much!!  Can't wait to play my first random game!
